== Chapter V.

[.chapter-synopsis]
* Family Visit at Sheffield
* Her illness there
* Consideration of removing into Ireland
* Journey into Lincolnshire
* Removal to Ireland
* Journey into Holland, Germany and France.

+++[+++In the first month 1787, she was engaged with Rebecca Jones and others,
in a religious visit to the families of Friends at Sheffield;
concerning which she writes as follows:]

[.small-break]
'''

The visit here is got through, and I hope profitably to many, and especially the youth,
of whom here are great numbers; some of the apprentices are very raw,
but others seem turning about with desire to find, and make, the right purchase.
They are indeed, altogether,
a great load of care upon the shepherds and shepherdesses in this place,
whose concern I hope is increasing.
It is pleasant to find increasing unity and openness
amongst rightly concerned Friends in this place,
and that love which casteth out fear.

[.small-break]
'''

+++[+++At the close of this family visit, she was taken very ill,
with a heavy cold and an inflammation of the lungs.
This disorder continued for several weeks,
during which she was brought very low in body and mind.
But the great Physician, on whom appeared to be her sole dependence,
saw meet to raise her again, and to renew a considerable portion of health and strength.
Of this illness, and the exercise of her mmd under it,
as well as of her feelings in the review of it, some account will be conveyed,
by the following extracts from her letters, written whilst she was on the recovery.]

[.small-break]
'''

I am now favoured with ability to answer your solicitude myself, and say,
that the account you had of my illness was, I apprehend, not worse than the reality;
having been reduced to the gates of death to all appearance,
with an inflammation of my lungs, which had been approaching some weeks,
and arrived at an awful crisis; at which time,
by the merciful interposition of the good Physician, the disorder took a favourable turn,
and opened again my prospects to this mixed state of things.
My bodily affliction was great, but the conflicts and gloomy exercises of my mind,
were not less, being involved in all the weakness and insufficiency of human nature,
in endeavouring to attain to the spring of pure consolation, at the same time that,
in unerring wisdom, it was sealed in my view: so that upon the whole,
it was a season of deep proving, and I humbly trust, lasting instruction;
by rendering more single the attention of my mind to divine discoveries,
whereby our duty is seen, and strength to perform it acceptably received.
To be found faithful in the great work of the present fife,
is an object of such magnitude, that all things else appear comparatively trifling,
when we are looking into a state of eternal duration.

The ways of wisdom are a great deep, and the designs of removing from, or restoring to,
this uncertain and probationary state of being,
are often for purposes which require a daily waiting for,
and dependence upon the unfoldings of pure instruction,
in order profitably to discover them.
I consider this to be my own case,
and often remember a remark of John Woolman`'s to a friend,
perhaps similarly circumstanced, "`do we (says he) get through with great difficulty,
and yet recover; He requires that we should be purged from dross,
and our ear opened to discipline.

I am favoured to continue recovering,
though often reminded that in every sense I am a poor weak creature,
and under abundant necessity to hold fast the little strength I have,
and patiently wait for the renewings of that life which quickens,
and gives joy in the spiritual creation.
But I am still too carnally minded, too much disposed to look outward,
and too little to press through the opposition of nature,
to that true weightiness of spirit which I earnestly
sought for in a late season of adversity.
These things convince us, that in order to win the crown in view,
we must fight the good fight, and wrestle for that faith which only gives the victory.

[.small-break]
'''

+++[+++The subject of removing into Ireland, and settling there, had for a considerable while,
engaged her solid consideration;
and the propriety of that undertaking was about this time attended
with such clearness to her own mind and that of her husband,
that they apprehended the time was near for their departure from this land.
Divers of her letters written on this occasion,
show her sense of the importance of this measure,
and how great and exemplary was her concern,
that they might be directed wisely and safely concerning it.
The following have been selected from them.]

[.small-break]
'''

Our minds have been under frequent, and sometimes, unprofitable,
concern how to dispose of ourselves.
There seems an abundance of places to choose from, both in Ireland and here;
but to know our right lot,
is what we are both desiring singly to stand open to the discovery of,
if conveyed to us ever so simply; the light which manifests it, be it ever so small,
will, I believe, satisfy our fasting minds.
We have need to be reduced low, that we may so obtain the knowledge of the divine will,
as cheerfully to yield obedience thereto.
Though we think we have waited long for instruction, yet as our opinions,
of ourselves especially, are often very fallacious,
it is not impossible but we are far from that state of self-nothingness and dependence,
which I am sometimes ready to hope we are on the brink of.
We are at present quite unbound to any place;
perhaps to have no place of abode is the lot designed us;
a lot that much opposes my inclination, but if right, however trying,
it must be submitted to, and its consequences likewise, as the requirings of the day.

My mind has of late looked with more clearness than before, towards Ireland.
It has been a subject of consideration, attended already with much anxiety;
and now that I am apprehensive I have seen a right opening towards it,
I wish to be preserved from looking back,
or entering into unprofitable considerations about it;
but rather to leave the matter at present,
only standing open to the discoveries of more light, either for or against it,
and respecting the right time of moving, or of not moving at all,
which I know to be the situation of my husband`'s mind respecting it.
I well know,
that except we are in our right places we can have no
true enjoyment or expectation of support under,
or the blessing upon, our allotted portion of suffering;
and we have proved both lands to have in them their share of trials and probations;
and know that things which look the most pleasant in either, may soon be embittered,
and shaded with gloom, as some of them have already at times been.
I wish however to number my blessings, for they are many, and far beyond my deserts.

I often wish that I could learn to be still when I have nothing to do,
and instead of straining my eyes in the dark, and watching the breaking of the day,
to dwell quietly in the ward all night, believing in the light,
and obediently working therein.
The outward day breaks gradually upon us,
and experience teaches us the certain indication of its approach,
a dawning of light which we are not apt to disbelieve,
nor doubt that the meridian of it will come in due time.
As in the outward, we cannot hasten that time,
no more can we with respect to divine illuminations.
Does it not therefore remain to be our business,
to wait for the light when a little of it appears, to believe in it,
and that the fulness of the day will come, though we do not now see it;
remembering that "`blessed are they that have not seen, and yet have believed.`"
This is what I apprehend to be right to do, and what I wish to attain;
but I would by no means insinuate,
that I confidently believe myself to have arrived at it,
in the prospect of removing to Ireland; meaning only, that after a state of anxiety,
and tossing about with every wind of the sentiments of others,
I seemed to get into resignation`'s harbour.
I am however willing to stand open to further conviction;
and if the will should be graciously accepted for the deed,
my poor bark excused the exposure, and my dear Robert satisfied,
which I do not doubt if it is right,
it will not be an unpleasant release from an engagement
to which I now feel myself rather bound.

There are many in this nation, and in our own county,
(setting aside my near relatives after the flesh) to whom I am closely attached,
and from whom nature will flinch to part;
but there are also divers of this class in Ireland, whose friendship will,
if my residence there be right, greatly repair the loss,
and tend to smooth the otherwise rugged path.
This is looking at secondary causes, a view which I do not wish often to take;
because to be in the place assigned, whether I was known of mortals or not,
where the great work of sanctification and acceptance in divine favour is going forward,
would, I am satisfied, afford a peace superior to all human consolations,
and enable the truly abased mind nobly to say, "`Although the fig-tree shall not blossom,
neither shall fruit be in the vines; the labour of the olive shall fail,
and the fields shall yield no meat; the flock shall be cut off from the fold,
and there shall be no herd in the stall; yet I will rejoice in the Lord,
I will joy in the God of my salvation:`" a glorious experience worthy our aspiring after!
Whatever has a tendency to loosen our affections from mixed streams of refreshment,
and centre them in the great source, the well in ourselves,
springing up unto everlasting life, I apprehend more truly qualifies for service,
than a situation replete with opportunities for the increase of human wisdom,
and activity in the visible church; which never fail to have in them their snares,
by gratifying self, if given way to, in one shape or other.

What I have felt at times on the subject of our removal, cannot be easily described;
divine support and direction, if singly sought to, under the weight of it,
will be found sufficient to sustain, and open the right way;
but I apprehend that our small grain of faith,
may meet with many trials and buffetings in our future stoppings; and oh,
that we may never make shipwreck thereof!

May the staff of Israel be our support, separately and together,
and may we have no other dependence, is the secret petition of my mind; for,
in the undertaking before us, we may say,
that with our staff only we are passing over this Jordan.

[.small-break]
'''

+++[+++Having come to a conclusion respecting their removal into Ireland,
and obtained the concurrence of their monthly meeting,
they proceeded to York and attended the quarterly meeting there; from whence,
after taking a solemn and affecting leave of their near connections and friends,
they set forward for the county of Lincoln; the meetings of which,
as well as some others, she felt a desire to attend, in her way to the yearly meeting.
Soon after this trying separation, the following letter appears to have been written.]

[.small-break]
'''

Last week but one was our quarterly meeting at York,
which was favoured with the overshadowing of the heavenly wing.
It was a parting time, and almost too affecting for my present weak state;
but I endeavoured what I could to look beyond personal enjoyments,
to that fellowship which is pure, standing with the Father and with the Son,
and which admits of no change by outward separation,
if we retain our integrity and places, in the adoption of children.
On seventh-day morning after, came the dregs of the cup of removal;
a heart-tendering farewell to my beloved connections at York,
with the proprietors of the school, and some of their husbands.
It was almost too much for my frame, faith being at a low ebb,
and discouragements coming in like a flood; but in the opening of true vision,
the spirit of the Lord was lifted up as a standard against them.

As to the body, I have now parted with many who seem interwoven with my existence:
with divers of them it was gradual, and I esteem it a favour it was so:
but though I am sensible, that in the church I leave both fathers and mothers behind;
and as to the brethren and sisters in the Truth, they seem almost daily added to,
and promise, according to their present growth, to be skilful servants in the family;
yet the near unity my spirit has felt with some in Ireland, affords me a ray of hope,
that should we be spared with life and strength,
to enter into and rightly stand in our lots at Clonmel,
we shall find every want supplied, and true yoke-fellows beyond our deserts.

[.small-break]
'''

+++[+++With divers companions in that service,
she visited most or all of the meetings and families of Friends in Lincolnshire,
and attended several other meetings as she proceeded to London.
Though but little of the progress of this journey is described in the following extracts;
yet the feelings of her mind, and the instructive remarks set forth therein,
will it is apprehended, render it proper to insert them here.]

[.small-break]
'''

We are favoured to get along as well as we might expect,
we hope in some degree of sympathy with the
state of the best things in this desolate county;
but upon the whole, my mind is and hath been favoured with a calm,
especially for these few days back, which tends to promote the restoration of health,
and strengthens with a good degree of resignedness,
to look forward to the prospects before me;
and so far from considering the pursuit of them a hardship,
I esteem the end proposed thereby, a favour of which I am unworthy;
for what is there worth living for, but to be found in the discharge of our duty?

We are now in the isle of Axolm, visiting a few desolate professors,
who are like sheep having no shepherd; and yet,
in a place as much neglected as perhaps any in the Society,
we are comforted in finding a seed alive, resembling Joseph in Egypt, and may say,
for my own part, that I have felt the most solid reward for a little labour here,
of any since leaving York.
It is not after the sight of the eye or the hearing of the ear, that we can judge aright.

They that suffer with the seed, shall reign with it; but it must not be in our way,
or in our time.
Patience is due on our part,
and the exercise of that grain of faith which we have received; for,
"`by faith the elders obtained a good report,`" I presume of the Lord,
rather than of men.
Then let us not be afraid of the trial, for its efficacy is proved thereby.
O that I was stronger in this spot! for even since we left York,
and particularly on leaving it, I have seemed to be reduced to the lowest ebb,
and nature hath foreboded discouragements beyond what I thought I was able to bear.
But this is not always the case; for sometimes,
when everything else is shaded with gloom, the foundation is most clearly revealed,
and its standing sure incontrovertibly known and believed in;
so that all things have appeared possible to him that believeth,
and the ways of the Most High discovered to be higher than our ways,
and his thoughts than our thoughts.
Here I love to repose myself,
and stand resigned to every dispensation which has the remotest tendency,
not only to let me see the work of my day, but to refine and qualify for it.

I have recovered so much,
that I have now scarcely anything to complain of respecting the body.
To be sure it is not very strong,
but it has thus far proved able to bear all that was laid upon it;
which is encouragement to myself, and also to others,
to persevere in yielding ourselves up, under the power of the cross,
to every opening of duty, seeing that all things are possible to them that believe.
And yet I fainted in my mind many a time,
and seemed to be one of those who have no faith: so that,
on reflecting upon this little embassy, the prospect and the progress of it,
it seems as if it was all done for me by that good Hand,
which requires the passiveness rather than the activeness of the creature,
in prosecuting His designs.

Though I now give a pretty good account of the body, I may also add, that, sometimes,
my mind gets encompassed with glooms and discouragements, which nothing can dissipate,
save a state of resignation and quiet dependence upon the everlasting Arm of Omnipotence;
and this is often so hard to attain, that I am afraid of falling in the struggle,
when a hope is again revived, of being under divine protection,
and that the day`'s work is really going forward.
This, at times, introduces a quiet serenity,
and strengthens to leave the things that are behind,
and press forward to those that are before.
The sympathy of my friends under my late trials,
has been considered a favour of which I am unworthy;
and there is undoubtedly no better way of securing it
upon the foundation of gospel fellowship,
than by learning to live without it,
and looking singly to the Rock from whence all good things are hewn,
and the hole of the pit, the humbling dispensations of infinite wisdom,
from whence they are dug.

[.small-break]
'''

+++[+++Soon after the yearly meeting at London, they proceeded for Clonmel in Ireland,
where she was favoured to arrive in safety, in the sixth month, 1787,
with her health much improved, and under a good degree of peace and satisfaction of mind;
which continued for some time after her arrival,
as a source of consolation and encouragement: she writes as follows:]

[.small-break]
'''

Our removal has altogether been blessed with a good
degree of that peace which passeth understanding,
and attended with such circumstances, thus far,
as we have great cause to be thankful for.
An unmixed cup of comfort in human life, is what my short passage through the world,
has taught me not to look for, and a small degree of religious experience,
not to pray for; and yet to pray for those things which are really good for us,
will ever require the renewings of that Spirit
which only breathes the will of the Father.
Nature shrinks at suffering; sometimes I am ready to anticipate a draught of it,
proportionable to the late and present degree of favour;
and sometimes I am flattered with a language that tells me, "`it is already drunk,
and that the bitterness of death is past.`"
An humble, resigned mind is however always our duty and interest to press after.
It is a fortification against the varied assaults of Satan,
and a sufficient portion of Gilead`'s balm for
every afflictive dispensation of infinite wisdom;
both of which, if my natural life is spared, will, I do believe, be my companions,
and prove frequent trials of an abiding and advancement in that gospel Spirit,
which loveth, hopeth, and endureth through all.

[.small-break]
'''

Fourth month, 1787.--Your company was pleasant to us, and the remembrance of you is so,
and I trust will continue as long as the sincere engagement of our minds is,
to be branches in the same Vine.
Though separately and unitedly we may experience the chilling blasts of winter,
and feel the dryness and strippedness peculiar to that season;
yet learning in the school of Christ, in every state to be content,
and perceiving with increasing clearness, where the sap remains, we can rejoice therein,
and salute each other in true poverty of spirit.

[.small-break]
'''

Fourth month, 1787.---I received a kind encouraging letter from thee some months ago,
when, with many others,
I was about the remains of our dear friend +++_______+++. We had been paying,
for a few days before, the last office of friendship to him,
and were witnesses to the awful conflicts of his spirit, in struggling,
after many years disobedience to the openings of Truth,
for that eternal peace for which his soul was poured forth like water,
and his bones seemed out of joint; but divine compassion was near,
through the efficacy of renewed visitation, to gather into the heavenly garner.
The season was altogether so deeply affecting to my mind,
which was low and depressed when I went,
and I got so involved in the gloomy passages of death through which he had passed,
that it seemed as if many circumstances attending my continuance in mutability,
were lost in the prospect of that solemn period wherein mortality must be put off.
But on reading that part of thy letter wherein thou sayest, that in thy late illness,
thy hope was abundantly confirmed in the invisible power of an endless life,
I was favoured with a little glimpse of the saints`' inheritance, which, at times,
has revived ever since, as a cordial to my mind: for in the course of divine wisdom,
the hand of affliction, and deep spiritual probation,
has lain steadily upon me for many months.
Thou wouldst hear of an illness I had at Sheffield,
which occasioned my dear husband`'s hasty return.
My dwelling, for some time, seemed to be at the gates of death,
both spiritually and naturally; being in that state wherein I could say with the spouse,
that "`I sought him whom my soul loveth, yea, I sought him upon my bed,
and found him not,`" yet his invisible Arm being underneath,
was graciously revealed in an acceptable time, when, through sore tribulation,
a resigned frame of mind became more my experience.

[.small-break]
'''

Fifth month, 1787.--If the right thing does but prevail in the approaching solemnity,
it may be a time of healing.
Those whose spiritual faculties are alive in the Truth,
can hardly fail of beginning to feel an exercise on that account;
and no doubt it is necessary that it should be so,
in order to prepare and reduce the minds of Friends to a state of childlike simplicity,
and that abasedness of self, which endureth all things, hath nothing to lose,
and therefore, with Christian firmness, rejoiceth in that tribulation,
by which the pure lowly seed of the kingdom triumphs in
overcoming evil by that which is good.
Thou and others have had to drink many bitter cups in that place; and it may be that,
through patient perseverance in well-doing, in secret suffering with the seed,
maintaining the faith in that power through which miracles are still wrought,
the day is approaching,
wherein that life which is the light of men may become more
conspicuously the crown and diadem of our assemblies,
and of the services performed in the church.

[.small-break]
'''

Fifth month, 1787.--I received thy letter, and was pleased to hear from thee,
though the account of thy health, etc., was not so favourable as might be wished;
but I hope that after thou got set off from home,
and became resigned to what had for sometime appeared right,
thou would revive both in body and mind.
I have frequently known it to be the case with myself,
having been often worse just before setting out,
when the mind was depressed with the weight of future engagements,
and loaded with the sense of its own exceeding great weakness,
and inability to do any good; and at the same time,
having the comfortable enjoyment of divine help veiled till the needful season.
This experience was never more confirmed to me than in the present journey,
nor the sufficiency of that Arm, which remains to be mighty to save,
is strength in our weakness, and a present helper in the needful time.
If we are but favoured in our future stoppings, to increase in this experience,
our trials which are in the way to it will not be too heavy,
in comparison of that pure consolation which they produce:
and as we are endeavouring (all of us I hope) to move forward in a
line of simplicity and faithfulness to what we apprehend is right,
do not let us add to our difficulties, by admitting carnal reasonings,
and taking too much thought for tomorrow;
but rather labour after that great attainment of living one day at once.

[.small-break]
'''

Sixth month, 1787.--You will see by the foregoing,
that we are arrived at the intended place of our abode,
and have ventured to ask at last for a recommendation
from our friends of the monthly meeting.
I trust it is with diffidence, and the humbling sense that we are liable to err,
that we take this step; and yet, as it appears in the way to peace,
it is no doubt safest to take it, and also most consistent with good order.
We wish not to get from under that disposition which,
in the feeling of creaturely weakness, "`feareth always,`" lest the subtle,
transforming enemy should beguile us, induce to eat of that which is not good,
and beget a confidence in our own strength and sufficiency to preserve ourselves.
A self-righteous spirit is greatly to be dreaded;
and though a state of doubting and discouragement is attended with many more sorrows,
yet if the faith remains unshaken, it is at times refreshed with that precious dew,
and the springing up of that well of life, which make amends for all,
secretly replenish the drooping, yet waiting mind,
and encourage it to press forward in the way which the vulture`'s eye hath not seen,
nor any natural fierceness ever trod therein.
Well!
I trust so much we may say, that our minds, since leaving England,
have been bowed in contrition before Him who sees in secret, and settled, sometimes,
in a quiet dependence upon his almighty Arm,
rather desiring to be sustained in obscurity, than to be accounted anything amongst men.

[.small-break]
'''

Eighth month, 1787.--Your joint salutation was truly acceptable;
for though our love was not lessened, yet the sensible feeling of it,
on reading your letter, was comforting to us, and strengthened the desire,
that neither heights nor depths, things present nor things to come,
may ever be able to separate us, either from the love of the great Shepherd,
or from any of his faithful flock; of which number, may we, beloved Friends,
approve ourselves in all humility and godly care,
enduring hardness as good soldiers of Jesus Christ,
and not in our wills entangling ourselves with the affairs of this life;
but seeking above all things to please Him who hath
mercifully called us into the spiritual warfare.

Ah poor +++_______+++ indeed! anything that denotes the entrance of the wolf,
seems to touch my tenderest feelings;
because that little part of the great Shepherd`'s flock has been peculiarly visited,
and their welfare the object of my frequent and fervent solicitude.
Oh what need there is of watchfulness! truly the wolf cometh to tear and destroy, though,
in order to deceive, he may put on the sheep`'s clothing:
so that nothing but the true light can discover the hidden things of his dishonesty.
I have had cause to say, since leaving my native country,
that the divine hand is full of blessings,
and that our real comforts depend not so much upon outward circumstances,
as on that holy attractive influence,
which at times graciously opens a passage for the humbled mind,
out of the cumbers and discouragements of the present time,
into a state resembling the green pastures of life,
and enables to lie down in quiet resignation as beside the still waters;
leaving future events, when we have done our best,
to that power which can turn the wilderness into a fruitful field,
and cause the fruitful field to be counted for a forest.
When this good is mercifully near, and we are favoured with the common comforts of life,
there ought to be a grateful acknowledgment thereof, as well as obedient returns.

[.small-break]
'''

Eighth month, 1787.--Thy brotherly salutation confirmed a hope I had entertained,
that there lived in both our minds such a degree of true love,
that whether we thus conversed together, or not,
we should nevertheless be favoured to feel one another in our respective lots,
and experience the truth of that saying, "`deep uttereth unto deep.`"
My dwelling, in general, has seemed so much in twilight,
that meditation suited me better than action,
and the increase of my acquaintance with the everlasting Friend, whose name is Wonderful,
and whose works are inconceivably so to the natural mind,
has seemed an enjoyment of the very essence of all friendship.
In seasons of awful retirement, since I came this time to this land,
my spirit has saluted the few fathers, the brethren and sisters, yea,
and the instructors too, whose counsel is the counsel of Truth,
and whose joy is in its prosperity: and O! that my steppings amongst you,
may be such as to bring no dishonour, nor be the occasion of stumbling to any!
I wish to be the companion of such as faithfully and secretly
labour for the increasing prevalence of gospel power;
that so, through its purifying and sanctifying operations, every work may be wrought,
and become an object of the blessing which makes truly rich.
Tribulations are undoubtedly the lot of all,
who are seeking to follow their Lord and Master in the regeneration;
but He who knows what they stand in need of, in His own due and appointed time,
reveals to them His consolations, if they are willing to dive deep enough for them;
for thou knowest it is in the deeps that wonders are seen, and pearls procured.
If I knew how to put into words,
the variety of my sentiments and feelings since coming to Clonmel,
the freedom I feel with thee rather urges me to it; but some way or other,
they seem enveloped in an undesigned secrecy, and whenever I attempt to unfold,
there is a sudden restraint, like the turning of a double lock,
and a wise and gracious intimation, to keep in my tent.
The Lord is the tent of Jacob.
How desirable is it then to be of the wrestling seed, the Jews inward,
"`of the circumcision that worship God in spirit, rejoice in Christ Jesus,
and have no confidence in the flesh:`" for these, knowing in whom they have believed,
have the refuge of the righteous to flee to; and being thus exercised and favoured,
no matter how little and simple such appear, how much they feel their own weakness,
nor how prostrate they lie at the feet of their Master, where,
with reverent attention His gracious words are heard and received.

I have often feared that, for want of faith enough herein,
and a patient waiting in the abasement of self,
for the renewed revelation of the divine will, the carrying forward of the Lord`'s work,
both in individuals, in the visible church, and in the earth in general,
should be retarded;
and those designed to be the instruments thereof should
forbear to follow the Lamb through suffering,
and to fight under his banner,
should lose that hope which maketh not ashamed (because the love of
God is shed abroad in the heart) and cast away their shield,
as though it had not been anointed.
Well! may we profit by these considerations;
and looking forward beyond the things that are seen which are temporal,
to the things that are not seen which are eternal, hold fast our faith,
and the profession of it without wavering,
seeing that he is faithful who hath mercifully called us.

I observe thy consignment of a few lovely plants to my care;
but hoping and believing that they are divinely cared for,
and are already taught where to seek their own bread,
I feel particularly cautious of being the means of drawing
their attention to any source of comfort or instruction,
inferior to that which has been opened in the secret of their own souls.
I wish them to be more and more acquainted with, and singly to rejoice in,
the voice of their beloved; and I know this is all thou covets for them.
But we must both allow,
that visited minds are sometimes in danger of
seizing and resting in secondary consolations,
by placing an undue dependence upon the instrument of their good,
and being thus prevented from getting down to those nether springs, where,
with pure and humble rejoicing, the spirit draweth water, and no flesh glories.
I do not mean that these dear girls are in any danger of being too much attached to me;
because they have neither occasion to be so, nor are so unwise; but though I love them,
and have apprehended myself constrained to demonstrate it,
yet my own state generally feels an object of the compassion
and sympathy of the feeblest traveller Zionwards;
and this consciousness makes me keep much at home, and mostly in my chamber,
where the sweet society of my beloved Robert Grubb, and our truly valuable +++_______+++,
sends back, now and then, a rising sigh, and urges me to number my blessings;
setting before me the comfortable experience of the apostle,
which I am zealously pressing after, that of learning "`in all states to be content.`"
We have been favoured with many epistolary visits from our friends in England,
which are not unlike little brooks by the way; but ah,
we may sit by them till they dry up! however, comforts they are in their proper places.

[.small-break]
'''

Ninth month, 1787.--Every blessing is at the disposal of unerring wisdom;
and our true enjoyments are generally proportioned to the resignation our minds attain,
to surrender whatever we possess to the turnings of the divine hand;
counting nothing truly good but what is purified by it.
This is a state which sweetens the bitterest cups;
and sees beyond the transient gratifications of a worldly superficial spirit;
and is only arrived at by a single attention to, and humble waiting and dependence upon,
the secret monitions of the Spirit of Truth.
Pleasant prospects, or enjoyments of any kind, are often much veiled from my view,
or shaded with a gloom, which the fallacy of human judgment,
and the futility of all natural gratifications,
cast upon the most lively and lawful ideas: having, therefore,
fixed our eye upon one glorious object,
O may it be preserved single to the end of the
race! that our running being with patience,
and the steps we take attended with light at the finishing of the work assigned us,
we may then be indisputably convinced, that having had no continuing city here,
we have found one which hath foundations.

[.small-break]
'''

Ninth month, 1787.--As the present scene is, consistent with the nature of things,
chequered with a variety of circumstances and feelings,
we must endeavour after that fortification of spirit,
which so endures all things as to profit by them,
and render ourselves objects of the care of the great Shepherd.
Just to arrive at an attainment of this kind,
is nearly all our drooping minds are led to desire,
without any extraordinary exertions for enjoyments out of the line of divine appointment.
I seem, at times, more and more encompassed with doubts and fears;
faith is often deeply tried, and such depressions for a little while come over me,
that conscious of having ventured, at the call, to walk as on the sea,
and the supporting evidence withdrawn, my secret cry resembles poor Peter`'s when he said,
"`save Lord or I perish.`"
Nothing short of divine compassion, and the renewed extension of holy help,
can strengthen us to press forward with acceptance
through the few succeeding probations of our day,
and open in us that eye of faith which, looking beyond them all,
brightens at the glory that shall be revealed unto those,
whose garments have been washed and made white by the spirit and power of the Lamb.
There is something in us so prone to settle down at ease in prosperity,
that without some fatherly chastisements,
we might forget from whom we receive our spiritual and temporal blessings.

[.small-break]
'''

Tenth month, 1787.--My mind, on returning and since,
was favoured with a secret humble trust that I was not out of the way of my duty,
in accompanying to Enniscorthy and Carlow, nor in leaving you at the latter place;
though my stay afterwards in Waterford was not unaccompanied with that mortification,
wherein no flesh can glory, and which was, no doubt, in mercy dispensed to us,
to keep the poor vessel in such a degree of sanctification and honour,
as to be at all fit for use in the spiritual family.
I conclude that I need more of this kind of dispensations than others,
because I think more of them falls to my lot, which proves there is more to mortify.
But though I often imagine myself ready to faint,
yet my fervent prayer is that I may not utterly;
but rather be strengthened to endure the cross,
and despise the shame of creaturely abasement, looking to the Author of all true faith,
for such renewed supplies as to steer safely through this uncertain state of being,
and for ability, in the due and appointed time,
to finish the wisely allotted portion of work,
in reverent dependence that that which is right, and abundantly more than we deserve,
will be mercifully recompensed.

In the service wherein thou art now engaged,
I trust help will not fail of being afforded in the needful time,
so as to give you all abundant cause humbly to acknowledge,
in the winding up of your visit, that ye have lacked nothing.
Perhaps the line of your proceeding, as to passing from place to place, is right;
but some way my mind follows you with a sort of regret,
that more time was not allowed to have visited, if Truth had opened the way,
the families of Friends in the station of ministers and elders.
There is much truth in a common saying, that the work which is well done, is twice done;
and though this may be found the more mortifying and arduous part of the service,
yet the necessity and propriety of it being great,
the peace resulting from faithful labour therein, would no doubt have been proportioned.
But this seems like an unseasonable hint,
and I don`'t know any use there may be in dropping it,
except by way of preface to an observation I was about to make,
that Friends upon religious visits often appear to be cramped in their passing along,
from a sort of human prudence which dictates their making a long string of appointments,
perhaps exceeding what is perceived by the eye of faith:
thus they may be prevented from approving themselves those simple,
humble followers of the great Master,
which in the sincerity of their own hearts they have earnestly desired to be.
Whether this proceeds from the want of faith in individuals,
or the undiscerned influence of general custom, I know not,
but certainly it is a safe and hidden path which the Christian traveller walks in, when,
in no respect, he desires to take the lead, but resignedly gives himself up to be led,
step by step through the difficulties of his allotted line of service.

[.small-break]
'''

Eleventh month, 1787.--I received this morning, with comfort,
the long retained token of thy affection; and can assure thee I am poor enough to enter,
with heart-felt sympathy, into the situation thou describes,
possessing nothing whereon to build hopes of divine acceptance,
unless renewed by the creative word of Omnipotence,
and replenished with strength to hold on my way.
Let us not then cast away our confidence, nor conclude ourselves unprofitably tried,
when we see ourselves as we are; but rather rejoice in this tribulation,
and temptation to call in question all that selfish propriety,
which human nature would subtlely suggest to us as wrought by the heavenly Hand.
Count it all joy that thou art so clothed with a secret sense of corruption,
and art sensible of thy own incapacity to do any good thing;
and rather desire to live long under these humbling impressions,
than to be taken away from all opportunity of magnifying that "`grace,
by which thou art what thou art,`" poor as thou thinkest thyself.
Should we be foolish enough to think we know anything,
the voice of Wisdom would soon inform us, that we know nothing as we ought to know:
in patience then possess thy soul,
and keep in view an increasing resignation to every secret pointing to duty.
We are very apt anxiously to look for that good in our own way, and in our own time,
which is only to be obtained by doing the divine will, after we have known it;
forgetting that they who err herein, are beaten with many stripes:
if this is not now thy state, the hint will do thee no harm.
He who knows what is best for us,
wisely makes us weary of ourselves and all visible objects,
in order to beget that hunger and thirst after righteousness,
to which the blessings and promise belong; and so to attach us,
in sacred union with himself, and love to his cause,
as that in these days of lukewarmness in holy zeal, when the pure seed,
through desertion, breathes the powerful query, "`whom shall we send,
and who will go for us?`"
we may, in singleness of heart, and living faith in divine sufficiency, answer,
"`here am I, send me.`"
Though this seems an intercourse superior to what we often think is ever allowed us,
yet the gentle movings of the spiritual life,
and the subjected disposition of our minds thereto, in my apprehension,
strongly resemble it; and if many visited young people in this land, as well as my own,
had placed their dependence upon the sanctifying operation of that sacred fire,
which quickens the mind and prepares the sacrifice,
rather than consulted vainly with flesh and blood,
they would have been stronger in the faith, and more of them righteous contenders for it.

[.small-break]
'''

Eleventh month,
1787.--It is by a single dependence upon that divine and
creative power by which all things were made that are made,
that we find hard things made easy, and the mixture of human events so sanctified,
as to be rendered salutary portions; the immortal part in us is strengthened to ascend,
as with wings of faith and love, that mountain spoken of by the prophet,
where "`nothing can hurt or destroy.`"
A true gospel spirit so strongly resembles this desirable habitation, that when,
in some degree of its own purity, it breaks in upon our impoverished minds,
we are renewedly convinced that flesh and blood hath not revealed it unto us;
but humbly submitting to its operations and directions, self becomes of no reputation,
"`and the Lord alone is exalted in that day.`"
I feel, as I am writing, a secret breathing for thy brother`'s and thy preservation,
and encouragement to pursue invariably the one thing needful, because it is sealed,
that that shall never be taken away.
The purity and permanency of heavenly treasure,
are objects of no small magnitude to the enlightened mind,
which has seen the fluctuation of visible enjoyments, and the vanity of all its efforts,
without divine assistance, to obtain the smallest particle of true spiritual bread,
or one drop of that consolation which is only derived from the pure gift, or well in us,
springing up into life everlasting.

But it is not enough to be enlightened; we must also wait, in the abasement of self,
for the thing spoken of and desired; and be willing to accept the apostle`'s exhortation,
not to be conformed to this world, but transformed by the renewing of our minds,
so as to prove what is the good and perfect, and acceptable will, and then to do it,
even at the loss of human approbation,
and all the riches of the unregenerate will and wisdom of the creature.
Here we learn the mystery of buying the truth, and selling all that we have for it:
a mystery, which amongst many more, is hid from the wise and prudent,
and revealed unto the babes in Christ.
I often lament my unfitness to receive these things, and a disposition,
out of the clearness and power of the gospel, to accommodate myself,
particularly in company, to a worldly spirit,
rather than suffer as a fool for the seed`'s sake;
and yet I trust I am making war against it, and have victory in view.

[.small-break]
'''

+++[+++Her mind had frequently, for a considerable time before this period,
been closely exercised with an apprehension,
that it would be required of her to pay a religious
visit to some parts of Germany and France:
and a few months after her settlement in Ireland,
this concern increased with such weight and evidence, that she was constrained,
in resignation, to spread it before the Friends of their monthly meeting; who,
after solid deliberation and sympathy, concurred therewith,
and gave her their certificate of unity and approbation.
She received also the near concurrence of their quarterly meeting and
that of the morning meeting of ministers and elders in London,
and set forward on this journey in the third month, 1788, in company with her husband,
George Dillwyn and his wife, and Mary Dudley; who were also bound to this service,
and engaged therein with the unity of Friends.

The following parts of her letters on this occasion,
describe the previous exercise of her mind, and contain a pretty regular,
though short account of the journey, from the commencement of it, to its conclusion.]

[.small-break]
'''

Twelfth month, 1787.--My mind after a season of deep trial and exercise,
was led to visits in what appeared to myself an extraordinary degree of gospel love,
many in that country, and some parts of Germany contiguous thereto; fully believing,
according to my feelings, that there were spiritual worshippers in those parts.

[.small-break]
'''

Twelfth month, 1787.--If the prospect before us be in divine wisdom,
we have great cause to acknowledge that it is unfathomable, and past our finding out,
because of my incapacity, in every respect,
to perform such a journey to the honour of the great cause.
I wish, however, now to leave caring too much about the future,
and endeavour after quiet resignation; well knowing,
that by taking ever so much unprofitable thought, I cannot add one cubit to my stature,
nor make one hair of my head white or black; and also hoping,
that when it comes to the trial, the will may be accepted for the deed;
which I have no doubt will be the case, if the province meeting,
or my sympathizing friends, advise me against it;
or if no Friend of superior weight in the ministry, proves under the like concern,
and admits us into their company.
Discouragements of various kinds crowd in at times upon me,
but when gospel love flows from the living fountain,
it overpowers all selfish considerations, and shows me my own unworthiness to be,
in the least degree, employed in the divine hand.

[.small-break]
'''

First month, 1788.--Our situation at present,
requires at least a grain of that faith which has power to remove mountains; for, truly,
vain is the help of man, in cases where the pure seed is to be exalted.
A sense of our insufficiency to do any good thing without divine assistance, will,
I trust, whatever our trials or temptations may be, so humble us,
as wholly to prevent a vain dependence upon anything of our own;
but surely there is as much need for watchfulness and prayer at this day,
as when the disciples were immediately recommended to it.

[.small-break]
'''

First month, 1788.--My mind is often under a load of exercise on my own account,
and in care lest the precious cause should suffer by me.
The present is a time of deep trial and searching of heart,
lest we should be meddling with, or doing,
anything which is not in the clear discovery of gospel light.
When I consider how little I am experienced in
the station wherein I may be likely to move,
the newness and peculiarity of the service in prospect,
and even the weakness of the outward tabernacle,
(which to be sure I think least of) my feelings suggest the applicableness of the saying,
"`I am a worm.`"
This however cheers me, that without some degree of clearness, we need not,
neither shall attempt to move.

[.small-break]
'''

First month, 1788.--To be furnished with that excellent armour thou speaks of,
is truly desirable, and when without it, the prayer of my heart is,
quietly to keep in my tent; and even with it, to make no boast,
nor to use it but by renewed commission.
It is one of the essentials for the poor Christian traveller in every station in life;
because of the open attacks, the side blows,
and crafty pursuits of our unwearied adversary.
I feel them daily, and long for an increase of strength to resist him,
steadfast in the faith.
He many times seeks to make our hearts sad, when the Lord has not made them sad,
and to perplex and embitter our passage through life,
when he perceives that that is the length of his chain.
We propose setting off for Cork in the morning.
Even that is a burden;
and I might soon work myself up to believe that I am not able to go half way to Clogheen.
How admirably wise, and adapted to the weakness of our frame,
was that exhortation of the great Master, "`take no thought for tomorrow:`" this,
and such like compassionate counsel,
sometimes drops into my mind in the midst of my conflicts,
and proves to be words of that kind which both winds and waves obey.

[.small-break]
'''

Second month, 1788.--I have been of late considerably indisposed,
but upon the whole am much better, though every day sensible of having,
by some means or other, a very broken constitution.
If it do but last till the portion of work allotted me is finished, that is enough,
even though it be performed under the pressure of bodily infirmities;
all which maybe no more than necessary to keep the mind to its proper centre,
and direct its attention, singly to an inheritance undefiled, and which fadeth not away.

[.small-break]
'''

Second month, 1788.--Though the root of any good affection be alive,
yet there is but one right season prescribed in divine
economy for it to manifest itself in the branches,
by causing them to bud, blossom, and bear fruit;
and that being the spring time of divine favour,
when the Sun of Righteousness breaks forth upon the Lord`'s plantation,
we must wait for it in patient, though earnest expectation,
that as our abiding is in the allotment of pure wisdom, the winter, however long,
will in time be past, the rains and tempests will subside,
the time of the singing of birds come, and the voice of the turtle be heard in our land.
Then, though we enjoy it in but a small degree,
we can salute each other in spirit and word, and hail all those who, like Mary,
are bearing precious seed,
let their stations in religious or civil society be what they may.
A salutation of this sort springs in my heart to my endeared friends;
to the parents who have known Him that is from the beginning,
and to the younger branches who have measurably
been strengthened to overcome the wicked one;
sincerely desiring, that as we have, through abundant mercy,
been begotten again to a lively hope by the power of the first resurrection, we may,
through our varied exercises, keep our eye single to the preserving power of divine love,
and to that inheritance which is incorruptible and fadeth not away,
reserved in heaven for those who are kept by the virtue thereof,
and the precious gift of faith, unto the last day.
For herein is great joy, when outward circumstances,
and the accuser of the brethren speak trouble;
here the tribulated Christian traveller finds an undefiled rest, and by the light,
commits his spirit in pure resignation to the guiding hand of Omnipotence;
feeling to the consolation of his afflicted soul,
that for all his omissions and commissions, he has an advocate with the Father,
not an high priest that cannot be touched with a feeling of our infirmities,
but one tempted in like manner, and who knows how to succour those that are tried.
Well might the Psalmist,
who was so largely acquainted with the dealings of infinite Wisdom, exclaim,
"`how excellent is thy loving kindness, Lord; because thereof,
the sons of men put their trust under the shadow of thy wing.`"

[.small-break]
'''

Third month, 1788.--We were at their weekday meeting here yesterday,
and had a large public meeting in the evening, in both of which, I trust,
we were owned by the Master of all rightly gathered assemblies,
and might have been more so, if resignation,
and a willingness to appear weak and foolish as we are, had been more experienced.
I often think that if, in this respect, we were sufficiently humble,
we should fare better than we do; and that,
whilst we were preserved from foolish preaching,
the foolishness of preaching (as the worldly wise
esteem it) when in the demonstration of the spirit,
would be blessed beyond our conception,
and made something like the barley loaves by which the multitude were fed.
We know our own employments; but the mysterious workings of the heavenly hand,
in carrying forward the redemption of the nations from the fall,
are wisely concealed from us.
Yet the inquisitiveness and judgments of the creaturely part,
often lead us into discouragements when we should, in the simplicity of little children,
do as we are bidden, and leave the event to Him who knows best how, and when,
to use the weak and foolish things of this world, to confound the wisdom of the wise.

[.small-break]
'''

Third month, 1788.--By way of apology for my silence let me say, that writing,
in many respects, less suited the disposition and qualifications of my mind,
for many months back, than a silent meditation upon the nothingness of self;
which was far from always obstructing the sweet circulation of Christian fellowship,
and solicitude for the preservation, under the shadow of the Holy Wing, of all those who,
by dispensations unerringly wise,
are involved in the depths of discouragement and dismay,
with respect to their own ability to promote any good word and work,
and yet whose diffident minds are often assaulted by the accuser of the brethren.
These have, however, no occasion of casting away their confidence,
when they reflect upon the many deliverances which they
have received through the communication of eternal help,
and remember the gracious promise of the great Master,
to those who dwell under his righteous government; "`lo!
I am with you always, even to the end of the world.`"
You are as epistles written in my heart, wherein I often meditate with secret comfort,
under the belief that you are, in unerring wisdom,
designed to be fellow-helpers in promoting the cause of Truth and righteousness,
and fellow travellers in the way thereof.
If you meet with trials and difficulties, you know there is nothing new in that;
they have ever attended the footsteps of the flock;
and when we are careful not to multiply them by any default of ours,
they are so many proofs of our being the followers of a suffering Lord,
which are sealed by our extracting benefit from them, and sanctified by obedience.
Hold on then as you have begun; "`count nothing too near,
or too dear to part with for Christ`'s sake and the
gospel`'s;`" fear not that humiliating baptism,
which crucifies us to the world, and the world unto us;
and may the Shepherd of Israel lead you as his own sheep,
convey to you the indisputable intelligence of his own will,
and so preserve you in a state of fidelity to himself,
as that none shall be able to pluck you out of his holy Hand!

[.small-break]
'''

1788.--It is a favour that the best root needs no great profession,
or specious words to nourish it;
it is not strengthened by a multitude of luxuriant branches, though, if it be alive,
it will discover itself by little buddings, blossomings, and fruit.
Whilst therefore we are not unprofitably anxious, in time of winter,
for that which is not to be had, neither let us be too unconcerned,
when the full time is come for the manifestations of the life of the tree,
nor count them of little value, but cherish and protect them, lest some indiscreet hand,
or spirit in ourselves,
should rub off that wherein is hiddenly contained the choicest fruit,
and so render the coming of the spring,
and the genial influence of the Sun of Righteousness, ineffectual to us.
Many cautions are necessary under this simile,
for even when a tree bids fair for profiting and enriching those who possess it,
if that which it is to produce in the fulness of time, be gathered before it is ripe,
it sets the teeth of the eater on edge, and causes the tree to be evil spoken of.
Thus, on many hands, dangers occur to us in the conduct of our gifts,
in religious and civil departments.
How needful is it then, to ask wisdom where it is to be had,
and to use it when we have it;
and also to cultivate that prudence which is her sister in service,
and which often opposes plans of our own contriving.
These are sentiments which, though thrown out to you, tend to show me where, and how,
I often miss my way; and excite me to review the consideration of that merciful kindness,
which is sometimes extended to us in a very low estate; when, in our own eyes,
we seem most undeserving of that help which can alone lift up our heads in hope,
when the floods of affliction prevail, and the billows pass over us.
May we deepen in our experience of the Lord`'s fatherly dealings with us; that so,
approving ourselves more and more babes in Christ,
our knowledge of the mysteries of the kingdom may be pure, and of that preserving nature,
that never puffeth up.

[.small-break]
'''

1788.--It is not because thou and thy dear wife were forgotten by us,
that neither my husband nor I have, since our return from England, dropped you a line.
Silence, on my part,
has chiefly originated in a consciousness that I have not been deep enough in my spirit,
so to draw water out of the wells of salvation as to be able, in true religious sympathy,
profitably to visit thy often discouraged mind.
To feel our incapacity to minister, in a spiritual sense,
a cup of cold water to ever so feeble a disciple (unto whom we may
nevertheless be bound in a constant friendship) is a merciful impression;
because it humbles us, and seals upon our spirits that invariable truth,
that "`there is none good but one.`"
What is this sense, but the anointing itself, which has holy certainty in it,
seeing that it is no lie.
Except it abide in us to this effect, our profession of being believers is vain;
we shall grow weary in the Christian life,
and our own righteousness will soon exhaust our strength:
tor supplies from the eternal Fountain would soon cease,
were we to appropriate them to the prosecution of ends
which the Lord never required at our hands,
and neglect that life of faith, of humble dependence upon the pure gift,
and those precious influences, hope and charity,
which constrain us to render unto the great Lawgiver, in his time only,
whatsoever he requires at our hands,
though incomplete and foolish to the unsimplified mind.

[.small-break]
'''

I often wish, on my own account, to be more in substance than I am.
That infinite kindness has made me a partaker of the common salvation,
has shed abroad in my heart a measure of his love, and strengthened me, at times,
to lay hold on eternal life,
I trust the deceivableness of unrighteousness will never be suffered
to draw me from the belief of But I look at the office of a gospel
minister with an awfulness which convinces me,
that there are baptisms, humiliations, and deaths peculiar to it; and that,
except these are often renewed, in order to strip off the plumage of past experience,
and of that knowledge of heavenly things, which, being like yesterday`'s manna,
cannot sustain, but subtlely puffs up the mind, that babe`'s state,
unto which the mysteries of the kingdom are unfolded, is unattainable,
and the inscription of holiness unto the Lord is withheld,
because they are not cleansed through the word spoken unto them.
What will it do for us, even to be called to the work of the ministry,
if we submit not to those purgations which unerring Wisdom appoints?
We may become vessels marred on the wheel; or, to use another simile,
if we suffer not ourselves, in Christian patience, to be bundled up as with the dry rods,
and to be as destitute of verdure as they, we may,
for want of complying Math the appointed means of fruitfulness,
frustrate the divine purpose to distinguish those who
are invisibly preserved by the hidden life.
Perhaps it may not be unsafe to conclude, that in our Society there are such defects;
but, as an individual, I find it safest, in conformity to the great Master`'s command,
to judge not, except through the spirit of the Son,
the judgment of the everlasting Father is known; and at such seasons,
the mind is too much humbled vainly to feed on this revealed knowledge.

[.small-break]
'''

Third month, 1788.--According to present appearances, we,
(I mean our little company,) stand in abundant need of the whole armour of light.
We are about to embark for a country, the language of which none of us know,
and in expectation of a path wherein we can see no footsteps,
and which must be attended with new and various trials.
May our trust be in the Lord alone, who is able, in seasons of the greatest difficulty,
to increase our faith, and make way for us where we see no way.

Having the concurrence of Friends, we left London and proceeded for Harwich,
where we were detained several days for want of a fair wind;
during which time we had two meetings, and afterwards,
(23rd of the third month) the wind turning in favour of our leaving that port,
we embarked; but it was fourth-day night, the 27th, before we landed at Helvoetsluys,
which was nevertheless a favour, and I hope esteemed so by us all.
We got to an agreeable English inn there, and after a pretty good night`'s rest,
set forwards towards Rotterdam, by way of the Briel and Delf,
and came in safe rather late at night,
it being there a great day`'s work of about twenty-five miles.
We travelled in an open wagon the first seven miles,
the road being so bad that no other carriage could get along with safety,
and the rest of the way went in their boats called Treckschuyts,
which are drawn by a horse, at the rate of about three miles an hour.
This is a very pleasant and easy way of travelling,
and it was through a country made as agreeable by improvements as it is capable of,
being very flat and marshy.
Many of the inhabitants followed us through some towns, and gazed exceedingly at us;
and some of them, as well as they were able,
manifested a love which met that in us that drew us hither;
but the strangeness of our language to each other, was a continual discouragement;
yet as it was not of our own bringing on, we endeavoured to keep quiet under it,
and secretly desired that our minds might be so influenced, as to convey to them,
in silence, that which is better than words.

We have now got into so new a line,
that it is no wonder if we should be more than usually blind; and it will be well,
if some of us should be also more than usually
dependent and patient respecting our steppings;
for being separated and remote from our friends,
and some of dispositions rather hasty than otherwise, there is, no doubt,
a danger of sometimes pressing forward with too much earnestness,
and thereby of preventing the completion of those little services, in one way or other,
which are intended for the purchase of our own peace at least.
Though Holland was not much in the prospect of us who came from Ireland,
yet we have been favoured with something more than a hope,
that we are thus far in our places,
and feel a comfortable and strengthening unity one with another therein.
The desire of my mind is at present strong, that, though in ever so much weakness,
we may be enabled to pass through the country in that singleness and dedication of heart,
which may preserve us from condemnation.

We stayed three days in Rotterdam,
and had two public meetings at the meeting house belonging to Friends;
there are a great many English people in that city,
and the attenders of our meetings being principally of that class,
we had no need of an interpreter.
There are some serious people with whom we got acquainted,
and to whom our visit seemed acceptable, but no professors with us, except one person,
who cannot be expected, in his present state,
to throw much light upon the testimony of Truth;
but he was very willing to render us such services as were in his power,
which we took kindly.

From Rotterdam, we came forward to Amsterdam, by way of Leyden, Haarlem,
etc. and were kindly received by our friend John Vanderwerf Here our minds, generally,
got very low on divers accounts.
Several of us were poorly with complaints in the stomach,
etc. which strangers are subject to,
before their constitutions come to bear the difference of their meat, drink, air, etc.
The few under the name of Friends in this great city,
yielded us little of that strength which is the fruit of sympathy of spirit,
and inward acquaintance with divine requirings; and which, if right,
would have been truly salutary and cordial to us at that time,
as we looked upon ourselves then embarking upon the
most arduous and discouraging part of our journey;
having a great distance to travel, entirely unacquainted with the country,
strangers to all their different languages, except a little of French,
and no interpreter to accompany us.
Under these complicated trials, our faith got into the furnace afresh.
This was much the case with me, and my dear companions felt no less.
However, as we endeavoured after resignation,
and were sometimes replenished with strength patiently
to wait for renewed manifestations of duty,
way opened, by degrees, to get clear of that place.

We attended their little monthly meeting,
the business whereof was transacted in the Dutch language;
so that we had not an opportunity of judging much about them;
except that their appearance, and the feelings of our minds,
convinced us that true religion is at a low ebb amongst them;
and yet there is something tender which loves Truth, and with which,
a family visit amongst them, made us better acquainted.
We were comforted in the belief that their solitary situations are divinely regarded,
and hope that divers of their deficiencies in some
points wherein we have been otherwise taught,
are counterbalanced in the sight of holy compassion and justice,
by the sincerity of their intentions,
and the discouragements in many respects peculiar to them, which we, by experience,
know a little about.
The keeping up of a meeting for worship every first-day, in their weak state,
is an act of faithfulness, which we might be often ready to faint under,
were we in their situation,
separated from the strengthening communications which religious society afford,
(not having received a visit of this kind for four
years) and being despised amongst the worldly minded.
We had also three public meetings there,
which were attended by many of the inhabitants of different descriptions;
but there are a few with whose company, both in and out of meetings, we were comforted.
They are a serious, religious people, not connected with any society,
and believing in the spirituality of all true worship.

We paid a visit to one of their families, which consists of a widow, her son,
and two daughters, none of them young.
They are people of considerable property,
which they devote very much to the service of the poor.
They were affectionately kind, and demonstrated their unity with, and attachment to,
our principles, as far as they had heard them in the meetings which they attended,
and were fully convinced of the necessity of an inward work,
and that all true worship must be performed in spirit and in truth.
In a religious opportunity which we had with them before we parted,
the cementing influence of gospel love flowed amongst us like a stream.

From this family,
we were furnished with letters of recommendation to such as themselves in Germany,
some of whom we have seen to our satisfaction.

During our stay in Amsterdam, we were interpreted for, by John Vanderwerf,
or one of his sons, both in public and private.
It seemed strange, and rather hard to us women, especially at first;
but we soon got over it,
and had reason to hope that our religious communications were not materially affected;
our friend seemed to have an awe upjon his mind when he stood up, took off his hat,
and delivered, sentence by sentence, what was expressed.
Thus after spending eight days at Amsterdam, and being deeply tried in that place,
our minds were strengthened to leave it, the 9th of the fourth month,
with a renewed trust, that the great Shepherd of Israel,
who knows his own sheep in every trial and situation,
however remote from the knowledge and consolation of their friends, would superintend us,
and graciously reveal himself for our help, in the needful time.

We essayed to proceed by way of Utrecht, (where a few books were distributed,
and much love felt for the inhabitants) Nimeguen,
and through part of the king of Prussia`'s dominions, into the elector of Bavaria`'s,
to a place called Dusseldorff, where we again made a little stop,
finding a few who could speak English, and most of them French.
Here we commenced an acquaintance with a solid, religious man, named Michael Wetterboar,
to whom we were recommended by the people whom I have mentioned at Amsterdam.
Being gathered to the principle of Truth, and engaged to conform to, it,
as revealed in the line of his own experience,
he walks much alone in a dark and dissipated place.
He was a kind friend to Claude Gay, when paying a similar visit to our`'s in this country,
many years ago, and was rejoiced to see us.
He lamented the lonesomeness of his situation,
and said that his mind was strengthened by the visit.

From hence we went eighteen miles and back, out of our road, to Elberfeld, where,
as at many other places, for want of an interpreter,
we suffered what often appears to us an unavailing baptism for the testimony`'s sake.
But perhaps it is not so much so as we are apt to think;
the ways of the Most High are not our ways, nor his thoughts our thoughts;
we know not but this deeply humbling path,
and the secret exercises we have daily to pass through without any visible relief,
may have a use beyond our finite conceptions; so that it is safest to leave these things,
and outward considerations about them,
in the Hand which can bless and render fruitful the things which are not,
by causing them to bring to naught the things which are.
However, we found an opening to some solid conversation with a few in this place,
and understood that there are many religious people there;
but we were discouraged by the difficulties we
found in getting an acquaintance with them;
so we returned, after staying one night, to Dusseldorff.
We left that place, and passing through a dark country, arrived in two days at Newvied,
the 18th of the fourth month.

We have had very little rain since we came upon the continent,
consequently the roads are dry, but being for the most part a deep sand,
we have not been able to travel over it so quickly as is desirable.
Thirty miles a day, is I think, nearly the average of our expedition,
though we mostly travel post.
The vehicles are heavy, being generally covered wagons or clumsy coaches.
We mostly prefer the former, as ourselves and luggage meet the best accommodation in them.
The inns are pretty good, and the people respectfully kind to us,
and in that line but little difficulty occurs in making ourselves understood.
Our road has lain upon the banks of the Rhine,
and furnished us with prospects of a country extremely beautiful, and, in some places,
for miles together, covered with vineyards.
But the pleasure which we might innocently have derived from those scenes,
has met with continual damps, by the gross prostitution of sacred things which,
in the crosses and images thickly scattered upon the road,
give pain to every feeling whereby spiritual worship is promoted.
The Roman Catholics are very numerous in many parts which we have passed through;
but in most places,
the protestants enjoy the privileges they desire without interruption;
and amongst them there is undoubtedly an awakened, sincere-hearted people.

On our arrival at Newvied, we found a great change in the face of things,
it being a new and pleasant town, inhabited by serious protestants,
and principally by the Moravians;
though there are about twenty families of the Menonists,
and as many of a people who call themselves Inspirants,
but by others are often called Quakers.
We were directed to a Moravian inn, which proved very agreeable,
feeling ourselves in that family very much as if we were at home.
Here we were, soon visited by several of the Moravian brethren and sisters,
some of whose minds appeared unprejudiced, and intent upon spiritual improvement;
which drew them often to our apartments,
and opened a door for the communication of such gospel truths, as from time to time,
occurred; and we had a comfortable hope,
that they dropped into some of their minds as seed into good ground.
We had the advantage in that place of an interpreter,
a young man of the Moravian economy, who cheerfully befriended us on many occasions:
and though, at the first,
he appeared under difficulty in communicating religious matter which was new to him,
yet before we went away, his understanding seemed more opened,
and his feelings much more cordially disposed to the principle of Truth as we profess it,
and to the several branches thereof.

We had a public meeting in that place the evening before we left it,
after a week`'s deep exercise and secret suffering;
but this opportunity furnished us with renewed cause to put our trust
in the gentle puttings forth of the Shepherd of Israel,
and in the revelation of His power, which we humblingly find is sometimes withheld,
till the seasons of our greatest extremity.
The young man, our interpreter, readily accepted his office in the meeting,
without any previous request, and performed it with great solidity.
Our visit to that place was closed by a season of divine favour,
in a family which cheerfully received the testimony we had unitedly to bear,
to the efficacy of spiritual worship, and the necessity of preparation for it;
and in much love and tenderness of spirit we left Newvied.
"`O the depth and extent of the riches,
both of the knowledge and wisdom of God! how unsearchable are his judgments,
and his ways past finding out!`"

We had abundant cause in our travels through Germany, to say,
that we were led in paths which we knew not,
and frequently reduced to a state of extremity.
We were sensible, according to our measures,
of the mist of superstition and idolatry which overspreads a great part of the country;
and also had, at times, revealed that most sure word of prophecy,
which penetrates the obscurest recesses of Sion`'s travellers,
draws them into hidden fellowship one with another,
and unites them in the sufferings of the precious seed,
though differently situated in the world, and their profession in it various.
Thus were we led in paths which we knew not, and ways we had not seen,
and were often incapable of finding out those whom we thus felt,
and when we did discover such, we were unable, for want of a knowledge of their language,
fully to communicate to them: but trusting in the all-sufficiency of Almighty help,
for the supply of all their needs, we were favoured,
when dedication of heart had been attained, and the green pastures of life opened,
to lie down beside the still waters, and leave the event of our travel to Him,
who blesseth, or blasteth, at his pleasure.

From Newvied we came to Wisbaden, a place in great request for warm bathing,
there being several boiling hot springs in the town,
from which the water is conveyed to private cisterns, where it cools for use.
There seemed something rather attractive in this place to our minds, and yet,
as was often the case, discouragements prevailed over our best feelings,
and we proceeded to Frankfort, a day`'s journey.
There we stayed two nights;
but though we had letters of recommendation to religious characters,
yet for want of being able to make ourselves understood,
we had no conversation with any but a Pietist who spoke English but poorly, and who,
after some discourse on religious subjects, left us with professions of love.

From Frankfort we proceeded to Basle, a large protestant town,
where we arrived the 3rd of the fifth month.
Here our minds seemed arrested,
and all efforts towards pursuing our journey were painful,
till we had settled a few days under our exercise, and embraced, though in the cross,
such opportunities as opened for relief Having
some letters of recommendation to serious people,
they were presented to them; in consequence of which, several visits were paid us,
and we observed in some rather a critical investigation of our principles.
They were cautious of embracing us till they perceived the doctrines we held;
after which there was great openness in some of their minds,
candidly to receive such communications on
religious subjects as from time to time opened.
One of them understanding the English language well, was, in several instances,
a very friendly interpreter to us;
and his mind being acquainted with divine illuminations,
he often discovered symptoms of conviction and sensibility, when, as a channel,
the openings of Truth were passing through him.
In a large company to which we were invited, this person,
observing our disposition to silence,
kindly and feelingly proposed and requested a compliance of the company.

We were favoured, to our thankful admiration, with the humbling influence of divine love,
and strength renewedly to bear testimony to the necessity of
an inward preparation for the solemn act of true worship,
which requires neither forms nor ceremonies,
to render it acceptable to the Father of spirits.
The opportunity was concluded in solemn supplication,
which our friendly interpreter rendered, sentence by sentence, into the Dutch language,
with a reverential awe, whereby the liveliness of it was preserved.

We had also a comfortable season of retirement
in the family of another of our friends there,
whose wife and daughters profess not to see the
necessity of a religious circumspect life,
as he and his eldest son do; but they were affectionate and attentive to us,
and we had reason to hope,
received no unprofitable impressions by this little act of dedication.
This person conducted with true brotherly kindness towards us,
discovering great simplicity of heart, and an openness to receive the Truth, wherever,
or however he might find it;
being experienced in that great work of repentance unto life,
and ceasing from many entanglements in the world,
which he believed had a tendency to enslave his mind,
and to keep him in a state of separation from divine favour:
so that to meet with fellow pilgrims who could tell him
a little of their knowledge of the right way,
seemed like marrow to his bones.

We have several times fallen in with persons who kindly entertained Claude Gay,
in his lonesome travel through these parts;
and in Basle we have found two agreeable religious old men,
with whom he was hospitably sustained for three weeks.
They are of a people called Inspirants, and often by others Quakers;
but upon an acquaintance with them, especially at Newvied,
we found them no less active than other professors in singing, praying, preaching, etc.,
in their congregations.
They appear to be descendants of the French prophets;
and amongst them there is an honest-hearted number to whom the
love and language of the gospel flowed with more openness,
and appeared to be received with more simplicity, than amongst some others.
To these two elderly men we paid several visits,
which were not unattended with instructive conversation;
but this did not afford that relief which our exercised minds seemed to want,
nor could we comfortably see our way from the town, till we had,
in their family and amongst such as they might invite, borne testimony,
by our example also, to the necessity of silent waiting.
To put the light into the candlestick, so as to bear, even in private,
a testimony to the Truth, and spiritual anointing in silence,
is here a greater trial of our love and faithfulness to the cause,
than any can readily believe,
who have not been led amongst those who are ignorant of a cessation from their own works.

It was a season obtained with difficulty, and passed through in tribulation of spirit.
The candle was not easily put into the candlestick, and when there,
evidently suspected by these people, not to be in its right place.
But before the meeting closed, public testimony was borne to it,
and to the resurrection of that life which is the light of men,
being the only qualification of spirit,
to come forth from that state of darkness and death in which we are by nature,
and to perform any religious duties, or acceptable service to the Lord.
At the close of this opportunity, we parted with these two men in love,
though not a perfect unity of sentiment,
which appeared more fully by an affectionate letter which one of them sent after us.

There was also in this place, and in most others where we stopped,
a prejudice against women`'s preaching,
which increased the difficulty our minds often felt in
obtaining relief amongst a people of a strange language;
but though our efforts were few and feeble; yet as far as dedication clothed us,
and we were careful not to cast away our confidence,
we had ever cause gratefully to acknowledge that
great recompense of reward was vouchsafed,
and the soul strengthened to return to its rest,
under a renewed sense that the Lord had dealt bountifully with it.
The kindness we have met with in many places, exceeds what we might have expected,
having several times experienced so much of the promise fulfilled,
that we have met with brethren and sisters, who,
though not altogether of the same profession,
are fellow travellers in the Christian path.
Sometimes a wisdom appears in our being stripped of that outward help, so desirable,
of an interpreter; as in our present circumstance, if any good is done,
there is no part of it wherein the creature can glory.

There is one thing which exposes us,
that does not often suit the disposition of our minds, which is, that at the best inns,
where we generally go, we must always dine and sup at the ordinaries,
where there is often a great resort of company.
If there is any use in this mortification, it will amply make up;
the only testimonies which are publicly borne this way,
are by our men Friends keeping on their hats,
and refusing to pay for the music which sometimes accompanies our meals.
We took a coach from Basle to Bern,
where we stayed over a first-day pretty much in private, save that an agreeable solid man,
an Inspirant, paid us some visits, I believe to mutual satisfaction.
We heard of a religious exercised coachman for whom was left a book or two,
he not being at home.

[.small-break]
'''

+++[+++The following letter was written at Basle the 9th of the fifth month, 1788.]

[.embedded-content-document.letter]
--

As it is probable we may leave Basle without taking leave of thee,
and acknowledging thy kindness with a gratitude due to it,
and feeling in my heart a Christian salutation, I take the liberty, this way,
of expressing my desire for thy increasing
knowledge of the mysteries of the kingdom of God;
which our blessed Lord thanked his Father for concealing from the wise and prudent,
and revealing unto babes.
The sacred influences of divine light upon our understandings, are cheering to the mind,
and animate its efforts to obtain the liberty of the children of God:
and as we wait in this light, and believe in its manifestations,
we are favoured to see more light, the means appointed to procure it are revealed to us,
and strength given to follow.
But as it was prophetically spoken of the Saviour of the world,
that there was no form or comeliness in him that
when we should see him we should desire him,
so the simplicity of his gospel is found to be.
Nothing more strongly opposes the will, wisdom, and activity of the creature,
than in all abasement, singly to depend upon the promised Comforter, the Spirit of Truth,
the anointing which an Apostle said the true believers received and had abiding in them,
the unspeakable gift purchased by the precious blood of the Lamb,
and dispensed in infinite mercy for our salvation, which, through its converting,
purifying power is effected; for he gave himself for us,
that he might redeem us from all iniquity, etc.
Nevertheless the glorious end for which this sacrifice was made ought to be advanced to,
and our dependence increase upon the smallest discoveries of the Spirit of Christ,
though to the natural mind there may be no form or comeliness in them:
but it may sorrowfully be said,
with respect to His inward appearance the second time without sin unto salvation,
that he came to his own, but his own received him not;
yet let us remember for our encouragement, that to as many as did receive him,
he gave power to become the sons of God.
So that if we surrender ourselves as clay into the hands of the potter,
and our wills to the refiner`'s fire, we shall this way,
be made living partakers of the sufferings of Christ, being fools for his sake,
and according to our measures, conformable to his death.
This is an experience which closes the lips in awful silence,
and restrains the imagination from feeding upon the tree of knowledge;
without which restraint,
there is a danger of our not sufficiently embracing the excellent example of Him,
who was led as a lamb to the slaughter, and as a sheep dumb before her shearers.
The spirit of this world, in any of its false refinements, cannot preside here,
neither can any righteousness of our own; because we humblingly see with the apostle,
that it is not for any of these works which we have done, but of the mercy of Christ,
that he saveth us, and by those means which he died to obtain,
even the washing of regeneration, and the renewings of the Holy Ghost.
Fervently desiring that thy sincere mind may,
through the humbling processes of true spiritual baptism,
be led in the faith and patience, to the rest which is prepared for the children of God;

[.signed-section-closing]
I remain in gospel love, thy friend,

[.signed-section-signature]
Sarah Grubb

--

After secretly suffering, as in many other places, we took our departure for Geneva,
travelling through a beautiful country the last twenty miles, by the lake of Geneva,
and in prospect of the Alps;
which were covered with snow in the latter end of the fifth month,
although the weather was very hot with us.
These, with the steep and craggy rocks of Switzerland,
and pines of various kinds growing spontaneously upon them,
and forming shades and wildernesses, compose a scene in nature truly magnificent;
indeed for six hundred miles back, the prospect of mountains spread over with vineyards,
with the grandeur of the Rhine, flowing below them,
and its banks adorned with variety and abundance of fruit trees in full blossom,
would have afforded a scene of pleasure to spirits at liberty for such enjoyment.
But our hearts were on the whole too sad to be captivated thereby;
a seed attracted us in sympathy, which was not so visible,
nor had carried with it these sensible delights; and for it, in part,
we travailed in spirit.

We spent one day and two nights in Geneva,
where being informed that John Eliot and Ady Bellamy were waiting for us at Lyons,
we hastened to them, and found their patience tried by a week`'s detention in that town.
We joined them, and spending one day to rest and be refreshed there, took a boat,
and rapidly passed down the Rhine, one hundred and thirty-two miles in seventeen hours,
to a place called Pont St. Esprit, from which we came to Nismes and Congenies,
the 22nd and 23rd of the fifth month,
having travelled nine hundred and fifty miles from Amsterdam.
It now looks pleasant to think of being soon amongst our friends,
and a people to whom we may speak without an interpreter;
for in that respect our situation is a sort of exile, but greatly made up,
by a secret sense, more often renewed to us than we might have expected,
that we are here in the appointment of Him who graciously regards the sparrows,
so that not one of them falls to the ground without His permission:
and truly these innocent open-hearted people are of more value than many sparrows.

We entered Nismes with such a peaceful serenity upon our spirits,
as portended the acquaintance we have since commenced
with minds panting after the waters of Shiloh,
and the strengthening effects of true gospel labours.
We went next day to Congenies, about four leagues.
Our arrival drew out of their habitations the people in general;
some looked at us with astonishment,
and others with countenances which put me in mind of Mary`'s salutation to Elizabeth.
These soon acknowledged us, and drew us into the house of a steady, valuable widow,
where we were solemnly saluted and received, and our minds melted together;
and such a stream of gospel love flowed,
as some of us thought exceeded what we had before experienced,
though no words were used to express it.

We obtained lodgings at the house of a person not professing with them,
with a view not unnecessarily to interrupt them in their useful employments,
and to be at liberty ourselves to go amongst them as there appeared a service;
but we only lodged there one night, and that with difficulty,
their desire to have us amongst them, and to render us their services in their own way,
was so strong, that after contending the point, we gave way, and returned to the widow`'s,
where we were entertained with the best they could supply.

Our friends are most of them poor, industrious people;
but we were favoured with all that was needful,
though those things we call so are scarce,
the country being generally overspread with vineyards, olive-yards and mulberry-trees.
It can hardly be thought how comfortable we were:
peace of mind sweetens every inconvenience.
We found these people different from our Society in their outward appearance,
and in their want of settlement, and sufficient quietude in their religious assembles;
but the humility and simplicity of their meetings,
attended with a lively consciousness of their own weakness,
make them ready to embrace every offer of help,
that is suited to their capacity and progress in the Truth.
There are a few of them, amongst the younger sort particularly,
who furnish a hope that there will be a Society in this dark part of the world,
established upon the right foundation.

We soon found, that to be useful to them, the visitors must be weak with the visited,
and in Christian condescension bear with them,
till Truth opened a door of utterance to show them a more excellent way.
Their monthly meeting was held on first-day, wherein, of their own accord,
they laid open their discipline,
by reading their minutes or agreements acceded
to on their first setting up these meetings;
which, for consistency with their profession, are, in general,
superior to our expectation.
But it extends no farther than to a care over their poor,
and one another`'s moral conduct; they have no other tenets, nor any testimonies,
recorded, by which they may be distinguished;
and our little band were not without a guard, with respect to proposing,
or urging any thing to them, which they have not, at present,
a capacity rightly to adopt and support.

At Congenies, and in its neighbourhood we spent two weeks; visited all their families;
attended their monthly meeting; had a meeting for conference with the elder rank;
a youths meeting, and a very satisfactory public meeting with the inhabitants;
and divers solemn opportunities unforeseen:
all which brought us into near sympathy with them,
and often deeply humbled and baptised our spirits on their account, as well as our own.
Our parting was a very affecting one,
but under a comfortable sense that the Shepherd
of Israel has them under His gracious care.
From Congenies we went to Giles`'s, about twenty-one miles,
where there are between twenty and thirty who profess with us, as they do at Congenies:
but they do not appear so much awakened in their minds, nor so earnest to be visited.
They received us, however, with great kindness, and were pleased with the visit,
which perhaps may be profitable to some beyond what we can now see.

As without faith it is impossible to please our all-wise Director,
so it is impossible to persevere and hold to the end in His service,
and in the humiliations which the creature meets with in it,
without this precious ingredient, which is His own peculiar gift,
and silences all fleshly reasonings.
After having three meetings at Giles`'s, we came to Nismes,
and there took coach for Lyons, one hundred and fifty miles.
From that we travelled post, by way of Roane, Fontainbleau, Paris, and Versailles,
to Alencoll) where we arrived the 2nd of the seventh month,
several of us being weak and weary,
after having travelled near six hundred miles from Nismes.
In our way to Lyons, we passed through Dauphine,
where some of our minds were not insensible of an attractive influence:
but having no certain information of some we had heard of there,
and several of our company strongly bending homewards,
it did not seem the time easily to find them out.

Truly there is a hidden, precious seed scattered up and down, not only in these parts,
but in Holland and Germany, measurably gathered, both from the superstitious,
and the vain world;
and seeking a foundation whereon they may rest the soles of their feet.
This appeared beyond all doubt,
both from a little knowledge which we obtained in those countries of some,
and from that most sure word of prophecy,
which penetrates the obscure recesses of Sion`'s travellers,
and unites them together in the ocean of gospel love.
At Alenton, we were affectionately received by J. D. M., and courteously by his wife,
who, through the whole of our visit there, which was three days,
appeared to enjoy the company of their visitors.
Here we endeavoured to take fresh counsel about the way of proceeding to England,
which ended in the conclusion,
of George and Sarah Dillwyn going to the island of Gurnsey,
to visit the few Friends there; and T. E., A. B., Mary Dudley, my husband and myself,
to London directly, by way of Dieppe, which we pursued accordingly,
and arrived in London the 13th of the seventh month, 1788.

We have had a solitary and exercising travel; but through infinite kindness,
are again restored to our friends, and some of us to our native country.
We attended the quarterly meeting of London:
the sight of so many Friends was new and reviving to us; and the renewed evidence,
that the Lord had been mercifully with us, that he had led us about, and instructed us,
and tenderly preserved us when, in childlike simplicity, we depended upon his counsel,
afforded, and still affords, abundant cause to praise him for his mercies past,
and humbly hope for more.

After a journey of more than two thousand five hundred miles,
attended with many difficulties, and close exercises of body and mind,
she was enabled to return to her home at Clonmel, in the eighth month, 1788,
under the comfortable sense of divine favour and protection.
Some parts of her letters written after her return, on a retrospect of this visit,
appear to be worthy of insertion.

We have had, since leaving York, many new scenes of trial,
and new demonstrations of Providential care;
especially in the course of the long and deeply proving journey which we undertook,
in hope that the Hand of Omnipotence led forth to the continent.
The state of mind in which I was involved previous to it,
the inexpressible humiliations and besetments which attended the accomplishment of it,
and since that, the commemoration of un merited support,
with the renewed discovery of human frailty, seem to change, in many respects,
the face of this world to me, not that I am redeemed from the love of it;
but that I have learned to expect less from it; seeing more and more,
that this is indeed a probationary state of being,
and that our sufferings and joys in it are no otherwise important,
than as they affect our attachment to the one great object of eternal good,
and our communion with it in the silence of all that is fleshly.

It is a joyous consideration,
that the glorious light of the gospel is emitted from the Sun of Righteousness; and that,
though instruments may be used to bear testimony to it, yet that he,
before whom all nations are but as the drop of a bucket, the small dust of the balance,
and who takes up the isles as a very little thing, can, when they fail,
do his work without them, and "`glorify the house of his glory.`"

I humblingly reflect upon our late journey on the continent,
and am bound to acknowledge (however as an individual I have failed in truly saying,
"`thy will be done`") that the word of the Lord is faithfulness and truth.
My mind is settled in a comfortable belief, that,
through the creating and converting word of Omnipotence,
the pure seed of divine life was visited with greater efficacy,
than the discouragements which we were under, allowed us to know at that time.
But ah, poor Amsterdam! yea, poor Rotterdam! and many,
many places on that side the continent, touching whose inhabitants my soul, at times,
sings mournfully to its well-beloved!

[.small-break]
'''

Ninth month, 1788,--Thy letter saluted us two days after our arrival at home,
and was truly cordial, reviving with great sweetness,
our love and friendship with thee and thy dear wife, and also strengthening our hope,
that He who, we trust, directed our steps to your parts,
and mercifully preserved us through many jeopardies, will,
as you and we surrender ourselves to His all-wise disposal,
so carry on the eternal purpose of his will as to increase our fruitfulness to His glory;
and though very remotely situated one from another,
make us partakers of the same living fountain,
whose waters purify and gladden the baptised members of
the church of Christ wherever scattered,
or however obscured by the general cloud of darkness which the
professors of Christianity are too apt to content themselves in.
But as the eternal purposes of God are, the election of His own precious seed in us,
(the Lamb that was slain) and the reprobation of that spirit or seed of the serpent,
which with all the wrath and artifice of a fallen son of the morning,
is ever seeking to oppose the coming of the kingdom of the Messiah,
how ought we to watch and be sober; considering ourselves no longer safe,
nor objects of divine favour,
than whilst our spirits and affections are dedicated to His righteous control,
cleansing and sanctifying by the converting influence of his own power.
The seed of the kingdom, through divine mercy remaining in us,
and a disposition to cherish and embrace it,
preserves from the sin which grieves the Spirit, and leads into death.
To stand in that which is elect,
and to experience redemption from that spirit which wars with it,
ought invariably to be our aim; and if, in a pursuit so essentially necessary,
we meet with suffering and deep spiritual conflict,
yet remembering how inferior it all is to what He met with,
who being truly the good Shepherd, laid down His life for the sheep;
and experiencing Him to be in us the hope of glory,
the afflictions of the present time are counted light,
and the omnipotence of the Lord`'s everlasting arm (as we singly depend upon
it) found to give victory over the enemies of our own hearts;
to lead, in the meekness of wisdom, through persecutions from without,
and to build up in the true faith and steadfastness of the great Captain,
who goes forth conquering and to conquer.

I know that religion is in a state with you, as well as with us,
which requires a patient waiting and quiet hoping for the salvation of God;
which is often near to be revealed when we faint in our minds,
and therefore fail of inheriting that blessing the patriarch Jacob wrestled for,
through a night of faithful and successful exercise.
Thy increase in heavenly treasure, my beloved friend and brother in the Truth,
is secretly and strongly coveted by me.
My heart often meditates upon thy solitary situation; and in the renewals of gospel love,
thou and thy valuable wife are made like bone of my bone, and flesh of my flesh.
May the God of all grace and consolation strengthen and
succour you! and I most assuredly believe he will,
as your love of His inward and spiritual appearance, and glorious work among men,
grows as a tree of righteousness, bringing forth fruit in its season,
and enduring with humble submission, every wintry and pruning dispensation.

We have heard something of thy prospect of devoting thyself to the education of children;
a work peculiarly wanted in your society, and which, if thou enters into,
in the simplicity and sincerity which Truth gives, will, there is no doubt,
be a blessing to many, and thou thereby rendered a feeling subscriber to that truth,
"`he that watereth, is watered himself.`"
Thou mayest find it an arduous undertaking, and attended with mortifying circumstances;
but the liberal soul, though it may suffer,
knows best how to travel profitably through them all.
It is not human approbation that we ought to depend upon, or have singly in view;
but our study should be to show ourselves approved unto God; and then,
whatever vocation in His wisdom we are placed in, or however weak we may feel ourselves,
we shall have no just cause to be ashamed.

[.small-break]
'''

Eleventh month, 1788.--I can feelingly subscribe to the truth of what thou sayest,
that it is good to spend one`'s days in the bands of a free and sincere friendship,
and in the unity of a solid and constant faith.
We are favoured with many in these parts,
who have been mercifully gathered to the pure spring of eternal life,
where true love and unity originate, and from whence they bring forth acceptable fruits;
but, as those consolations sometimes abound, so do tribulations,
on account of the spirit of the world, and many other snares,
by which the enemy of all good is daily seeking to draw aside;
and for want of watchfulness and care, he prevails to the great hurt of some,
and casting a shade over the purity and simplicity that there is in the gospel of Christ.
So that, notwithstanding we are encompassed with many blessings and advantages,
we are not without our portion of trials; and can therefore in much sympathy and love,
dip in spirit with thee,
and feel thee as a fellow traveller in that path of suffering and probation which,
in infinite Wisdom,
is cast up for the regeneration and establishment of all those who walk in it,
and hold out unto the end.

Fear not, neither be dismayed, though thou feel thyself as a solitary bird,
as a pelican in the wilderness, or a sparrow upon the house top.
He that is in thee, is greater, than he that is in the world.
His wisdom will direct thee.
His counsel guide thee, and His everlasting omnipotent arm sustain thee,
as thy faith is steadfast therein,
and thy patience maintained in travelling through the
abasing dispensations which may fall to thy lot:
for I do believe thou art intended to be a man for God, and no wonder then,
if thou suffer persecution and affliction.
Remember they are but for a moment, and light,
compared with that exceeding and eternal weight of glory,
which is revealed to the poor distressed mind,
when it looks beyond the "`things which are seen, to the things which are not seen.`"
I feel much love to the dear young people amongst you,
and shall be glad for them to be told so;
and that the good account thou sent respecting them has rejoiced the hearts of many.
If they follow on to know the Lord, their minds will increase in holy stability;
the enjoyments of this world will fade in their view;
and an inward acquaintance with the spirit of Truth will become most precious to them.
They will not do their work (like the Pharisees) to be seen of men,
but the solidity and weightiness of their spirits,
will demonstrate that they have been with Jesus,
from whom they receive all their qualifications to perform true worship,
or do any thing that is good.

[.small-break]
'''

Tenth month, 1788.--Thy letter, which arrived about a week ago,
was sweetly refreshing and truly salutary to us; and I may now tell thee,
that though acceptable, as an individual,
I needed it not to revive the strength of affectionate attachment;
for my spirit often embraces thee in the flowings of increasing love and fellowship,
and feels thee, according to my small measure of true knowledge,
in that precious unity which is better than all words (though
ever so frequently and finely expressed) without it.
Were it not for this cordial drop, which, like oil,
sometimes swims on the top of our bitterest cups,
our faith would hardly be strong enough to make us victorious over even the
little perplexities attendant upon this pilgrimage and state of probation.
But He who knows that we are "`feeble folk,`" and graciously compassionates our case,
becomes to us not only the shadow of a mighty rock in a weary land,
but teaches us so to build our nest therein, that, in times of storm and trial,
his holy inclosure preserves, his faith stays us, and this rock pours out precious oil.
May our dwelling ever be here, and our inheritance be enlarged in that which is pure!
Then let our allotments be what they may, whether our bodies inhabit the dark,
or the more illuminated parts of the earth;
whether we are encompassed with sorrow and travail,
or have to rejoice more sensibly in the revealed salvation of the almighty Arm;
all will work together for good;
and we grow in qualification to worship and magnify that great and excellent Name,
which only is worthy of the incense that in every place and situation is to be offered.

[.small-break]
'''

Eleventh month, 1788.--If I know my own heart, it is my desire to know my business,
and simply to do it, whether it is taken cognizance of or not,
by the truly wise and honourable; whose friendship, though strengthening, consoling,
and therefore acceptable, may,
if the heart be not in some degree redeemed and
redeeming from the mysterious workings of self-love,
be perverted, and instead of nourishing the pure immortal part,
build us up in an airy notion of our own merits and attainments,
and prove a snare instead of a blessing.
A little acquaintance with one`'s own human nature,
a frequent detection of its corruption,
and the perplexities into which it introduces us when its subtle arguments prevail,
are enough to weary out a mind blessed with the
least sincere aspiration after permanent good,
durable riches and righteousness; and to content us in the most obscure situation, if,
through unmerited mercy, it may but be in the courts of the Lord; with the coarsest food,
if but ministered to us from the hand which is full of blessings;
and under the most unpleasant work, if faith is vouchsafed,
that in love and pity it will be accepted.
Some of us here feel it to be a low time; my knees often are ready to smite together,
and my soul is exceeding sorrowful.
That there are causes in myself and circumstances attending our present situation,
I doubt not: "`give me wisdom,
and reject me not from amongst thy children,`" is my secret petition.
