[#testimony, short="Testimonies of Sarah Grubb"]
== A Testimony from our monthly meeting for the County of Tipperary, concerning Sarah Grubb, deceased.

Our minds being deeply affected by the recent great loss which the church hath sustained,
in the removal of our beloved friend, Sarah Grubb,
daughter of our friends William Tuke and his late wife Elizabeth, of York,
we feel it incumbent on us to give forth a testimony concerning her;
for as the memory of the just is blessed,
so the remembrance of this dignified and eminently useful member in the church militant,
is precious to many; to whom she was a nursing mother, raised up,
by a thorough submission to the operation of the divine Hand,
to the stature of an elder in the Truth, though, as to years,
she had scarcely attained the meridian of life.

She was a woman of extraordinary natural abilities, strength of judgment,
and clearness of discernment;
and being favoured with the visitation of heavenly love in the morning of her day,
and submitting to be brought into that passive nothingness,
wherein the vessels in the Lord's house are formed and fitted for usefulness,
she witnessed an early preparation for service,
coming forth in public ministry about the twenty-third year of her age.
After exercising some years the precious gift committed to her,
to the consolation of many, she joined in marriage with our friend Robert Grubb,
and very soon after manifested the fruit of entire dedication,
by visiting the meetings of Friends in Scotland, where her service was truly acceptable,
and continued in such a line of devotedness,
that in the course of about five years she visited most,
or all the meetings in Great Britain and Ireland.

About three years since,
she removed with her husband to reside within the compass of this monthly meeting;
wherein she was deeply exercised in spirit, for the arising and spreading of life,
and frequently and earnestly engaged in exciting her
brethren and sisters to diligent labour after it.
In ministry, she was sound and edifying,
not only like the scribe instructed to the kingdom,
bringing forth out of her treasure things new and old, but qualified by pure wisdom,
to bring them forth in the demonstration of the Spirit and with power,
in the authority and becoming gravity of the gospel;
being in her delivery an example to all concerned in
bearing a public testimony for the Lord's cause.

The view of coming to settle in this nation,
was accompanied with a sense of divine requiring to establish a school,
for the education of the daughters of Friends in useful learning, simplicity,
and that unaffected piety into which Truth leads its followers;
which she was enabled to accomplish, we trust,
to the lasting advantage of some of the rising generation.
Soon after her coming to reside amongst us, she,
in consequence of a concern which had for a Considerable time rested on her mind,
engaged in a religious visit to Holland, some parts of Germany and the south of France;
in which she was joined by several Friends,
and wherein she was eminently gifted for the service to which she was called;
her ministry, private admonitions, and exemplary deportment,
reaching the witness in many minds; so that her fervent labour,
and the sweet savour of her exercised spirit, we believe are still felt,
and will be long profitably remembered in those parts.

After her return, she paid an acceptable visit to several parts of this province,
and had meetings where none of our Society dwelt,
much tending to spread the knowledge of the Truth.
And lastly, under the prevalence of gospel love,
and earnest solicitude that the sheep not yet of this fold
might be gathered to the teachings of the great Shepherd,
she again left her own habitation, and engaged, with some of her former companions,
in a very arduous and exercising visit to Dunkirk, Holland,
and some of the northern parts of Germany: wherein, we have reason to believe,
she had eminent service, to the confirming of many visited minds in the faith,
and promoting the blessed cause of Truth and righteousness.
In this glorious work, her intrepid spirit shrunk not from suffering.
The extending of the government of her dear Lord
and Master in the hearts of the children of men,
and the promotion and increase of his spiritual kingdom over sea and land,
being nearer to her than her natural life, or any other consideration,
she was brought to a willingness to be spent therein.

In her return, she attended our national meeting,
and in the meeting of ministers and elders, giving an account of her late journey,
under the influence of that humility which was
so conspicuously the covering of her spirit,
she ascribed all to Him, whom she knew to be the Author of every good work,
in these expressions: "`we have done but little,
but the Lord is doing much;`" concluding with, "`return unto thy rest,
O my soul! for the Lord hath dealt bountifully with
thee;`" as though prophetic of that everlasting rest,
into which she was so near being gathered.
Her bodily strength being considerably impaired, by almost constant exercise and fatigue,
it proved unequal to the force of a distemper, which soon after seized her frame,
and by a rapid progress,
terminated those afflictions of which she had so largely filled up her measure,
for the body's sake, which is the church.

She attended our quarterly meeting at Cork, returned a lively account of her journey,
and was acceptably exercised in the meetings there; after which,
she was confined by sickness at the house of our dear friend Samuel Neale,
near that city, where, amongst other weighty expressions, she uttered the following,
"`I have been much favoured with quietness of mind from the first,
though a stranger to how the present afflictions or trials may terminate;
but the grain of faith and hope which is mercifully vouchsafed,
I esteem preferable to all knowledge.`"

In a letter which she dictated to a near friend four days before her decease, she said;
"`My soul,
though encompassed with the manifold infirmities of a very afflicted tabernacle,
can feelingly worship and rejoice in nothing more than this,
that the Lamb immaculate is still redeeming, by his precious blood, out of every nation,
kindred, tongue and people, and making a glorious addition to the church triumphant,
whose names will stand eternally recorded in the book of life.
I express not these things from a redundancy of heavenly virtue,
but from the soul-sustaining evidence, that,
amidst all our weakness and conflicts of flesh and spirit,
an interest is mercifully granted in Him, who giveth victory over death, hell,
and the grave.`"

This, with other corroborating circumstances, clearly evinced,
where her hope and dependence were,
and that her refined spirit was prepared for its glorious mansion,
into which we have no doubt it was admitted.
She departed this life the 8th of the twelfth month, 1790;
and after a solemn meeting being previously held at the meeting house, wherein,
and at the grave yard, several living testimonies were borne,
her body was interred in Friends' burying ground, in Cork, the 12th of the same;
aged about thirty-four years.

Her conversation was innocently cheerful, which endeared her to the youth of both sexes,
and gave her much place and influence with them.
To her beloved husband, she was a truly affectionate wife; to her friends,
a near sympathizer in affliction;
and being clothed with that charity which seeketh not her own,
and breatheth peace and good will to all, was ready to reach forth the hand of help,
so that the whole of her conduct was in uniform consistency with her holy profession,
and the purity of those doctrines which she surely
believed and was engaged so extensively to publish.
May she, being dead, yet speak with a prevailing language to us all who are left behind:
"`follow me as I followed Christ;`" that so we may die the death of the righteous,
and our latter end be like theirs.

Given forth at a monthly meeting for the county of Tipperary, held at Clonmel,
by adjournment, the 13th day of the second month, 1791.

[.signed-section-signature]
Signed in and on behalf thereof, by many Friends.

The annexed testimony concerning our beloved friend, Sarah Grubb,
has been read in our quarterly men's and women's meeting for Munster province,
held in Cork, the 21st of the second month, 1791, with which we have near unity.

[.signed-section-signature]
Signed on behalf of our men's meeting, by Richard Abell, Clerk.

[.signed-section-signature]
And on behalf of our women's meeting, by Margaret Grube, Clerk.

Read, and approved, in our half-year's meeting for Ireland, held in Dublin,
from the 1st of the fifth month, 1791, to the 5th of the same inclusive,
and on behalf thereof signed by John Davis, Clerk to the meeting this time.

[.centered]
=== A Testimony of York quarterly meeting concerning Sarah Grubb, late wife of our friend Robert Grubb, of Clonmel, in Ireland.

This our valuable friend,
having been a member of this meeting till within the last four years of her life,
and the remembrance of her being precious to many of us,
we feel our minds engaged to unite in a short testimony concerning her,
with desires that many, from her pious and excellent example, may be stirred up,
according to their different measures, to follow her, as she followed Christ.

She was born in the city of York, in the year 1756,
and was favoured with a guarded and religious education, which,
with the divine blessing upon it,
preserved her from many dangers and follies to which youth are often exposed,
and prepared her heart for that open reception of the Truth,
and entire surrender to its dictates,
which remarkably distinguished her through the more advanced periods of life.
But though she was early under the visitations of divine love,
yet being of a quick and lively disposition, joined to great natural abilities,
she found it hard work to submit to the lowliness and simplicity of the cross of Christ;
and endured many sore conflicts before she surrendered
her will to the government of the Prince of peace.

Whilst under the Lord's preparing hand for the work of the ministry,
she experienced many deep baptisms of spirit; but He who knew her sincerity,
and earnest desires for His holy help and direction,
graciously sustained her in this proving season,
and in due time brought forth living offerings, to His own praise,
and the comfort of many minds.
In the exercise of her ministry, she was careful not to move in her own time and will,
nor to exceed her gift; but to be attentive to the arisings and continuance of life,
with patient resignation and dedication of heart.

Her love and gratitude to the Father of mercies,
and her fervent concern for the prosperity of his cause on earth,
made her unwearied in her labours to promote it,
and to be willing to spend and be spent for his great Name's sake.
She was an example of true humility and abasedness of self,
feeling that all her springs were in the Lord,
and that though the creature may at seasons be honoured,
yet every good and perfect gift came from above, and called for unfeigned acknowledgment.
To the necessity and powerful efficacy of the
pure principle of light and grace in the soul,
she bore many living testimonies, and recommended, above all things,
the closest attention and obedience to its holy manifestations,
as that alone which can preserve from the spots of the world,
redeem the mind from its spirit and enjoyments,
and confer that peace which the world can neither give nor take away.
She beheld and mourned over the breaches and waste places of Zion,
and we believe laboured honestly, according to the strength received,
for the repairing thereof, and the restoration of ancient beauty and simplicity.

Her superior abilities, sanctified by the humbling operations of the Holy Spirit,
qualified her for extensive service in the
administration of the discipline of the church;
wherein she was concerned to act, under a degree of that covering,
which ought to influence every religious movement.
Of a solid and weighty spirit, she was engaged to dig deeply for the hidden treasure,
and laboured to dwell near the spring of divine life:
yet infinite Wisdom saw meet to suffer her at seasons to experience great inward poverty:
but under these proving dispensations, she murmured not,
being resigned to the will of her Lord and Master, and made willing "`to suffer with him,
that she might also reign with him.`"
Having partaken of the sufferings and consolations of the gospel,
she knew how to sympathize with the exercised and mourning spirit, dealing her bread,
when qualified, to the hungry soul,
and pouring in the wine and oil to the help and refreshment of many.
As this devoted faithful servant of the Lord,
was thus instrumental in glorifying his name amongst mankind,
and promoting the divine government in their hearts, so she became more and more refined,
and redeemed from all visible enjoyments; till, in unsearchable wisdom.
He who put her forth and went before her,
was pleased to "`cut short the work in righteousness,`" and to remove her, we doubt not,
from His church militant on earth, to his church triumphant in heaven.

Read, approved, and signed, in, by order,
and on behalf of our quarterly meeting held in York, by adjournments,
on the 30th and 31st of the third month, 1791, by:

[.signed-section-signature]
Mordecai Casson, Clerk to the meeting this time.

[.signed-section-signature]
Elizabeth Tuke, Clerk this time.
