[quote.epigraph, , John 6:12]
____
Gather up the fragments that remain, that nothing be lost.
____

== Introduction

As few lives have exhibited a more pure example of piety and virtue,
than that which is set forth in the ensuing pages,
it has been thought right to bring it forward to general notice; under a hope,
that an account of this humble, self-denying, and dedicated servant,
will prove the means of instructing others;
and of strengthening their faith in the efficacy of that divine Spirit,
"`which wrought all her works in her.`"

It will be proper to inform the reader,
that the materials from which this work is composed,
consist of journals written by herself of her travels through Scotland, Ireland,
and some of the western counties in England,
and of a considerable number of letters to some of her intimate friends.
From these last have been extracted such parts,
as were descriptive of her other labours and travels, or likely to be of public use.
A connection of the different events and circumstances, has been made throughout,
by short narratives or explanations; but great care has been taken to preserve,
as much as could be, her own words and arrangements.

Although, from the time of her engagement in the ministry, she was greatly dedicated,
and much employed in various religious services during the remainder of her days; yet,
for lack of materials left by herself,
an account of many of these is omitted in the following work;
which it seemed proper to confine, almost throughout,
to such part of her life and labours as could be collected from her own writings.
It may not be improper to observe also,
that this mode of composing a narrative by extracts from letters, will sometimes be,
unavoidably attended with a lack of close connection, and with a degree of repetition:
but as this was the only way by which a material
part of her labours could be brought into view,
it is hoped that these circumstances will not be deemed of much consequence;
and that the deeply instructive nature of her literary correspondence,
will sufficiently warrant its publication.
