== Chapter I.

[.chapter-synopsis]
* Her education
* Divine visitations
* Conflict arising from her natural vivacity, etc.
* Solid state of her mind in the early part of life
* Exercises about the time of her first appearance in the ministry
* Visit to part of the counties of Westmoreland and Cumberland
* Visit to the meetings of Cheshire, and a part of those in Lancashire, etc.

+++[+++Sarah Grubb, daughter of William and Elizabeth Tuke, was born at York, in Great Britain,
20th of sixth month, in the year 1756.

In her tender years she was deprived of her mother, who was removed from her by death,
before she was five years old:
but her father marrying again about the tenth year of her age, this loss was,
from that time,
abundantly compensated by the maternal care and regard of a second mother;
of whose tenderness and solicitude for her best welfare,
she has left many grateful and affectionate testimonials.

The watchful and religious education with which she was favoured,
proved as a hedge round about her, and under divine care,
preserved her during that dangerous season of life,
from the many corruptions and follies that abound in the world,
and to which unguarded young people are sorrowfully exposed.
In the days of her youth,
she was often made sensible of the goodness of her heavenly Father,
and her eyes anointed to see the emptiness and delusion of all worldly enjoyments,
and to behold the beauty which there is in the Truth;
and strong desires were often raised in her mind, that she might be thoroughly refined,
and even at the loss of everything else, be made to possess the pearl of great price.

These gracious extensions of divine regard met with
great opposition from the liveliness of her disposition,
and the strength of her natural powers;
which occasioned the self-denying meekness and simplicity of the Christian life,
to be to her a hard attainment; and many painful struggles she experienced,
before she was made willing to yield up every sacrifice,
and to follow her Lord whithersoever he might be pleased to lead.

During the last illness of that eminent minister, John Woolman, she was, at times,
favoured to wait upon and assist him.
His faith and patience, with the sweet savour of his pure spirit,
made a deep and profitable impression on her mind,
exemplifying the power and goodness of that divine hand,
which she felt secretly at work in her own heart, calling her to newness of life,
and holiness before the Lord.
It was to her that this valuable friend, when near the close of life,
addressed those comfortable expressions, which, indeed, may be called a blessing:
"`My child, you seems very kind to me, a poor creature;
the Lord will reward you for it.`"

A deep sense of the purity of the divine life, and a lively feeling of her own frailties,
joined to an earnest concern that she might become fully purified in heart and life,
caused great circumspection and fear, and made her often go mourning on her way.
This appears from the following extracts of various letters to her friends,
written in early life, which in some measure,
show the exercise and state of her mind at that period; and which may be acceptable,
as they serve to exhibit the beginnings and gradations of that work,
which conspicuously marked the future periods of her life.]

[.small-break]
'''

1772.--I feel your bearing with my weaknesses, and your candour in judging of them,
which makes me the more ready to communicate what I feel.
Oh could I tell you, it would be comfortable!
But that which is felt and not understood, cannot be described; and, indeed,
I begin to think a state of insensibility to what is good is approaching.
I may truly say I dread it.
May I, by that fear, guard the more; yet my infirmities seem so just a cause,
that they are numerous enough to depress the little life that is left.

[.small-break]
'''

1772.--Your letter has excited in me the warmest
wishes for the extendings of divine bounty,
to be enabled, with resignation and fortitude, to do, bear, or suffer,
whatever it may please the Father of spirits to inflict upon me.
Yet I cannot but, with conscious sorrow, own the truth of your remark,
concerning a too great anxiety for a larger
portion of the descendings of the Father`'s love,
than is suitable in the sight of an omniscient Deity.

[.small-break]
'''

Sheffield, fifth month, 1772.^
footnote:[In the sixteenth year of her age.]--I
cannot but wish to spend a few weeks with you,
either here or at York;
but as I am sensible it is not good for any of us to
have our inclinations gratified at all times,
I am desirous to be easy,
and resigned to everything that may cross my natural propensities; that so,
when affliction and probation may present themselves,
which certainly will attend our pilgrimage through this uncertain stage of life,
I may be the more strengthened to undergo these
trying seasons with patience and fortitude.
But I may conclude with the words which you have repeated before; "`to will,
is present with me, but to do,
I know not:`" for though this fortitude and resignation are things much to be desired,
yet to be entirely given up to the will and disposal of a kind Providence,
is no easy attainment.

You mentioned the difference of our situations;
and it would be ungrateful if I did not consider, and look upon my privileges,
as favours from indulgent heaven, if I make a proper use of them.
But it is the state of the mind that limits our happiness;
and alas! it is the lack of a sufficient care in the cultivation of my mind,
that is a means of obstructing that peace which it would be sweet to enjoy.

[.small-break]
'''

1773.--I seem recovering from my late illness and have favourable symptoms for life;
but for what kind of a one I know not.
I am at a loss to say whether it is a pleasing, or a painful prospect.
I feel the effects of both, and am ready to countenance the latter,
knowing there is something in my nature,
which is unwilling to be subjected under that power,
which ought to actuate every part of our demeanour; and there is nothing, that I know of,
so contrary to my natural will, as that patiently waiting, and quietly hoping,
which you mentions; it being, certainly, preparatory to the work of reformation in us;
and if this be rightly performed,
no mundane enjoyment would be adequate to the foretaste of that consummate felicity,
which I believe is the result of so desirable a work.
But O, this glimpse of hope, how ready are we to catch it,
though the twig be ever so slender,
and the prospect ever so faint! yet there is a danger of being deluded,
as the adversary is ever ready to attack the weak part,
and that is one which is generally exposed,
there being room in the human breast for such prepossessions.
I acquiesce with you, that it is in silence we enjoy advantage,
and in solitude we muse the wonder of unsearchable wisdom.
Could we but partake of a larger share of retirement,
I am sensible the works of an almighty hand would have a greater influence,
and the mind would not be so alienated from this source, this pleasing source,
of every joy.

[.small-break]
'''

1773.--Surely the commemoration of the goodness of infinite wisdom,
in favouring a large share of the youth of our
Society with a virtuous and sober education,
ought to inspire us with a willingness to imitate the bright examples we have,
rather than those, whose loss we should pity; for many are the irreligious principles,
that the adversary is endeavouring to suggest in the minds of youth,
more especially when they are exposed to the tempestuous billows of an unstable world;
but happy is it for those that resist the temptations, and surmount the difficulties:
if any may look to the recompense of reward, it is certainly they.
But for my part, I am often afraid lest I should grow like the heath in the desert,
that knows not when good comes; or that the manifold favours should prove,
as water spilt upon a stone; for I am sure there is a hardness in the natural heart,
not easily penetrated; and though I experimentally confess it, yet I hope there are many,
on the other hand, who can say,
they witness the returning from their gatherings with Friends,
as arising from the washing pool.

[.small-break]
'''

York, seventh month 1773.--I often think our troubles are much augmented,
by looking on those who are in a more advantageous station, according to our opinion;
when, if we could but content ourselves with putting their many mortifications,
to balance the adverse conditions of some on whom
external circumstances seem never to have smiled,
and whose life has been a series of affliction, it would amply compensate for the labour.
Due consideration would make our sorrows appear greatly
short of what Providence might have allotted for us,
and would frequently prove them to be the result of passion or imaginary ills.

[.small-break]
'''

York, fourth month 1774.--Your letter was salutary and grateful,
arriving when my mind was anxiously concerned on many accounts.
The care of so large a family, you will readily own,
must engross a large share of my attention;
it is a task to which I often think myself unequal, especially among children;
but that I am willing to make the best of, if I may but be enabled so to conduct,
as to give no real cause of offence,
nor to example in anything that is contrary to the simplicity of Truth.
Under these considerations, I see my own insufficiency,
and how unable I am to act the part of an elder sister,
without a daily support from the fountain of every good.
What should we do, were there nothing to fly to but the instruments,
the publishers of the gospel! what aid can they lend us! what strength in weakness,
in comparison of that inward stay, which, if enough looked unto,
would be the staff of our lives!
And with this gracious privilege,
how mournful is it to consider the preference that is
given to the foibles of this transitory life,
before that true peace which flows from the divine monitor, the teacher within!

[.small-break]
'''

1774.--We certainly reap great advantages from a friend,
when the mind and natural flow of spirits are depressed.
It is at these seasons we hear the intelligible language of sympathy,
in its pleasing notes, and look upon friendship in its exalted station.
A view of these enjoyments excited me to taste their fruits,
by opening the fountain of sorrows, and unlocking the spring of painful feelings.
That they may overflow the banks of my pleasures,
and bring down the tall cedars of Lebanon, laying waste the hills and the mountains,
and establishing in the room, that rock whereon the church must be built,
is the swaying inclination of my heart.
But how apt are we to turn our feet from the path which is narrow;
being unwilling to make strait steps, a thing most repugnant to our unregenerate wills!
We therefore cull out every discouragement, and stumble at the smallest stone;
each prospect appearing in its gloomiest colours, or rather,
our eyes being blinded by the glitter of worldly objects,
and inexperienced in the joys accruing from faithfulness, we see them not.

[.small-break]
'''

1775.--Though trials and conflicts are allotted to the faithful followers, yet they rise,
as with stones of memorial, from the bottom of Jordan; when alas!
I, and such like, instead of being benefited by these baptisms,
find them unpleasing and contrary to our natural propensities, and so shun them,
for a more easy way to peace.
Cannot such be met with in a strait place, where neither the devices of the creature,
nor the pleasures of the world, can rescue them from the pains of a wounded conscience?
When I look at these things,
and consider how intricate the path to our real happiness is,
it makes me frequently say in my heart,
"`blessed are the dead that have died in the Lord.`"

[.small-break]
'''

1775.--My mind was often with you yesterday,
though I could not thereby partake of the valuable company of our dear friends;
but I hope many that are more worthy did:
for certainly the society of those labourers in the great vineyard,
must be pleasing and instructive; yet, at times,
we feel a mortification in their absence, which, if allowed to have its proper effect,
might be a means of exciting us to seek after an
inward communion with the Source of all good,
the Spirit of Truth, which is pure and unmixed with human propensities.
But I am afraid that I am speaking more from hearing the experiences of others,
than from my own; for I know the language of this internal monitor is more intelligible,
when the mind is prepared by the subjection of its will,
and all its powers yield to the Supreme: and this state I am so often deprived of,
by the predominance of self, that it seems hard to say,
whether I ever rightly enjoy this divine privilege.

[.small-break]
'''

York, eighth month 1775.--And now permit me to tell you how welcome a part of your letter was;
it led me, when I read it, to conclude,
that after looking on all the frailties of human nature,
and perplexing ourselves with a view of the various and intricate scenes of this life,
the necessary result should be, "`to be quiet, and mind our own business;`" or,
as you say, to endeavour to feel ourselves approved by Him who sees not as man sees.
If we make welcome every obstacle that is presented in the way to peace,
we may justly conclude that we shall never arrive at the peaceful Jerusalem,
the quiet habitation which comes down from God out of heaven.
The consideration of this enjoyment, sometimes prompts the mind to soar,
or to ascend gradually to the holy mountain,
where we may be taught the ways of righteousness,
and be instructed in the paths of true peace:
but how fast we descend to the place from which we came! how precipitately
do we drop into some region of darkness! for surely there are many degrees;
but happy are they who are redeemed from its power.
May we not justly deem ourselves, when under any entanglement,
any fetter that prevents our deeds being brought to the true light,
the light of the Lamb, as alienated, in part, from the Father of mercies,
and estranged from His celestial spring! how necessary
therefore is it for us to watch at all seasons,
in times of peace, as well as in the spiritual warfare;
for we know not when the hour of temptation comes,
and our fortification may prevent the engagement.
How preserving is that language;
"`I will get me to my watch tower;`" and what a favour it is, our not being ignorant,
that the name of the Lord is a tower to the righteous.

[.small-break]
'''

1777.--When we are favoured to feel an internal communion,
an intercourse incomprehensible, it is indeed attended with rejoicing of heart.
A state which I can impute to no good cause, frequently accompanies me,
in which it would be hard for me to say, I love my friends;
but perhaps it is a constitutional stupidity,
which nothing but the immediate operations of Truth can divest of;
and it is only during the over-shadowings thereof,
that the useful faculties of my mind are applied to good purposes;
for the springs of my machinery are indeed weak,
and daily require a supernatural aid; but when wisdom utters her voice,
when the gentle movings of uncreated purity have gained our ear,
what obduracy does it require to resist its energetic language,
and lightly esteem the offers of permanent peace!
My heart glows with an earnest solicitude, that we, my dear friend,
may never faint in our pursuit after celestial treasure,
but resignedly surrender our whole affections to the
gracious disposer and preserver of his people;
then, I doubt not, our union will increase, in the increase of purity,
and our joy and rejoicing in the fruition of reward,
will be of that nature with which the stranger does not intermeddle.

[.small-break]
'''

Tenth month 1777.--I expect this will find you at +++_______+++,
where I wish your visit to be attended with more solid satisfaction than you looked for;
if not, it may be no less profitable.
My very small experience has taught me,
that endeavouring to keep near to the fountain of life,
in company where its arisings are evidently suppressed,
often tends more to our real growth in the root of true religion,
than the easy enjoyment of valuable friends company,
with whom we are not driven to our refuge.

[.small-break]
'''

Twelfth month 1777.--I doubt not but you have thought, with myself,
the conduct of the generality of young men to be painful;
for what numbers do we see of these, who,
prompted by the irregularity of youthful fervour,
permit their minds to be entangled with every fluttering object of vanity;
little considering that they are exposing themselves to innumerable sorrows,
and inconsiderately and rapidly pursuing an ignis-fatuus,^
footnote:[i.e. a false light, a deceptive or misleading guide.]
which will lead them into a labyrinth of perplexities.
Oh! could they, instead of this, centre and retire to that reverent fear in themselves,
which would prove a fountain of life, preserving from the snares of death,
there is no reason to doubt that the Lord Almighty,
would not only turn their feet into the path of peace,
but so far establish their goings therein,
that every important concern of their lives would be favoured with divine direction;
and in that very momentous one of marriage,
the language of truth would be so intelligible as to direct them to the right object;
and then, with what holy confidence might they propose these connections, while our sex,
with a humble awful diffidence, wait also for counsel from on high,
and to feel the same assurance of divine approbation:
thus all would be consummated to the praise of
Him whose favour they had sought and implored.
Much do I wish that my heart may ever be favoured to
possess a degree of this primitive purity,
though no matrimonial considerations require it;
the saying of the apostle often occurs to my mind;
"`that godliness is profitable unto all things.`"

[.small-break]
'''

Seventh month 1778.--We are now again left with the care of a
family that requires some attention and circumspection.
I never felt more unfit for the task, nor more ready to query, who is equal to it?
and to conclude, surely not I. A discreet conduct, an affectionate behaviour,
attempered with just so much steady authority as to excite respect,
united to an unavoidable love, and these not to fluctuate with the situation of the mind,
is an attainment which I fear will never be mine,
and which indeed will be unnecessary in a very few years with respect to my sisters;
but yet it does appear, at least in my eyes,
absolutely requisite for those on whom the education of children devolves.
Where people are thus qualified, and discharge their duty,
they will find a pleasure with the important charge: "`for in it there is a happiness,
as well as care.`"
There is certainly something in the affectionate part of us,
which tends rather to defeat, than promote the growth of true religion,
except it be sanctified under the operation of the divine hand;
when that is happily experienced, some of the natural propensities become blessings,
and very laudibly heighten the enjoyment of spiritual ones.

[.small-break]
'''

Eleventh month 1778.--You have, I doubt not,
already heard of the unsettled state we have lately been in,
occasioned by a sorrowful and affecting event,
the death of our dear friend +++_______+++. She seemed but
just arrived at the summit of earthly happiness,
and to have conferred the same enjoyment upon her beloved partner;
yet alas! how transient was the duration of this state; and indeed,
how unfit is it for minds who are too apt to rejoice in prosperity without trembling,
and whose affections are centred only in social comforts!
We cannot but conclude that, by these instructive lessons of mortality,
the divine intention is to refine and purify, and to show all who behold them,
the necessity, the great necessity,
of having our minds centred where fluctuating things can never come.
This was, beyond a doubt,
the happy situation that her mind was in sometime before her departure;
for about a week before her death, she told her husband,
"`that her mind was steadily fixed upon the joys to come;`" and added,
"`I am sensible I shall not recover;
and I have now been where they were singing hallelujahs to the Highest,
and it was pleasant in my ears.
I have seen the beautiful situation of the inhabitants
of the new Jerusalem:`" with many similar expressions,
which I have hardly either leisure or room to insert;
but the foregoing will give you an idea of the comfortable state her mind was in,
which she appeared to preserve to the last.

[.small-break]
'''

+++[+++In the twenty third year of her age, Sarah Grubb appeared in the ministry.
For this awful service she had been prepared, by the great head of the church,
with deep and humbling baptisms of spirit.
But as she continued patient and faithful, under this proving dispensation,
she experienced divine support, was graciously brought through all,
and enabled to stand acceptably for the cause of truth and righteousness on earth.

The close trials and humiliations of her spirit about this time, are,
in some degree testified, by the following selections from her letters,
to some of her near, sympathizing friends.]

[.small-break]
'''

1778.--I do not know but a little love for my friends, and sensibility of their favours,
are the only virtues I possess, and, consequently, all that I can derive any good from:
for to my dear friend, to whom my heart has ever been open, I may confess,
that whatever has heretofore felt like life, or a participation of eternal substance,
(though always small,
and no doubt the food convenient for me) is now entirely extinguished; and the law,
the testimony, and the effusions of some little secret devotion,
are all as springs shut up, and fountains sealed.
You are experienced, and tried with many deep baptisms, with needs and with aboundings;
but perhaps such a state of insensibility to,
and desertion of all that seems good and valuable, was never seen fit for you;
your resignedness rather bringing you its rewards, those of true obedience,
which have built up and compacted as a Jerusalem, the foundations whereof are sure.
But if you knew the different situation of my poor tossed mind, it would, I believe,
excite a degree of your sympathy and fear, that the tempter will wholly overcome:
for now in this time of deep poverty, the world has indeed occupied much room,
and what may be called the enjoyments of it,
are as clay fettering that part appointed for immortality.

I often wonder when better times will come; when, in truth,
we can adopt the language of the just to their ancient source: "`spring up O well,
sing you unto it!`"
But how can my humiliation be deep enough, when I confess,
that this fountain appears to be, to me, neither ancient nor new?

[.small-break]
'''

1778.--There is, I believe,
a holy intercourse and communion experienced by those whose language is similar and pure,
whose feet are established upon the immovable rock,
and whose teacher and strength is the sovereign Lord.
This is, I doubt not, one of their rewards; but its sanctity,
its refined and exalted nature, seems to exclude me from the participation thereof;
for I may confess,
the painful experience of my mind is often under
such a state of desertion from infinite Goodness,
that I scarcely dare look towards his holy temple, or address him,
but in sighs unutterable.

[.small-break]
'''

1778.--Let us travel, unitedly travel forward in the path of humble obedience,
which though tribulated,
and those that walk in it have often to experience a share of this legacy,
"`In the world you shall have trouble,`" yet the annexed peace,
the bread that is handed in secret,
and the joy with which a stranger does not intermeddle,
are surely sufficient rewards in this life, and an earnest of that which is to come,
that glorious reserve of immortal bliss.
I feel a greater solicitude than words can describe, that we may, unitedly,
be entitled to it, and partake thereof, and that we may feel this certain mark,
that we love one another, even with that love which will subsist beyond the grave.
But I wonder how arose these sensations,
for I daily conclude myself destitute of any that are good;
and in the absence of Him whom I wish to be to me the chief of ten thousand,
I implore the path of obscurity, and, with the mournful prophet,
exclaim in my lonesome habitation, the secret of my heart,
"`Oh that I had in the wilderness a lodging place!`" but alas! this will not do,
this is not the will of him who desires, not to take us out of the world,
but to preserve us from the evil that is therein.
It is the path of suffering, it is the cross and the shame that we recoil at;
and for lack of true dedication of heart, many deep and hidden sorrows are ours.

[.small-break]
'''

First month 1779.--The reestablishment of our own, or our friends`' health,
from the verge of that eternity to which we are hastening,
ought to excite deep gratitude of mind,
and lead to a still greater degree of obedience and preparation for the final call.
The seasons which I passed, and the meditations with which my mind was supported,
when watching over my departing friend, are, I think I may say, continually before me.
How low and how grovelling, appeared every mundane thing!
How insignificant the most desirable connections in life,
when compared with that certain portion of happiness, that unbounded sphere of felicity,
which is reserved for the pure in heart! even the strong ties
of friendship and love were subservient to these feelings;
insomuch that I have queried,
when reflecting how these fetters to our dissolution were removed,
while those important prospects were before me, "`what ailed you, you sea, that you fled,
you Jordan, that you were driven back, you mountains, that you skipped like rams,
and you little hills, like lambs!`"
But alas! this lasted not long; for when the solemn,
awful messenger had proclaimed liberty to a captive spirit,
and translated it to where mine could not ascend, then arose every natural emotion;
and instructed me, that in a continual warfare consisted my peace.
But what can I now say?
for on these things, as on the manna that was gathered yesterday, am I too apt to live,
without enough seeking the fresh descendings of celestial food,
and patiently submitting to that creative power which
would form us into the state of a little child.
The aptitude of my disposition to rise above the humbling power of the Spirit of Truth,
and form to myself a likeness which may be compared to a marble statue,
or an image of substantial good, often leads my mind into deep lamentation and mourning;
with a painful fear,
that I shall never be entitled to the handing forth of the royal sceptre,
the mark of divine approbation; but to that sentence of depart,
and being set as on the left hand: yet when we survey these fleeting moments,
or rather look over them to the endless ages that ensue,
we cannot but conclude that nothing short of a
state of infatuation would lead us to exchange,
or even risk our everlasting well-being, for the very best things of this world.

[.small-break]
'''

Fourth month 1779.--Alas! how is a large degree of Truth, inward excellence,
and whatever constitutes true loveliness, removed! how is the beauty fallen!
Affecting instance to us her friends; but to that immortal spirit in her which has long,
in prospect of a future glorious admission into the celestial regions of light,
been willing to descend into the deeps,
and there behold the marvellous works of Him whom she served, it is a happy lot.
Though she suffered much, though sorrow came in the night,
in the close of a world wherein she had many troubles, yet joy has, I doubt not,
sprung in the morning, in the opening of an endless day.
How justly may we rejoice on her account,
who was counted worthy of so early an entrance to where the aged whose work is done,
can but hope to be: a circumstance which the impatient mind, I believe, often wishes for.
A lamentation for those who knew her worth,
and who hoped for a future uniting with her in the covenant of life,
and of that wisdom which is from above, may, with unfeigned propriety, be adopted.
For my own part, all that was within me,
(when I found what your intelligence was) seemed struck with amazement,
and was lost for a time in reflection on her great and awful change;
but when I recollected myself, that she was forever removed;
and that through the intricacies of life,
I was left to move without her friendly assistances, and fellow-feeling mind,
a deep sense of mourning ensued: for from so short, and even from a long intercourse,
I think I never reaped so much solid benefit with any.
And alas! short-sighted as I was,
I imagined it an earnest of some future fellowship in this life; and that,
through the various trials that attended it,
a providential help might be dispensed us through each other.
But now, I find it was the fulness allotted us, and that, like Jonah`'s gourd,
it sprung to me in a night, and has withered before the brightness of the day;
withered in a time wherein my weakness leads me too much to lean on such helps.
But this shock relaxes the desire, and points to the strong tower,
the refuge of the righteous, where alone is true safety; and oh! may we flee there,
for the habitation is quiet and sure.

I very much sympathize with you in the present trial,
the loss of so near and valuable a friend.
Your attachment I believe was strong, and the separation hard;
but how much more profitable, if, instead of unavailing sorrow,
we consider the church`'s loss; that one who filled a useful sphere is removed,
and consequently, that that share is left to devolve upon the shoulders of some; I say,
if we consider and look sufficiently at this, being willing to step, if required,
into her path, (which I know was secretly exercised, not only for herself,
but for the prosperity of the great and noble cause,) and thereby redeem the loss,
how acceptable must that tribute be, in the sight of Him who sees not as man sees; and,
if it spring from a heart devoted to the work rather than the reward,
how truly profitable to ourselves!
The end of the righteous is desirable, in whatever stage of life it arrives;
but for my own part, if I could hope mine would be such,
I own I cannot help feeling a wish,
that its approach might be in the early or middle part: in what the desire originates,
I cannot pretend to say, but it is, perhaps, in some unjustifiable part of self-love.

[.small-break]
'''

Sixth month 1779.--How acceptable was your account of the latter, and last end,
of our beloved friend!
My mind often recurs to it for hope, and for strength to persevere and to obtain;
but there appears so much to constitute our claim to the peaceful abode,
into which the righteous only can enter,
that my mind enjoys but a small portion of faith
to believe it will ever reach its confines;
yet I am sometimes led to consider, whether our researches after happiness,
are not too much actuated by principles of self-love;
and whether it is consistent with the benevolence which the gospel inculcates,
that in all our concerns, and the exercise of our greatest virtues,
we should be continually enquiring after the reward: does it not, my friend,
(for I really do not know) indicate a littleness of mind,
and a lack of confidence in Him who is, "`just and equal in all his ways?`"
for in our works there is no merit to the creature; if we trust not, where is our faith?
if we persevere not, where is our patience?
and if in this life, we partake of the fulness of that joy which is sown for the upright,
where is the glorious reserve for futurity?
Should we not then,
if our minds were clothed with the nobility of the Spirit in which we believe,
resign all things?
and being humble, suffer all things?
and do all things in pure love, exclusive of any selfish view?

In your county as well as ours, there are a few, who have not bowed the knee,
nor sacrificed to the workmanship of men`'s hands,
yet the general depravity does so often obstruct the current of life,
and thereby stagger the feeble mind, that I believe you often experience,
a seeking water and finding none; but fear not,
for he in whom is the fulness of strength, is your refuge.

[.small-break]
'''

Eighth month 1779.--Though I am firm in the belief,
that if we experience the work of true regeneration,
all our attachments must be tried in a furnace,
which the natural understanding cannot of itself comprehend,
and that the precious must be separated from the vile,
by the mysterious operations of the divine hand;
yet I do also hope that ours will be permitted to stand, and that,
if we live to survive the strength of that youthful
ardour with which our present union is heightened,
there will be enjoyed a fellowship,
better and more pure than any we have yet experienced, and against which,
all the fiery darts of the enemy will never be able to prevail.
This, and similar to this, is, next to the immediate influence of the divine presence,
what I strongly covet to partake of, in this vicissitude and vale of tears;
wherein a cup is sometimes handed, which is so repugnant to our nature,
that we cannot help entreating, let it, I pray you, pass from me.
But oh! that we may be found worthy to enjoy the
celestial blessings dispensed to the faithful,
by obedience to that power, which in all its workings, tends to crucify self,
and prepare the mind to adopt that refined language of, "`not my will,
but yours be done.`"
The more a mind possesses of that wisdom and nature,
which act in opposition to the true simplicity of a little child,
the greater must be the exercise;
and if it has long refused the clear manifestations of duty,
it is no wonder if a season of painful uncertainty ensues.

[.small-break]
'''

Ninth month 1779.--Are you in health?
are you strong in Him who goes before you,
and who has promised that His glory shall be the
reward of the number that deal prudently,
and go not by flight? Isaiah 52:12-13.
How safe do the steps of such appear,
who have this glory for a light to their feet,
and the divinely illuminated lamp to attend their path!
It is no wonder that a way should often open,
where the human understanding (which is dark and comprehends
not the things of the spirit) can see no way;
and that every necessary refreshment should be interspersed therein.
I sometimes think it is a favour, that an eye is opened into this path,
and that though the advancement in it is small, if there be any, yet, thus seeing,
and pressing forward, we may obtain.
I hope you are treading this sure ground, and that your memorials,
which are brought from the bottom of the purifying waters of Jordan, are not hid;
or if they be, that it is only for their refinement.
But perhaps they are like the sling stones which David had ready in his bag,
till the appointed time of meeting the defier of Israel was come,
and are to be alike powerful in prevailing against the enemies of the poor,
and the afflicted people, which may be spared in the day of general calamity.
But be this as it may, obedience is still to be attended to,
and the prophet`'s advice remembered, of not seeking to ourselves great things,
but to be content with every dispensation, whether of need or of plenty.
When this situation is in any degree attained,
how thankful do we feel for even a small appearance of good;
for if the divine presence is no more beheld,
than by the putting forth of His hand through the hole of the door,
it still sustains and refreshes, and serves as food for many days.

[.small-break]
'''

Tenth month 1779.--Poor +++_______+++, I feel for her frequently,
and have often thought of writing to her; but it has as often occurred,
that except the great Shepherd of Israel assist her, how shall another do it?
As his voice, his crook, and his protection are undoubtedly offered,
it is surely weak to suppose that the language of the
creature can equal the voice of this Charmer;
if indeed it do not derogate,
(as I am inclined to think it does) from the Omnipotence and wisdom of our holy Head;
and I sometimes think,
that nothing more proves the deep rooted depravity of the human mind,
even when measurably illumined with the brightness and glory, of the eternal excellency,
than looking at the members for help, and craving it from that often poor,
benumbed quarter, when, at the same time, it might be said,
"`you have an anointing from the Holy One, and you know these things.`"

[.small-break]
'''

1779.--To inform you, my dear friend, of the secret path I have trod of late,
is a thing which I know your good sense, and experience in the mysteries of godliness,
will prevent your requiring.
In the sacred union, we see the necessity of the leaven being hid,
which cements together and brings our nature into oneness,
till the whole lump is sanctified.
Under this apprehension, I have of late been led to endure many new and severe conflicts,
without daring to seek consolation, save from that fountain,
which issues in the right time, an inexhaustible stream;
but to which I am ready to conclude, I am not entitled to approach.

[.small-break]
'''

1779.--I have lately thought the blessing that was craved for us, was abundantly shed,
and our walking seemed, a little, as if it was by the pillar and the cloud; but,
now the sun and the moon, even those heavenly bodies which are universally diffused,
have, from our eye, withdrawn their light.
For my part, I have several times concluded, the work is done; and if it be sufficiently,
I am glad; but when it feels like the description of meat and drink, there lacks,
not only patience, but resignation;
an attainment which appears to me to be a degree harder than the other.
Oh may we walk in the way cast up for us, and may we, now our Moses is withdrawn,
be preserved from making a likeness!
A south land will, I hope, yield you springs of water:
they require hard digging for here; but the fountain is found to be so deep when come at,
that we need not be afraid of the labour.
But I have nothing to boast of,
for the refreshing influence of the waters of this fountain, has, I doubt not,
been wisely withheld from me; and to have a channel ready for their return,
is what I endeavour, though feebly, to preserve.

[.small-break]
'''

1779.--My mind has been for some time, incapable of deriving any satisfaction,
from either the intercourse with, or consolation of, a friend.
And not having any desire to seek comfort, or have any but from the fountain of it,
silence was not only most consistent with my judgment, but most easy to myself,
if I found anything that could bear that character.
Floods of distress have indeed nearly overwhelmed me, and I know not where to turn,
or where to look; I abhorred myself, and beheld not the power that could purify.
"`When I looked for good, then evil carne; and for light, behold there was darkness.`"

[.small-break]
'''

1779.--I went to meeting yesterday morning, with, I thought, some degree of devotedness,
and for some time sat in darkness; but after a deep labour of mind,
there felt something to gather about me;
and with it came my deep rooted dislike to the work; which so strove with the other,
that for a time, enduring a state of agony, the meeting broke up.
On going in the afternoon, I concluded myself given up,
and little expected to feel anything again at that time: but after sitting a while,
the matter again returned, and would, I believe, have terminated the same way,
had not a Friend stood up with the passage,
"`He that knew his Lord`'s will and prepared not himself,
neither did according to his will, shall be beaten with many stripes.`"
This did indeed come home, and so operated with what was already kindled, that,
after such a conflict as I have cause ever to remember, I ventured upon my knees, and,
in a manner I believe scarcely intelligible, poured out a few petitions.
Now I feel in such a state of humiliation and fear, as I never before experienced;
and my strength, both natural and spiritual, so low,
that the floods are ready to come upon me again.

[.small-break]
'''

First month 1780.--There appears to me, no joy like the joy of the righteous,
nor any unity like theirs; and next to the immediate influences of the divine Spirit,
it is to me desirable.
But obedience being the terms of this great and valuable possession, what numbers,
for lack of this, are deprived of it!
Yet he who is infinite in condescension, and whose love is unutterable,
deigns to reward for every little service, and grants, at times,
a sacred view of the mystery of his own church, and his marvellous work therein.
My friend is, I doubt not, well instructed in these things,
and though I also believe it is a time of suffering like Jacob`'s,
when the sun consumed by day and the frost by night,
yet he who knows our necessary refinements, is able to limit the waters,
that they do not overflow us, and, in his own time,
will say of the operation of the furnace, "`it is enough.`"
Till then, I trust deep will "`utter unto deep,`" and with an increase of suffering,
we shall experience an increase of holy fellowship.

[.small-break]
'''

1780.--I often keep silence, and find myself a subject copious enough for meditation,
which is not always of the pleasing kind;
but I endeavour to pass along as quietly as I can;
it being seldom my lot to experience much sympathy or fellowship with my friends, and,
consequently, I cannot expect to derive much from theirs.
And yet for all this, I do not mean to complain, but am abundantly convinced,
that I lived upon this pleasant fruit, this sensible union, long enough;
and to know the lack of it, is, I doubt not,
sometimes as necessary as its free circulation, which, may perhaps return in its season,
when it may prove like the dew of Hermon.`"

[.small-break]
'''

1780.--I cannot but fear your apprehension of my
alliance to a state of properly attained peace,
arises more from your good wishes to me, as an individual, and from that universal love,
which is imprest with a sense of the benevolent extendings of divine regard,
that desires all may partake as at the river of life freely,
than from a just sense of the real situation of my mind;
which has not yet cast its sackcloth covering, nor received a garment of praise.
And as this change cannot be effected, but by the miraculous power of the divine arm,
I wish only to seek for it from this source of strength:
and if it be my lot to go softly all the days of my life, in the bitterness of my soul,
I wish to submit to this allotment, and endure the necessary turnings of the divine hand:
but oh! that I had in the wilderness a lodging place, that no eye might see,
nor ear hear, the imperfect state of a heart, the depth of whose distress,
omnipotence only can fathom.

[.small-break]
'''

Third month 1780.--My dear friend`'s letter was too acceptable to lie long unacknowledged;
because it revived in the breast of her friend
all the cordiality of a union and fellow-feeling,
which I trust do not originate in the part appointed for destruction;
but are rather the offspring of minds engaged,
(though feebly) to travail on as in great weakness and fear,
and sometimes having no language to express, either to the fountain of good,
or to one another, but "`sighs unutterable.`"
How infinite is the condescension of that precious Saviour who helps our infirmities,
and is touched with a feeling of them; aiding the mind, with a degree of holy confidence,
after all its apparent exclusions from the participation of
divine good once more to look towards his holy habitation.
And as it is through sufferings that our natures are refined and sanctified,
they must not be of our own choosing, because the suffering might then,
in a great measure, cease,
and that necessary heat which attends the furnace of affliction,
and which purifies the mineral, get quenched; for so depraved are our ideas of things,
that I have thought, and in some measure felt, that even in our baptisms of spirit,
we would wish to have a choice; so active is self,
that it cannot be satisfied without a sphere to move in.
Think not, my beloved friend, that I consider this as a peculiar propensity of yours;
for it rather occurred as a degree of painful experience.
I have often viewed your situation,
(and particularly since the receipt of your letter this
morning) as almost too trying for flesh and blood,
but He who places the members of his church, and appoints them their lots,
does not leave their support to flow through these corrupt sources;
but marks their steps, and, perhaps quite hiddenly, confirms the feeble knees,
and leads them in a way they know not.
My mind is frequently too much depressed, and sometimes tossed with tempests,
to admit a consolatory sentiment,
much less to offer my friend the language of encouragement;
nevertheless I cannot help expressing my firm belief,
that all your troubles will work together for good, and that the deeper they are,
the greater will be the preparation for a glorious reward in the house of the one Father,
with whom a book of remembrance is written.

[.small-break]
'''

1780.--When your letter, before this last reached me,
it was my full intention to have replied to it very soon; but in this,
as in the most important and necessary pursuit the human mind can have,
the spirit of procrastination prevailed; which I generally find is the case,
when the first ability the mind possesses to do good, is not accepted.
This is a reflection I have often painfully to make,
because its subject never fails to impart a feeling sense of weakness;
and when we consider it properly, that our being here is uncertain,
and that the time wherein we can acquire durable riches, is,
though sufficient for the work designed us, short and fleeting,
we can scarcely quench an impulse to vigilance, or view ourselves in any other light,
than sojourners in a land of exile, where the spirit that is pure,
and the light which is the life of men, is oppressed and rejected,
because to the natural eye it has neither form nor comeliness.
I may, to my dear friend confess,
that my travel has long been through a waste howling wilderness, where,
(though surrounded with innumerable blessings) my mind
has been led mostly to feel itself like a pelican,
and to wish for an outward situation similarly obscure,
that I might forever be hid from the eyes of men,
of whom I often feel a fear that baffles description;
but as this allotment has not fallen out for me, there seems no way,
but simply to attend to that impulse which I have apprehended to be divine,
and at the same time am thoroughly willing to be convinced, is not.

Your wish, that faith may be equal to the trials of my day, was peculiarly applicable;
for could I give you an idea, how often I am ready to sink in the depths of distress,
when the weeds are indeed wrapped about my head,
and all supports are either refused or withdrawn,
you would readily conclude me short of faith and patience too.
But no language is able to set forth that situation of mind,
when the wisdom which is from above,
and that which is from beneath are struggling for victory.
It is truly a fiery trial,
but one which I fear will never in me consume all the reprobate silver.
I have stumbled on a subject, which I had no thoughts of even hinting at, when I began;
but in confidence and freedom I have been often led to open my mind to you,
and I trust that, wherein we were heretofore united,
will not fail to strengthen our bond, and open to us a channel of converse,
more hidden and pure than we have yet altogether experienced;
and a fellowship which is only understood,
when the mysteries of the true church are opened.

Tell me, my beloved friend! are you passing through this wilderness,
and often ready to faint for lack of water?
If so, allow me to say, prolong not your journey there,
through a tearfulness of taking your possessions in the promised land,
nor of the inhabitants which are to be subdued before it can be enjoyed;
for I trust no transient, fading joy, can yield your mind that peace it desires:
therefore let not your hands hang down, but rather put on strength,
in the name of him who is able to help, and in whom is the fulness of power,
and be strong and work; for I believe it is a day,
in which this command is gone forth to those whose hands are not polluted,
and whose language is not that of confusion.
Deep are the baptisms of such,
or how could they be fitted to stand in that day of trial which is,
with a gradual and steady pace approaching, if not rooted and established upon that Rock,
against which the gates of hell can never prevail.
And though these, for the present, have to drink of that cup of adversity,
whereof our holy pattern first tasted,
and have to be baptized with the baptism he was baptised with, yet,
in the immediate revival of his promises, from that Comforter whom he has sent,
there remains to be consolation.

[.small-break]
'''

Fourth month 1780.--I want to hear how you feel yourselves at your new habitation,
and whether it proves a Goshen to +++_______+++,
whose mind has often felt to me to be secretly clad with sackcloth,
even when perhaps obeying the command, to wash and to anoint,
rather than appear to men as if fasting.
As this is a situation necessary for us,
its continuance administers no cause of discontent,
if we have but an evidence that we have not stepped out of the holy inclosure;
finding the fence of divine appointment to be about us, no matter what we suffer.
It is not for our rejoicings, and what feels comfortable to ourselves,
that we can expect a reward; but rather for our trials and probations,
if we endure them with patience;
and even for these we have no reason to expect a full reward; for if that were the case,
where would be the reserve for the fruition of joy in the life to come?
Nevertheless, we do sometimes get favoured, in our wilderness journey,
with a little bread handed in secret, and with an opening of the brook by the way;
and the remembrance of our partaking of this together,
refreshes and strengthens in some gloomy seasons.
I have often reason to number your friendly regard to me among the blessings of my life,
and I sometimes think, in the feeling of a nearness I cannot describe,
that my affection to you is not less than filial.
May I be preserved worthy of this fellowship, and, by an increase of purity,
find an increase of that union of spirit which lives beyond the grave!
I think nothing has more conduced to my confidence in, and fellow-feeling with you,
than the belief that your reproof and plain
dealing would be as readily administered to me,
as your encouragement; and I beseech you, never lose sight of this openness,
for I am surely one of the weakest and most frail of the whole flock and family,
if I am worthy to be included in the number.
Yet, if I know my own heart, it is not myself, but the cause which I have in view;
and I wish for still more of that disposition which can enable us to say,
"`let the righteous smite me, and it shall be a kindness; let him reprove me,
and it shall be an excellent oil.`"

[.small-break]
'''

+++[+++In the fourth month 1780, with the approbation of the monthly meeting,
and in company with her mother,
she was engaged in a religious visit to Friends
in the counties of Westmoreland and Cumberland.

The following extracts contain the material parts of what are collected,
from her own account of her concern in this visit.]

[.small-break]
'''

The meeting at Bowes was trying, though I believe satisfactory to my mother.
For my part, I had deep heart-felt mortification,
(which I have been very little free from since) and went very much fatigued to bed,
it being ten at night when the meeting broke up,
and we had a hard day`'s work in travelling.
Next morning, we sat a little with a schoolmaster and his wife,
to whom there was much openness to communicate close counsel, as well as encouragement.
Next day we went to Penrith, where we stayed over first-day,
and had two suffering meetings;
in both which I felt a greater unwillingness to submit to a necessary wading of spirit,
than I can describe; for really, the spring of life requires such digging for,
in places where the substance of religion is departed from, and only the image retained,
that, in this exercise, I frequently felt ready to faint,
and always engage with it in great dread; because it opposes that natural part,
which would keep the house in peace, and be free from all these troubles.
However, I felt more ease of mind in the evening than I could have expected,
having drank tea at the house of a widow friend, and had an open,
favoured opportunity among her daughters,
several of whom appear to be under a fresh visitation.
We were at the monthly meeting at +++_______+++ and a most painful, trying time it was:
but after much labour, and deep suffering, the right thing got uppermost,
and though the other was not slain, it was a favour that it did not altogether rule.
Oh the untempered mortar there is in that place,
and the unsoundness almost from the crown of the head, to the sole of the foot!
I ventured to stammer out what appeared, though in a manner scarcely intelligible,
and in great fear, having previously had specimens of offerings,
which carried not the evidence of having been prepared at the altar,
and which indeed often create the query, "`who shall stand?`"

Longtown^
footnote:[The northern yearly meeting was then held there.]
was, as I expected, a place of some suffering to me;
but I could not have expected to have felt myself such a speckled bird as I did,
though I kept myself much to myself:
but it was impossible to keep as retired as was desirable,
nor were my motives for it justifiable, being only to shun the appearance of a fool,
among a set of wise and fine folks, whom we had at our inn.
Indeed, a state of deep heartfelt mortification has been my lot, mostly, since I saw you;
but as the cause, without doubt, originates in the impurity of my own mind,
I ought to be thankful for dispensations so necessary, though hard to bear;
for surely there never was any, to whom the simplicity of Truth was so irksome,
and who caused themselves such deep and hidden conflicts as myself When one is got over,
and another approaches, that disposition, which loves not sorrow,
but would walk easily through life, is ready, in the remembrance of what it has suffered,
to say, like the king appointed for destruction,
I thought the bitterness of death was past;
but oh! how many strokes do I need to accomplish this death!
It has been hard for me to have my mind bent
under any degree of that weight and suffering,
which are generally necessary to feel before the spring is found to be opened,
or any circulation of divine life experienced:
because flesh and blood cannot aid in this labour, and, its strength being set at naught,
it wars with the spirit: in the feeling whereof, I am often ready to faint.
Oh! that my feet may stand fast in the bottom of Jordan;
that I may neither flinch from a necessary wading of spirit,
nor be overpowered with the floods of the mighty deep; and, above all,
that I may be preserved from uttering words without life, for truly, "`I am a child.`"

When I wrote you last, my mind was indeed in a sad spot;
the billows seemed to go over my head, and life felt almost to be a burden;
for I could not at that time,
look at our going to Whitehaven without the view of visiting the families,
and that work appeared so ungrateful to me,
that I could not bear the thoughts of having anything to do in it.
However, I endeavoured to forget it, and to consider that if the thing was right,
it would be got through, and that somebody, better able and better skilled than myself,
would have the burden to bear, and the work to do;
and that if I got mortified with having something to do, now and then,
the visit might be of as much benefit to me as to the whole meeting besides.
Thus I endeavoured to rest it, when my mind would submit to think coolly on the subject;
and indeed I had almost lost the painful impression when we got to Whitehaven,
till we both felt it in the forenoon meeting on first-day, with this conclusion,
that to yield was the only way to leave the place in peace.
My mother having, previous to her view of this visit,
concluded to have a meeting at Maryport on third-day,
found herself most easy to pursue that plan,
and accordingly we went on second-day afternoon.
We found that the right time was fixed on for Maryport, and a favoured meeting it was,
there being much openness to labour,
indeed far more than in some places where a greater appearance is retained; but where,
it is sorrowfully to be felt, the mighty are fallen, and tribes are lacking among them.
There are many such places in this county, as well as in ours; and under a sense thereof,
we have known a going bowed down all the day long.

After this meeting, we returned to, and proceeded in, the work at Whitehaven.
The labours in this visit were of the mortifying kind,
and required a continual exercise of both faith and patience:
because we had generally to sit where the people sat, which was often in dismal places;
but being, I trust, in the right line,
it will be made more profitable than could then be seen.
It got finished on sixth-day,
and in the evening there was a meeting appointed to begin at five o`'clock; which was,
like all the visit before, a suffering meeting;
but I hope the rightly concerned in that place, will reap the benefit of it, for it was,
though painful, a remarkable time.
It is with a degree of thankfulness I may acknowledge, that I felt in this visit,
a greater resignation to what I apprehended was the divine will,
than I ever experienced before; and I can, now it is over,
cheerfully submit to the belief, that I was of no use,
(if even preserved from doing harm) but that the thing was made useful to me,
in subjecting my own mind, and teaching me, by a little more experience,
the true way to wisdom,
which is first becoming a fool. This state of preparation I expect to be in,
all my life long; but I wish, (with a fear) that it may be so abode in,
as to obtain the prize at last.
Well, this trial is over, with being refused, reviled,
and fought with as by beasts as Ephesus; yet these are small troubles indeed,
when compared with the enemies of our own houses,
that host of opposition which is often hard to press through.
This woe is past, and I pray in my heart that another of the same kind may not soon come;
for though I was favoured to feel it made much easier to me than I could have expected,
yet the work of visiting families has always, since I was led seriously to consider it,
appeared to be so awful, and to require the royal signet to be so evidently affixed,
that the fear is great, of either moving without it,
or being concerned in so momentous a work, when there is not strength enough to support,
and wisdom to teach.

[.small-break]
'''

+++[+++On their way home, they felt a concern to visit the families of Friends at Kendal;
near the conclusion of which, she says,
"`the spirits and body seem both ready to fail under the present exercise;
but we have no reason to repent engaging with it; for, thus far,
we have experienced strength sufficient for the day.`"
Soon after her return from this journey, she writes concerning it as follows:]

[.small-break]
'''

After many close exercises and deep trials, mine chiefly of my own making,
we are now enjoying a good degree of peaceful serenity,
and though (I think) sufficiently stripped,
yet we seem pretty clear of any painful reflections on the past allotment.

[.small-break]
'''

Fifth month 1780.--How truly valuable is this precious unity which,
like the oil that was poured upon the head of Aaron,
remains to anoint the very skirts of the garments of
those who have obtained the mark of discipleship,
to love one another.
In the renewal of it,
I feel greater consolation than is usually bestowed upon me from causes of this kind,
because there are few indeed with whom I find myself nearly united,
or whose regard affords me relief in the time of need,
although I know them to be far superior to myself;
insomuch that I conclude the command is certainly to me, "`salute no one by the way.`"
But glad I am that there is an exception to this,
and that I hope I can in the right line salute my friend by the way,
and visit him in the wilderness,
where all who are united to the true church must chiefly dwell,
and wait for its redemption.
If this is not found in our time, we have yet reason to hope,
that having partaken in some measure of its sufferings,
whether principally for ourselves as members, or for the whole body,
this offering will be acceptable to the tSearcher of hearts; and,
then if in His wisdom some of our days should prove to be few and full of son-ow,
may we not look towards the morning of a better day,
and an inheritance in that country whose inhabitants never say, they are sick?
Were it not, now and then, for a little of this hope which lives within the veil,
I know not how things would be got through;
so selfish am I that I fear the reward is too much an object,
and not that perfect love which casts out fear,
and is ready to obey and suffer all things for the work`'s sake.

[.small-break]
'''

Ninth month 1780.--I have felt a more than usual impulse to salute you,
my much beloved friend, and, according to my little ability,
to strengthen you in repeating the efforts which I trust you are, at times,
concerned to use for your own everlasting welfare,
by turning a deaf ear to the subtle insinuations of the adversary,
who is evidently seeking your destruction.
I am well convinced that no language I can use, except it be blessed with the efficacy,
as well as appearance, of indisputable truth, will ever be acceptable to you,
or prove profitable; and it is, I may truly say, at this time particularly,
the fervent engagement of my mind,
that you may come to a settlement in that power which is unchangeable, and which would,
if your anxieties and heat of spirit were more damped,
instruct you still further in the mystery of yourself, and that of godliness,
which is profitable for you.
With what manner of love has the Father loved you,
has often in effect been the query and exclamation of my mind,
when the wonders of your deliverance from Egyptian bondage have occurred,
with an evidence of the hand that wrought them,
and of that mighty power which has caused the bush to burn before you,
and convinced you that the ground whereon you stood was holy.
As sure as ever He was with Israel, and with Moses their leader, he is with you;
and your trust in him,
and seeking for a passive state of mind in that wilderness travel which may be assigned,
will, I believe be crowned by your arrival at the land of promise.
But think not, my beloved friend, when there is a lack of water,
and of that refreshment which the unmortified will is eagerly thirsting after,
to use the means whereby the meekness of Moses was overcome, to strike the rock,
and thereby offend that holy providential care,
which will never leave you to suffer for lack of true knowledge,
but will be found to provide you with food in due season;
and though it may not always be pleasant, but, at times,
may resemble Mara`'s waters for bitterness, yet the spiritual Canaan being in view,
and not expected on this side Jordan, the river of true judgment,
it will animate to still greater degrees of virtue, such as patience, fortitude,
and strength, in this holy travail.
Under a renewed belief that you are in the place allotted by divine wisdom,
I feel an earnest solicitude,
that you may be strengthened to discharge your duty in every good word and work;
and that He who has plucked your feet out of much mire and clay,
may not only set you upon the immovable rock, and establish your goings, but,
in His own time, put such a song of deliverance into your mouth,
as will last to all eternity.
It is, my dear friend, with a love which I trust is more than natural,
that I re-salute you, and bid you be of good cheer, and labour to detect every delusion,
for truly there is fight enough for it.

[.small-break]
'''

Tenth month 1780.--Animated with the effusions of much love and near fellowship,
I have many times secretly saluted you, since my abrupt departure from +++_______+++;
where I was thankful to feel, after a long fast from sensible enjoyments,
either religious or social,
that there is yet a union to be attained with the spirit of pure love,
and that we can in a state of mutability, in proportion to our faithfulness,
partake together of its binding influence.
A revival of this sense, I was, and am, I hope grateful for,
and glad to find a similar sentiment in my companion, I neither received,
nor expected any great peace and reward for the offering of paying you a visit,
which was not completely of the free-will sort; but thus much I may say,
that a degree of comfortable serenity attended my returning mind.

My throwing myself in the way of meetings,
in which my attendance has not appeared to be in the movings of light, is not,
in my idea without danger: for if we depend,
though in ever so small a matter upon a puffing forth
which has not a little clearness for its evidence,
we may likewise conclude it to be equally safe,
to offer our service from as doubtful an impulse; and thus, I am apprehensive,
a clouded state may ensue.
And having been accustomed to adopt things through perhaps a willingness to do good,
which have not borne the royal impression,
our distinguishing feelings may gradually become so weakened,
that the pure unmixed word may get sullied,
and the powerful demonstration I thereof decrease.
This is a sentiment which I offer by way of apology for myself;
and yet I would not have my friends to conclude that I
believe great openings are to be looked for,
in every little service.
If the token of rain be ever so small,
yet if it be so sure as to bear the comparison of the cloud of the size of a man`'s hand,
I am of opinion,
(though not always willing to accept it) that it is as much to be depended upon,
as if the clouds were opened, and we felt the showers from there.
It is certainty, though ever so little in appearance, that I wish to follow.

[.small-break]
'''

+++[+++Towards the latter end of the year 1780,
she came under a religious concern to join her friend and relative Tabitha Hoyland,
in a visit to the meetings of Cheshire, and a part of those in Lancashire.
And having the concurrence of the monthly meeting, and a certificate thereof,
she set forward to engage in this service, in the twelfth month.
The ensuing parts of her letters on the subject, afford some account of this journey,
and show the situation of her mind, under the prospect of the work before her,
and in the prosecution and completion thereof.]

[.small-break]
'''

Cheshire has long attracted my mind, and of late more than usual;
and on my cousin Tabitha Hoyland laying a similar concern before me,
those feelings revived with some weight;
and not without a great fear lest (though the impulse might be right)
the time and companion might not be in the same appointment:
and hence appeared the necessity of having it hewed and squared.

It is only in a little faith that I look towards the journey in prospect,
and at the rectitude of it; and though I fear it is not equal to a grain of mustard seed,
yet I think I am thankful for this little: and since it has been received,
and the affair mentioned, a degree of peacefulness and quietude has attended my mind,
which is all the light I find upon it; and which requires, sometimes,
all my vigilance to retain,
lest the floods from the mouth of the dragon should overwhelm,
and cast away that little strength that is at present afforded;
and instead of adding thereto, by devotedness to be anything or nothing,
leave me tossed upon the unstable element,
where neither rock nor shore can-sometimes be perceived.

It was not the least of my concern, or rather dislike,
to submit to the thoughts of going to some places in Lancashire, which I had in view;
for, indeed, that seemed not much less than giving up my life:
and this proceeded from considerations which I think you can hardly share,
having surmounted many of the difficulties and
mortifications which appear very formidable to me.
But when we have suffered for disobedience,
and are favoured with a view of the rewards of the faithful,
and are likewise I convinced of the importance of our duties,
though ever so small in appearance; when our nothingness is sufficiently felt,
and our minds impressed with the awfulness of the divine requirings;
life itself looks but a small sacrifice, and so reasonable,
that there is no excuse for withholding it,
especially that inward existence which does not co-work with the life of true religion.

[.small-break]
'''

--From Ackworth, I had a companion who imparted some good and wholesome counsel to me,
and more encouragement than I could have looked for;
but my secret sitting was in the dust, and much gloom seemed to cover my views.
I reflected on the preceding evening,
and found its enjoyment was like manna two days old,
having lost both savour and nourishment; and instead of a renewal of the same,
a fast was dispensed, the cause of which I must leave: but it is a painful one,
and if I had felt myself before I left home, as I have done since,
it is much if the venture had been made.
Could I believe that this is anything like going forth without either scrip or purse,
I should perhaps be more reconciled.
I am thankful that in every state I have some degree of the comfortable impression,
that unity is good; and though mine is not of the most expansive kind,
yet in a renewed feeling of my little, I cannot but wish,
that we may be so willing to suffer together,
and frequently to go down to the potter`'s house to be there
fashioned and formed either for vessels of honour or dishonour,
(as may best please him who has power over the clay) that we may also
experience a humble ascent to the house of true prayer,
and a rejoicing together.
My heart is too full for words to relieve,
but being convinced that there is a better and more refined intercourse than this,
a communion which, proportioned to our obedience, is pure and edifying,
I wish in that to remember, and be remembered.

[.small-break]
'''

--We went to Lowlayton, on sixth-day, and found there but one family of Friends,
who came in by convincement.
It was a comfortable place;
for their simplicity and integrity rendered their cottage an agreeable mansion,
in which there was nothing painful to be felt.
The meeting there next day, was much larger than we looked for,
many people in the neighbourhood coming in, whose solid, innocent countenances, were,
I thought, as likely to do us good, as we to do them any.
It was a satisfactory meeting, and afforded some encouragement to proceed.
We went to Stockport on seventh-day afternoon; the meeting on first-day was a painful,
trying one, and yet strength was not withheld.
From Macclesfield we came to Leek,
and have just finished (except one family) a visit to the families here.
We have had eight sittings today, besides the week-day meeting, which has been close work.
We are however thankful, and have cause to be,
that strength equal to the undertaking has been afforded;
and though we have been deeply tried, yet, upon the whole, I believe we may acknowledge,
that we have lacked nothing, and have been much united to a few in this place.
This work of visiting families, is the last I should choose for myself,
if I might be my own chooser; but as it is wrong to desire that indulgence,
I see I may as well give myself up to what appears in the line of duty.

[.small-break]
'''

--It is with thankfulness of heart,
that I acknowledge myself in a tolerable degree of health,
through many different dispensations which have fallen to my lot since I saw you;
for there have been experienced a lacking, and a sufficient abounding;
but I wish I could add, that in every state I have learned to be content.
Great indeed has been the condescension of him who is pleased to make use of poor,
weak instruments, and by things which not only appear low and contemptible,
but are so in reality, to bring to naught,
and to reduce things that are mountains in prospect;
proving to us a present help in every needful time, and, by his invisible power,
strengthening us when we are ready to faint in our minds.
And still greater, I may acknowledge, has appeared his wisdom in deeply trying us,
or however myself, with the most abject poverty and strippedness of mind;
indeed so much so, that I think I never before experienced such humility,
in a sense of myself, and under the convincing proof that of ourselves we can do nothing.
This is a situation wherein we see from where all good comes,
and the necessity of casting ourselves so wholly upon the divine arm,
as to have no confidence in the flesh.
No dispensation, however desirable the enjoyment of good may be,
seems so much to drive us to the root of life,
if we endeavour sufficiently to profit by it; and consequently,
none that we ought to be so thankful for,
when our hearts are capable of feeling true gratitude;
for he who knows the weakness of our frames,
and is touched with a feeling of our infirmities, sees what we can bear,
and knows how frail we are.

Thus have I, in this little journey, been wisely taught, through many trials,
to live by faith; and thus far, in reflecting on the past, to own I have lacked nothing.
But we are abundantly convinced,
that they who are sent out in this day to a people who have, in a great measure,
forsaken both law and testimony, and what is still worse, see not their states,
but are secure in themselves, have not to eat much pleasant bread.
I think I may say, it has often been our lots to go bowed down all the day long,
and to mourn in a deep sense of the great desolation which overspreads the Society;
insomuch, that we often admire there should be any sent out to visit them,
and that the feet of those that are rightly shod,
should not more generally be turned to others: for from these,
there are the greatest hopes in this county, which is likely, in many places,
to be left desolate of friends who keep their places.
We have, however, in a few of the meetings which we have last attended,
been agreeably disappointed,
in finding more preserved or quickened by the life of religion, than we expected;
and it has been our lot to visit these, as well as a very contrary sort, by families.
A very trying work it has been, and it is not yet done.
In it I have often lamented, lest for lack of that spirit of discerning,
with which the prophet was endued, when he went to anoint one of the sons of Jesse,
there should not be a right division of the word, and thereby much harm be done.
Under this consideration, great abasedness has attended my mind,
and a desire that the fleece may be tried both wet and dry.
We left Namptwich undone, and hoped, no even resolved, to return to it no more;
but now I have to confess, we are on our way there.
It is however a favour, that, through all,
we are led to feel and sympathize one with another; I mean my companion and self,
and that our little services have been harmonious;
and if we keep near that preserving arm which has been with us,
I doubt not but this strength will continue and increase; for in unity,
if it be of the right kind, there is certainly strength.

We got to Manchester, after a week of many probations,
which ended better than we could have looked for, at the beginning of it,
when our hearts were ready to faint, and the billows seemed to run over our heads,
in the feeling of what we had already suffered,
in remembering the affliction and distress, the wormwood and the gall.
Our minds were humbled in the prospect of an opening field;
but I trust it was He who commanded the waves to be still, that calmed these floods,
and renewed a degree of faith and patience to persevere in the tribulated way.
What need there is to keep near to the fountain of life,
and to receive our refreshment solely from it! because from there only,
arise our fresh springs and immortal food; which,
though the bread of adversity and the water of affliction, yet coming from this source,
they are no less efficacious to the nourishing, strengthening, and building us up,
than the sensible union with divine purity.
Our hearts are very incapable of judging concerning the dispensations of providence;
we know not ourselves, and consequently, cannot prescribe for ourselves.

How passive then and how like little children,
should we be to him that searches the heart! but I am often afraid, lest,
by indulging my own ideas of what is good,
and not labouring after a total resignation of mind,
but wanting to have things in my own way, I should frustrate the divine intention,
which may be to humble and reduce self, more than flesh and blood would point out.
The great meetings we meet with, are almost overmuch for us,
and what made it still worse to us at Liverpool, was a funeral in the afternoon,
and a vast number of people.
We little thought when we fixed to stay over second-day at Manchester,
that we should have one to attend there, which is the case this afternoon,
and how it will be got over, I know not.
If we may but be favoured to be rightly quiet, it is all we desire;
and if we cannot be that, it is certainly our best way, as far as we are able,
to take up the cross, and despise the shame; which sometimes feels great, and at others,
I may thankfully acknowledge, is in a great measure removed: but then,
what need there is of care not to overrun the guide,
and work without the power of the word?
Dangers surround us on every hand, and our standing often seems as on a sea of glass.

[.small-break]
'''

--With satisfaction and pleasure, I have lately looked towards home; indeed with so much,
that a fear sometimes strikes me,
lest in wisdom some unforeseen affliction should be sent to moderate it.
According to my present feelings, I am returning peaceful and easy;
and though we have missed some meetings, which I own I had a view of,
yet it was with a full belief, that they will not be laid to my charge.
I wish that we may be thankful enough for the favours we have received many ways,
since we left home; and, what appears to me no small one,
for the readiness of my beloved connections,
in making everything as easy as outward means can possibly do,
and affording accommodations, for lack of which many lie under very great difficulties.
The consideration of these, things often affects my mind.

[.small-break]
'''

Bradford, 19th of First month, 1781.--I thought, when we left Manchester,
that it was a strange thing if we did not return to it again;
yet I had since lost the impression,
further than wondering why such a thought should then have struck me;
and even the concern about many meetings, which I thought we had missed,
was so much gone off my mind, where it had dwelt with some weight,
that I seemed perfectly easy,
under the belief that the concern would devolve on my companion,
but little expected it was so soon to be evinced; for after much secret sorrow,
which I perceived, but dared not pronounce my apprehensions of the cause,
she disclosed last night her uneasiness, and desire to return to the places we passed by,
as well as to go to some others in this county.
On looking a little seriously at it,--indeed not a little,
for we had nearly a sleepless night,--I could not see
that it was less than my duty to return with her;
not only from having had a view of the same places, but as a companion, who,
if truly one, cannot leave in the day of trouble.
I wish myself better qualified to sympathize with her in this trial,
which is a very great one,
and requires all the alleviations that are in my power to bestow.
I believe her willingness is now so great, that for the purchase of a little peace,
she would return to all the places, to do the things which appeared needful,
and were not fully joined in with;
but when this great sacrifice of the will is completely made,
I trust some ram will be caught in the thicket, or some smaller offering accepted.
Home now looks at a great distance, and I find that it will contribute most to my peace,
to think as little of it as I well can; and if it had been less in my mind of late,
this turn in our affairs, would by me, have been less felt.

We find ourselves after the meeting today, in a very gloomy situation of mind;
as it was a suffering time,
and we thought left us with the sentence of death in ourselves;
perhaps that we may not trust in ourselves,
which I ardently wish we may be preserved from.
We intend going to Leeds tomorrow evening; we dread it not a little,
and this day`'s work increases the apprehension of very great suffering;
but it often seems best to leave, or draw the mind from future trials, and endeavour,
as well as we can, to bear those of the present day,
which are generally found to be sufficient.

[.small-break]
'''

First month 1781.--The trials which I believe are in
infinite wisdom allotted to the rightly concerned,
are many; of which, I trust, we have been favoured to share;
yet we have no need to make our way harder,
by adding so continually our own judgments and discouragements upon them;
making comparisons which we have no right to do,
and weighing things which can only be tried in the balance of the sanctuary:
for we know so little of things about us,
that we are very incompetent judges who stand most in divine approbation.
I cannot but much wish that +++_______+++ would grow wiser respecting these things,
and endeavour to shut out discouragements which do not come in the line of wisdom;
and then, I am satisfied, she would find her way to be as easy as she thinks mine is,
and would be convinced that her labours have
been more acceptable to Him who put her forth,
than she will often allow.

[.small-break]
'''

First month 1781.--Does not Solomon say,
that a few words fitly spoken are like apples of gold in pictures of silver?
I think he does; but whether or not, it is so in the scripture of my heart,
and your lines prove the justness of it.
Feeling has no fellow,
and if the address be but felt by the receiver in the covenant of true love,
it is something like such a ministry as I covet, where words are lost in power.
Deceitful as I know my own heart to be,
I will not allow that my remembrance of you arises wholly from "`an imbibed
favourable impression in times past,`" and that a personal absence revives it.
I should conclude that to be.
a formal attachment which has nothing but age for its origin,
and is not supported with repeated renewals of life.
Is this the inward tie that no change can break?
the love that many waters cannot quench, or the floods of affliction destroy?
Surely it is not of that nature which can endure the fire, and be refined by it;
it is more like the base metal which would rise as the scum and be lost,
than the solid gold that appears afterwards,
and is able to endure even the seventh purification.

[.small-break]
'''

Manchester, 4th of Second month,
1731.--Our minds are often bowed down under a sense of the awfulness of our engagements,
and dismayed at the sight; nor need I say how closely our time is filled up therewith;
for after sitting with seven or eight families, we are generally ready for rest.
I have the very great satisfaction now to say, that, except one family,
we have finished in this place; have had four today, besides the two meetings,
and upwards of forty since we began, with putting now and then two together.
We were at Stockport on fourth-day, and had it unexpectedly in our power,
to pay off a small debt, which we contracted when there before.
It has been wonderful to us, how we have been, and are likely to be, turned to places,
and thrown in the way of doing our first works; which we cannot but view,
as a mark of divine condescension to our infant state:
indeed it has been manifested to us, far beyond what we could have looked for,
in the course of this journey throughout; and not less so since we came into this place,
where instruction has been daily administered from different sources;
some of which have proved deeply trying to flesh and blood; but being, I trust,
in the ordering of unerring wisdom,
I wish--perhaps more than I endeavour--to profit patiently thereby,
and value the rod as well as the staff.
It is indeed high time to number our blessings.
They are truly many, and we cannot fail of seeing and feeling them;
that of having the parental care and solicitude of
several of our much honoured and valued friends,
is not small in our estimation.

[.small-break]
'''

--We have now got to Warrington, and are endeavouring to keep ourselves quiet,
and as much as we can, labour to feel what is the divine will concerning us; which,
with respect to our coming here, has been much a mystery.
The prospect almost dismays us, attended with a fear,
that we may now be in danger of compassing a mountain in the wilderness,
and engage in a service, for which our strength is not proportioned; and so,
notwithstanding we have been favoured with divine condescension to our states heretofore,
bring upon ourselves unnecessary trials,
and thereby pierce our minds in future with many sorrows.

It is no small concern to us to find, with the present view of things,
every qualification lacking for such a service;
and our minds greatly stripped of strength and clear discerning;
and to move without a renewal of these, we dare not.
When my companion first proposed our return, the evidence I thought was so strong,
that I cheerfully complied; yet feelings very unlike these ensued,
even a state of deep distress and mortification,
when I found we must turn our backs on home, and return from where we came,
to do our first works.
Great was our pain, from, I believe, an unsubjected will; but great likewise and evident,
was the operation of the divine hand, in judgment upon us for the past,
and no doubt as a preparation for the future; for it never appeared clearer to me,
than when under this dispensation, that for every fresh service and work in the church,
we must experience a renewed baptism of spirit and purification of the gift;
and that the more we have of the dross, or the reprobate silver,
the more frequently must we pass through the refining fire.
Notwithstanding I was, sometimes, in the impatience of my heart,
ready to query as the children of Israel did, "`were there not graves enough in Egypt,
that we are brought here to die?`"
yet there were times,
when all that was within me was prostrated under the chastising hand,
and sought that it might not spare.
How preferable is it to all secondary administrations of judgment, when with David,
we wish rather to fall into the Lord`'s hands, than into the hands of man! and surely,
the more we seek to derive our instruction and food from the fountain of good,
the less we shall be subject to instrumental means.

[.small-break]
'''

--I never felt myself under such complicated discouragements at any time;
and oh! that we may both be enabled to bear these fiery trials,
with resignation to the divine will, and seek to profit by them,
that the state of a weaned child may become our experience.

[.small-break]
'''

--As I make no doubt it will be acceptable to you to hear from two poor pilgrims,
who are almost worn out with things that appear too mighty for them,
I just embrace a little vacant time, to hint how we have fared;
and may in the first place say,
that the present engagement has been the most trying of the kind we ever experienced.
It has been frequently our lot to go down as to the bottom of the mountains,
where the earth with her bars, was about us.
Under this pressure, our minds have been secretly clad with sackcloth and deep mourning,
when it has evidently appeared, that the pure life of religion is in a state of bondage,
and that it sensibly utters the language, "`I am oppressed under you,
as a cart with sheaves.`"

To visit this seed of the kingdom, we find to be no light matter,
especially when hid under the briars and thorns, and then plumed with human wisdom.
Who indeed is sufficient for these things?
I often lament, and with reason, that my heart is not more bound to the cause,
and more willing to suffer for it; and I fully believe,
that until this is more experienced, there will remain to be, as there have already been,
many trials and afflictions, which originate not in the divine will;
for it is still a truth, that our greatest enemies are those of our own houses,
and that to endeavour to subdue these, is our indispensable duty;
but oh! what strokes are in wisdom administered to us,
to destroy that life which has no existence in the divine purity;
and except we be faithful unto this death,
we can with no probability look for the crown immortal.
We have frequently had to recur to the moving cause of this journey, and,
as an additional trial, found the feeling sense of that withdrawn from us;
but all these things teach us where to place our present dependence;
and notwithstanding dispensations thus painful have been our portion,
we have great cause,
thankfully to commemorate the blessings of the divine and bountiful hand,
which has been strength in our weakness, riches in our poverty,
and a present helper in the needful time; and has refreshed our drooping spirits,
insomuch that, with alacrity of heart, we have pursued the path cast up for us,
and have been favoured to see the great necessity of
passing frequently through the furnace;
and oh! says my heart, that I may be willing to descend again and again,
till He whose invisible arm sustains us there, is pleased to say, "`it is enough.`"

[.small-break]
'''

--We have now finished, for what we know, our engagement at Warrington.
We wound up all in this family last evening;
but oh what a day was yesterday! my companion`'s situation and mine were very different,
though both trying; and the more so, because we were not alike led;
but still there is a secret trust, that we were both in our places.
The meeting was held at Penketh, and being the preparative meeting, was very large.
The first meeting was so low and painful in the forepart,
that I was glad secretly to offer myself to do anything,
if light might but shine upon my dwelling.
In this situation, I soon saw that we had nothing to do in that sitting;
but it seemed as if I heard a voice, "`visit the men and women when separated,
for they require different food.`"
The evidence was, I thought, so strong,
that I earnestly desired to be preserved faithful,
however hard it might be to the creature, lest a worse state should befall me.
When the meeting parted,
I just requested my companion to feel if it
might not be best to go into the men`'s meeting:
her reply was, "`she had seen nothing of it, but would go with me.`"
This greatly increased the burden that was upon my mind,
but remembering my recent view and request, I dared not,
after all the favours I had received at the divine hand, in our late probationary visit,
refuse a compliance with this intimation of duty; and finding I had a little strength,
was made willing, with that, to become still more a spectacle to angels and to men,
than before in this place.
I believe I had my companion`'s sympathy, but she said she had nothing to do; which,
I own, so discouraged me, with the painful apprehension that I had been out of my place,
led by an unsanctified zeal, or, at least,
had so imprudently administered the right thing,
that I had already done more harm than good; so that,
though there was a covering of good over the women`'s meeting,
and a little ability to relieve my own mind at least, I so lost faith,
and gave way so much, to thinking myself quite spent and exhausted,
that I managed to bring my load away with me; which,
added to the mortifying remembrance of what I had done,
nearly sunk me for a time into the deepest distress.
But by endeavouring to keep it to myself,
and to recur to what I apprehended was the moving cause of my doing and leaving undone,
there ensued a little quietness, and a small but comfortable evidence,
that the offering of obedience, as far as it had been made, was acceptable;
and that what was omitted, was viewed with divine, compassionate regard to the weakness,
and not willfulness, of my poor depressed mind.

Notwithstanding we had three sittings afterwards,
and my body almost as ill as I thought it could be, to bear up,
yet there felt to me full as much strength and life as I have found before in this place;
and this morning I feel so refreshed with the foregoing, and a good night`'s rest,
that I don`'t know that I have a complaint of any sort;
only I could wish for a little more clearness respecting some approaching days.
Thus I comfortably and thankfully experience,
that though sorrow has come for a long night in this place, joy springs in the morning.
When the sun of righteousness, in any degree, arises,
and the mind feels its refreshing influence, how does it encourage to press forward,
and to think nothing too hard to submit to, for this excellent appearance!
But how ready, like the disciples,
are we to solicit that our tabernacles may be built here,
and we not descend into the lower parts of the earth again,
there to be covered with its bars, and feel ourselves as at the bottom of the mountains.
Yet it is from there we are led to look for a better habitation,
and to labour that the pure life may arise, and we be favoured to dwell with it,
though seldom in a state of dominion, remembering for our instruction,
that Aaron the great high priest,
was permitted to enter into the holy of holies but once a year,
for his common service was in the tabernacle.

I cannot but look upon this morning, which feels pleasanter than many,
to be perhaps the opening of another tribulating day;
for it does not appear a time for such as are, in the smallest degree,
able to be baptised into the present state of the church, to eat much pleasant bread:
but I wish I was more preserved from those infirmities of darkening counsel,
etc. in times of proving, when a gulf seems to open for present destruction.

Oh, what a trial,
or trials of this sort have we had in this place! but I wish to forget these toils,
and rather seek for greater wisdom to bear the future.
It is marvellous to me, how things are brought about, that we have had views of,
but no probability of being effected;
and particularly with respect to this monthly meeting, which I thought I saw,
before we set off from home, and often wondered when we were leaving Lancashire,
how such things could be?
and sometimes, on that account, was ready to call all in question;
finding many such causes of discouragement, which now seem gradually removing.

[.small-break]
'''

Liverpool, 20th of Second month,
1781.--The fellowship and tenderness of our friends were never more desirable,
than in these days of deep probation and instruction.
Wonders are indeed yet manifested in the deeps, where,
finding the demonstration of the spirit and power, even my strong heart has,
to my own admiration, been made willing to receive the bitterest cups;
and all that is within me, has bowed and done obeisance to Him,
before whom I have had daily and piercingly to abhor myself; under renewed,
powerful evidences, that without the frequent administration of the Holy Ghost and fire,
and repeatedly descending to the washing pool,
there is no offering an acceptable sacrifice;
and that this must be a dispensation for life,
if ever any offering is found to be without blemish, which I fear it never will;
but if preserved with spiritual sight, and a necessary jealousy over myself, I shall,
I trust, so far deem myself blessed.
How are such as move in this line to be pitied!
their standing cannot be better described,
than as being on a sea of glass, mingled with fire.
But I would not say anything to discourage, nor would I wish to be like the evil spies;
therefore may add, that from what I have seen of the good land,
attainable at times in this work, it is well worth our pressing after,
and its fruit is so pleasant, that it amply refreshes the weary traveller.
I could, yesterday morning, set my seal to the truth of this; but alas I the scene has,
since then changed much.
We were at the monthly meeting at Hardshaw today,
for which we have both cause to be thankful; not because the food was pleasant,
but because it was, we trust, wholesome; and this evening we are come to this place,
to which we set off in the bitterness of our spirits.
It looks indeed often to my mind,
as if a singular visitation is renewedly extended to our Society;
but there is a painful fear, that the day will pass over the heads of many; yet, with it,
a hope springs, that there are others who will be purified, tried, and made white.

[.small-break]
'''

York, 3rd of Third month, 1781.--Many of our late tribulations appear to me,
more and more, to have been in the ordering of divine wisdom;
and such as have more evidently arisen from our unwillingness
to submit to the humbling power of the cross,
will surely be profitably remembered by us,
and gradually work that patience and pure resignation of heart, which can enable us,
in holy confidence, to rejoice, and count it all joy,
when we fall into various temptations and tribulations,
for the trial and refinement of our faith in him, who was made perfect through suffering.

My mind, has, in general, since my return home, felt a state of deep prostration,
and humble gratitude to that all-ruling power, which has, I fully believe,
helped us in our late engagements, and would more eminently have done it,
if our minds had borne a greater similarity to the passive clay.
Great instruction arises in the commemoration of these things.
To feel our minds centred in a quiet submission to the present allotment,
now we are returned, and a willingness either to do or suffer,
appears the most desirable state for us, and is what I hope you largely experience.

[.small-break]
'''

Third month 1781.--I think I have entered into my domestic station,
with a degree of aw fulness and fear,
and not without a humble sense of the unmerited
favours I received from divine condescension,
and from my friends during the cessation of it.
And notwithstanding many deep trials attend our leaving home,
when under an apprehension of duty, and many painful jealousies necessarily arise,
lest the most important of causes should suffer,
yet when we are in a settled satisfaction, or under the cares of a family,
by not being so frequently put upon a sense of our danger,
and of our own unfitness to do good of ourselves, our minds are apt to lose their centre,
by getting off the watch, and so become dissipated and carried away with trifling things;
at least with things short of that certain treasure which is
secured out of the reach of either moth or rust;
and then they become to us (however plausible to that wisdom which
cannot comprehend the mystery of godliness) unsubstantial trifles.
Thus we see the necessity of having a foundation of our own;
and we need not that another should build for us,
but that same power which directed the first stone,
similar to what was and is laid in Zion, tried, elect and precious,
whereby we may be built up in the most holy faith.
I often find it my duty,
strictly to scrutinize into the moving cause of my steppings in various respects;
and notwithstanding the greatest abasedness is my due,
on viewing my own innumerable frailties,
and inability often to turn my mind availingly to the invincible fortress,
even in times of deep probation; yet if there was not a secret testimony in my heart,
that it is much my lot to know an abstraction from human dependencies,
my feelings would be insupportable,
because I could not look for that peace which is
preserved from human mixture and interruptions.

[.small-break]
'''

Fourth month 1781.--Weary indeed I have felt myself of
this changeable world for a few days past:
perhaps it proceeds from too great an indulgence to that eye,
which is viewing the discouragements of the present day,
and which has cause to run down with water, for the slain of the daughter of Zion.
How are the Aarons removed, and removing,
and such as might seem likely to receive the garments,
have the work cut short in righteousness!
How do the standard-bearers faint, and how does the enemy prevail in his transformations,
in deceiving and drawing down even of the priesthood!
In contemplating these things, I think I may say,
that I never felt my mind similarly clad with a state of secret mourning and sackcloth,
as since you left us; insomuch that I am ready to enquire, who shall stand?
or from where can the watchers come,
that will faithfully discharge their trust upon our walls in a future day?
I am daily convinced of the great need there is for me
frequently to be taken throughout in pieces,
that no comeliness may remain to self, nor manna be preserved from one day to another;
that my own state,
and the wilderness state of the church may be (though not fully yet) clearly seen.

[.small-break]
'''

Sixth month 1781.--I have, after contending my ground by inches,
ventured to set off towards a place which I have
often looked at with a kind of dread and dismay;
from an apprehension that it strongly resembles that great city Babylon,
in which it is hard to be preserved from tasting of the cup,
either in a greater or less degree; and where, if there even be preservation from this,
deep suffering must be the consequence;
a state not likely for flesh and blood readily to enter into.
I can truly say it is in great fear and abasement of mind, that I advance towards it;
earnestly desiring to be kept to that power
which discovers the hidden things of darkness,
and shows us the different sources of self-love.

[.small-break]
'''

Eleventh month 1781.--We are sometimes at a loss to account for our own actions,
because they proceed from causes unsearchable to us,
and which we are led insensibly to comply with for our own good,
that that part in us which is appointed for death, and which,
by means of the flaming sword, is totally separated from the tree of life,
may receive no food or vigour to support it.
Since I saw you, many and complicated have been the concerns and feelings of my mind;
new causes and new anxieties have occurred,
from which I have seen great need to procure a secret dwelling in a quiet habitation,
and to crave daily assistance to abide therein,
that my own root might not be more impoverished;
but that by an inward attention to the voice of the true Shepherd,
a more intimate acquaintance with him might be cultivated,
and a greater subjection of spirit experienced;
whereby I should be more clothed with that true humility and pure simplicity,
which are essential to the cause of righteousness,
and necessary for the preservation of our minds in a state of acceptance with Him,
who sees not as man sees, but who knows what His wisdom has prohibited to us,
and marks our obedience.

How affecting was the removal of our beloved +++_______+++! Silent astonishment,
and secret mourning, for an individual and general loss,
was all the language I could use.
My heart was indeed affected,
and is not less so in the fresh feeling of a dissolved affectionate tie,
and of the uncertainty of all our comforts and attachments,
notwithstanding they may in prospect appear durable;
but as we do believe there is a union which exists beyond the grave,
a fellowship unconfined to these mortal bodies,
how strong an incentive is it to purchase this permanent inheritance,
though at the expense of our own fervour, and that,
friendship which is conceived in the false refinements of the human imagination;
and which being tinctured with the gilded impurities and dregs of nature,
becomes of that kind which is at enmity with God,
because not subject to the power of His cross.
To be stripped of ourselves, to be simple, to be fools in our own eyes,
and in the eyes of others, are experiences not pointed to by our own dispositions,
but are indisputably the way to that kingdom which flesh and blood cannot inherit.

By yielding to this way,
how humbly may we commemorate that power which gives according to our advancement,
the victory over a host of opposition,
and dims that eye in us in which our enemies are magnified;
giving a holy confidence that binds up the mind,
humbly exalts it above these momentary things, and, by measurably uniting us to itself,
enables to discern the origin of our feelings, and what proceeds from them,
by tracing them to their spring, and proving them in the light.
Our experience is small, but I trust we mutually long for that which is good;
may we each be, more and more, drawn from every mixture of self,
and become as a weaned child!

[.small-break]
'''

Twelfth month 1781.--If I had known your plan of proceeding,
it is likely I should have met you with a few lines somewhere;
but a morsel of friendly converse, or a token of true regard, may, perhaps,
be as acceptable now you are returned to a more homely fare,
and feeling a little more descent to some inferior service in the house,
than was then allotted.
Notwithstanding those that visit the true seed in this declining day,
seldom find themselves, either secretly or publicly, mounted on the king`'s horse,
but rather have to experience a baptism into its sufferings, and a fellowship therewith;
yet even in this state, if our minds are kept low enough,
and in a situation ready to receive and dwell under the divine allotment,
there is a strength attends it, of which the most favoured servants,
we have cause to believe, are often stripped on their return.
No wonder then, if we, who are infants in this service,
should be permitted to feel ourselves, as the dry bones in the open valley.
Under this state of humiliation before Him who knows all things,
and who wisely strips us of our judgment, in order to refine it;
how beautiful that reply to the query, "`can these dry bones live?`"
"`you know, oh Lord!`"
In this humble situation, how ready are we to receive the resurrection of life,
or to wail for it the appointed time, till all unprofitable moisture is exhausted,
and the seasons have passed over us!
A most affecting circumstance it is, that a man, and indeed a family,
standing in apparent approbation as +++_______+++ did,
should bring such dishonour to the cause,
and themselves be plunged into such deep distress!
It is, however, a proof how we ought, in whatever we do,
to fix our eye upon the right object, and to prefer a consistency with the Truth,
to our appearance in the eyes of men;
for certainly if this had been more the engagement of many minds,
there would have been preservation experienced from
many of these painful and dishonourable circumstances.

[.small-break]
'''

+++[+++In the twelfth month, 1781, with the approbation of the monthly meeting,
she was concerned in a religious visit to a part of the
families within the monthly meeting of Owstwick and Cave.
Although her stoppings along in this service were attended with close trials,
yet she was enabled to perform it with a degree of peace and satisfaction;
which appears from her own expressions on this occasion:]

[.small-break]
'''

We have got along as well as we could have looked for,
considering the prevailing declension and weakness of the present day; which in these,
as well as in many other places, widely spread themselves.
Deep suffering, and a painful exercise of mind, are often our lot; but being, I trust,
in a good degree resigned thereto, they are, at times succeeded with a calm,
and a little evidence that the servant is not wholly disunited from the Master.

[.small-break]
'''

+++[+++She was engaged, in the first month 1782, in a visit to some families,
which had not been visited by the Friends who had
lately been concerned in a family visit in that quarter.
At the conclusion of this visit, she remarks as follows:]

[.small-break]
'''

It was, I think, the most trying service of the kind that I ever had any sense of;
the general unfeelingness and impenetrableness of the visited,
rendered the labour almost without hope.
So greatly departed are many among us, from the virtue of heavenly dew,
that it is now deemed an unnecessary attainment.

[.small-break]
'''

First month 1782.--My remembrance of you was tenderly affectionate,
and a solicitude accompanied it, that we may live so near the pure life of Truth,
having our minds frequently stripped of whatsoever is
tinctured with the gilded impurities of nature,
as to feel an increase of unity therein.
When I am led to consider my own aptness to get from under the power of the cross,
a fear is ready to enter, that the garments, the coverings of my mind, which may,
in some small degree, have been washed, will again gather their spots,
and I become more and more reconciled to them;
so that the consequence may be an inability to
distinguish between the clean and the unclean.
In this necessary perspective of myself, the means of preservation have,
in infinite condescension been discovered;
and a willingness frequently to descend to the washing pool,
has proved the request of my heart, that He in whose hand I wish to feel myself,
may not only be the reprover, but the remover of every opposer of His work.
Discouragements arise from without, for on every hand there is cause of mourning,
and the few stakes that can be perceived among us are ready to fail with weakness:
therefore we see the greater need, with all the vigilance we possess,
to repair to that foundation which stands sure;
and truly those who are established thereon have
engraven upon them that indisputable seal,
and most desirable evidence, of divine acknowledgement.

Our pilgrimage here seems, and will prove, of so short duration,
that the sufferings which attend it for our refinement,
are blessings demanding our humble acknowledgement.
I have often reflected upon your situation with a
sympathy which I trust is measurably of the right kind;
and have felt the arduousness of your path, the stability that is required for it,
and patient resignation of the cause to Him whose own works alone,
or those of His own pure spirit, can praise Him,
and effect true and profitable deliverance to his dependent children.
What can the wrath and envy of man (if we are tried with it) do unto
those that are hid in the secret places of the Almighty,
and gathered under the healing wings of the Prince of peace?
since by his armour of light they shall be able to stand in the day of trial.

[.small-break]
'''

Second month 1782.--I place little dependence on dreams;
they are often a mass of confusion;
but we are bound to acknowledge that they sometimes
contain clear intelligent information or caution.
I believe, however, it is always safe to attend to the hint,
"`let him that has a dream tell +++[+++it as]
a dream,`" but the pure word should be spoken more freely,
for what is the chaff to the wheat?
Your letter was expressive of a union with your friend which is comfortable to her,
and from which it is the fervent desire of my mind we may receive
strength and instruction in the future movements of our lives;
wherein perhaps, if we are favoured to be of any service at all, it may go hand in hand;
but what are all the emblems of this fellowship to the thing itself?
what are the branches without the root that bears them?
I often wish the great objects in my eye may be solid and permanent;
that visionary and delusive gratifications may be proved,
by being brought in their infancy to the balance of the sanctuary;
and that nothing may resist the fire in doing its office upon that which is light,
and which has not been formed and tried in the
hand of the potter and purifier of his people;
but watchfulness is our best retreat, and I find that without it,
in this land as well as in our own, there is continual danger of being warped aside,
and losing our attention to the secret reproofs and dictates of wisdom.

[.small-break]
'''

Third month 1782.--I felt a satisfaction in hearing from you,
and finding that the exercises which had attended,
were productive of that peace which never succeeds our
moving out of the line of pure wisdom,
and is therefore an evidence of the Master`'s approbation; and what more do we wish for?
for if that is experienced when we have broken the morsel of bread given to our charge,
it is enough for us, and the blessing must be left to that bountiful hand,
which owns only its own works.
Though poverty was the covering of my mind on my return home,
yet I felt no uneasiness from an apprehension of having left you too soon,
but rather a belief that it was right for you to
feel that you were stronger than you apprehended:
and I now hope, that as you have afresh found the divine ability allotted you,
to be sufficient for the work of the day,
that you will be more devoted to move alone in future,
and become less dependent upon reeds shaken with the wind.
It is an excellent thing simply to mind our own business,
to attend to the path cut out for us individually, and let it be what it may,
to be content therewith;
because it is only by the members of the body thus keeping their places,
that they can be made truly useful to one another,
and prosperous in the cause wherein they are engaged.

[.small-break]
'''

Third month 1782.--I can feelingly sympathize with my
dear friend in her present situation of mind,
and under some difficulties, which may be increased by the lack of feeling,
baptized elders, such as live near the spring of life themselves,
and whose deep can call unto the deep in those
whose line of service varies from their own.
Where there are such as these,
they are felt to be stakes in the divine enclosure
about those I call the most tried of the flock,
the poor messengers that blow the trumpet on the holy hill,
and have to descend from there into the deeps, and awfully to dwell there,
humbled under a sense of themselves and what they are:
and though in this day of weakness, each member does not keep in its own function,
but numbness and insensibility have seized many,
let us trust that our holy Head will not permit us also to become castaways,
if we attend to His direction.

A secret dwelling as in deep waters we know to be safe; and, my beloved friend,
may we keep there, grow more and more united to the Truth itself,
and support one another in the fellowship thereof!
