== Chapter II.

Her marriage--and journey into Scotland, Cumberland, etc.

In the fourth month 1782, she was married to our friend Robert Grubb,
of Clonmel in Ireland, who had for some time resided at York;
to whom she was a faithful and tender companion, and a sympathizing,
strengthening helpmeet, in the various probations of their spiritual pilgrimage.
On this subject, the following instructive letter, written some months afterwards,
appears to be worthy of insertion.

--It is an awful thing to me, to enter into this new sphere.
I am now blessed with all, and more than I had any right to ask for in it.
I wish to number these blessings, and approve myself worthy of them.
This belief ever accompanies my mind,
that if we wrest not ourselves out of the divine hand,
whose fatherly care and protection is over us, our cup of life will be so blended,
as to prevent our sitting down in outward enjoyments.
Few and fleeting are the days of our pilgrimage;
and every additional experience confirms the sentiment,
that our solid satisfaction depends not on our possessing all
that the unmortified part in us can desire;
for there still remains, in the immortal part, a void, which immortal substance only,
can satisfy.
To have this supplied with wholesome food,
and every other gratification to stand subordinate thereto,
is the present secret breathing of my spirit: that so,
the blessing of preservation may attend us, and patience have its perfect work,
till the burning of the Lord's day has done its office,
and a quiet centre in everlasting repose, is obtained.

About two weeks after this event,
she entered on a religious visit to Friends in Scotland,
in company with her friend Mary Proud;
having previously obtained a certificate of concurrence from the monthly meeting.
This concern had, for many months, dwelt frequently on her mind, and had now matured so,
that she thought it her duty to engage in it, at this time.
Her feelings under the view of it, and in the prospect of her marriage,
with her resignation to the service, and desires for divine preservation and direction,
are in some measure, set forth, by the following extracts from some of her letters,
written on those occasions.

I cannot be on the verge of such important, and some new, concerns,
without feeling deep anxiety and many fears:
my mind is often so deeply oppressed with my present load,
that I feel continually bowed down under it, and not very fit for this employ.
The mind or body seldom suffers alone, and it is comfortable to believe,
that they are not intended to be always, or long companions.
I have not been very well of late, which is not to be wondered at,
nor is it worth much attention.

--The sentiment you drops respecting Scotland, is so exactly similar to my own,
that it was like a little strength handed in the time of need; and I greatly wish,
if the thing be proved to be right,
to be enabled to make a sacrifice of every selfish inclination;
that my offerings and prayers in this one step,
may be pure and acceptable to Him who sees in secret.
But I often feelingly remember a saying of Mary Peisley's,
that she was "`torn as between heaven and earth;`" and
it many times is a matter of doubt,
in which I shall centre.
I have as much nature as most, and as great an aptness to cover myself with it,
and live upon it; and though to be thus drawn from such a source,
is cause of thankfulness, yet it seems like the pangs of death, and I sometimes query,
whether my natural body will not fall under the operation.
Was it not for experiencing now and then my strength a little renewed,
and my mind clothed with the quietness of that habitation
which the arrows of the archers cannot penetrate,
I must fall to the opposition of the enemy in myself;
but when the arm of power is felt to be near,
then it is that we rejoice in the means of our salvation,

--There is still a secret belief,
that the growth and cultivation of my views respecting a northern journey, were,
by that hand, from which I have apprehended my most important engagements have proceeded;
and though it has, for many months, dwelt frequently upon my mind,
yet I cherished a belief, that it was very far off;
till the prospect of settling in a new line of life drew nearer, and then,
this distant view as fast approached.
It was afresh revived when I wrote to you last;
but I wished to try it still a little longer, if, in the kindness of Him,
who knows my great unfitness for an engagement so important,
my resignation to it might be an acceptable sacrifice.
Instead of this, the weight increased, and I found,
on complying with some early proceedings in another affair,
that my peace materially depended on having you informed of what I had in view;
that thereby this concern might keep pace with the other,
and I attend to what may appear to be my own business, no further,
than resignation to a superior service was experienced.

My dear friend knows the necessity of an entire surrender of ourselves, to what appears,
in the pointings of duty, to be our proper business,
and of keeping our eye as steadily to that as we can; that so, by its singleness,
we may have light sufficient for the work of our day.
And as, without this quiet attention, we are often led into doubts, fears,
and many reasonings, so we are frequently found to require provings of mind, strippings,
and many baptisms, in order to fit us for the slate, in which alone there is safety;
a truly humble, dependent state, reduced in ourselves, and seeking that honour,
which comes from God only.
It is with great awfulness I look at the work before us, and under a deep sense,
how unable we are of ourselves, at all to help forward the cause,
wherein we desire to be engaged,
or to bring honour to that name (either among us as a Society,
or those who are not of our fold) to which the nations may yet be seen to gather.
It is desirable, however, that our dwelling may be deep,
that the wisdom and instruction we receive, may, though small, be pure;
that if we venture to move, the cloud may sensibly be taken off the tabernacle,
and we careful to follow the appointed guide, and be favoured,
in this day of deep degeneracy, with an evidence, that we have done what we could.

The following is an account of her journey, through Scotland, etc,
taken from a short journal written by herself, and found among her papers.

--The 20th of the fourth month, 1782, I left York, with my friend Mary Proud,
for the yearly meeting at Edinburgh, intending from there, to visit Friends in Scotland,
Cumberland, etc.
We were at Thirsk on first-day, the 21st,
were we sensibly felt the pure life of religion to be at a low ebb,
though the professors thereof are numerous; and such as have been anointed for,
and employed in, the Lord's work, dwell among them.
But these being only standard-bearers while they continue exercised in the Lamb's war,
and prove their loyalty to the King of kings by their careful attention to his pointings,
and humble walking before him,
have need to live under an awful sense of the importance of that service,
to which they are called: that so, their spirits may be kept savory, their conversation,
likewise, seasoned with the heavenly salt, ministering grace to those that hear.
For lack of the Lord's servants, or those in the foremost ranks of the people,
being thus preserved near that power, in which their life and their strength consist,
great declension has happened to us, as a people; and those,
who have been looking for the substantial part of religion in them, have,
instead of finding its influence, received, by the lightness of the conduct of such,
a warrant for their own propensities.
Under the consideration of these things, I was affected,
and feeling the aptness of my disposition to yield to the like infirmities, I was led,
renewedly, to beg for strength.
Notwithstanding we had to suffer with the seed in this place,
and to behold the breaches which are made as in the walls of the royal city, yet,
a renewed visitation was extended to many, and especially to the youth;
and our minds were a little encouraged to press forward in the work before us,
under a fresh sense of divine regard.

The next day we left Thirsk, and my husband, who had accompanied us thus far,
went with us a few miles further on this day's journey; and after we parted,
my mind felt a covering of divine love to replenish it, with faith and patience; and,
from a little sensible experience, I could thankfully say, with a disciple formerly,
"`I have left all to follow you.`"
Under a renewed sense of this holy attachment,
and of my own unfitness for the service before me, without frequent baptisms of spirit,
and the sanctifying power thereof, I was inwardly favoured with some new instructions,
respecting the office of a minister of Christ, and openings how to fulfil that office.
Thus, I was led to acknowledge, that He who had called is faithful,
and his grace is sufficient for us, as our dependence is placed thereon,
and all confidence in ourselves removed.
We attended a meeting on third-day, and had, painfully,
to feel the state of things among them; and it appeared clear to my mind,
that the work was in the Lord's hand, and that he will, in his own time,
make manifest the hidden things of darkness;
when those that retain a little life among them, will be enabled to renew their strength,
and show themselves on the Lord's side, though their number may be few.
We were favoured in some degree, to relieve our own minds, and left them that afternoon.

The next day we were at a meeting which, for some time, was a painful sitting,
under a sense that the leaders of the people caused them to err, and were crying,
"`the word of the Lord,`" when the Lord had not sent them.
But after experiencing something of the baptism unto death, with our Holy High Priest,
we were favoured to feel the resurrection of life; in which,
judgment was placed on the head of the transgressing nature,
and the minds that were desirous to know
something of the work of religion for themselves,
were pointed to the means of redemption from sin.
From there we went to Newcastle, and were at their week-day meeting on fifth-day,
where truth measurably prevailed.

On sixth and seventh-days, being the 26th and 27th of the month,
we travelled from Newcastle to Kelso, and were at their meetings on first-day,
which are very small of Friends, but many others came in, especially in the afternoon;
and though, at first, they appeared rude and ignorant, yet the power of Truth,
in which the authority is felt, rose so into dominion,
that it became a solemn opportunity.
Thus we had fresh cause to observe, that it is only by divine strength,
that we can run through a troop, or leap over the walls of opposition.

On second-day, we went to Edinburgh, where, on third we rested,
and on fourth and fifth attended the yearly meeting, which was but small,
there being very few members of Society of that nation then present.
There were several, who, through neglect of Christian discipline,
think they have a claim to the Society, as being the offspring of Friends;
others were like the Philistines in whose hands the ark of the testimony is fallen,
and esteemed by them as a contemptible thing;
there were also present a number of students from distant parts,
whose parents are not only members of Society, but some of them useful therein.
On account of all these, our minds were painfully exercised:
and notwithstanding the public meetings were large, and owned with divine favour,
in covering these assemblies with a degree of holy awe,
and the minds of some of +++[+++the Lord's]
servants with gospel power and authority, to declare the way of life and salvation;
yet through all, the sense of deep, hidden, as well as flagrant corruption,
so impressed my mind, that I was led to believe.
Truth will never prosper in this place, nor the excellency of it appear unveiled, till,
not only the branches of the corrupt tree are cut off,
but the root so dug up that the remembrance thereof may rot; and then,
there is a hope that the present planting may get watered,
the ground renewedly cultivated, and fruits appear to the praise of the great Husbandman.

Deep discouragement attends the Lord's exercised servants in this day,
when labour is added to labour, baptism to baptism,
for those that are dead in trespasses and sins, and for those that are unacquainted,
in their own experience, with the glad tidings of the gospel; so that,
if they were not at times refreshed with a little bread handed in secret,
and their evidence confirmed, that the foundation of God stands sure,
having this seal that the Lord knows them that are his,
they would be ready to faint in the work, and to shrink in the day of battle,
when the arrows of the archers surround,
and the spirits of the people are opposing sound doctrine,
and crying "`prophesy unto us smooth things.`"
But I have had frequently of late, under these discouraging views,
to remember the prophet when he mournfully exclaimed; "`I have laboured in vain,
and spent my strength for nought;`" yet recollecting himself in holy confidence in,
and interest with, invisible and divine justice, he added,
"`but surely my judgment is with the Lord, and my work with my God.`"
From some necessary baptisms of mind,
and renewed evidences that this is enough for any true minister of the gospel to desire,
I have been led awfully and humbly to implore increasing strength and ability,
to walk before that gracious eye that sees in secret, without seeking the praise,
or regarding the censure of men who are not circumcised in heart and ears,
and who cannot discern, or value, sound uncondemnable words,
but want their sensual wisdom and depraved ideas gratified with the divinations of men,
and approbation of themselves.

We had an exercising, close, and searching opportunity of fifth-day evening,
after the public meetings were over, with those under profession with us,
and particularly the students; to whom divine regard was eminently manifested,
and a powerful call extended,
to close in with the present visitation and day of salvation that is offered;
whereby they would be redeemed from that wisdom
which separates them from the pure fear of God,
and the tree of immortal life;
and also preserved from going down to the chambers of death,
by falling in with those snares and gilded pollutions,
with which the unwearied enemy of our souls is seeking to entrap and defile us.
Their minds were sensibly affected, at that time, under the power of truth;
and He who was pleased thus to influence their spirits,
is alone able to prosper the work.^
footnote:[It is difficult to suppress a remark,
respecting young men of our Society being sent to complete their education at this place;
which is, that the advantages of medical improvement are, beyond all comparison,
out balanced by the pernicious principles of infidelity which are imbibed there.
Several young persons, religiously hopeful at the time of commencing their studies,
have returned from there deeply poisoned in their religious principles;
and some who have not been altogether slain in the contest, have it is feared,
become so much wounded, as to endanger their going halting all their days.
It is of unspeakable importance for parents and guardians solidly to consider,
in their disposal of youth, the danger not only of this,
but of every other exposed situation in life.
No professional advantages or qualifications whatever,
can be put in competition with the loss or injury of that pure faith and principle,
which is our unerring guide, our support and comfort through time.]
The next morning we went to Kirkaldie, by Queen's ferry,
where we had a meeting with the town's people, some of whom behaved well;
the glad tidings of the gospel were preached, and a satisfactory meeting it was.
From hence we went that evening one stage further, and purposed next day for Montrose,
forty-nine miles.
The first stage in the morning was to Coupar in Fife,
where we felt a considerable openness for a meeting,
but having too much in our own inclination, fixed our work for this day,
we put by this simple feeling, and thought that, if way opened,
we would give up to it in our return.
A few hours convinced us that our plans were frustrated;
for when we arrived at Dundee ferry,
we found ourselves about half an hour too late for the tide,
so that our horses could not be taken over till about that time in the evening,
at which we should have been there, had we staid and had a meeting at Coupar in Fife.
From Dundee we went to Aberbrothwick, which we left next morning for Montrose,
where we had a meeting in the evening with the town's people, who behaved well,
and to whom divine regard was powerfully manifested.

From hence we went to Inverbervy, a little sea-port between Montrose and Aberdeen.
Here we found we could not get away, without a meeting among the town's people,
which was readily provided for, and a very solid company attended;
whose minds seemed like the good ground cultivated by the divine hand,
for the reception of the seed of the kingdom.
Divine aid was eminently extended to us, and to the people, and we were led,
publicly and secretly,
to return the gratitude of our hearts to him whose works alone can praise him, and who,
in infinite wisdom, after these favoured opportunities,
is sometimes pleased to lead his poor, weak servants, as from the holy mountain,
and from tasting the animating wine of the kingdom, into the wilderness;
and to cause them, like their Master, to experience something of the forty days fast,
and the power of the tempter; that so, their own inability may be proved,
their humble confidence renewed in the divine arm,
they drawn from having any confidence in the flesh,
and taught not to live by bread alone.
From hence we proceeded to Stonehaven, and sat with the few Friends there,
in whom the life of religion is weak.
We went to Aberdeen that evening, and next day had a close time with the Friends there.

The same afternoon we reached Old Meldrum, and next day had a meeting there,
where we found we could not get away without sitting in the families,
and having a public meeting with the town's people; the first we set about the same day,
and had a satisfactory meeting with the people in the evening.
We found things very low among the Friends, but a comfortable hope,
that of the youth would be raised up such as
would be qualified to support the cause of truth,
which is ready to fall in the streets,
and the principles thereof almost forgotten by those that profess them,
particularly in departing from the plain language,
and losing the distinguishing marks of their profession; whereby the cross is evaded,
and the people's minds become like the high-way ground.
We finished the visit to the families at Kilmuck,
and went from there on seventh-day evening for Aberdeen, and staid there the next day.
My companion attended the meetings, where she had good service,
and many people of the town came in.
I had been unwell for some time before with pain in my face and teeth,
which had now so increased upon me, with fresh cold, that,
feeling no particular draft to the Friends or people, and scarcely being fit to move,
I staid in the house that day, in order to use some means for recovery,
which were not ineffectual, and next morning we set forward for Urie.
Here the Friends of Stonehaven met us, but it was a painful opportunity,
and little of the divine life to be felt.
We reached Montrose in the evening, and next day went to Aberbrothwick,
where we used some means to obtain a meeting, but they not being effectual,
we were easy to leave the place; and went forward, without any other meeting in the way,
to Edinburgh, where we arrived on fifth-day evening, the 15th of the month.

From Aberbrothwick she writes thus to a Friend:

The minds of many of the people in this land seem preparing, like the good ground,
to receive, in childlike simplicity, the ingrafted word,
and though it may be long before fruits appear, yet if those that come this way,
follow the simple openings of truth, in stopping at places where there are no Friends,
and get baptized into the states of the people, it appears clear to us,
that such will be instrumental in helping forward the
light of the perfect day of the gospel,
which has dawned in many of these parts;
but it is under present chastisement for neglect of duty,
that I acknowledge we have not sufficiently trodden this path.
One material omission the week before last,
has laid a foundation for repentance through this land, if not through time,
unless our Master sometime sends us again to pay debt and interest; because,
from that one neglect, has proceeded many entanglements, and preventions of doing right.
We have great cause to believe and acknowledge,
that the divine aid which has been afforded, particularly in this land, has been great;
and though it may have been chiefly on account of the people,
yet gratitude has covered our minds for it,
and it occasions us to feel more deeply any lack of faithfulness.

The following letters were written a few days after getting out of Scotland.

--It is a favour when we are at liberty to feel one another,
in the cementing bond of pure love and unchangeable fellowship; for, really,
in journeys of this kind, our minds are often so stripped of satisfactions like these,
that instead of feeling as if we belong to any body,
or have any outward source of comfort,
the state of the pelican in the wilderness seems most similar to ours; and, no doubt,
for wise ends, our minds are thus clothed with abstractedness,
and separated from domestic blessings: for our eye then being single,
and we considering ourselves servants that have
need to watch every pointing of the Master,
we are in the greater fitness to receive that divine light, in which, and by which only,
every service in the church can be rightly accomplished.

--We are convinced it is right for those who go into Scotland, to go without plan,
or fixed times for things, and simply to attend, day by day, to the openings of Truth,
giving up their time freely, and considering themselves in no respect their own.
Such as thus faithfully visit Scotland,
and get deep enough in their minds to bring up such
weapons as will penetrate the minds of the people,
and reach the divine life, rather than aim merely at convincing the judgment, will have,
I am persuaded, great service in that land,
and find the free dedication of their time to be an acceptable sacrifice.

--We have now got as into our own camp, where close painful labour is often our lot;
which being almost continual, and without apparent effects,
we are sometimes ready to shrink from the work, and turn our faces homeward,
considering ourselves, in every sense of the word, unprofitable servants.
But I have thus far found, that when we have been so reduced, as has been the case,
that we dared not look for great things, divine strength has been most administered,
and the blessings that attend our thus dwelling in the deeps,
have been couched under these feelings;
and the spirit of discernment has so proceeded therefrom,
that we have had humbly to admire the dealings of the divine hand, which,
by reducing his servants, exalts his own cause.
When self is most brought down, there is least anxiety about the fruits of our labour;
they are left to the great Husbandman, who causes the rain to descend on the just,
and on the unjust;
and surely it is enough for us to experience our meat and our
drink to be an obedience to the will of our heavenly Father:
for thereby, we get food that the world knows not of,
and feel ourselves bound to his Truth, though many may forsake it.
We are reconciled to suffer therewith, seeing with an eye of faith,
that notwithstanding the declension among us, the smiting of the shepherds,
some in being happily removed from the evil to come, and others by the hand of the enemy,
and the scattering of the sheep, yet the promise will be fulfilled, upon the little ones:
and these keeping to their Judge and Lawgiver, they shall with the Lamb,
experience a victory.

The next evening after leaving Edinburgh, we reached Kelso, and Morpeth on the 17th,
from which we went next morning to Newcastle to breakfast,
and attended both their meetings; in which we had deep, searching, but honest labour;
and a degree of quietude, resignation, and serenity of mind, closed the day.
The next day we rested, and on third-day were at Shields, fourth at Sunderland,
fifth at Benfieldside, sixth at Newbiggin, seventh at Allondale, first at Aldston,
and second at Cornwood; at all which,
the effects of an inattention to the unerring spiritual guide, were deeply felt by us;
and from place to place,
our spirits were pained in viewing the declension and
desolation which have spread themselves,
even among the foremost classes of the people.

Some of those who have appeared as shepherds over the flock,
have been overtaken therewith, smitten by the hand of the enemy,
and proved their disqualification for service;
whereby many that knew not the sure foundation, but whose eyes were fixed upon man,
and whose walking was circumscribed by the appearance of others,
have been scattered from the place of true feeding,
and thus lack an anchor to their souls in the time of trial.
This the spirit of Truth would have amply supplied,
had it been made the object of their researches, instead of the honour, the wisdom,
and the complicated gratifications of man in his depraved state.
But in the course of these meetings, particularly at Newbiggin, Allondale and Cornwood,
we felt an evidence that the divine promise will be fulfilled upon the little ones,
and that there are of this number, who, if they keep faithful under the preparing hand,
will be raised up to be standard-bearers in the work and house of their God,
But oh the danger of even these, that have been several times dipped as in Jordan,
not abiding the day of further trial, wherein nothing but the pure gold will stand;
because the fiery baptism of the spirit,
is so superior to every thing but what is of its own durable nature,
that whatever has been mixed with it must, in this test, be swept away;
that the vessel which is formed of the residue,
may be so pure as to be entitled to the inscription of "`holiness unto the Lord.`"

As it is for lack of this patient dedication of heart to the operation of Truth,
that many vessels among us have been little better than
sounding brass or tinkling cymbals to the people,
having no authority from that of which they spoke,
nor discovering an alliance to the Master by following his holy pattern,
my heart has been led fervently to implore for myself, and for a number of those,
to whom I felt united in our heavenly Father's love,
that whatsoever may be the sufferings of the present day,
and howsoever one may fall on one hand, and another on another,
our eye may be fixed on the Rock of our strength, and our faith so replenished,
that though the feet may be placed as in the very bottom of Jordan,
we may not flinch therefrom,
nor seek an easier path than that which the wrestling seed of Jacob have ever trod;
nor have any greater joy than to be united by an exercise of spirit to our holy Head,
whether in suffering or in rejoicing.
We had, in all these places,
the renewed assistance of that spirit which helps our infirmities,
teaches how to pray and travail in spirit,
and how to minister to the states of the people;
whereby some of the hidden things of darkness were searched out,
the strayed of the flock invited to the fold,
and the little travailing remnant were encouraged to go forward on their way.

We had a uniting season at Cornwood, in that pure fellowship of spirit,
which supplies every member in the body with fresh vigour to perform its function.
From hence, with our friends M. J. and J. W. we went to a meeting in Cumberland:
it was a time of deep exercise of mind, but in faithfulness thereto,
the power of Truth rose into dominion,
and we had reason to hope it was a profitable time to many.
We left this place, and in the afternoon were at another meeting, which was,
for a time painful beyond description; but by a humble waiting,
it was discovered that the people were fed with an unsound ministry,
that the ark was taken into the hands of the uncircumcised,
and that there was a number who loved to have it so.
The power and authority of Truth arose,
by which we were enabled to place judgment on that spirit,
which was seeking to support the testimony with unsanctified hands,
and to have their honour from men,
forgetting that holy anointing and preparation of heart,
whereby the Lord becomes sanctified in all those that draw nigh unto him,
and the bread that he gives them to break, receives a blessing upon it,
in that it shall not be void,
but prove a visitation of his love to those to whom it is sent,
whether they will hear or forbear.
Here we had afresh to observe, that where ministers maintain their inward exercise,
and keep near to their gifts, the spirit of true discernment, which searches all things,
is not lacking to prove, from the line in which it leads them,
the rectitude of their ministry to the living and wise in heart;
who judge not by the sight of the eye, or the hearing of the ear,
but by the unerring evidence of Truth, which remains to be the savour of life unto life.
Our minds were thankful, under the fresh sense of divine favour and strength,
in being found worthy to suffer with the suffering seed,
and with the little remnant that are thus exercised, and who belong to this meeting:
to these, though they are weak, the bread of encouragement was broken.

Next morning we set forward, and on our way, I received an account from my husband,
who was then in London, of the death of his father,
and that he purposed going over with the Friends who had attended the yearly meeting,
to accompany his sister, and to pay a visit to his mother and friends,
on this affecting occasion; reasons with which my judgment led me to coincide,
though I felt myself deeply affected with so unexpected a circumstance.
Having received a letter conveying sorrowful intelligence on various subjects,
I was ready,
with the additional concern of the important service in which we were engaged,
to sink under the general pressure of my mind.
But, in this situation,
I had fresh cause to recur to that divine and invisible arm which drew me out;
and in the feeling whereof I could then say, with a degree of holy confidence,
"`Lord I have left all to follow you`" to that
station into which I apprehended myself called,
though but a child, and to nothing short of a disciple of the Lamb,
to fight under his banner,
and to prefer his work to every gratification or concern of my own.
I found it was an easy thing to say, I will follow you, wheresoever you lead;
but when our fidelity is tried with cross occurrences to our natural feelings,
united to the fresh painful sense that the foxes have holes, etc.,
then are we ready to shrink, and desire that the cup may pass from us,
forgetting that all must be left to the great Disposer of all things; that so,
with holy confidence, our resolution may be, "`though you slay me,
yet will I trust in you.`"
Under this dispensation, I was afresh stripped, and became a suppliant at wisdom's gate;
where I found I had nothing to receive for my help,
but a patient submission to the divine will, and renewed strength,
simply and singly to wait,
not only respecting circumstances relating to my social concerns,
but in the line of my religious duty and in the exercise of the gift;
seeing that it is only when the eye is single, that the body is full of light.

We attended the next meeting, which for a time was inexpressibly dark and painful;
but being engaged fervently to travail for the resurrection of life,
we had renewedly to acknowledge that our labours
were blessed and strength afforded for that time,
to awaken a number from a state of spiritual death,
and to show them the deplorable situation they were in.
We proceeded to another meeting, and on first-day attended both the meetings there;
in the first of which we were enabled to relieve our minds from the weight which,
in the forepart, deeply affected us, and it was a time of renewed favour.
Numbers will not hear either the master or the servant
when sound doctrine is delivered unto them:
but the most fine gold becoming changed,
and they remembering something of the work of the refiner,
but not keeping under it themselves,
are making something for the people which is specious, and feeds their itching ears,
but which at the same time is putting death into the pot;
so that for lack of those that hear recurring to the witness for God,
the true spirit of prophecy, the seed of the kingdom becomes stifled,
and total insensibility ensues; a state over which, in this county,
we had deeply to mourn.
The meeting in the afternoon was silent, and our minds preserved in great resignation.

On third-day following we went to Moorhouse and Kirkbride,
on fourth at Wigton and Bolton, on fifth at Berkfoot and Maryport,
and on sixth at Allonby and Broughton.
The closeness of the exercise in meetings, and in travelling,
had by this time sensibly affected or reduced our strength and spirits;
but resting on seventh-day with a friend, helped to restore us a little.
The wounded and captivated state of our Society as a people,
and especially in this county, renders a little present rest,
like the eating of the passover, with bitter herbs;
for how can the servant rejoice where the Master reigns not!
On first-day we sat with the Friends at Pardshaw,
where divine regard was renewedly extended to us and to them,
in opening the book of His law,
and discovering the transgressions of the professors thereof.

The same evening we rode to Whitehaven, and had a meeting there the next day the 10th,
which was painful; but a little oppressed remnant were strengthened;
for which thankfulness ought to arise, and gratitude cover our spirits,
notwithstanding we, as the poor servants and off-scouring of all things,
are often abased under the sense of our own nothingness,
and of our omissions and commissions;
for on these the compassionate eye of the Master condescends to look,
when we see ourselves, and are prostrate before him,
under the sense of how liable we are to swerve to the right hand or to the left,
from the clear and pure openings of Truth in our religious services,
without a close attention of mind thereto.
This requires a previous strippedness, and baptism of spirit,
that our own activity may be reduced,
and subjected to the power that quickens and gives life; and that, likewise,
unprofitable timidity and fear of man, may become so removed, that we can,
with singleness, and resignation,
depend solely upon the simple revelation of the divine will.
For though it is needful for our refinement, and fitness for service,
to be clothed with the sense of our weakness,
and the insufficiency of our wisdom and discernment in the mysteries of the kingdom,
and in performing the least work for the spiritual building; yet on this,
when called to labour, our eye should not be fixed, but rest with faith,
on the invisible arm of divine power;
that being in a situation ready to receive help from it, we may be therewith content,
and favoured with that blessing which renders acceptable the smallest offering,
or the bread that may be compared but to the barley loaf.

We went to another meeting, where things are very low,
some of the members being so weak as to let fall some
of the fundamental principles of our profession;
whereby the few that are faithful are oppressed with the seed,
and are ready to sink under discouragements,
and also with some appearances in the ministry,
concerning which we felt no answer of life as unto life.
Here we lodged at the house of our valuable friends J. and B. D. who,
next day accompanied us, with some other Friends, to Keswick,
where we had a pretty large and satisfactory meeting among the town's people.
On fifth-day the 13th, we attended the week-day meeting,
and monthly select meeting at Greysouthen,
where gracious condescension was eminently extended to us, and to the members thereof;
and we parted with many of our friends on that side, in much affectionate fellowship,
and sympathy with each others' tried situation,
arising from the deep declension and desolation which widely spread over us as a people.

Next morning we rode to Isell meeting, in a very stormy, tempestuous day, so much so,
that the Friends belonging to the meeting dared not venture out, except three men,
for whom, in a cold damp meeting-house, we waited in our wet clothes,
three quarters of an hour; having no better accommodations for ourselves or horses,
than a bare shelter from the heavy rain that fell.
We sat down with the few that came, and our guides, ready to conclude that,
under these circumstances,
it would be an unavailing attempt to have our minds properly stayed;
but he who mercifully condescends to visit the two or three that gather in his name,
was pleased eminently to own us, that day.
I remembered, and had to open the passage, "`Blessed is that servant that watches,
and keeps his garment, and who, when his Lord Comes, is found ready.`"
It appeared to my mind that all those who have enlisted under the spiritual,
unconquered Captain, have received a mark thereof, a change of heart,
an awful covering of spirit, a loving one another,
and means whereby such might stand in readiness for the word of command;
and that therefore the peculiar blessing of the
divine hand rests upon these faithful servants,
who when not actually in service, so remember their office, as to be fit,
when called thereto, to step into it, and move only in that raiment,
and with that armour, which the Master gives them.
For lack of this watchful, attentive care, in times of withdrawing, many among us,
when there has been an opening for labour, have not been found ready,
nor approved worthy to advocate the heavenly cause;
and thus the warfare has not been maintained, but the battle is retarded,
Israel falls before his enemies, and the accursed thing is in the tribe of Judah.

At the close of this meeting,
where my mind had been led to centre to a quiet
dependence on the smallest evidence of the divine will,
after some days of deep probation, and frequent desertion of spirit,
the aforesaid passage, "`blessed is that servant,
etc.`" powerfully revived and spread before me,
and a voice intelligible to my spiritual ear, applied it to myself;
which introduced such a calm over my mind,
and separation from the natural feelings thereof, as I never before experienced.
Under this sense, I concluded it was the last meeting I should ever be at;
that the dedication of my heart, and some afflictive dispensations that were past,
had proved acceptable, and that now there was no obstruction to my final dissolution;
nor an attachment in me to anything below:
a situation of mind so different from what I usually felt,
when I have feared that the closeness of my connections had the
ascendency over my love and travail of spirit for the cause of Truth,
that I wondered at the change.
I looked towards my friends, saw some of them in their places,
and feeling myself in my own, without a cord to break, I apprehended that,
in a very little time, I should be gathered to that eternal habitation of rest,
whereinto I never before so sensibly entered, and of which I had never such a foretaste.
It was nothing that elated me, my natural ideas were dormant,
but what I experienced seemed solid substantial truth.

After the meeting broke up,
and I was making the necessary preparations tor proceeding to the next meeting,
there was no interruption to my mind, till riding along the road, with a fresh,
awful application to the Lord,
and breathing that I might not rest too much under this impression,
and that if there was any other end to answer than what I had seen,
it might be discovered; lest by looking too much at an opening so comfortable to myself,
I should be in danger of neglecting a continued exercise of spirit,
and the service I might be called to from place to place;
and thereby render that which was intended a blessing,
a block in my way in pressing after so desirable an end as had opened therein.
Thus waiting to see further the way cast up for me, I thought I clearly discovered,
that it was a mark of divine regard at that time extended,
in order to show me the excellent, ultimate, effect of what I had had to open to others;
and the need there was for me to attend to it myself,
during the course of my own pilgrimage; and also to remove an idea,
that the ties of nature are so interwoven with
my attachment to eternal excellency and purity,
that the separation must be,
like the furnace being heated seven times hotter than it had before been experienced.
Instead of this, I had to behold, in humble admiration,
the works of an Almighty hand in the deeps, and how,
when our hearts are upright before him, he invisibly works our deliverance,
by means which the unenlightened understanding of man cannot comprehend.
When the power of Truth predominates, we see, in the vision of light,
its superiority to every natural endowment or gratification;
so that the insurmountable difficulties that are beheld by the natural eye,
are subjected, and the mountain of the Lord is exalted on the top of all the hills.
In commemoration of this token of divine regard, my mind is bowed,
under the sense of my own unworthiness, and how unable I am, notwithstanding this view,
to dwell in a state of preservation and acceptance, without wrestling, from time to time,
for that faith which overcomes,
and that patience whereby we are kept in the hour of temptation:
for if the Lord keep not the city, the watchman watches but in vain.

After the meeting at Isell we went to Coldbeck, where we had a suffering time,
but were enabled in a good degree to search out the cause.
Next day we attended a meeting at Mosedale,
where we had comfortably to observe that the Master's feet had been,
though in general things are very low.
On first-day, the 16th, we were at both of their meetings at Penrith,
where we painfully felt the oppression of the seed, as in many other places.

That evening we rode to Terril, and next morning had a meeting there;
where the necessity of those who are called to the ministry
sitting loose from outward connections and profits,
and following the Master whithersoever he leads them, was clearly set forth.
From hence we went to Strickland meeting, and on our way, I had a fall from my horse,
with which I was hurt, but attended the meeting, which was favoured,
and I gradually recovered.

From Strickland we went to Hawkshead, and from there to Swarthmore,
where many not of our Society attended; and it proved an eminently favoured season.
Our next meeting was at Height which was a low time.
We then proceeded to another meeting, rested and wrote on seventh-day;
and on the first sat both their meetings, where we had secretly to mourn over,
and publicly to discover, the affecting situation of those who, from year to year,
have been divinely favoured, and, like the vineyard we read of, dug about, fenced,
and visited by the good Husbandman: but oh, the falling short!
One may plant, and another may water, yet as the increase is of the Lord,
and He not being devotedly sought unto, for that dew of heaven which renders us fruitful,
and that pruning hand which would keep the branches clean, numbers,
after having been planted choice vines,
have become the degenerate plants of a strange vine unto the Lord;
and notwithstanding they keep a greenness, and an appearance of life,
it was clear to the view of our minds, that if there was not a getting deeper,
even to the washing pool, and being stripped of themselves,
the princes also arising from the dust of the earth and anointing the shield,
spiritual death will greatly increase among them,
and the judgments of the Lord for disobedience will ensue.

We took the week following, Preston, Grayrig, Sedburg, Dent, Garsdale, Ravenstonedale,
and Lartington; and also had a satisfactory rneeting at Bowes,
where are none of our Society; and at the others,
we were favoured with strength for the exercise that fell to our lot therein.
The first-day following we attended the meeting at Staindrop,
and another in the evening at Bishop Auckland;
on second-day we went to Durham to their quarterly meeting,
and attended the several sittings thereof; in all which we were enabled,
far beyond our expectation, to relieve our minds, by honestly, in the fear of the Lord,
and not of man, expressing our sense of the state of things among them;
and it was a time of renewed favour.
From there we went forward,
and were at a meeting wherein the uncircumcised spirit
was painfully felt to prevail in the forepart thereof,
but our help and safety depending upon our going down to the brook,
we were engaged patiently to wait for divine clothing,
knowing that it would be dangerous to go against them in untried armour,
notwithstanding the cause might be good: and we may thankfully say,
that good is the word of the Lord,
and efficacious to the smiting of the Goliaths of this day.

Her own account of this journey ends here;
but it appears that she proceeded from this place, and visited the meetings at Stockton,
and Yarm, back to Benfieldside, then Ayton, Bilsdale, and Kirby,
and returned home about the middle of the seventh month.

After she had got out of Scotland,
she and her companion felt their minds disposed to salute the
Friends of the monthly meeting of Old Meldrum with an epistle;
a copy whereof follows.

Benfieldside, Seventh month 7th, 1782.

Dear Friends!

As in our travelling along,
we have frequently felt our minds covered with
an earnest engagement for your preservation,
and a sense of the love of our heavenly Father towards you,
which engaged us to pay you a visit, we are drawn in the renewed extendings thereof,
to salute you with a few lines, and according to the ability received,
to strengthen the little life that is among you;
that the elders may be gathered to the true place of feeding; the middle aged arising,
may become men and women of valour for God,
and the youth having examples set before their eyes of a steady circumspect walking,
seasoned with divine virtue, may be engaged, by the efficacy of the same holy Spirit,
to succeed their parents, and the faithful in all ages,
in carrying forward the Lord's work, and in His name, which is his power,
setting up their banners.

But, dear Friends, as there are many impediments which have hindered us as a people,
both in this land and in yours, from advancing in our spiritual progress,
and increasing our strength in the Lord,
let us enquire into the cause from which they have come, and to what they will tend;
for if we had kept to the sure foundation,
and in all things considered ourselves the followers of a crucified Lord,
rather than nominal members of a religious society;
and been concerned to walk even as He walked;
the snares of the enemy would not have prevailed
to lead so many captives into a strange land;
because, against the Rock of ages, whereon we might have been built,
the gates of hell shall never be able to prevail.
But for lack of keeping an eye open to this preserving power,
a spirit of indifferency has crept in, and, while many have slept, tares have been sown;
which, as they sprang up, have had a tendency to choke the good seed,
those tender impressions, and reproofs of instruction,
which would have prepared our spirits,
and have bound them to the holy law and testimonies of Truth.
Thus, strength has been lacking to maintain the discipline of the church,
in that purity wherein it was first established;
and a door has opened for increasing liberties.
Hence, has ensued a mixing with the spirit and customs of the world;
so that those who have not been taught the same doctrines, but are looking upon us,
may query, "`where is your God?`"
seeing, that though we profess to be led and guided by the Spirit of Truth,
our fruits differ not from theirs; but the cross is removed out of the way.

As one deviation from the path our predecessors walked in,
conformable to the precepts of Christ, painfully affected our minds,
both when our lot was cast among you, and since;
we feel not easy without renewedly observing, that,
in the promise of the restoration to Israel, it was said,
"`I will turn to the people a pure language;`" and knowing
that this gospel day is still more glorious than that,
if we did but live in the light thereof,
which would clearly discover to us the corrupt source of flattering titles,
and seeking to gratify the vain mind of man,
how can we without offending the Spirit of Truth, which leads and guides into all truth,
give up that pure language to which our forefathers were turned,
and adopt the unsound words of you to a single person,
and calling the days of the weeks and months by the heathen names; and those,
our masters and mistresses, who are not really so; forgetting the command to call no man,
master.
Is not this returning to the night of apostasy,
and in our dealings and converse with men, crucifying afresh the Son of God,
and putting him to open shame, by thus denying,
or refusing to bear his cross and testimony to the world?

We believe there are a number among you, who, by example,
have been trained in a deviation from our holy profession;
and these we tenderly address and exhort to feel for
themselves after the influence of that holy Spirit,
which leads its followers in the same path,
however remote from outward help their situations in life may be;
for the peculiar privilege of these is, they need not that any man teach them,
but as this same divine anointing teaches them all things.
Though you may have but few to strengthen your hands,
by their example and sympathy with you in your honest
endeavours to break down the partition walls,
which the enemy has raised to prevent your advancement to the perfect day of God;
yet be not dismayed in your labours;
but remember the fervent zeal of our predecessors in the Truth;
how they endured the persecutions of that day, and how,
with unconquerable fortitude and resignation to the Lord's will,
they steadily pursued the path of true self-denial, and fought the good fight of faith.
And if we, in this day of deep declension, look to the Rock of our strength,
we cannot fail to find that it is a day which calls for diligence;
and that whatever pointings of duty we are favoured with,
our preservation depends upon faithfulness thereto.
Therefore, beloved Friends,
be you engaged to see what it is that keeps you in a state of weakness,
and prevents your feeling the strengthening and
comforting influence of the Spirit of Christ;
that so, you may be enabled to remove the impediment out of the way.

Be faithful to the Lord, and stand in the authority of his Truth;
that endeavouring to rule your own houses well,
and to have your children in subjection with all gravity,
you may know his baptizing power upon your spirits, in your assembling together;
and your secret prostration and fervent breathings will be acceptable to his holy eye,
and blessed by his bountiful hand.
In your meetings for discipline,
you will likewise be seasoned with the salt of the covenant,
and by your honest endeavours to keep the camp clean from all disorderly walkers,
you will grow stronger and stronger, and your minds,
become united together in the bond of true peace.
Thus, may it please the Lord to operate upon your spirits,
and to influence the youth among you to a watchful attention to their thoughts,
their words, and actions; that being preserved from mixing with those,
who would draw away their minds from the discoveries of Truth,
and centre them in the corrupt language and changeable customs of the world,
they may prefer a religious awfulness upon their spirits,
and seek for that pure fear of the Lord, which is a fountain of life,
preserving from the snares of death,
and securing a safe hiding-place in the day of trouble.

With satisfaction we acknowledge, that we felt, while with you,
that the hand of the Lord has been at work upon the minds of the youth,
and that some of these have submitted thereto; to whom our spirits were,
and are led into near sympathy,
and filled with an earnest desire for their preservation and
progress in that good work which is begun in their hearts.
Be encouraged, beloved Friends, to hold on your way,
and more fully to submit your necks to the holy yoke;
that thereby you may be made willing to sutfer for the cause of Truth;
and though you may not have many examples and helpers in the Lord,
yet being engaged to dwell near the root of divine life,
and seeking for strength therefrom,
you will feel the progressive dispensation of the heavenly visitant, and grow in stature,
from the state of children, to young men in the Lord.
Let situations be what they may, and outward advantages ever so great,
we are abundantly convinced, that whoever Experiences an inheritance in the Truth,
and an establishment therein, must purchase it for themselves,
learn to live on manna of their own gathering,
and know from where all their fresh springs proceed.
And now, dear Friends, the fervent desire of our spirits is,
that you may be stirred up to a renewed sense of the declension of the present day,
and under it,
be engaged to seek for strength to establish you in every good word and work;
that being clothed with a zeal according to knowledge,
for the prosperity of Zion and the enlargement of her borders,
you may become established as a city set upon a hill,
having the light of the gospel day upon your dwellings.

Sarah Grubb

Ninth month 1782.--When an unavailing anxiety has possessed my mind,
about the situation of things among us, and the wilderness state of the church,
I have been led to conclude that it is not consistent with the divine will,
that we should be ever impatiently enquiring "`what will you do for your great name?`"
but that we should rather centre deep in our own minds,
and resignedly and faithfully cooperate with his work in the earth;
feeling our minds so reduced as only to pray for that which is the mind of the Spirit,
even if it required the petition, "`feed your people with your rod!`"
In our late visit, we deeply felt, at times, our weakness,
and when most baptized thereinto, with our eye single to divine help,
we had humbly to observe, that then His strength was manifest in our weakness;
and that it was only as we descended to the spiritual brook,
and there received with simplicity the heavenly armour, that the battle was blessed,
our heads covered therein,
and ability found to discover the little ones on whom the purifying hand is; turned.
I believe I may say we returned under the humbling
impression of being unprofitable servants,
begging to be enabled to continue suppliants at the gate of wisdom,
and to attend in future to the smallest of its pointings.
I need not tell you how agreeable it was to meet my husband at my return home.
On our separation, the passage feelingly occurred to, and refreshed, my mind;
"`Lord I have left all to follow you.`"
To be employed in the cause of Truth, and to have the Spirit thereof for my companion,
appeared, when nature was subordinate,
far to surpass every selfish enjoyment in this life,
notwithstanding I might prove a vessel of the least honour in the family.
On our meeting again, I found there was need of a renewed engraving of these impressions,
in order to preserve a preference to the Truth,
and to keep in our remembrance that we have no continuing city here.

Tenth month 1782.--It is an unspeakable favour, through all, to believe that,
if we dwell in the pure life and oneness of the Truth, many waters without,
or floods of temptation within, will never be able to quench our love, though for a time,
when they rise high, they may veil it.
The prayer of my spirit is, that my dwelling may be in this hidden life,
that I may prefer its substantial operations to either spiritual or temporal enjoyments,
and that by it my body and mind may be preserved from running to and fro in the earth,
with any blast from the wilderness.
But oh,
the need of "`standing still in the watch,`" the
infirmities of our nature are so many and great!
Remember me and crave my preservation, that my life at least may be given me for a prey;
and may you and I farewell, and increase in that life and love which change not, nor end.

1782.--I received your affectionate letter in due course: it was truly acceptable;
and though you were far from being forgotten by me,
it tended to revive that near sympathy with your secret spiritual travail,
which particularly accompanied my mind when near you in person,
and which I trust proceeded from the cementing influence of divine love,
and gospel fellowship.

We meet with but few in this pilgrimage and state of probation,
who are dipped into sympathy with us,
and know what it is to be destitute of all comeliness.
There are many who, were we clad in royal apparel,
and had the king's signet always unveiled upon us,
would no doubt acknowledge us in the gate; and, in the victory of the heavenly cause,
cry, Hosanna! with us in triumph.
But what was the path of the Master?
Is it not the path for his servants, that they might be encouraged,
and have a stedfast example therein?
He trod it before them,
and endured the several gradations and dispensations of the spiritual warfare;
he fasted in the wilderness, till he was hungry.
Let us not then think it strange that the servant is not greater than his Master.
Our safety depends upon our watchful attention, that when we are tempted we yield not;
but oh! how near does the impatience of our dispositions border upon that language,
"`command these stones that they be made bread;`" forgetting that it
is not by bread alone that our hidden life is preserved,
but by every word that proceeds out of the mouth of God,
and by every turning of his divine hand upon us; whereby, in his wisdom,
we grow from stature to stature, which by taking thought for ourselves we cannot do.
If we are found worthy to stand as pillars in the Lord's house in this day,
when there are many heavy burdens to bear, we must be first upon a sure foundation;
our dispositions,
like those of the disciples that discovered the
love of their Master's glory o(C) the mount,
must be subservient to divine control:
and we must not only learn to descend from the vision of light, but to keep the charge,
and to tell it no man until the divine life and power arise.
How hewing and forming are these things! and what
instructive traces do they leave of the Master's work,
because they reduce self, and convince that no confidence must be placed therein!
May it be our experience, dear friend, in the few succeeding steps of cur lives,
patiently to suffer, and fervently to wrestle for the blessing of preservation.

