== Chapter III.

[.chapter-synopsis]
* Visit to her husband`'s relations in Ireland
* Journey into Norfolk, etc.
* Visit to the meetings of Friends in Ireland.

+++[+++In the Eleventh month 1782, she felt an inclination and freedom of mind,
to accompany her husband into Ireland, on a visit to her relations.
The deeply instructive exercises which she met with previous to her landing in Ireland,
with her humble, watchful state of mind and engagements there,
may in part be collected from the following letters, which, except the first,
she wrote in that land.]

[.small-break]
'''

--This place (Holyhead) is uncomfortable to stay at, among a great deal of company,
and no woman but myself; and though it is made easier by their great civility,
yet the journey altogether is an awful thing.
On surveying my inducements for coming and impartially examining myself,
I have not yet found any uneasiness, though I am low,
and our present situation is a trial of both faith and patience.
Indeed,
the many rocks and shoals attending us in our religious
and civil concerns through this trying pilgrimage,
will, I apprehend, ever prove a trial of these; and therefore,
by the direction of the best of pilots, to guard against them,
and to steer wisely through life, is the work of our day;
and will open most clearly the prospect of the haven of durable rest.

[.small-break]
'''

--I was greatly pleased when we got to Holyhead, hoping soon to be in Dublin,
and dreading the water but little.
Here our disappointments began.
We went out to sea next day, were tossed about for fourteen hours,
and I then returned extremely ill; so much so,
that it became a matter of doubt to my husband
whether he should not have to bury me there.
I thought as soon as my head was laid after our return,
that I perceived a cup bitterer than death; for death, except on Robert`'s account,
I should not have regretted,
so shaded are all the domestic enjoyments and temporal blessings of life, when,
abstracted from them, we are called upon, faithfully and with singleness of heart,
to do the will of our heavenly Father.
To have a meeting at Holyhead presented with great weight,
and at the same time the appearance of things told me that, on various accounts,
(my own bodily weakness not the least) it was an impossibility.
I was afraid, but I think I was not rebellious.
In the depth of distress, I offered myself as one unable to answer the requiring,
hoping the offering would be accepted, and that some ram would be caught in the thicket.
Here the call seemed renewed to obedience, and not sacrifice;
and I saw that if anything short of the demand was offered,
though I even exerted myself in faithfulness in Ireland, as I promised to do,
I might be permitted to fall into a snare, and return from there,
instead of the reward of peace, with the query, Who has required this at your hands?
Present obedience, and subservience to the operation of Truth on our minds,
are no doubt what will preserve us on this sea of glass mingled with fire;
for if we keep with the life, and move therein, it will keep us humble,
reduce our confidence in the flesh, and draw is down into suffering with it.
When our dwelling is as among the pots, and no goodliness remains in us,
then we know in whom is eternal help,
and the travail of our spirits is for ability to look towards his holy habitation.

Our first sailing was on fourth-day, and by sixth-day I was something better,
when the captain and a great number of passengers were disposed to sail,
and none of them more so than ourselves, if the wind would take us, which,
according to the feelings of my mind, I believed it would not.
But I have no cause to think it was unacceptable to try the fleece again; which we did,
and after getting out of the harbour, the wind turned against us, and grew very rough.
The vessel was violently tossed, and at one time, we were in great danger of foundering.
I lay as quietly as I could, beholding the wonders of an Almighty hand concerning us;
and in the deeps, both spiritually and temporally, I felt, myself a Jonah,
when the people were crying that there was one on board; and all was tremendous about me.
The danger we were in was evident, but my hope never failed me;
which I esteemed an unspeakable favour,
and which led me to a greater willingness than I had before felt,
to give up to the meeting, or anything else that was required.
We were out this time but about four hours, and after we landed,
a large merchant ship was wrecked in our sight, but no lives lost.
My situation now became awful; there seemed no way but resignedness to the meeting,
and that I could not see was to be till first-day.
My husband I perceived was afraid,
for he considered us accountable for whatever the cause suffered by us,
especially as there never was a meeting there before.

On first-day morning we were tried again, for the wind being fair,
we prepared for sailing, and when all was ready for going on board, a storm came on,
and the captain dared not venture to loose the ship in the harbour,
believing that if he did it would be soon wrecked.
We then returned again,
and the time came on for the people to go to some place of worship;
when finding an empty house near the inn, we engaged it,
and felt most easy to give notice to but a few,
that we were going to sit in our usual manner to worship, and that if they,
or any others, chose to accompany us, we had no objection.
Before we got to the place, many were there, and more followed;
and to our humble admiration, divine assistance was near,
and wonderfully helped us over that sitting.
At the conclusion, the people were desirous of another in the evening, which,
when we had considered it, we consented to; and if I may venture to say,
it was crowned with good,
and the melting operation of Truth appeared to be experienced by many of the people,
who behaved with great solidity.
The next evening the tide suited for our passage, and with peaceful minds we embarked,
and were but nine hours from bay to bay.
Thus have we cause to turn back to this page of our lives, with humble gratitude of mind,
and to acknowledge that a simple pointing of duty, and a simple discharge thereof,
is productive of solid satisfaction, when, on the other hand,
no exertion or anxiety of our own, can furnish us with one grain of it, nor can we,
by taking thought, add one cubit to our stature!

[.small-break]
'''

--Often, very often, since I saw your faces,
has my mind visited you in affectionate nearness;
but I have seldom felt greater inability, than since I came into this land,
thus to converse with my friends; for as our coming was sudden,
it has occasioned deep searchings of heart, for preservation,
and direction how to move in the line of wisdom.

We met with a very cordial reception in Ireland;
the hospitality and affection of our friends
were not unacceptable to a poor stranger like me;
nevertheless my mind has not seemed at liberty, as I could have wished,
to enjoy that society which is gratifying to self.
It is good for us renewedly to feel ourselves not our own,
to stand resigned to the divine will, and to know it to be our meat and drink to do it.
Every little additional experience tends to convince us,
that herein consists our most solid and permanent satisfaction;
and were our disposition of resistance to the
painful preparation for devotedness removed,
we should more often have feelingly to acknowledge, that with the divine blessings,
there is added no sorrow; but we make sorrows for ourselves,
we add that which our gracious Benefactor has not in store for us.
A path exempt from trials is what I have no right to expect,
and what I hope I am learning not to desire.
A patient submission to every divine dispensation, is what I wish for an increase of;
that so, the mingled cup of life may prove a profitable draught, and impress me,
more and more, with a humble sense of the multiplied blessings bestowed upon me:
for by this means,
I believe we shall increase in knowledge how to move and conduct ourselves,
amidst the various temptations, besetments, and cross occurrences,
incident to this probationary state.

We went pretty directly from Dublin for Clonmel, after the half-year`'s meeting,
and spent two days very much to my instruction, at Ballitore.
We stayed about ten days among our relations, who are valuable and kind,
and then went for Carlow quarterly meeting,
where were Robert Valentine and his companion, etc.
I think, upon the whole, it was a very favoured gathering, though here, as in our land,
the world and its spirit have made great devastation
and scattering among the gathered tribes.

[.small-break]
'''

--We look with a degree of satisfaction at our return.
A little rest to body and mind will be truly acceptable,
as our visit to our relations seems now completed.
Our passage through this land has been encumbered with many thorns,
and attended with many trials unforeseen by us.
It is a day of deep humiliation, and it sometimes looks as if our judgment was taken away.
I do not want to make complaints; I wish rather to profit by what I have suffered,
and reap instruction from every renewed dispensation of infinite kindness;
feeling myself unworthy of the least of His benefits, and that,
without his peculiar care, I shall be overwhelmed,
and warped aside from the stability of the truth:
but by being baptized into a deep sense of my own weakness and frailty,
I have been led to acknowledge, that even the bitter things are sweet; seeing,
that in infinite wisdom,
they are ordered for the strengthening of our spiritual appetite,
and bringing down that part in us which is at enmity with the cross,
and loves not its government in the mind.

[.small-break]
'''

First month 1783.--What has felt very desirable to me is,
that in these outward separations, we may increase in that which is good,
and that whatever befalls us may tend to settle
us more in the ground work of true religion,
that therein we may stand, and therein grow.
Then will the fluctuations of this uncertain state become sanctified to us,
and being instructed in the school of Christ,
our spirits and conduct will become more conformable to the purity of the pattern.
My fear of myself daily increases,
and I am also apt to think that by looking too much at any evil,
we may insensibly be almost drawn into it.
It is nevertheless good to survey our standings, to prove our own infirmities,
and repair to the place of help.
The multiplied distresses, both spiritual and temporal,
that have been permitted to befall us in this land, or since I left my own,
have often occasioned a secret cry for the continuance of divine preservation;
and a little ray of hope that the Lord has not forsaken us,
is all the succour that my poor tossed mind has often felt.
There is great need in time of outward perplexity, impartially to examine the cause,
to search what there is in us that requires these things;
by so doing we may often see couched under them the wisdom of a divine hand,
and that to remove the cause in ourselves, is to go to the root of the matter.

[.small-break]
'''

First month 1783.--I feel now, as at many other times, my mind drawn into near affection,
and, I trust I may say, that true fellowship with you,
which springs when I am capable of experiencing
any better enjoyment than what is natural;
but as that only arises from the renewings of life, I am often afraid to speak of it,
lest it should fall short of its character in the time of trial.
However,
I may say I feel that love which many waters and seasons of deep and secret distress,
have not quenched or diminished.
A degree of this mark of discipleship reviving in my mind,
has sometimes been as a temporary cordial,
tending to dispel the gloom of many discouragements,
and opening the view to a little pure serene satisfaction.

My dear friend, many are the trials of the enemy of our peace to overset us,
many have been the assaults which I have met with since I saw you,
far exceeding what I ever knew before.
If divine help will condescend to be near,
and preserve me from sinking in the pit of discouragement,
just keep my spirit alive to confide in His name, and dwell under his power, my heart,
I trust, will bow in humble gratitude before him, and acknowledge his might.
Our eye is now much fixed upon Yorkshire;
oh! that we may there experience the evidence of divine acceptance, and that,
in our movements, or not moving at all, the blessing of preservation may attend us.
Outward enjoyments, domestic tranquillity, and the affectionate regard of our friends,
are all in themselves desirable objects, but without this blessing, what are they?
insipid, or fruitless delights.

[.small-break]
'''

First month 1783.--As,
(in infinite wisdom no doubt) our minds are at times drawn into solitude,
so as to resemble the pelican in the wilderness,
having no access to the habitable parts of the earth, nor subject to human observation,
so it appears consistent with godly jealousy that human consolation should be forbidden,
and that, having our dependence only on a gracious and merciful Father,
who deals with us as children who require his chastising hand, his rod and his staff,
we may be built on a safe foundation, with a quiet habitation thereon,
out of the reach of human interruptions.
Surely there are none so tried as the poor weak instruments,
that are used for the divine will to be communicated through.
These require not only the forming of the potter`'s hand, but higher degrees of drying,
and greater heat in the furnace to prepare them, than almost any other vessel: no,
if I may be allowed the comparison,
they are like dishes that have to pass through the oven for every service, and which,
after they are emptied, and the company has enjoyed them,
need more washing and care than any other utensil at the table;
and great danger there is that, by indiscretion of some sort or other,
they will get cracked or broken.
I look with dread, I am bowed down and dismayed,
at the sight of the precarious standing of such, but especially my own:
the consideration of human weakness, and "`how frail I am,`" is almost my meat and drink.
How excellent is the privilege of having a monitor at home,
an impartial friend in our bosom, who, if we enough attend to Him,
is able to make us as wise even as our teachers! the reproofs and
wounds of this friend are better than the kisses of an enemy.

[.small-break]
'''

Clonmel, first month 1783.--I have now continued about two weeks longer in this place,
have received very affectionate kindness, and great hospitality from my friends.
Were there not something in our minds that is panting after superior, more extensive,
and secret enjoyments, I have thought myself placed among the cordials of life:
but without the seasoning virtue of Truth, and an evidence, though ever so small,
of divine approbation marking, or resting upon, our dwelling,
they are tasteless and insipid enjoyments.
Perhaps I have deprived myself of that which is good,
and am now too ready to let others share the same;
a disposition which I wish not to cultivate,
it being highly inconsistent with the benevolence of the gospel,
which breathes no language inferior to that of, "`Glory to God in the highest,
peace on earth, and good will towards men.`"
But how to distinguish, at times, the grand cause among a multiplicity of causes,
requires wisdom, undefiled wisdom,
that the immortal birth may be surrendered to the breast and care of its true mother,
and that nothing hurt it, or diminish its strength; but that,
under all turnings and overturnings, divisions and subdivisions,
it may gradually and steadily grow in stature, in wisdom and pure understanding,
and take to itself an everlasting dominion in us.
It is the "`deep that calls unto deep.`"
I thought I felt, on reading your last,
something of the mind of Truth in reviving a little my drooping spirits;
a degree of thankfulness covered my mind,
and I was encouraged to wait the passing away of this gloomy night,
in comfortable hope of the dawning of a better day,
wherein the former and the latter rain may descend, to add sap to the root,
and to refresh the branches.
What is it in us that flinches so much at suffering?
It must be that flesh and blood which can never inherit the kingdom.
I have bestowed some pains to silence it with reasoning,
and arguing the nature of things; but alas!
I have sorrowfully found it fed thereby,
and perceived that it is only in humbly abiding under the divine operations,
that subjection is wrought, and the most so, when the cause was not fully discovered;
for then the lowly petition ascends, which at this time covers my spirit,
Grant me a grain of the precious gift of faith, that I may live and walk thereby.

[.small-break]
'''

First month 1783.--O this root of self, when will it be subjected!
It perhaps appears more to oppose your service,
but I believe it more secretly prevails in me,
and is not under that control and subordination
in which you have it in more minute things.
But let us not weigh ourselves by one another;
let us rather bring our spirits to the balance of the sanctuary,
and if there we need chipping and hewing,
not think hard of the instruments that are to do it;
but passively and patiently endure all things,
in hope to enjoy that little which is our own in the end,
having it pure and separated from the vile.
My mind has been drawn into great nearness to you many times since we parted.
I have feelingly remembered the seasons when, though beset with many secret probations,
we might say, we took sweet counsel, and our spirits were baptized together,
and prepared thereby to go up as to the mountain of the Lord,
and to the house of the God of Jacob,
where He has graciously condescended to teach us more and more of His ways,
and begot fresh resolutions in us to walk in his paths.
Let us not faint, my beloved friends,
but wrestle with Him for the renewal of this blessing;
that though it may be our lot often to be separated,
our spirits may unite together in holy fellowship,
and that pure love which many waters cannot quench,
nor all the changes of this uncertain state of being ever diminish.

[.small-break]
'''

Sheffield, sixth month 1783.--My mind is much with you,
and I trust it is in that fellowship which can unite with the absent though in suffering,
and breathe for the prosperity of the precious Truth.
I beg to be more and more bound to that,
let its appearance among men be ever so mean and contemptible;
for it is here that we are not afraid of human wisdom and displeasure.
But is there not, sometimes, too much fear of this sort, when under that power,
and the burden of that word which, if it met with no obstruction in the instrument,
would oftener break the rocks, and be a consuming fire among the cedars of Lebanon?
May this season of suffering be blessed to you and the
church! and oh! may your hands be strong in the faith,
and hold out to the end in patience, that with the church coming out of the wilderness,
you may repose on the breast of the beloved of souls, and your cause centre with Him.

[.small-break]
'''

Lancaster, seventh month 1783.--My best wishes accompany you,
in this awful service of visiting the few scattered professors under our name,
and perhaps of unfolding in the fresh openings of life,
further manifestations of gospel light to such as are not yet of our fold,
particularly in Scotland, I remember that before we entered the borders of that land,
and indeed whenever I viewed it in prospect, it was clearly impressed upon my mind,
that there was no track for us to go in,
nor any footsteps to be depended upon in that journey;
but that our attention would be continually required to
the fresh pointings and qualifications for service;
and on our leaving Scotland,
we had greatly to lament a deviation from this pure indwelling of spirit,
and unfaithfulness to some manifestations of duty.
When the mind, after being engaged in service, has got a little liberty,
and feels itself as a bow unstrung, it is too apt to rejoice,
and evade the next bending for service; whereby half our commission may be neglected,
when we are peculiarly called to watch, to try and to feel every step which we take.
Here simplicity and humility are our companions, and if a pure holy zeal covers us,
in a state of true dependence, the wisdom of the creature has no part;
but the life rising into dominion,
and being taken for our guide in every step under the exercise of the gift,
we have no need to be anxious for doctrinal
arguments to prove what we assert to the people;
because this life, answering the life in those that hear,
can expound and unfold such mysteries as have been hid from ages;
and it is only by our single attention to the
purity of the gift and the milk of the word,
that we can be preserved in that simplicity which confounds the wisdom of the wise,
brings to naught the understanding of the prudent, and exalts the seed of the kingdom.
Thus I apprehend the ministers of the gospel are led, not only to teach all nations,
where they are sent, but to baptize them into the power of the gospel,
however few the number of their words may be.

I feel a strong desire for your faithfulness in this journey,
and that as you pass through little villages and towns,
it may not be without feeling for service, for in this respect we were deficient.
Look not too much at your own weakness,
but consider the strength of that Almighty arm which
works marvellously for those that rely upon it,
and gives them faith for their victory.
I know there is something in us, when we occasion many people to be called together,
that fears for ourselves, and for the Truth; it is well, in these times of trial,
to consider our own inability, and in whom help and power dwell;
for then a calm sometimes allays these anxieties,
and spreads upon our minds the beauty and convincing influence of a lively, awful,
silent worship, which stands in need of no addition, but which, at times,
is accompanied with words in the demonstration and power of the same spirit.

[.small-break]
'''

Seventh month 1783.--I think I was scarcely ever sensible of
more death and darkness than since I came here:
if a little life and light should spring in our future sittings,
it may have some reviving effect, for really my spirits are in a drooping way,
and my strength also.
I expected nothing but suffering on coming here, and thus far it is my portion;
this satisfaction, however, attends me, that it is but for a day or two,
and I endeavour to lift up my head above sinking too much;
but oh for the cause! the testimony of Truth seems nearly laid waste,
and the pure life crucified.
Here are, indeed, many valiants, but what can they do?
it is not the servants of themselves, that can make the dry bones live.
The little strength I feel,
seems to be in endeavouring after a settled retirement of mind out of meetings,
and being willing to appear foolish as I am.

[.small-break]
'''

Seventh month 1783.--There is a beautiful order in the growth of the spiritual,
as well as natural man: he is at first carried and fondled,
and it is then generally right to give him what he cries for; in a little time,
he makes some efforts to go by himself, which, sooner or later, mostly prove effectual.
Presuming now on his own ability, he assumes the air and carriage of a man,
and in this confidence goes forward, till his stumblings, his falls, and his wounds,
have sufficiently convinced him, that he is but a child,
and that his will is no more to be depended upon than his strength.
As it was right to indulge the simplicity of his first desires, so now,
these becoming mixed with evil instigations,
either in the appearance of a friend or an enemy, it becomes necessary,
in order to preserve this simplicity,
and the divine impressions which may renewedly descend upon it,
industriously to repel and guard against the powerful influence of self-love,
and self-seeking, which is the beginning of our continual warfare.

I at times thankfully view some of the exercises of my mind, as a probationary childhood,
frequently occasioned by indiscretion,
and increased by the growth of the corrupt will
with a growing knowledge in divine things;
so that I have been and am frequently ready to conclude,
I shall one day fall by the hand of this enemy:
but oh! may we support the warfare which is mercifully
begun! and by depending solely on that arm,
which cut Rahab, and wounded the dragon,
be no ways instrumental ourselves in preventing a maturity in the pure life,
and preaching by good works.
I hope my dear you continue, and will continue,
to feel your habitation like the house of Obed-edom.
It is indeed distant from us; but of how little consequence is that,
when there is fellowship in the circulating life of Truth,
wherein we are as epistles written in one another`'s hearts, which are meditated in,
at times,
to the refreshment of our spirits when drooping and
feeble.--It is a blessing not to be lightly esteemed,
to be married to those of lively spirits, and clean conduct; not drawing back,
but helping forward, that work to which there is a divine calling:
and as is among those who are thus blessed, it will, I have no doubt,
sweeten many unpalatable cups,
and render moderate some blasts from the wilderness of this world,
and its corrupt fluctuating spirit.

[.small-break]
'''

+++[+++Her home for several years after her marriage, was at Foston,
a village ten miles from York.
This was to her a comfortable retirement when not engaged abroad in the service of Truth.
But though gratifying to nature, and a desirable resting place,
her concern for the advancement of her great Master`'s cause,
which was her most desired meat and drink, often called her from this abode,
so that she seldom resided there for a month together.
It appeared, indeed,
that she was unwearied in promoting the cause of Truth and righteousness,
and willing to spend and be spent for the great Name`'s sake.]

[.small-break]
'''

Foston, first month, 1784.--Oh the need there is,
when we feel a secret divine approbation for some little faithful services,
as the answer of well done, carefully to centre to this treasure,
and leave it in the hands of our great Benefactor! for how unfit are
our earthly hearts to be entrusted with riches so weighty,
and so different in their nature! they are indeed found to be as bags with holes,
which lose the precious gift among the rubbish of the house.
Under these considerations, I am led at times to prefer poverty, and nakedness, and want,
to an appearance of wealth, and spending my spiritual substance in riotous living:
and to be preserved chaste and faithful in this state, is one of my strongest desires,
yet attended, in some degree, with the certain knowledge of how frail I am.

[.small-break]
'''

York, first month, 1784.--We have great need, in this day, for clean-handed,
single-eyed instruments, in the work of reformation; such as demonstrate,
in the particular parts, and general tenor of their conduct, that they truly fear God,
and hate covetousness: for,
of such only is the pure spiritual building composed--the church,
against which Satan and his agents can never prevail; whereunto the nations may gather,
behold its purity, and be invited to become living members thereof.
But, oh how defiled is our camp! how temporizing are the spirits of those who ought to stand,
as valiant soldiers, against spiritual wickedness in high places,
and fight manfully under the banner of the Lamb!
The world, with its gilded baits, has allured their attention, and attracted their sight,
from the example of our holy Pattern; it is therefore no wonder,
if the work they undertake is superficially done; and that which has been their snare,
passes unobserved for lack of purification.
From a view of these things, I have been led to prefer, and even to request tribulation,
mortification, and what may be called evil things, in this life, to an unsubjected mind,
being an unsound member in the church, and seeking to be heir of two kingdoms.
Whether I am thus preserved or not, I believe that now, as formerly, the lame, the blind,
and the dwarfs, will not be accepted to minister of the most holy things,
and carry forward the cause of righteousness in the earth,
till their application is uprightly, and humbly made to Him,
who is the healer of all diseases, and the restorer of ancient paths to walk in.

[.small-break]
'''

Second month, 1784.--You have often been in my remembrance since we parted,
and both when hoping and doubting, I have wished to address you in this way,
believing it warrantable now, as in the captivity of the Jews,
for those who are uprightly, though feebly, concerned for the prosperity of truth,
to speak often one to another; and the trusting that a book of remembrance is written,
casts, in some depressing seasons,
something of a ray of spiritual sunshine upon the spirits in prison; which,
though not a promise of freedom, yet cheers a little,
and renders tolerable our unavoidable situation of mind.
A multiplicity of concurring circumstances, past and in prospect,
have of late deeply affected me: the spirit of Goliath rages from every quarter:
its power I feel, the low state of the church is evident,
and my own weakness stares me in the face.
I would be glad to dwell in obscurity, and have my name blotted out of remembrance.
There are many called soldiers among us,
but oh! how few of such as are loyal to the King of kings,
and whose work is diligently to establish his government;
insomuch that such children as I am, are ready to conclude, that if we move at all,
our hand must be against every one, and every one`'s hand against us:
for though retirement is what above all things I would choose for myself,
yet if I apprehend myself called to service at all,
it is the fervent prayer of my spirit to be preserved therein from the fear of any man,
and from doing the work deceitfully: nevertheless,
the secret feelings of my mind seem to say unto the seed, that "`bonds await you.`"
May we then possess our souls in patience,
and not fear in seasons appointed to contend for our faith.

[.small-break]
'''

Second month, 1784.--Being affected with the general causes of discouragement,
and so much afflicted with some particulars, I am ready at times to conclude,
I cannot hold fast my faith without wavering in this time of trial.
You, my beloved friends, have your share of exercise; and whatever others do,
be faithful unto death, spiritually and naturally,
and then will your services be crowned with that life which cannot be disputed.
We have much disloyalty among us to the King of kings,
and some who are his subjects want to take from him an improper share of rule.
Seeing these things, let us be lowly, and shelter ourselves under the spirit of the Lamb,
that the prevalence of this alone may be the weapons of our warfare:
though we experience him to be slain as from the foundations of the world,
and have to go down into suffering with him, and our faith deeply tried,
yet let us remember that He lives and reigns forever, and that,
notwithstanding the combined powers of darkness,
of the increase of his government there shall not be an end.

Our passage through life is like a journey wherein are difficulties and snares;
and wherein we find many who say they are going to the same port,
and who think they have found out, from longer experience and superior wisdom,
a better and somewhat different road; but when we believe them,
and make a little trial of their path, how have we, with painful steppings,
to return to our tribulated pilgrimage?
I feel deeply engaged in my spirit, that I may, and that we all may,
look to our own standings, not even to the most approved instruments for instruction,
when our application ought to be to the spirit
and example of our holy Head and High Priest.

[.small-break]
'''

+++[+++In the spring of the year 1784,
she appears to have been engaged in a visit to the
meetings and some families of Friends in Norfolk,
and to several other meetings, as she proceeded to the yearly meeting at London.
Of this religious engagement, no regular accounts of her own, has been discovered;
the following are the material parts of all that has been collected from her letters.]

[.small-break]
'''

We had nine meetings last week, at eight different places,
beside private opportunities in families, which we dared not avoid;
finding the declension to be so great in almost every one, where we have come,
and so few who seem to know it, that we are ready to say,
For Zion`'s sake we cannot rest nor hold our peace,
till at least they are informed of their state.

We attended their week-day meeting at this place, with which we were well satisfied,
it being a time of much instruction, however, to my mind;
finding by a degree of living experience, that there is indeed a Minister of ministers,
on whom we have great cause to wait to be instructed ourselves, in our private,
as well as public duty; that, in all things, we may approve ourselves obedient servants,
and good examples to the flock.
It was my lot to sit in silence, viewing the great,
and almost general insensibility to true religion.

[.small-break]
'''

--We have not only travelled hard, but found much work at places where we have come,
finding it rather more than usual in the line of our duty, to bear a testimony,
not only to the Truth,
but against the numerous evils and inconsistencies which have
generally overspread the professors in these parts;
and as our peace much depends, in our passing along, in being honest,
and speaking the truth without parables, we have been enabled, pretty tolerably,
to discharge our duty, and to show them how far they are from what they pretend to be.

This is hard work, and we find that the more abundantly we manifest our love in this way,
the less we are loved by many who have been used to smooth things,
and have sought to make the Truth conform to them,
instead of their conduct being brought to, and regulated by the Truth.
Indeed many are blind in error, and those that see,
will not exert themselves to search their own houses,
and remove the inconsistencies that are in them.
A mournful prospect appears in these, as well as many other parts;
no likelihood of a succession in the Truth,
and even the present standard-bearers ready to faint.
Under these impressions, we seek not great things for ourselves,
but rather are disposed to consider it a favour, great enough for us to expect,
if we have our lives for a prey, from one place to another.

We have little expectation that in any sittings,
our minds will get above the spirits of this people;
and till that strength arises which puts the armies of aliens to flight,
I trust our lips will be sealed, and we content therewith; for indeed,
it is not an easy task to minister to this degenerate age,
who think they know all things, and, like the magicians in Egypt,
can account for all the works of the divine hand but what a favour it is,
that there is still extended to us as a people,
that power which confounds the wisdom of these,
and brings to naught their great understanding.

We have been much engaged the few days we have stayed at Norwich.
It has been to our minds a suffering time, during our stay in that place;
but though we have mourned, and perhaps rather murmured at times,
yet we have great cause to be thankful for the help wherewith, in infinite kindness,
we have been helped.
It is a day of great discouragement,
and I think I was never more ready to lay down my armour,
than in silence this day at meeting.
The situation of mind I was in, I found tended to humble and reduce the creature;
and as my soul was hungry, even the bitter food I partook of, became sweet,
and I saw the profit of these seasons.

We left Norwich on seventh-day, were at Yarmouth on first, Pakefield on second,
Beccles on third, Leiston on fourth, and Woodbridge today, where,
as at some other places, we sat in mournful, but I trust instructive silence.
What falls at times to our lot in meetings, and sometimes in conversations out of them,
seems much like pulling down old houses,
and we are often afraid of being choked in the dust;
for indeed most of the buildings we see are painfully superficial,
and our little labour has been deeply distressing;
so that the language of my heart often is, "`who has believed our report?`"
but I am thankful in feeling the burden decreasing as our work seems closing.

York, eleventh month, 1784.--I am really very poor, but whether enough so I cannot tell.
I am however rather more contented than when you saw me last,
having been a short time with--, and secretly comparing trials a little has done me good:
indeed I think it is a wise way, when we imagine ourselves under suffering,
to look into the pages of another`'s book, and meditate in their probations.
Here we number our own blessings, and a language sometimes unexpectedly arises,
"`what shall I render unto you for all your benefits?`"

[.small-break]
'''

+++[+++In the year following she felt a religious concern to join her friend Rebecca Jones,
+++[+++from Philadelphia,]
on a visit to the meetings of Friends in Ireland,
etc. and having laid the same before the monthly meeting, with the approbation thereof,
and the concurrence of the quarterly meeting,
she set forward on this journey in the seventh month, 1785.
Of this visit there is preserved a short journal written by herself, which is as follows.]

[.small-break]
'''

I left home the 13th of the seventh month, 1785, and spent two nights at York,
in order to allow a comfortable opportunity of taking a
solid and affectionate leave of my connections there;
and on the 15th, went with my husband to Bradford, where, next day, I parted with him,
he returning to York,
and I proceeding with my cousin W. M. (who was
to accompany me to Ireland) for Manchester.

We stayed there the next day, being the first of the week,
and I was at both their meetings;
which savoured to my mind of that righteousness and wisdom of man,
which never can work the righteousness of God,
nor savour the things that pertain to His kingdom.

But there is a precious suffering seed in that place,
to which my spirit was renewedly united in the covenant of light and life.
On second-day we went, with many Friends, down the water to Warrington, where,
on the 19th, was held their monthly meeting, which I felt most easy to attend,
though I might thereby miss an opportunity of crossing the water,
so early as I otherwise might choose;
and I was comfortably satisfied with this little dedication by the way.
I went that evening to Liverpool,
and waited till sixth-day for a suitable wind for sailing.
During this time, was their week-day meeting, and my spirit was there deeply exercised,
on account of some who were substituting their
own righteousness for the righteousness of God,
which is inherited in pure faith, in the virtue and power of that creative word,
by which all things were made, that were made in the spiritual creation, and by which,
through the reduction of the natural will and wisdom of men,
they can no more worship the work of their own hands:
and in the strength with which my spirit was renewedly supplied,
I attempted to express something on this subject, for which I felt peace.
We next day embarked for Dublin, in the Hawke packet,
and had a very tedious and distressing voyage, being uncomfortably detained,
in part for lack of wind, and in part by its being contrary;
the latter occasioning us to put into the Isle of Man, where we stayed two nights,
and found a very courteous and hospitable reception from the inhabitants.
My mind was attracted to them, in the secret effusion of gospel love,
but feeling abundant weakness in myself,
and lacking that united exercise which is received by fellow-labourers,
I did not perceive it to be my woe if I preached not the gospel; and therefore,
in a humble trust that the great Shepherd of Israel would send
more suitable servants for that work in that isle,
and not put my omission in the balance against me,
I embarked again with the rest of our company, save one, whom we left dead on the island.
Being out longer than we expected, by two days, our provisions were exhausted;
and though through divine protection we did not suffer much from want,
yet it was a favour gratefully to be commemorated,
that we were enabled through some difficulty to land when we did; which,
with the instruction conveyed to my mind, under deep discouragement,
and close searching of heart, when all human consolations stood afar off,
afforded humble cause to believe,
that this trying dispensation was intended as a necessary
baptism of my spirit into the service before me.

[.small-break]
'''

+++[+++A more particular account of this voyage, with several additional instructive remarks,
is contained in the following selections from her letters.]

[.small-break]
'''

It is very unexpected to me to write from this port; but so little do we know what,
in the course of divine wisdom, shall fall to our lot,
that every increase of experience convinces us,
there is no safer or easier situation of mind, than a daily dependence on,
and quiet resignation to Him who knows what is best for us,
and what will tend most to His own honour.
We sailed last sixth-day from Liverpool, having got there on third,
but the wind not being very fair when we set out, and turning more against us afterwards,
occasioned a troublesome and a wearisome passage thus far, not only by contrary winds,
and severe sickness,
but by the almost intolerable stench and suffocating closeness of our cabin and lodgings,
and the continual wicked, obscene conversation of our passengers,
who are seventy in number.
Sometimes, I was afraid it would overcome me, both in body and mind;
when recalling to my remembrance the poor negroes, (who, added to what I have mentioned,
in a far worse degree, are chained together,
under the load of that anguish naturally attendant on a
forced separation from the nearest connections in life,
and with the prospect of perpetual bondage under
cruel taskmasters) my small trials in this line,
and indeed in every other, diminished in my view; and the multitude of blessings,
in infinite mercy, showered down, so crowded in their place, that at times,
instead of repining, I saw abundant cause to enquire, "`what am I,
that you are thus mindful of me, and what shall I render unto you?`"
We put in at the Isle of man, and were hospitably received by the inhabitants,
whose engaging simplicity, and religious zeal, have attached my mind to them.
I am sincerely desirous that if I do nothing for the Truth, I may do nothing against it;
and when I look thus, I feel a comfortable belief,
that even this care shall tend to the furtherance of the gospel,
and that it will somewhat open the way for future service in this place;
for if the sense that attends my mind be right,
when the feet of the messengers are more eminently turned into the way of the Gentiles,
to Pul and Lud, etc. and to the isles afar off, this little place will not be forgotten,
but offerings will be brought here to the mountain of the Lord`'s holiness,
and His glory shall break forth.

[.small-break]
'''

--I am safely arrived in this land, and have humbly to commemorate divine protection,
and secret supporting goodness in my passage here.
The ways of the Most High remain to be ways of wonders,
and his acts are past finding out; nevertheless, he still reveals secrets,
as he did unto Abraham, when a degree of the same faithfulness is,
through His humbling power, attained to; and without it, how little do we know,
even when we think we know most?
Never did I so sensibly enjoy the bosom of the church, which I may humbly acknowledge,
was cordial to receive me; but how much more excellent is that pure faith,
which reveals itself when all human consolations stand afar off,
and by centering our spirits therein, wonderfully convinces us,
that it is the "`substance of things hoped for, the evidence of things not seen.`"

[.small-break]
'''

--I feel myself much recovered from fatigue,
and have gratefully to commemorate divine protection, and secret sustaining help,
when the feeble efforts of bodily strength and natural fortitude,
seemed unequal to render me that support, which one grain of living faith affords.
Oh! what abundant reason we have, not to trust in ourselves, but in Him who died for us,
to whose death, if we are not conformable,
we cannot fully experience the prevailing power of eternal life.

[.small-break]
'''

--I trust the probation my spirit experienced in our passage here,
will not prove altogether an unprofitable dispensation, on entering a service,
the right performance whereof depends on our being baptised enough, and weaned enough;
so that whatever is brought forth may be of the new creation,
unconnected with all old heavens and old earth.
And indeed I may say that, before I left home,
though my mind was much stripped and tried,
I often suspected whether I had fully partaken of the necessary cup of suffering,
preparatory to such an undertaking as the present;
and believed I should have a trying baptism to pass through before I entered upon it;
though I now have no doubt but my movings this way, were in the right time.
It is an unspeakable blessing to meet with the crucifying power of Truth by the way;
and the desire of my heart often is, to be more and more in love therewith.

[.small-break]
'''

--On our landing, I soon met with our honourable friend Samuel Emlen,
whose animating company and fatherly kindness, greatly revived me,
and helped me to leave the things that are behind,
and to press forward in prospect to a degree of humble
dedication to the renewed pointings of duty.
My beloved friend Rebecca Jones, with George Dillwyn and wife,
having performed a family visit to friends in Dublin, were gone to Ballitore,
where they found a similar engagement to that in which they had been employed;
and when I reached them, they had nearly finished, and were almost ready to proceed.
In a few days we accordingly set forward together, namely: George Dillwyn,
Rebecca Jones and myself; our prospects comfortably corresponding one with another,
we cheerfully concurred therewith, to travel in company.
On the fourth-day following we went to Christians Town,
and in the evening visited a family of young people,
one of whom was in a declining state of health; to whom, with the rest,
instruction and encouragement were handed,
to prefer the humbling dispensations of infinite wisdom, to all temporal gratifications.

We then returned to our lodgings, and sat with a family;
where my beloved companion was enabled, in awful supplication,
to breathe for continued support, and preservation in the path of obedience;
which comfortably cemented our spirits together.
Next day we went to Rathangan, where we had to travail for the arisings of pure life,
under the discouraging apprehension of its being very low in that place;
but infinite kindness vouchsafed to own the deep exercise,
and graciously sent forth his light and truth,
whereby the way to his Holy hill was opened in the demonstration of the spirit and power,
and the meeting ended under a humbling commemoration of his goodness.
In the evening we went to New Park, and next morning to the meeting at Timahoa,
which was small, and the public service rather laborious,
because of the unfitness of many of the professors to receive spiritual things.
In the afternoon we went to Prosperous, a new settled town,
where there are no members of our religious Society.
We had a meeting there much to the satisfaction of visitors and visited;
the people behaved well, and we had reason to believe, by the ownings of Truth,
that there is a precious seed there.
We went to New Park again to lodge,
and in the morning sat with the family and others then present,
and some profitable counsel opened.

From there we went to Edenderry; and next day, being the first of the week, we stayed,
and were at their own meeting, their preparative meeting,
a public meeting in the afternoon,
and in the evening sat with their ministers and elders; at all which,
merciful help was near in the needful time,
and enabled to discharge our several duties in simplicity,
for which the reward of peace and quietude was not withheld.

On second-day the 8th of eighth month, we came to Oldcastle,
and were at their meeting next day, where many people not of our Society attended;
among whom there was openness to labour.
After meeting we stayed with those few in profession with us,
when their low estate was felt, sympathized with, and counsel flow`'ed thereto.

On fourth-day we went to Cootehill, where are very few Friends;
they are in a poor shattered situation as to the life of religion,
and scarcely able to keep up their meetings.
Many of the town`'s people came to the meeting, and it was a solid favoured opportunity;
and a comfortable belief attended our minds, that there is a precious seed in that place;
but the professors of truth are stumbling blocks.
We sat down with them select at the conclusion of the meeting,
and found it exercising work to visit the seed in them,
but were enabled honestly to discharge our several duties.

[.small-break]
'''

+++[+++In a letter dated the next day, she writes:]

[.small-break]
'''

Through divine support, mercifully vouchsafed from day to day,
we have been enabled to discharge the mission committed,
so as to leave each place with a good degree of peace.
Indeed it is a relieving consideration,
under the discouragements that poor travellers often meet with,
that the work is not ours,
and that an instrument has only to be passive in the hand of Him that uses it,
leaving its prosperity, and the honour of the cause,
to the all-sufficiency of the divine arm, which can work with us or without us.

From there we went to Castleshane, a place very like Cootehill;
and in the evening after the meeting there, reached Grange, near Charlemount,
and lodged at the house of a visited young man, who, with two others in his family,
afford a comfortable prospect or a revival of ancient simplicity,
and right zeal in that place.
Our spirits were nearly united to them,
and the streams of encouraging counsel flowed freely for their refreshment and strength.
We were at their meeting next day, being the first of the week,
which was a suffering time; and in the evening,
had a very large and satisfactory meeting of the
country people not in profession with us,
who behaved well, and in many of whom the witness of Truth was raised.

Next day we proceeded to go round Lough-Neagh, by taking Toberhead, Colerain,
Ballynacree, Ballimena, Grange, and Antrim; at all which places,
we had deeply to lament the low declined state of the professors of Truth,
not only as to numbers, but in a departure from the precious,
preserving Spirit of light and life;
whereby the living members of the church are kept in their lots,
and enabled to stand with firmness, as a city set on a hill,
to the praise of His grace who has called them out of the world,
into His marvellous light.
The country people coming in at the aforesaid places,
tended to the more free circulation of life,
wherein the spring of gospel ministry was sometimes opened;
but it was my lot to pass along in gloomy suffering, and, at times, instructive silence.

After meeting at Antrim, the 21st of the eighth month,
being met by a friend and his wife, we returned home with them, and rested next day;
on the evening of which my dear husband came to us from England,
and after staying in the neighbourhood where we were,
and falling in at several meetings for discipline with us, he went to Clonmel,
and stayed till we came near that place before we saw him again.

On the 23rd we went to Newtown, and next day had a meeting with the few Friends there.
The knowledge and virtue of true religion seemed very low among them,
and it was hard work, by deep and secret exercise, to minister to the pure life.
From hence we returned to Lisburn, and attended their monthly meeting,
wherein a little strength seemed given me for some public labour;
but my dear companions were silently baptized under a
concern to visit the families of Friends in that place,
though the time did not appear to be then come.

After being at Hillsborough, Lurgan, Ballyhagan, Moyallen, and Ballinderry meetings,
we returned to Lisburn, and in about a week performed the service;
the Minister of ministers being near to hand forth in the needful time (often after
long suffering silence) suitable instruction and consolation to the visited.
Great indifference and insensibility,
as to the knowledge of the Lord`'s dealings with His people, prevail in that place,
though a little tried remnant dwell among them.

[.small-break]
'''

+++[+++The following is extracted from a letter bearing date the 1st of the ninth month 1785.]

[.small-break]
'''

Such is the state of our Society in these parts,
as well as in several places in our land,
that it is hard dragging along for poor travellers;
the prevailing death is ready to swallow them up,
and so put a stop to all circulation of life.
Well! drooping as our spirits often are, we have no where else to go but to the fountain,
which is, at times, when faith and patience are at the lowest ebb,
unexpectedly opened for our renewed refreshment,
and encouragement to trust a little longer.
Here are, notwithstanding, in the north of this nation where we have been,
a few beautiful plants among the young and younger men, whose roots are, I trust,
deepening in the heavenly soil; but in the prospect of their future trials,
if they are faithful, I am almost ready to tremble,
there is such a host of opposition for them to press through,
in reviving the purity of the gospel.
We are nearly united to them, and to find them was like meeting with near kindred.

At the close of this visit,
came on the quarterly meeting at Ballinderry for the province of Ulster,
which was rather a low suffering time.
Here we met with our friend Zachariah Dicks from North Carolina,
who was come over on a religious visit to this land,
and who was in some expectation of our companion George Dillwyn joining him;
but not feeling released one from another in the service wherein we were joined,
it was judged most prudent to wait for the openings of Truth, as much in our separation,
as we had endeavoured to attend to them in joining.
We left this province pretty directly after the quarterly meeting,
and set off towards Dublin, taking Rathfriland meeting in our way,
to which many town`'s people came, and it was a large and favoured meeting.
We reached Dublin the 15th of the ninth month, where we stayed near a week,
and sat several meetings, under great oppression and discouragement of mind,
and without much relief saw an opening to leave the place and go to Timahoa.
Here we visited their families and had peace therein.
From there we set off for Edenderry; and going by way of Rathangan,
an opening which had been put by when we were there before, of.
having a public meeting among the town`'s people, presented again;
and we had cause to admire,
how providentially we were cast in the way of performing such pointings of duty,
as had been, more from diffidence than a rebellious mind, passed over.

Here we stayed over first-day, and had a large crowded meeting in the evening,
which was considerably disturbed by some rude people in liquor, but many were very solid,
and it ended well.
From Rathangan we pursued our journey to Edenderry, Tullamore, Moat, Ballimurry, Birr,
Kilconnermore, and Roscrea; in all which a degree of painful exercise was our lot,
under the feeling sense of the general departure of the professors of Truth,
from that ancient, righteous zeal and primitive simplicity,
for which the people of God who walked faithfully before Him, were, in all ages,
conspicuous.
But He who never said to the wrestling seed of Jacob,
"`seek my face in vain,`" graciously condescended to reward the,
travail of our spirits, by arising for His own name`'s sake,
and giving strength to lift the standard of righteousness,
and furnishing with an invitation to the youth to repair to it,
and so inherit the blessed effects thereof.

[.small-break]
'''

+++[+++From Birr, she writes as follows:]

[.small-break]
'''

Gloomy is the prospect that opens in many places, and yet, by getting low enough,
we sometimes find to our refreshment, that there is, in most places,
a hidden suffering seed, with which we have sympathized,
and in the extendings of renewed strength, been led to visit,
though it is but little known or valued by the easy carnally minded professors;
and I have sometimes thought,
that if our coming answers no other end than to strengthen a few, weak hands,
and be instrumental in reviving the hope of the humble, tried children in the family,
it will be enough, though the reward to ourselves may be but small.

We went to Limerick from Roscrea, and stayed there over first and second-days.
The public meetings were low, distressing opportunities,
and little ability to labour among that people,
who seem much under the influence of the god of this world;
but on first-day evening a number of youth being present at T.
M.`'s and a few honest-hearted Friends more advanced in years,
we had a very favoured season of retirement, and the streams of love and life,
through instructive, comforting ministry, ran freely.
On third-day we left Limerick for Youghall;
my mind was dipped into a sense of my own weakness,
and great discouragement and dismay surrounded me.
I saw the necessity of an increasing labour to dwell near the pure gift in myself,
which I have ever found to be the most effectual preservation,
in the conflicting work of purification and faithfulness in more public service;
for when it reduces the mind, and brings it down as into the bottom of Jordan,
it likewise stays the billows thereof by pure faith,
and succours by the incomes of patience,
whereby every divine dispensation is rendered profitable, and every bitter thing sweet;
centring us out of the reach of fleshly confidence,
in that state of abasedness to which divine compassion is most eminently extended.
We lodged one night at an inn, and on fourth-day reached Youghall, where, on fifth,
we had two large and favoured meetings.

Next day we got to Springmount near Cork,
to the house of our dear and honourable friend Samuel Neale.
Here I heard of the decease of our beloved friend, Robert Walker,
who departed this life at Tottenham, near London,
after having paid an acceptable religious visit
to Friends of that city and its neighbourhood.
He was a man who having passed through deep baptisms of spirit,
in preparation for the work of the ministry, became eminent therein.
The multitude could not judge, neither did they know, his frequent,
suffering descendings with the seed, when crucified in the hearts of the people,
as in the streets of spiritual Sodom and Egypt;
and considering himself as an unworthy minister thereto,
he was clothed with resignation to the dispensation of the day.
Great was his industry,
and yet many were the trials of his faith for the supply of temporal things.
Though unadorned with human literature, he was instructed in the school of Christ,
as a good scribe to whom was committed the knowledge of the mysteries of the kingdom,
wherein all necessary accomplishments were acquired, and displayed in gospel simplicity.

Since my coming into this province,
the subject which has for some time been under my consideration,
of settling in these parts, has often been presented to my mind; with an anxious desire,
that the most endeared companion of my life, may, with myself,
be kept single in all our views,
and resigned in our spirits to whatever infinite wisdom sees fit to do with us;
that the way before us, though it be strait and narrow,
may not be made more difficulty by any willings and runnings of our own.
I am often afraid of myself in this respect; I feel, when unsupported by best help,
a partial attachment to my native land; and to part with my connections,
and some to whom I am closely united in spirit, at times appears hard:
but even on this footing, I find a counterpoising weight on my husband`'s side,
who has also valuable relations, and many friends in the best sense,
with temporal concerns and conveniences more suitable than elsewhere.
Oh then, may divine counsel influence our spirits,
in the consideration and determination of this important step!
You know, O Lord! the fervency and exercise of my spirit herein; you know, that,
above all things I wish to serve you, with the dedication of all that I have,
when you call for it; and as by your power only, a holy compliance is wrought;
O withhold it not in the needful time!
Permit not our feet to slide from the ancient foundation,
but with the right arm of your strength enable us to make war in righteousness,
in the lot you assign!
O show us the lot!
Permit us not to wander in the dark, but be graciously pleased spiritually to lead us,
by the cloud and pillar of fire,
certain tokens of your holy approbation of the way that we take!

At Cork we stayed, (except going one day to Bandon, and returning the next) eleven days,
and attended nine meetings, and many private opportunities in Friends`' families,
where counsel and encouragement often unexpectedly opened;
which were ministered under the precious influence of divine love and life;
wherein the spirits of a remnant Were cemented together, in a degree of holy fellowship,
and an exercise generally prevailed to help one
another forward in the new and living way;
which in many places lies much unoccupied,
the travellers having got into paths so widely different,
that it is sometimes difficult to find it; and when found,
so to believe in its rectitude, as to make strait steps therein.

During my stay in and about Cork,
I had frequent occasions humbly to commemorate the wisdom, mercy, and power,
of our gracious Helper, who, in a time of deep humiliation and adversity,
sustained my poor tossed soul; and,
by a portion of that holy faith which I knew to be his own immediate gift,
gave me to see his all-sufficiency, and my own nothingness;
and after melting all that was within me, by his humbling dispensations,
saw fit again to renew his image upon my heart,
and to cause me to experience more largely the work of the new creation,
and the necessity of ever abiding in lowliness of mind,
and treading the courts of the Lord with holiness and fear.
O! said my soul, withhold not from me whatever has this tendency;
let the voice of the Holy One go forth, which says,
"`cut down the tree,`" rather than it should overspread, and bring forth fruit,
to dishonour the great and excellent Name; nevertheless,
may that which is pure be fastened,
as with a band of iron in the tender grass of the field, that so,
humility and simplicity may spring, and more loudly acknowledge,
that the Most High reigns in the kingdoms of men,
and gives of his own precious gifts and favours to whomsoever he will.

We went from Cork to the house of a Friend who, for some months past,
has been in a low dejected state of mind;
and in the evening my dear companion Rebecca Jones, was dipped into his situation,
and her mouth was opened in living counsel and encouragement,
which for a time seemed to revive him.
Here I met with my dear husband, to our mutual consolation; and from hence,
after attending a meeting next day at Garryroan, which was rather a low time,
we went to Clonmel to our mother`'s there,
and rested one day before the quarterly meeting for Munster province came on.
Our minds were measurably baptized for the approaching solemnity,
particularly that of my beloved friend Rebecca Jones, who with dear George Dillwyn,
had good service; and the meetings, though laborious,
were eminently owned with the extension of divine good,
and Friends were renewedly encouraged to faithfulness in their respective lots.

I sat all the meetings silently,
not without a fellow-feeling and travail with
those engaged in turning the battle to the gate;
but my spirit was so clothed with the garment of mourning,
and the sense of my own insufficiency, that I was ready to say, with the prophet,
"`I will speak no more in your Name.`"
Yet to be preserved in a state of patient exercise,
and in resignation to what might be the allotted
portion of suffering in this day of trial,
was the fervent desire of my mind.
In this frame, I have often known the most sensible incomes of holy help,
and been more enabled from there to bring up stones of memorial,
than when the travail of my soul has been more shallow,
and the streams of the ministry have lain nearer the surface of the people`'s spirits.
O! that, in all seasons of proving, I may never shrink from under that mournful covering,
till the sense of what I am,
and a degree of living faith in the immediate teachings of divine wisdom,
are not only raised, but prevail in my heart; that so, the creature, its wisdom,
and activity, may die daily,
under that power which crucifies all that is of the flesh and sanctifies throughout.

After the quarterly meeting was over,
we were most easy to sit with the Friends of that particular meeting;
where I felt an openness for some religious communication; and it was a close,
but favoured time; nevertheless a degree of sadness remained with me.
After this meeting was over,
and partaking of a cup of heavenly consolation in the family of a relation,
we went down to Anner Mills that night, and next day set off for Dublin,
in order to attend the half year`'s meeting, held in the eleventh month.
It was rather a low time,
but holy help was near (according to ancient declaration) to the poor in spirit,
the exercised wrestling seed, of which, through preserving goodness,
there is a remnant in this land;
with whose tribulated path I have often been dipped into near sympathy,
and was renewedly so at this time: nevertheless, we had unitedly to believe,
that if some of these persisted in unfaithfiilness to the manifestations of duty,
concerning their religious services,
they were in danger of occasioning to themselves such a wilderness travel,
as might prove very difficult for them to be delivered from.
These were fervently and honestly laboured with,
"`to offer to the Lord the sacrifice of thanksgiving,
and to pay all their vows;`" that so,
a generation might be raised up more zealous for
the honour and promulgation of the great Name,
than many of later times have been.
My mind was greatly depressed in this city, and I found it conduce to my safety,
to weigh well what I apprehended to be the motions of Truth.

The meetings were large,
and my beloved companions being not only better qualified for service therein,
but coming from so distant a part of the world as Pennsylvania in America,
and there being little or no prospect of their ever having another opportunity,
of so fully relieving their minds to Friends in this land, I sought for obscurity:
which is always most desirable to my own mind, knowing that safety attends it;
and that it requires deep baptisms, and a close dwelling with the gift,
rightly to minister life, and visit the seed in large mixed congregations.
Without an extraordinary degree of these,
it seldom happens that the appearances of those who are young in experience,
afford satisfaction to the true church of Christ,
or that they reap the reward of solid instructive peace in their own minds.
Often feeling that I am one of these, the prayer of my spirit has been,
that I may be kept under the humbling sense thereof,
and be preserved from burdening the living by being too shallow in my spirit,
or spreading too much into fruitless branches; that so,
the great and excellent cause of Truth may never be dishonoured by or through me.
Infinite wisdom is, nevertheless, to direct and go before us,
in the line of His own appointment:
and under an apprehension of the puttings forth of the heavenly Shepherd,
I ventured to step forward in two large meetings; and through His sustaining goodness,
I was enabled to relieve my own mind in a good degree; for which,
with many gracious assistances, from time to time dispensed,
may my soul bow in humble gratitude and awful fear,
through the continued stages of my tried pilgrimage.

My dear friends Rebecca Jones and George Dillwyn had
great and good service in the course of these meetings;
and Rebecca Jones feeling an engagement to have a meeting with
the women Friends,--none being held for discipline for them at
that season of the year,--after laying it before Friends,
it was cheerfully complied with, and a solid profitable meeting it proved.
Rebecca Jones and myself,
feeling something more than a freedom to sit with a committee of men Friends,
appointed by the national meeting to consider the state of Society,
and complying with it, we were enabled to feel with Friends thereon,
and to lay down our respective burdens.
The evening preceding our leaving the city, and after the meetings were over,
many Friends being collected at our lodgings, we had a refreshing,
instructive opportunity of retirement; wherein counsel and encouragement were ministered,
and Friends parted under a living sense of the
extension of the Lord`'s favour to His church and family.

Next day we went to Baltiboys, a very poor small meeting;
after which we proceeded about five miles further,
intending next morning to set off for Mountmellick;
but when all was ready for our departure, a hesitation sprang, and spread,
respecting the propriety of our pursuing the intended plan;
and the more it was looked at,
the more clearly it appeared best to sit with the few Friends select,
there having been many not of our profession at meeting the day before.
One of our guides, therefore,
kindly undertook to collect the members of that meeting together; which was done,
and we had no cause to repent our stay,
but were rather encouraged to trust in future to the turnings of the spiritual guide,
who requires that we should be followers, and not leaders,
if we pursue the path of true peace.
Instead of going to Mountmellick from Baltiboys, we went to Ballitore that night,
and next day to Athy meeting; then to Mountmellick, Montrath, Knockballymaher,
Ballynakill, and to Carlow to the quarterly meeting for Leinster province held there.
It was a remarkably low time,
and the minds of many were baptized into a feeling sense of the coolness and
indifferency that prevails among the professors of Truth in these parts,
and silent sadness was much our lot.

Intending from hence for Waterford, and the counties of Wexford and Wicklow,
we first paid a visit to the little meeting at Castledermot; it was small,
but divine goodness was near.
My mind, in time of silence, was comfortably gathered from some buffetings, doubtings,
and dismay;
and the language of the apostle sweetly passed through
and settled me in a humble confidence and calm;
"`be patient, establish your hearts, for the day of the Lord draws nigh.`"
We returned to Carlow and next day attended their week-day meeting;
after which we went to Ballydarton, belonging to Kilconner meeting,
which I was prevented from attending by a pain in my head and teeth;
but was enabled to proceed with my companions to Ross next day, where growing worse,
they were under the necessity of leaving me,
after they had sat with the few Friends there,
in order to attend the first-day meetings at Waterford;
where my husband and several of our relations from Clonmel came to meet us.
My Robert came to me, and was a truly acceptable guest, my mind having sunk,
and my strength seeming to be exhausted with the pain.
I was so much relieved as to be able to go next day to Waterford,
to rejoin my beloved friends Rebecca Jones and George
Dillwyn whose company and services have been,
through the course of this journey,
instructive and strengthening to my often doubting mind.
When through the descending of heavenly virtue, my spirit has been cemented with theirs,
and in the unity and covenant of life, a harmonious exercise has prevailed in me,
either in public or in secret,
I have had renewedly to admire the gracious
condescension of our holy Head and High Priest,
in anointing, in any degree, for a work so great and awful,
and leading into this excellent fellowship.

At Waterford we stayed their week-day meeting on third-day, which was a favoured time;
and after having likewise several comfortable religious
opportunities with Friends of that place,
there being a quickened remnant growing in the spiritual life,
we took leave of them under a precious sense of divine superintending care,
and went to Forest, Cooladine, Randal`'s Mills, Ballinclay, Ballicane and Wicklow;
and found an honest-hearted set of Friends,
who are preserved in a good degree of consistency with the principles we profess:
yet there are others who widely differ in this respect.
Our kind friend J. W. having met us at Ballicane,
we went in company with him to Dublin on the seventh-day of the week,
and next day attended their meetings in Meath street and Sycamore-alley;
at both which my companions were silent.
My mind was deeply exercised in them,
and as I perceived some little opening for public labour,
I gave up thereto under many discouraging impressions;
in part the effects of a reasoning disposition,
and unprofitably ruminating on the repeated labours of more qualified instruments,
and the unsuccessfulness of many of them; and in part, I trust,
of a right and necessary jealousy over myself,
lest I should be the means of conveying a lifeless multiplicity of words,
or be found feeding the people, when the divine word might proclaim a fast.
But it awfully sprang in my mind,
that if ever so small a warning was given me to deliver, and I concealed it,
the blood of those for whom it was intended might,
according to the declaration of the Most High to the prophet, be required at my hands.
As this visit to the nation was closing, a secret prayer was begotten in me,
that we might be enabled, as faithfully and willingly to finish the work, as,
through humbling operations, we were resigned to begin it; which,
to the praise of His grace who puts forth and goes before His own sheep,
we were strengthened to do, and had afresh to discover that His ways are not as our ways,
nor His thoughts as our thoughts.

When we apprehended ourselves at liberty to sail from that city,
and had agreed with a captain bound for Whitehaven for our passage there,
the wind proved contrary, and we found it safe to look around us,
that if any little service was omitted, it might then be performed.
This we were ready to think was not much the case,
having attended their men`'s and women`'s meetings on third-day, where,
through divine ability graciously afforded, we had a close, searching,
and humbling season: but now standing in the resignation,
not being detained of ourselves,
several opportunities for public and private labour unexpectedly opened,
generally tending to invite the ignorant,
and to encourage the sincere and drooping minds to faith in
the sufficiency of the gift of God in themselves,
for the sanctification of the soul,
and the necessary supply of every spiritual enjoyment
and qualification acceptably to worship;
which must now, as formerly, be sought for, in the beauty of holiness,
and in newness of life.
The wind proving contrary, we stayed over another first-day,
when my companions George Dillwyn and Rebecca Jones
were enabled to bring up living stones of memorial,
to the sealing I trust of their testimony on the spirits of many;
and my cup of affectionate fellowship seemed to overflow in secret.

The next day a gale rose in our favour, which we thankfully accepted,
and were gently wafted over by it in twenty-five hours,
having had as pleasant a voyage as we could wish for, sickness excepted;
and for the holy directing and protecting power of immortal goodness,
we were gratefully humbled.
We stayed one night at Whitehaven after our landing,
and next day attended their week-day meeting, which was a low time.
Soon after it closed, we set off for Greysouthen,
where Rebecca Jones and I stayed that night.
Our much loved friend and companion George Dillwyn and his wife,
who had been with us ever since we were at Cooladine,
finding it conduce most to their peace to stay the quarterly meeting for Cumberland,
to be held the week after;
and we having a prospect of attending the quarterly meeting for the county of York,
to be held at Leeds; we found the time for our separation was come;
and had to commemorate the kindness of infinite wisdom, in so casting us together,
and cementing us, according to our measures, in the hidden life.
Here we took an affecting and affectionate farewell of each other.

We stopped at Cockermouth in our way to Kendal,
and spent a few hours very agreeably with our friends J. and B. D. and their children;
and before we left them, the spring of heavenly consolation arose,
and refreshed both visitors and visited; and with grateful hearts we set off,
and reached Keswick that night; and next day, having a pleasant ride among the mountains,
we were favoured in good time to get to Kendal,
where my dear companion had an opportunity of visiting J. and R. W.`'s children, who,
since she was there before, had lost their honourable father,
and it was a humbling favoured opportunity.
Finding ourselves at liberty to leave that place,
and Rebecca Jones having passed by Wray and
Bentham meetings when she was that way before,
and now feeling a draft towards them, we went next day, the 24th of the twelfth month,
to Wray, and in the evening had a good meeting with the few Friends there,
and some others who came in.

Next morning we went to Bentham meeting, which was an exercising time,
but ended in awful supplication, wherein my beloved companion was publicly engaged.
Having an evening meeting appointed at Settle, we reached there in time,
and it proved a solid, instructive season.
From there on second-day, the 26th, we got to Leeds,
and there we met with my dear father and mother, to our mutual satisfaction.

The quarterly meeting came on next day,
and held till the evening of the 29th. Through the several sittings thereof,
I had undoubtedly to believe that my companion was in her right place; and was thankful,
under the consideration that we were there in better wisdom than our own,
and were found worthy to bear a share in the weight of sufferings,
which generally attend these large assemblies.
Rebecca Jones being disposed to spend a little time in
rest with our mutual friend Christiana Hustler,
we parted after our quarterly meeting, and I came homewards,
with a desire rightly to feel my way,
whether to continue a while longer with this my endeared friend,
in her religious service, or to give up and surrender my certificate.
For though I had a prospect, when I left home,
of visiting the western part of this nation, to which my certificate was also addressed,
yet if the commission should close sooner than I looked for,
my compliance therewith appears as necessary, as it would be if it should extend further;
seeing that the virtue of all our religious
movements consists in the divine putting forth,
and the continuation of holy anointing;
which we have abundant cause to acknowledge is not at our command.

[.small-break]
'''

First month, 1785.--Though outward separation,
and other circumstances inherent to our peculiar stations,
may sometimes blunt the continual keenness of natural affection;
yet the pure cement of true religious union being more durable in its nature,
and of a more preserving quality, it can never be diminished,
as our spirits become more and more influenced thereby,
and we so transformed by the renewings of the mind,
as not only to prove what is the divine will concerning us,
but to yield obedience to all its requirings.
Under this holy and spiritual canopy are preservation and peace;
and while the carnal mind, and the wisdom thereof is perplexed,
and exposed to almost continual fluctuation and disturbance, they that are gathered here,
not from speculation, or the line of another`'s experience,
but from a living and heartfelt sense of the certainty of divine truth, can acknowledge,
"`we have a strong city`" and that "`salvation is appointed for walls and bulwarks.`"
Oh! that we may more and more know our dwellings to be within this holy enclosure;
for the incorruptible inheritance is nowhere else to be found,
than in knowing the divine will, and doing it.

[.small-break]
'''

Seventh month 1785.--There is a love which I trust is ours,
independent of visible signs, and distinguished by that freedom which the Truth gives,
whether it be in speaking or in being silent.
The substance of true friendship is hidden; and it is not of a corruptible nature,
if we keep it in its right soil.
Though its branches are often cut down by the good Husbandman, yet the stump is fastened,
like that we read of, with a band of iron and brass in the tender grass of the field;
and when we renewedly experience that the Most High reigns, it puts forth again,
and excellent dignity is added unto it.
I feel as I write an affectionate nearness to you;
and oh! may we all so dwell under the dew of heaven,
and the times and dispensations appointed to pass over us,
as that the joy of the Lord may fully become our strength!

[.small-break]
'''

Eighth month 1785.--Perhaps this may find you in some desolate place,
where my spirit salutes you in the renewed feeling of sympathetic affection,
and comfortable hope that, through the multiplied trials of your day,
and of the present journey, you will be secretly supported with the arm of Omnipotence,
and refreshed after many weary steps, with streams of divine consolation;
so that you will still be able to do all things, through Him that strengthens you.

My mind is much with you and your valuable companions,
and sometimes I think I feel a fellowship in some of your sufferings,
not doubting but a measure of them is mingled in the cup of your service:
and why should it not be so, when we consider the tribulated path of the great Master,
and that it is enough for the servant to be as his Master, and the disciple as his Lord.
The wise purposes of the great Potter are not always seen;
there are many things in the process of forming the clay, or a people to his praise,
the necessity whereof is not always manifest to those that stand by;
and I have thought that in the line you are, have been, or may be led in,
some among you may find openings to services,
which not being found in the pages of past experience, may occasion doubts and dismay,
and perhaps a profitable query, has the Lord done this?
yet it is also profitable to remember,
that it is not for the instrument to say to him that uses it, "`what are you doing?`"
I do not wonder at your feelings in being so separated in person from the visible church.
I remember, though in a less degree, similar impressions which have never left me;
and indeed my mind is comforted in finding an increasing attachment to,
and value for the precious fellowship of the brotherhood,
though it is not always found in an entire similarity of prospects,
and of ways and means of prosecuting good, so much as in a uniform,
upright concern for the prosperity of the cause,
which under the shadow of heavenly instruction,
is one of the best cements that fellow travellers can experience.
We should be glad, in our passing along, to find more of it;
and were this united engagement to appear in an
honest search into the real state of individuals,
of families, and of meetings, some of Jericho`'s walls might fall in the contest,
and people`'s attention get turned to desolated Jerusalem.
But it is a land of mists and fogs, yes, in some places, of clouds and of thick darkness:
may that overruling Power which has its ways in the deeps, dispel these temporary things,
and usher in a greater display of pure light, that they who are engaged to work,
and are appointed for it, may work in the light,
and fully approve themselves children thereof.

[.small-break]
'''

Eleventh month, 1785.--I feel for +++_______+++, and wish her an increase of faith,
or a more free exercise of that which she has, that so,
it may fully be accompanied with such works as
the great Father of the family has assigned her;
perhaps both she and I would fare better,
did we look more inward and less outward in our reflections upon ourselves,
and for every future supply of wisdom and strength.
It is surely a wonderful attainment to live by faith;
it is deep beyond human penetration,
and seems to comprehend all that is needful for a follower of Christ to experience:
but the trial of it remains to be more precious than that of gold,
and preferable to the best of our faculties that we can substitute for it.
Poor +++_______+++, she has often felt near to my life.
It is the poor that can most feelingly salute the poor,
and dip with them in their afflictions; go with them to the house of mourning;
and when the holy anointing is poured forth, rejoice together in hope.

[.small-break]
'''

First month, 1786.--I hope that county is by this time profitably visited,
or rather the seed therein,
a place where I once thought it was the hardest
to find--however in myself--of any I was ever in.
But places and persons alter; and where death most reigned,
perhaps life may now most eminently abound;
and life is never more acceptable than when it succeeds a total death, nor light,
than when it springs out of the greatest obscurity.
To dwell with that which teaches to die daily,
and to be preserved from the sleep of carnal death, is an attainment I sometimes covet;
but flesh and blood had rather be sustained with a little of yesterday`'s manna,
and retain a former evidence of life, than undergo, from day to day,
in religious services, the conflicting exercise of being buried in baptism,
though it is blessed with the resurrection of divine virtue and power:
and the reason I apprehend is, because no flesh can glory herein;
it therefore opposes this work,
and the resisting of this opposition with the little strength we have,
truly occasions a continual warfare to the Christian traveller
The present is a scene of conflict and probation;
but when we are strengthened to look over it, to that glorious habitation,
whose walls are salvation, whose gates are praise,
and whose inhabitants no more say they are sick;
there is something so animating in the prospect,
that we are willing to endure all things to attain it.
Let us then take courage in hope, and faithfully endeavour to do our present best.
