== CHAPTER IV.

[.chapter-synopsis]
* Account of her visit to some of the western counties of England.

+++[+++A few months after her return from Ireland,
she felt a renewed engagement to accompany her friend Rebecca Jones,
on a visit to some parts of the western counties in England.
Of the principal parts of this visit, she has left the following journal.]

[.small-break]
'''

After my return from Ireland,
my beloved companion Rebecca Jones being detained in Yorkshire, on several accounts,
for three months, I was thereby set at liberty to adjust some family concerns at home,
and pay some visits to neighbouring meetings as Truth appeared to open the way;
especially to Whitby, Scarborough, Bridlington, Hornsea, and Hull.
My mind was, in the needful time,
mercifully supported with renewed supplies of holy help, though, in general,
in a low and stripped state; fearing lest, in the exercise of the gift,
a zeal which is not according to true knowledge,
nor originating in that baptism of spirit wherein the creature is humbled,
should so mix with the divine openings,
as to carry away the mind from that sate standing in the deeps,
which is justly compared to the bottom of Jordan.
Here, it is necessary for true gospel ministers steadily to abide,
with the weight of the service they are engaged in upon their shoulders,
till the spirits of the assembled are, in some degree, attracted to the promised land,
the new heavens and the new earth, wherein dwells the righteousness of faith,
and where spiritual worship is rightly performed,
in the beauty of holiness and newness of life.
To be instrumental in the divine hand of thus, in any measure,
converting the spirits of those to whom we may be led to minister,
requires an anointing altogether unmixed; but when revolt, backsliding,
and a superficial spirit, have been necessarily unveiled, I have, sometimes,
distressingly found, that some of my armour was carnal;
and O! how has all within me been humbled at the discovery,
that the Lord`'s righteous controversy with the works of
darkness had not been righteously upheld,
nor the door of escape therefrom wisely opened.

An increase of experience convinces me,
that preaching is a mystery which every one exercised therein,
has need to be often industriously and impartially learning,
as far as concerns themselves; and where this is the case, I am abundantly persuaded,
that our dependence must be drawn from the sentiments
of those Friends to whose judgment we are most attached,
in order rightly to distinguish between the unity of the one infallible Spirit,
and their partiality to us, and to be weighed in the just balance of the sanctuary,
where we are sometimes found defective, even when all around us speak peace.

My dear husband accompanied me in this little round: his sympathising mind,
and care for my preservation every way, were truly strengthening,
and afforded frequent occasions of humble thankfulness to the Author of all good,
who had so bountifully provided for me, both in spiritual and temporal things.
After our return home we gave up housekeeping,
not with a conclusion that we should remove from England,
but under an apprehension that it was right to take that step,
as the way opened for my being again united in the
service with my beloved companion Rebecca Jones,
and my husband had no prospect of being settled during my absence.
We therefore removed our furniture, and ourselves to York,
the quarterly meeting there being at hand; after which, the 1st of the fourth month,
1786, I went to Ackworth to meet my companion, who had gone there the day before.

We stayed there on first-day, and found some close and necessary labour,
not only in public, but in private opportunities, among the masters,
mistresses and servants, severally.
The enemy of all good has proved himself busy,
in endeavouring to sow his tares among the good seed in that institution and family;
and unless those on whom the weight and care of it most devolve,
keep in view the necessity of attending more to the holy oracle in their movements,
than to the strength of their own wisdom and understanding,
it will lose the lustre that Truth would put upon it,
and become the nursery of a worldly spirit,
though disguised with an appearance of religious form.
There is in that family a suffering, wrestling seed, an exercised remnant,
which though small, is a means, under the divine blessing,
of keeping open the spring of life; and if such keep their places,
there is reason to hope that more will be added to their number, and,
through the influence of their example, the Truth, in its own simplicity, gain ground,
instead of the disguised spirit of error.

A salutation of love flowed to such, under a sense whereof we left them,
save our worthy friend W. S. who went with us to Wakefield,
where several are under convincement, and some of them appear to be rightly so.
Here we had an open, instructive opportunity; and from there we went to Bradford,
and next day proceeded to Manchester, where we attended their week-day meeting;
in which my companion was greatly favoured to dip into the state of the seed,
and profitably to visit it, and silence was I believe rightly my lot.
From Manchester we went to Stockport, Macclesfield, Morley, and so to Warrington,
to the monthly meeting there; where again I thought my companion had eminent service,
and close searching labour, wherewith I felt a spiritual travail,
and sympathetic mourning over the great carnality, and departure from the way of peace,
which greatly prevail in that and the neighbouring places.
Though there is a peculiar people, and a royal priesthood, in that monthly meeting,
yet as the number in a very different spirit, is great,
the pure life is prevented from circulating, and purifying the temple.
So that the prospect, among the youth especially, is exceedingly discouraging;
dissipation, or the gilded corruptions of human nature, having possession, and,
like the strong man armed, keeping the house and all the goods thereof in peace:
and until a stronger than he, by the spirit of judgment and of burning,
dislodges him of his hold, casts him out, and spoils all his goods,
there is but little room to expect such to demonstrate to others,
by the liveliness of their spirits, the circumspection of their conduct,
and a rightly seasoned conversation,
that they are acquainted with the efficacious virtue of true religion.

From Warrington, my husband returned to Yorkshire, and we back into Cheshire.
It was rather a gloomy parting to me,
being very unwell with a rheumatic complaint in my head,
and more depressed in mind than I was free to express to any;
which is often the case with me,
when under a sense of the awfulness of the work I am embarked in,
of the little effect it has on the minds of many, and of my own exceeding great weakness,
and apparent unfitness for engaging with sacred things;
so that my way oft seems to lie by the valley and shadow of death;
where I feel myself subject to fearful apprehensions, and a deep and gloomy exercise.
Nevertheless, to the praise of the divine grace,
my soul can thankfully and humbly acknowledge,
that through what appeared the smallest grain of faith,
preservation has been experienced, and strength to ascend, in the Lord`'s time,
that holy mountain where nothing can hurt or destroy; because the creature,
and its attendant evils are subjected, and access to the feast of fat things,
and of wine well refined, is graciously afforded,
to the renewed support of the drooping mind, which was ready, but a little before,
to cast away its confidence, and say, "`the Lord has forgotten me.`"
Thus, as by a tender father, are we dealt with, under those proving dispensations,
which are essentially necessary for carrying
forward the work of sanctification in the soul,
and a preparation to receive the inscription of "`Holiness unto the Lord.`"
When I consider the necessity hereof, a fear, on the other hand,
often arises lest it should be partially or superficially effected;
and a fervent craving of spirit, that the refining operations of the Holy Ghost and fire,
may so perform their assigned office,
as that every specious appearance of self-love may be consumed, and the spring of action,
in the performance of both religious and moral duties, rendered pure.
Thus variously, is the attention of the travailing soul turned;
and if the pure discoveries of Truth are but the object singly sought for.
He who created light out of darkness, and has sown it for the righteous, does,
in times of our greatest extremity reveal himself to be the Lord Almighty.

From Warrington we went to Sutton, Franley, Newton, Chester, Nantwich, and Middlewich,
when our visit to Cheshire seemed ended, where, as in other places, we had to view,
and mourn over, the desolation which has prevailed among the professors of Truth;
so that the heathen may query, "`Where is their God?`"
Our next stage was to Leek, and so to Colebrook Dale.
We had meetings both at the New and Old Dale, which were favoured, strengthening seasons;
ability being graciously afforded and accepted,
to sink down deep into suffering with the precious seed;
and a little exercised remnant were found wrestling in spirit for the divine blessing,
who were visited in the renewings of life, and instructive counsel flowed towards them.
Several of the younger sort among them, have been visited by affliction;
the day of the Lord has come upon all that was lifted up, and the projects,
like the ships of Tarshish, which were intended to go to fetch gold,
have been broken early in their setting out, as at Eziongeber,
and all their pleasant pictures spoiled; which has evidently been permitted in mercy,
that their affections might be loosened from things transient and perishing; and,
instead thereof, durable riches and righteousness become their inheritance.
But as this work is great and glorious, and cannot be effected,
save by the humbling processes of the work of sanctification in the soul,
a deep engagement dwelt upon my mind, that those in whom this work is begun,
may be preserved from flinching under it, or taking themselves, or one another,
as out of the furnace, before it effect the great end for which it was prepared;
and that, being redeemed from the superficies of religious experience,
to an entire dependence on the holy purifying spring of immortal life,
they may approve themselves the humble followers of Christ;
and through the efficacy of his own Spirit,
be qualified to advocate the cause of Truth and righteousness.

From hence we went to Shrewsbury, and were at two meetings there on first-day,
which were favoured opportunities; the latter was public,
and a great many of the town`'s people attended.
There are some visited young people in this place,
and a prospect of a revival comfortably affected our minds.
It was here to be determined whether we should turn towards Worcestershire,
Herefordshire, etc., or into Wales,
which was occasion of deep enquiry to find out the good and acceptable way;
and as our minds were single herein, we were favoured to unite in the conclusion,
that it was better now to turn into Wales,
a step we had no reason to repent on any account,
finding a peaceful serenity attending our minds
through the course of a solitary travel therein;
and such a supply of strength to dip into, and visit the seed in those parts,
as was cause of humble thankfulness to the Author of every good and spiritual gift.
His eye perceives the most obscure parts of his own creation,
and graciously shows compassion to His humble suppliant children,
who under a sense of their own needs, are casting all their care upon him,
and looking singly to his bountiful hand for food convenient for them,
both spiritual and temporal,
in preference to the luxurious enjoyment of transitory things;
desiring that blessing which makes truly rich, and whereunto no deadly sorrow is added.

We were comforted in finding a number of this sort in Wales,
particularly at Tydynigarrig and Llanidloes; though, at the former,
among many of their members,
a worldly spirit and lukewarmness about the best things prevail.
We were also at Eskergoch, a very poor desolate place every way; but some solid people,
not professing with us, attending the meeting, were a help to it;
and my beloved companion was drawn in the language of consolation to visit some of these,
who were as sheep wandering upon the mountains, and panting after a shepherd.
It was from this place we went to Llanidloes, where we had a large public meeting,
and from there to Rayadar, a place where there are no Friends,
but where we had a satisfactory meeting among the town`'s people,
in one of the rooms of the inn; and after it went to Pales,
and were at meeting there next day, which was a laborious, searching opportunity,
many disorderly walkers being there.

We then stepped out of Wales, and visited the few Friends at Almilly and Leominster,
in Herefordshire.
The first is very small, having scarce any weight to support a meeting;
but many solid neighbours attending, it was a precious lively opportunity,
and my spirit was humbled,
and awfully reverenced the condescending goodness of our Almighty Helper,
whose lovingkindness is better than life, and the lifting up of His countenance,
than great riches.
The meeting at Leominster was low and trying.
We went from hence to Troy near Mammouth in South Wales: here we lodged one night,
and next morning set off for Pontypool to the quarterly meeting,
which was to be held there the first-day following.
Our dear and much valued friends T. Corbin,
H+++.+++ Wilkins and T. H. overtook us upon the road; we were mutually glad to see each other,
and also to feel each others spirits in the meetings we
attended together at Pontypool and Cardiff,
where we went (after the quarterly meeting was
ended) to attend the Welch yearly meeting there.

My mind, on drawing near to that place, was awfully affected,
in a renewed sense of the important station of a gospel minister, which,
the more my understanding is opened,
the more I perceive it to call for a watchful care to keep in the station,
and to preserve it unblamable, by endeavouring to dwell low enough with the gift,
so as rightly to distinguish between a silent union with the seed in meetings,
(wherein we sometimes sympathise with the concerns of
others,) and our own public service for the cause.
And I was thankful in feeling my spirit humbly contrited,
under a sense of my own weakness,
and the commemoration of infinite kindness in times past;
and I secretly supplicated that the approaching solemnity
might be graciously owned with the virtue of divine life,
immediately imparted from the great Minister of ministers; whereby I felt,
in a good degree, strengthened for my own measure of exercise,
which proved altogether in silence.

But this was not the case with some ethers;
with a few of whom a sense of near unity attended my spirit,
both in a secret travail of spirit, and in the exercise of their gifts;
never that I remember, being so sensible of the purity of that life which,
and which only, quickens services in the church,
and qualifies the centred mind) to judge righteously
concerning public offerings in meetings.
Whatever has a tendency to close up the spring of this life,
by casting rubbish thereinto, instead of industriously removing it, such as the shallow,
superficial judgment of the natural mind, its old experiences and wisdom,
which are held out of the life, can never availingly invite the wrestling soul,
that is panting after the pure milk of the divine word,
to the fountain of spiritual consolation,
or refresh the Christian pilgrim in his journey heaven-wards.
O the purity of that life which is hid with Christ in God!
It cannot be supported but by the flesh and blood,
the virtue or divine nature of the Son;
nor can it unite with that which is not congenial to itself.

There is a ministry which, like the whirlwind, the earthquake, and the fire,
makes apparent effects upon nature, shakes it, throws it into confusion,
and kindles it with untempered zeal;
but proves very deficient in settling it upon the sure foundation;
or introducing it into that rest which is prepared for the people of God,
who cease from all their own works;
or teaching it to distinguish between the voice of the Shepherd,
and the voice of the stranger.
Hence, many, otherwise well disposed minds, have got bewildered,
their attention diverted from the one great object,
and fixed upon sacrifices of their own; which, in time,
are so depended upon for righteousness,
that the hunger which was once begotten decreases,
and the state of the church of Laodicea becomes theirs; growing rich and full,
increasing with goods and in need of nothing;
when alas! though specious their appearance, their situation is most wretched, and,
in the light of Truth, they are discovered to stand in need of everything.
Under these considerations,
my mind is often instructed in the necessity of
confiding only in the Spring of life itself,
and approving nothing as religious, but what comes from it, or is under its preparing,
sanctifying power.
For this end, it is necessary to be very watchful over the activity of self,
that the spirits may be tried, and my faith proved,
whether it is grounded and established upon the right foundation,
or is of that sort that wavers and floats upon any imaginary presentation,
whereby I may be rendered of those who are not to
expect anything at the hand of God.--James 1:6-7.

There are so many ways for the mind, when it is off its guard,
to be ensnared either into sensible darkness, or a righteousness of its own,
which is worst of all, that, when clothed with a sense of my infirmity and weakness,
I mourn in spirit; and am thankful when, in a grain of unadulterated faith, I can say,
"`if you will, you can make me clean,`" and breathe for the blessing of preservation.
From a fear of being instrumental in settling down young people especially,
in the form of godliness without the power;
and urging them to an appearance which might create self-complacence,
and reconcile them to an apprehension that they are further
advanced in the work of religion than is really the case;
I have often forborne to drop such advice upon the subject of dress,
among those who were inconsistent in their appearance, as, sometimes,
I felt the testimony of Truth to dictate;
a departure from true simplicity herein being generally obvious.
At large meetings particularly, where Friends from distant parts are collected,
there is a considerable appearance of inconsistency in clothing and demeanour, which,
with many other things, indicate a love of the world, and a fellowship with its spirit;
but though a regulation herein is only a small part of the fruit of the good tree,
yet it is as assuredly a part, as the more striking constituents of a Christian.

"`Whatsoever is not of faith is sin,`" is a comprehensive truth,
which neither approves an inconsistent, nor a plausible, appearance and conduct,
merely as such;
but wholly condemns every part of our lives which is
not governed by the redeeming Spirit of Truth,
wherein our faith should stand: so that, to attain this state,
to live under the righteous control of divine monition,
is I apprehend to be a follower of Christ,
under whose spiritual baptism the precious is separated from the vile, and by whose fan,
the chaff, to which the vanities of this life may be compared, will flee,
and leave the wheat, for divine protection, in the heavenly garner.

Feeling my mind drawn to a little solid conversation with a young woman,
to whom I had felt near unity,
and whom I believed to be under the preparing hand for service, but diffident in spirit,
and a suitable opportunity offering, I accepted it;
wherein I dropped a little matter by way of encouragement to her,
in her silent steppings and hidden exercises; taking occasion to observe,
that as she had hitherto been preserved, in a good measure,
independent of human consolations, so I wished her to continue,
believing that the arm of Omnipotence was most
eminently revealed to us in this state of singleness,
under such spiritual provings and conflicts as
are essentially necessary for sanctification.
It was a time of mutual comfort, and I was thankful that I gave up to it.

At Cardiff we met again our beloved brother George Dillwyn,
which both he and we rejoiced at.
He was much favoured in several of the meetings, especially the public ones,
which were large; but my dear companion had not much openness for public labour,
till the last opportunity with Friends select;
when she was strengthened to visit the members of our Society in a memorable manner;
which with some, will I trust, be as a nail fastened in a sure place.
In our way from Cardiff to Bristol, to which we were bound,
we stopped at Newport to breakfast,
where my companion and George Dillwyn felt an inclination to have a public meeting,
which was readily complied with, and held in a room in the inn; many came to it,
and it was a favoured opportunity.
We then proceeded on our journey, crossed what is called the new passage,
and reached Bristol late that night.

We met with a hospitable reception from Lydia Hawksworth, with whom we sojourned,
and next day I went with my companion and Lydia to see our beloved, honoured friend,
Catherine [Payton] Phillips, then at J. Hipsley`'s at Congersbury.
She was in a languid state of health,
which in some degree occasioned a depression of spirits, but her best life was strong,
though hid from herself with Christ in God.
She has been a faithful, laborious servant in the church,
especially under the exercise of her gift, which was eminent for its purity,
its copiousness, and clearness; distinguishing the good and evil trees,
by representing their fruits in their true light.
Her ministry had a tendency to raise into dominion the pure life,
and in supplication she has been often wonderfully favoured with near access,
and enabled to cast down every crown, and to ascribe worship and praise,
salvation and strength, to the Lord God and the Lamb.
Since my mind has been graciously visited with a sense of Truth,
such has been my sentiment concerning this great and good woman: but about two years ago,
to my humble admiration in a season of great proving of spirit,
it was so renewed and sealed to me, the inward attraction so strong,
and the evidence that she was a faithful follower of the Lamb, so undoubted;
(a language sweetly flowing through my mind,
"`I have chosen her and she is mine`") that I not only rejoiced, and was strengthened,
but saw the abundant superiority of the unfoldings of Truth,
to all the prepossession we can receive from the experience of others;
my lack of an outward acquaintance with her being thus amply supplied
by the gracious condescension of the Head of the church,
who wisely and mysteriously unites together the large and small members of His body,
and by such connections,
makes them more useful to each other than they know or can of themselves conceive.
Where this union and sense is thus received,
I am of the belief that nothing but a departure from the divine life,
wherein Christian fellowship stands,
can ever alter our inward feelings towards the Lord`'s anointed.

Though I am often dismayed at the sight of things within and without,
and since the time alluded to, have been ready to say in mine haste,
"`all men are liars;`" yet it was matter of renewed consolation and abasement of mind,
that on being in company with our beloved friend, Catherine Phillips,
my feelings respecting her were revived, with sweetness and rejoicing.
But these were mixed with an inexpressible sympathy,
and sense of the buffetings and floods of the dragon, yes,
and of his temptations as in the wilderness; where though she hungered,
yet with unconquered fortitude, nobly resisted every importunity,
to command these stones to be made bread.
Having suffered with her Lord and Master, and been preserved through many temptations,
my secret belief was that life will again arise abundantly in her, and her garments,
even in this state of mutability, be washed and made white in the blood of the suffering,
yet victorious Lamb.
And oh! how did all that was within me bow under this persuasion,
and under a sense that the disciples of Jesus have,
in proportion to their strength and gifts, a measure of affliction to fill for their own,
and the body`'s sake, which is His church.
Here my reflections on myself were exceedingly awful.
I considered that I was just entering the field, unskilled in war,
with the armour but newly put on,
and exceedingly uncertain whether I shall not fall a prey to mine enemy.
But O Lord! teach, I pray you, mine hands to war, and my fingers to fight,
even the good fight of faith, in the sufficiency of your power,
and against every intrusion of my own; that you in all things may be glorified,
and if I perish, it may be at your footstool!

The yearly meeting at Bristol came on, and lasted three days.
It afforded many opportunities for suffering,
and deep exercise to those who travailed in spirit for the arisings of life, which,
nevertheless, for a short season, in several of them, sensibly circulated;
but it seems as if, for lack of vessels rightly prepared,
the current was often turned backward, and retired again into obscurity,
where a baptized number endeavoured patiently to dwell;
among whom was my beloved companion,
who found but little liberty to relieve her burdened mind.
The first-day after the yearly meeting we were at Claverham meeting,
which was a favoured instructive opportunity,
and returned to Bristol to their evening meeting; at the conclusion of which,
my companion had to revive the message sent to Hezekiah, and,
with evident strength and clearness, to apply it to some there.
A young man who was then in the vigour of life, was soon seized with an epidemic fever,
and in a few weeks removed from this stage of mortality;
and several others who took the disorder, narrowly escaped with their lives;
to whom the previous admonition, to set their houses in order, was likewise seasonable.

Next day we went to Sudbury, to the quarterly meeting for Gloucester and Wilts.
Here we found a great lack of true zeal, and love to the cause of Truth,
wherein living members are united in harmonious labour,
and cemented together in the covenant of life;
which preserves from a disposition that would look only to selfish things,
and enlarges the heart in an upright care for the prosperity of others.
From Sudbury we took meetings at Bath, Wesbury, Lavington, Devizes, Marlborough,
and Uxbridge, in our way to London,
being favoured to get safely there the 31st of the fifth month,
which afforded us a few days to rest, before the yearly meeting began.

This meeting opened, to those whose spiritual faculties were have in the Truth,
a field of exercising labour; wherein a steady,
watchful care was necessary for all to keep to their own stations and vocations,
with an attentive eye to the great Master;
as a busy indiscreet interference of his servants,
ever interrupts the beautiful order and prosperity of His work.
The select meetings were to me, as they generally are at our yearly meetings,
(though not all alike attended with life) seasons of deep instruction,
which I was made humblingly sensible could not be the case,
by any capacity of my own to render them so, but by being admitted, however undeservedly,
for a short time, by the Master of assemblies, into the heavenly treasury,
where the saints`' provision, the armour of righteousness,
and the just balance of the sanctuary, are all to be found; and where,
as we deeply and quietly abide, we are furnished with an unerring perception of what,
among the many offerings in the visible church, proceeds from the divine repository,
and what does not; so that individuals thus gathered, though in an obscure exercise,
may say with the apostle, and which I heard revived in one of these meetings,
"`in everything I am instructed.`"

As in the opening of spiritual things,
and being favoured in some degree with a sense of Truth,
respecting the subjects of deliberation which come before these meetings,
the natural disposition sometimes prompts us to
make public remarks consonant with our feelings;
I have, thus far, found it necessary to set a double watch upon this side,
lest I should step forward unbidden to put a hand to the ark,
(the real state of which Uzza saw as well as I) and so, like him, unavailingly labour,
and introduce death upon myself; proving unworthy of an admittance into the treasury,
and of being entrusted with divine secrets.
These are not to be revealed but in the divine will,
and under the sensible direction of the High Priest of our profession;
that the bread which we minister, being given us by Him, may also be blessed, and that,
however apparently coarse and insufficient,
its efficacy and extensive usefulness may abound to those who are fed,
and redound to His praise whose will is our sanctification.

As an attentive care on this hand is necessary,
I likewise perceived a danger on the other, when,
in the simplicity and nakedness of truth,
and consequently unadorned with anything goodly in my own eyes,
a right season has been discovered to express a few words,
and through unprofitable diffidence, and undervaluing the smallness of the appearance,
I have put by these little openings to duty.
This was more than once the case, during the sittings of the select meetings this year,
and which contributed to my own increasing weakness.
So that, while we are desirous to keep our own hearts,
and be preserved from prodigality in imparting our religious feelings,
we ought also to stand resigned to the secret intimations of Truth,
in order to approve ourselves good stewards of the manifold grace of God;
advancing from one degree of favour, acceptance, and communion with him, to another,
and thus become established before him as children without rebuke.

The meetings for discipline of women Friends became exceedingly weighty to me,
as the Friend who was clerk last year declined the office,
and my name was mentioned by several for that service.
I sought to object, under an awful sense of the weightiness of that station,
especially in so large and newly established a meeting,
and with the feebleness of my qualifications for it;
but I soon left all resistance chained down in me, and a secret,
fervent breathing begotten for that holy assistance,
which I knew to be superior to every effort of my own without it.
For though a degree of exertion is necessary,
and the natural faculties of the mind called upon to service,
yet I saw they are no longer instrumental in helping
forward the cause of Truth and righteousness,
than while they are actuated by divine love and life, and abide in the faith,
without the government of which, they are no better than sounding brass,
and a tinkling cymbal.

Under this humbling persuasion I took my seat, having E. T. and S. D. to assist;
and the business of the meeting opened, which proved, in the several succeeding sittings,
a profitable service, introducing women Friends, more generally than heretofore,
into an exercise on their own, their families, and the church`'s account;
for lack of which, great declension from the virtue of true religion,
and the simplicity it leads into, has long lamentably spread among us as a people.
And since, in the turnings and overturnings of the great Controller of events,
a women`'s yearly meeting is established,
and for these last two years has been regularly opened
in correspondence with the several quarterly meetings,
in order more deeply to enter into the state of society, as it is seen in the Truth,
a necessity was evidently discovered from meeting to meeting,
for Friends to increase their acquaintance with the light, which only makes manifest,
and without which our judgment is exceedingly imperfect; and when this is obtained,
not only to work in it, but to work wisely in it,
endeavouring to suppress a disposition which is not
purely intent upon reaching the witness in each other,
even when under the necessity of humblingly displaying that Christian virtue,
of rendering good for evil, and of being willing to endure all things.

Christian condescension is one of the great
wheels whereby the cause of Truth is advanced,
among rightly exercised members, in meetings for discipline.
When a burden rests on the mind of any, which in simplicity is removed,
it adds greatly to its value, and recommends it to those to whom it is offered,
when submitted in the spirit of true meekness,
and no inclination discovered to urge that out of the Truth,
which at first was delivered with the savour of it;
even though it may seem to undergo persecution,
by that wisdom in others which is from beneath, and is carnal;
for a blessing belongs to those who rightly endure persecution, and being reviled,
revile not again.

To discriminate between our own spirits, and a right zeal when contending for the faith,
requires great singleness of heart, and openness to self-conviction,
which I have sorrowfully observed too few arrive at, or dwell in;
and hence we are deprived of an increase in the increase of God,
the fruit-bearing branches not being so effectually purged,
as to enable them to bring forth more good fruit.
O the beauty of the living branches, when they abide in the vine,
draw their sap from the root,
and retain only a holy emulation with each other! a preserving
canopy would such form in meetings for discipline,
as well as worship, and many who are light in their spirits,
resembling the fowls of the air, would be induced to lodge under it.
No boasting, no self-seeking,
no spirit that would rend or tear the tender feelings of any feeble traveller,
could here have any place; because being branches which bring not forth good fruit,
they are cut off and cast into the fire.

But as, in the present mixed state of things, and especially in these meetings,
where Friends are untrained to the public exercise of their gifts,
and unaccustomed to sit under a diversity of sentiments,
occasions cannot fail of being furnished for the trial of Christian virtues,
I was renewedly convinced of the necessity which those who act
in the station of clerks have to be clear in their views,
by dwelling near enough to the spirit of the gospel,
so as to receive qualifications therefrom, in pure wisdom,
to strengthen or make way for that lowly plant which is righteous,
and boasts not itself in the garden of the Lord;
but to which the promise and blessing belong,
"`for all the trees of the field shall know, that I, the Lord,
have brought down the high tree, and exalted the low tree, have dried up the green tree,
and caused the dry tree to flourish;`" yes,
the valleys are exalted and the mountains reduced, when the seed of immortal life reigns,
and sways its pure sceptre in the assemblies of the people of God.

The attention of my mind was, therefore, secretly attracted to the Father of lights,
by whose powerful discoveries I saw myself;
and notwithstanding the business of the meeting almost constantly employed me,
yet I was favoured to feel a frequent abstractedness, and ample opportunities,
under a prevailing sense of my own weakness,
fervently to petition the Lord to be with my spirit,
to keep me patient in my present employ, meek in my demeanour,
and truly a servant to His cause and people.
And I may with thankfulness acknowledge, to the praise of His grace,
which is sufficient for all the needs of His children, that,
however deficient in many respects for the station,
I comfortably felt divine strength and wisdom underneath;
wherein the precious unity of the one spirit, not only with the present,
but several absent friends, comforted my often drooping mind.
Notwithstanding the foregoing observations, the meetings, in general,
were attended with living virtue,
and the humble travailers refreshed and instructed therewith.

After the yearly meeting was over, my husband and I stayed a few days about London,
as did my beloved companion Rebecca Jones,
to whom I still felt bound in the service which she was engaged in;
and therefore set out again with her for the western counties,
the 17th of the sixth month.
We took the meetings of Staines, Basingstoke, Whitechurch, Andover, Salisbury, Rumsey,
and Ringwood, in our way to Fordingbridge,
where the quarterly meeting for Hampshire was held.

It was a time of some degree of favour and encouragement,
to a few honest-hearted Friends in that county;
some of whom are under a renewed visitation of divine mercy.
From hence we went to the quarterly meeting of Dorset, held at Pool;
in which my dear companion was enabled to discharge her
exercised mind of a load which she found there,
in a powerful manner; the state of that county being very low,
the living scarcely able to bear the dead.
We then proceeded to the meetings of Shaftsbury, Marnhull, Sherborne, and Yeovil,
where my dear husband left us, intending for Bristol, and from there to Ireland.
On this occasion,
I felt a secret breathing for the continuance of the Lord`'s protecting providence,
both with respect to the safety of the body,
and the preservation of our minds in His fear, and an increase in His favour.

From Yeovil we went to Puddimore, Longsutton, Ilminster, Chard, Bridport,
and so to Exeter, where we found, as in some of the foregoing places, a few innocent,
concerned Friends;
but the lack of that baptism which initiates into the church of Christ,
and builds up the members into a spiritual house, a holy temple in the Lord,
where He presides and ministers, was sensibly felt;
and yet the language of encouragement to press forward to this state,
appeared to us to be the language of Truth.
In general, the spirit of the world, though often disguised, so much prevails,
that before the right foundation can be discovered,
a specious pile of buildings needs pulling down;
and therefore for ministers rightly to visit meetings and individuals in this state,
requires soundness of judgment, strength in the pure faith,
patient perseverance and righteous zeal; all of which, when I see myself,
I feel the lack of.

[.small-break]
'''

+++[+++The following passages are extracted from her letters:]

[.small-break]
'''

9th of the seventh month 1786.--As I trust our alliance to each other in spirit,
is stronger than the ties of nature, it is not, we may conclude, inconsistent therewith,
to impart to each other without straitness,
in the circulation of mutual love and renewed sympathy;
for without this quickening experience,
all our communications must be lifeless and insipid.
How excellent is the life of Truth!
The lack of it in myself, and in others, is a daily burden to my mind;
and the burden bearers, in places where we come, being very few,
renders it still more heavy.--To say that the state of
the Society is low in these western parts,
is so general and so just a complaint,
that there is a danger of its being taken up without
feeling sufficiently the spirit of mourning.

[.small-break]
'''

13th of the seventh month 1786.--We endeavour quietly to get forward;
and by the continued sustaining evidence,
that the best strength is graciously near to assist in the needful time,
and the blessing which makes truly rich, sometimes revealed in the midst of our poverty,
we are preserved thus far,
in a degree of thankfulness to the great Supplier of all the necessities of His people;
though often attended with the spirit of mourning over
the scattered remnant of a once flourishing heritage.

Though in some places there is but little to visit,
yet not being a people wholly given up to reproach,
and the pure seed still groaning for deliverance, a little room is left to labour;
and here and there an exercised member dwells, with whom, whenever they were found,
our minds could not but dip into near sympathy; so that any little opening to service,
in such desolate places, ought not to be declined, but rather cherished in confidence,
that the good Husbandman will again plough and sow His plantation,
and bless the labour of those He puts forth.
I cannot say that this is an expectation which has abundantly attended my mind,
in our passing along; but, just as I write, a little hope is renewed,
that the vineyard will again prosper by a right and necessary extirpation of the briars,
the thorns, and noxious weeds; and, by a holy cultivation,
be prepared for the true plants, wherever scattered,
being enclosed within divine protection, and rendered fruitful in holiness,
so as to be fitted to receive the heavenly Visitant,
and made able to endure the northern and the southern blasts.
O that this hope may not perish, but prove true in a future day,
when the earth is shaken of her rest!

We stayed their first-day meeting at Exeter, and then went to Kingsbridge,
taking a little meeting at Newton Bushel in our way, and to Plymouth,
where we attended their monthly meeting; which is in so weak a state,
as to be far short of supporting the dignity of Christian discipline in its own spirit;
and this is lamentably the case in many other places.
It is only as the gathered churches become sensible of their deplorable situation,
look beyond their own natural abilities, to the well of life in themselves,
and get low enough to draw water thereout,
that a restoration of the power will be witnessed, which is Jesus in the midst of them.
We also attended their meetings the first-day following, which were deeply exercising;
but our gracious Helper was near, strengthening to an honest labour;
wherein the right way to the kingdom,
was proved to be widely different from that wherein many are walking;
and under this help, a degree of holy solemnity was felt.

[.small-break]
'''

+++[+++In addition to the preceding journal, which appears to be left short of the visit,
the following extracts have been made from her letters; which,
though not containing a regular, continued account,
may afford further information and instruction.]

[.small-break]
'''

The present journey with my beloved friend has been a fresh
trial of the uprightness of my desire after dedication;
for after returning from Ireland, I earnestly sought quietude and obscurity,
to settle down among my valuable connections and enjoy their society,
or the benefits of solitude;
but the reward of peace was not the attendant of these prospects;
nor did the cloud appear to rest upon my tabernacle; the words,
"`Time is short,`" were deeply inscribed upon my heart,
so that one thing or other bid me take a few more steps
in the tribulated path of gospel obedience.

I have felt myself these few days back, as near the end of my present commission,
my faith, patience, and every Christian virtue, as to the point of land before us;
and being so far from home, aggravates the prospect,
and gives me very much the feeling of a pelican in the wilderness,
out of the reach of almost any other help,
save that holy Arm which leads about and instructs,
in what appears to us the most deserted situation,
and moreover has promised to keep as the apple of the eye.

Could I believe myself to be one thus provided for,
and to whom the arm of power will continue to be extended,
some of my secret cogitations would be less painful and gloomy,
and with greater pleasantness, I could advance, though in a tribulated way.
From Plymouth we came into Cornwall, taking Germains, Looe, Liskard, Austel,
and Mevagessey meetings, in our way to Falmouth, where, and in its neighbourhood,
we have met with some valuable Friends.
In these western counties through which we have come, namely, Hampshire, Dorsetshire,
Somersetshire, and Devonshire, the Society,
as to the circulation of that life which we profess to be seeking the influence of,
is indeed lamentably low.
A worldly spirit and a state that is neither hot nor cold, greatly prevails;
so that the few living members (for there is here and there
one) are scarcely able to lift the standard of Truth,
or revive the remembrance of the law.
But in this county Cornwall, things are better; a right zeal having sprung up in many,
to search into the real state of the church, and what is more,
a care first to search themselves;
an exercise greatly lacking among active members in many places.
Catherine Phillipps`' labours in these parts have been, we think, eminently blessed;
and the good effects of such a faithful discharge of duty,
and bearing a steady uniform testimony to the Truth, and against error, would,
there is no doubt, oftener be found, if that was oftener tried.
We get but slowly forward since we came into this county;
for though I have mentioned some good in it, yet we find it close exercising work,
to get clearly down to the good thing alluded to;
and have stayed longer in places hereabouts, than any where before.

Yesterday was trying to my almost worn out mind;
my companion got a little relieved in the morning,
but I saw no way for myself all the day, though under a great weight; but so it is,
we need patience and subjection in such times,
lest we move before the waters have risen to their appointed height.

We have been favoured to get along without accidents,
and have to acknowledge that many ways, we are helped beyond our frequent expectation;
finding, as we suppose others do, discouragements on the right hand, and on the left;
which, if allowed to prevail,
would soon destroy that little grain of efficacious faith which removes mountains,
and without which, however we may labour and waste our strength,
such mountains of difficulty and unfruitfulness, as the Christian traveller meets with,
can never be removed.
How necessary is it then to fight the good fight of faith: that so,
when pure life is circulating, instead of knowing it not,
we may be strengthened to lay hold of it,
and to experience the inner man so renewed in us, as to actuate every service.
Here we see our own insufficiency,
and how unavailing it is to depend upon our strength and judgment,
in things belonging to ourselves or others.

I have been at meeting this morning at Collumpton,
a small gathering of lukewarm professors, in the general;
but a few solid young people afforded a comfortable prospect for the future.
Silence was my lot here; but my spirit was deeply humbled,
in feeling the baptizing virtue of truth near to purify my vessel,
which I esteem more than the fairest qualifications for public service;
and am more and more led secretly to supplicate the increase of this solid experience,
and ability to endure with Christian firmness and
patience those dispensations by which it is obtained.
Nevertheless, I am often deeply tried in religious meetings,
with such exceedingly great strippedness of good,
and intrusion of thoughts which I by no means approve there, that I mourn under it;
and when anything opens, which appears like a discovery of Truth,
to give it to others when I am ready to perish with hunger myself,
is almost irreconcilable; especially when after giving up to it,
I find myself as poor when a meeting breaks up, as when it began.
I can hardly describe what I secretly suffer from meeting to meeting on this account;
so that when I am favoured with a sensible evidence,
of the sanctifying power of the Minister of
ministers yet dwelling in mine earthen vessel,
abundantly does my soul acknowledge, that the excellency of the power is not of us,
but of Him, and that He has a right to reveal it when and how he pleases.

[.small-break]
'''

+++[+++She attended the circular meeting at Gloucester, in the ninth month;
from which she returned pretty directly into Yorkshire,
and was at the quarterly meeting for that county.
In the forepart of the tenth month,
she proceeded with George Dillwyn and others to the county of Durham,
and attended the quarterly meeting there.
Of these services no remarks can be added,
as there does not appear anything material of her own preserved on these occasions.
The following extracts from other letters are also instructive and interesting:]

[.small-break]
'''

Fourth month, 1786.--We have often conversed about Friends in Ireland,
and felt the glow of true love therein; which, though not much expressed to themselves,
is yet a living spark in all our breasts, which many waters cannot quench;
nor will long separation be able to erase those
epistles which are written by the finger thereof,
and in which there is a liberty sometimes allowed for the spirit to meditate,
with a degree of strengthening consolation, especially when,
by the clearness of the characters, we find one another as fellow-pilgrims,
travelling after the resurrection of pure life,
and making steady advances towards that city which has foundations.
Upon this object I sometimes fix my eye, with renewed resolutions, through holy help,
to press forward through the difficulties of the present scene,
and to count all things but as dross and dung that I may win Christ, and be found in him;
not having on my own righteousness, but the righteousness of faith in Christ,
that thereby I may attain the resurrection of His power,
the fellowship of His sufferings, and be made conformable to His death.
The spirit is willing thus to endure, but the flesh and its inherent propensity to ease,
creates a warfare, wherein I sometimes fear,
the natural and best life will entirely fall.

[.small-break]
'''

Fifth month,
1786.--We are sometimes like pilgrims whose faith and patience are at a low ebb I
and were it not for the gracious condescension of Him who regards even the sparrows,
and whose arm of everlasting strength is underneath in seasons of drooping and dismay,
we should be ready at times to faint;
but it is the renewings of holy help that become strength in
weakness to those that put their trust in if;
and is a present sufficiency when we are not able to provide for ourselves.
May you be fully grounded in this trust, that thereby,
in times of discouragement and sifting, your stability may endure,
and your experience increase in the knowledge that all things work together for good,
to those that truly love the appearances or manifestations of the divine will.
I believe you know that I dearly love you, and, I may add,
have felt sweet unity with your spirit;
and therefore hope ever freely to pour into your mind any
little hints which may in that love revive towards you.
And now, as you have put your hand to a good work, let me say, look not back;
and when the certainty of your being rightly anointed for it is withdrawn,
which is no uncommon trial,
look not then to the sentiments of others for support and encouragement;
but labour after true quietude and patience of soul, whereby you may,
with comfortable assurance, in the right time, have your head raised in hope,
and your growth in religious experience be less superficial,
than I fear is often the case even with those
who have been put forth by the heavenly Shepherd.
There is no consolation, no confidence, wisdom, or strength,
like that which proceeds from the deep and hidden spring, whereunto we must learn to dig,
if ever we are rightly grounded in the work of sanctification:
and as the divine will is our sanctification, if we obey it;
be not slack in surrendering yourself thereto.
I write not these things from an apprehension that you need them more than others,
for my sentiments of you are very different;
but I wish you to set out independent of any instrumental help,
except that which is sent from the fountain of purity;
and to look to no example further than it is consistent with the holy Pattern.

[.small-break]
'''

Seventh month, 1786.--I remember it is said,
that even "`when the sons of God met together,
Satan came also among them;`" so that if he did so again, it was no new thing;
and we are instructed by the angel how to deal even with him;
not to bring a railing accusation, but patiently, and with Christian fortitude,
to commit the great cause to that power which can protect it, and rebuke the adversary,
but not in our way, and in our time;
for it is in general most eminently displayed when the creature is reduced,
and nothing left:
in us that can boastingly exult even over Satan
himself To behave ourselves wisely in the church,
humbly and watchfully to fear meddling with things too high for us,
things into which our minds are not renewedly baptized,
is a care which I wish we may ever preserve; for herein a godly jealousy over ourselves,
and our own spirits,
will help to centre us in that meekness for
which the paths of true judgment are appointed,
will give a right feeling of what is opposition to the Truth, and what is not,
and how to use the armour of light, which,
when rightly put on in meetings for discipline, unfolds the simplicity of Truth,
and discovers the pure,
disinterested foundation of those who are engaged to contend for the faith.
It is becoming the nobility of the cause of righteousness,
to see its warriors so unfeeling of personal opposition, as to return good for evil,
and patiently to endure all things, seeking an opportunity to bless,
by candidly opening each other`'s understandings, and then generously forgiving.
There is no doubt, but that, in our Society,
if the root and ground of Christian discipline in ourselves were attained to,
and abode with, meetings for the promulgation of it in the general,
would be more owned by their members being baptized by one spirit into one body,
and more crowned with that life which is peculiarly in reserve for those,
who have been faithful to the death of the cross in themselves.
I am often humblingly convinced, that whatever I do in the sacred offices of the church,
if it be the fruit of speculation, a lively imagination,
or only a desire to render myself useful, however suitable it may seem,
yet not proceeding from some little influence of the holy anointing,
which lets me see myself with others,
it is sure to leave a painful corroding sense upon my own mind,
which I am afraid I have sometimes charged others with being the cause of,
rather than myself Thus danger appears on every hand, except we are watchful and humble;
but "`the humble the Lord teaches of his ways,
and the meek he guides in the paths of judgment:`" "`your
gentleness (said David) has made me great.`"

[.small-break]
'''

Eighth month,
1786.--I see abundant occasion to watch the spring in
myself from which my rejoicings and depressions come.
Self is a subtle enemy,
insinuating itself into the company of the purest intentions and approved services,
claiming a share of their peace and of the spoil of the
most righteous victories over every enemy but itself.
A furnace, however, is wisely prepared for gold,
where this dross discovers itself by separation;
so that if we are zealous enough to get rid of it, we must frequently retire to the test,
submit to whatever degree of purification the great Refiner sees fit,
and cheerfully endure hardness under his gracious protecting power; for,
according to my experience,
I take this redemption of the pure life from all self-seekings,
to require the closest combat, and most intrepid perseverance of a Christian,
in order to gain access to that river which makes glad the city of God,
and to inherit the promises of the gospel in their own purity;
where the edge of many sorrows and trials is blunted,
when they have nothing to strike at but holy humility.
O it is a blessed experience which my soul fervently craves!
I sometimes think I gain a little ground towards it,
when a discovery of its animating glory, substantial feeding, and impregnable defence,
is made to my understanding; but,
on finding how little capacity I have to receive things genuinely divine,
the acknowledgment is readily made, that I know nothing as I ought to know,
which is only attained by an experimental growth and establishment therein;
and yet short of this I sometimes desire to find no rest.

[.small-break]
'''

Tenth month, 1786.--Experience teaches us,
that it is not always we are capable of even enjoying
that good and profitable communion which,
by virtue of the key of David,
is sometimes opened for our present refreshment and encouragement,
in our path of deep proving and frequent dismay; much less of so resting in it,
as always to be ready for the expression of those things which are not at our command.
I conclude you know that has been sometime in a low depressed situation of mind,
but her company had a savour in it, of which she herself was not sensible,
as is generally the case with those who are under the
most unmixed dispensations of purifying virtue.
That state wherein all sense of comeliness is taken away, and under which we are clothed,
as the prophet Daniel thought himself, with corruption,
is that which appears to me the most acceptable,
and no doubt is the best prepared to receive the language of, "`arise,
you that are greatly beloved of the Lord;`" the chastening of these having been seen,
and their many mournings heard, by the gracious ear of the Lord of Sabaoth.

How different would things be among us as a people,
if all those who wish to be considered as under the divine forming hand,
and who are ready to step into service, were but enough emptied,
and their beauty stained in their own eyes! many spacious
buildings on a sandy foundation would then be thrown down,
and there would be more exercise and care in searching for the immovable Rock of ages,
which really in many places seems grievously neglected.
My prospects are often mournful when I look at myself;
there weakness and inexperience in some necessary refinements are sorrowfully manifest;
and on taking a view of the state of the visible church,
we see many of its members so diseased that they cannot perform their allotted functions,
nor edify the body, though they retain their places there:
the redeemed sanctified church how small! and in what a wilderness state!
So that to look at ourselves, at the degenerate, or at the preserved, church,
ministers discouragement,
and shows us the necessity of turning our attention another way; inward,
instead of outward,
and there waiting for the renewings of that power by which the worlds were made,
and receiving supplies for spiritual needs at the first almighty Hand.

[.small-break]
'''

First month, 1787.--Your joint affectionate salutation came duly to my hands,
and with the sympathy expressed in it,
afforded me a little of that consolation which
the drooping mind sometimes longs to partake of,
when meditating on its own weakness and unworthiness of the
renewed proofs of friendly regard and Christian fellowship.
It is pleasant indeed for brethren to dwell together in unity;
and O that in order to retain this mark of discipleship,
our eye may be single! for this leads to a communion still more excellent and pure,
than that which we enjoy with each other in this mixed state of things,
even a communion with the light which discovers all things,
and is the life of those that believe in it.
Yes I do know your path, and that it is a tribulated one:
may you run your race therein with patience; for "`tribulation works patience,
patience experience, and experience hope, and hope makes not ashamed,
because the love of God, (and not of ourselves) is shed abroad in our hearts.`"
Here is a foundation which the gates of hell cannot prevail against, and which,
as we keep to it, will preserve us from being soon shaken in mind,
or troubled with those changeable things,
which in the course of our pilgrimage may befall us.
I hope you will continue to keep in your remembrance a poor little sister,
beset with many discouragements, and sifted with many fears and doubtings,
particularly respecting our future movements;
for I endeavour what I can to leave the things that are behind.
