== CHAPTER VI.

[.chapter-synopsis]
* Her concern respecting a Boarding School for female youth
* Visit to Friends families in Cork
* Journey to London
* Visit to Dunkirk, Holland, Pyrmont, etc.
* Her return
* And decease
* Testimonies concerning her.

+++[+++It may now be proper to take some notice of a concern
which had weightily engaged her attention,
respecting the propriety of opening a boarding school at Clonmel,
for the religious care and education of female youth.
This subject had, for some time, been deeply pondered, both by herself and her husband;
and had, at length, so matured in their minds,
as to afford an evidence that it would be right to set forward the work.

Their motives for this undertaking appear to have been purely disinterested,
and with the single view of promoting a guarded and religious education of children;
being themselves in easy circumstances,
and under no necessity to pursue this employment for family support.

When we consider the susceptibility of youth to early impressions,
with the general permanency thereof on their minds;
and reflect that they are soon to participate in the concerns of life, and will,
in a few years, be the principals on this stage of being;
we cannot but perceive the extensive importance, both to individuals and the community,
of an early moral and religious education;
nor be surprised that this earnest labourer for the good of mankind,
should feel it her duty to cultivate this ground of general reformation,
and to encourage others, upon pure principles,
to engage in an employment so truly honourable and productive of good.

Though under doubts and discouragements of mind,
arising chiefly from the humble sense of her own weakness,
and lack of qualifications for so arduous and important a service,
she was enabled to open the proposed institution,
the month after her return from the continent.

She was much concerned that the children committed to their care,
might be preserved in innocence, and trained in the paths of piety and virtue;
and when not called from home on religious service,
laboured faithfully in advancing such measures as tended to
promote the solid advantages of this institution.

On the subject of this school,
there does not appear to be much remaining written by herself: a few of her letters have,
however, been collected,
expressive of her tenderness lest she might interfere with other institutions;
and of her cautious stoppings in this concern; with several other instructive sentiments;
most of which have been extracted, and are as follows:]

[.small-break]
'''

The prospect of removing to Ireland in any line, continues to my mind very awful;
and undertaking a matter of so much consequence as the proposed school, is not less so:
but if our friends whose judgments we esteem, feel uneasy with it,
and freely express themselves, it will rather be a relief than a disappointment;
especially as we have no intention of getting, or saving money by it to ourselves.
If we are but favoured to see the work of our day,
and found faithful in the performance of it, though ever so humbling to flesh and blood,
I sometimes think, it is all that I desire.

I do not like the thoughts of crowding new institutions upon Friends, imposing objects,
or doing anything which has the remotest appearance of
opposing our own or others`' prospects,
by dividing or scattering the little strength, which, if put together,
might prove no more than sufficient for one undertaking at first; though afterwards,
it might increase for whatever further openings might be perceived in the Truth.

I have, at times,
been much depressed with a fear of interfering with the school at Mountmellick,
and discouraging the valuable Friends engaged therein.
I felt most easy to write them a few lines, with a view, as I tell them,
"`to open a door for a free communication of sentiments,
respecting what we both have in view;`" expressing my love and esteem for them,
and belief, that as both they and we are disinterested in our views,
desirous of promoting the same cause, and rightly directed, we shall move,
either separately or together, with a comfortable degree of unity and sympathy;
and requesting their openness with me, in saying whether anything has occurred to them,
on hearing of our plan, which would be any strength or encouragement to them,
and which is in our power to afford;
whether they wish us to be united in our undertakings,
or think that two schools will answer; and lastly,
whether they do not think it will be better for
them steadily to pursue their own prospects,
till our house is opened, (if ever it should be) and then to stand resigned,
either to unite or keep separate, as at that time appears best.
So much seemed a little relief to myself to say,
feeling great affection and tenderness towards them;
at the same time that my own faith is nearly tried.
I, however, feel a hope as I am writing, that if our offering is not accepted,
but proves like David`'s proposing to build the house, that, nevertheless,
we shall feel that secret supporting language, "`you did well,
in that it was in your heart, etc.`"

Do you not wonder at the undertaking we have in view?
My dear Robert has kindly condescended to make ample
preparations for a boarding school for girls,
and has built a considerable addition to our present dwelling;
which stands upon an island, in a navigable river called the Suir.
It is about a hundred yards across, and near a quarter of a mile long;
has on one side of it the quay and town, and on the other, cultivated mountains,
which seem almost to hang over it.
The prospect from the front of the house, is through the garden and a pasture,
to the river and valley, and is terminated by a very high and rugged mountain,
several miles distant.
The place is altogether very commodious, and pleasant for the intended purpose;
but how we shall meet with suitable,
disinterested persons for undertaking the immediate care of the children, etc.,
is not clear; a hope however cheers us, that if our views are right,
and deserving a blessing, all things needful will be afforded us in the needful time.
I should like to have such, for almost every station in the family,
as possess a sincere concern for the prosperity of the work,
and find a dedication in their own hearts to it: being afraid of drawing any,
merely to gratify ourselves,
that have not some such foundation to support them in seasons of trial, which generally,
more or less, attend the most upright and disinterested designs.

I have had a very low dull time of late about this undertaking,
from a fear that we shall not be found equal to it.
I do not mean in the sight of men, for probably we could not please all,
let us do ever so well;
but I mean in the sight of Him whose blessing is more craved and panted after,
than the most specious appearance it can wear.

Having formerly mentioned the discouragements of my
mind in the setting out of the school we are engaged in,
it is but just also to say, that things respecting it now wear a pleasanter aspect;
with a hope that that which was sown in weakness, seems, through divine help,
for to that only it can be attributed, rising into greater strength.
The minds of some of our precious charge are evidently increasing in verdure,
by the dew of heaven; and, in the general,
innocence is to be felt from the influence of their spirits.
Our helpers also grow, we hope in the root of true religion.
Indeed, did the world, or our religious and civil concerns with its inhabitants,
speak no more trouble to us than what we find upon our little island,
it would be too great a state of prosperity for
human nature profitably to be indulged with;
for even that calls for a watchfulness and industry, which the flesh is at enmity with,
and in which I fear being found lacking.
To feel an evidence that we are under the care
and blessing of the Shepherd and Bishop of souls,
after conflicting doubtings respecting it,
is such a cordial as reanimates the soul to fight the good fight of faith,
and to lay hold on eternal life.
In seasons of favour this has been the case;
but it is hard to lay down all these precious gifts, still to walk as the Master walked;
to testify, by our dedication, that we believe that he came to save sinners,
and as to the means whereby his glorious work is promoted, to say, "`not my will,
but yours be done.`"

[.small-break]
'''

Eleventh month, 1788.--We have twelve girls, and expect more soon;
so that you will believe cares multiply upon us;
but all our endeavours will be ineffectual, both in this, and all other undertakings,
except the blessing which makes truly rich, in unmerited mercy, rests upon them.
Did the world know,
how dependent all substantial comfort and permanent joy are upon this heavenly gift,
people in general would toil less, think less of their own wisdom,
and more simply follow that day-star which arises in the heart,
and directs to the pure life, in which the Father is well pleased,
It is a comfortable belief to my mind,
that you are arrested by this precious principle of divine light,
which discovers things as they really are.
Be not afraid to be led by it, into ways you know not, and into paths you have not seen;
for, in due time, it will dispel the darkness before you,
and make crooked things straight.

One of the most beautiful, though most abasing dispensations,
in the true Christian progress, is that of becoming as a little child;
the judgment is here taken away for purification,
and to be made truly useful in the Lord`'s work,
the soul breathes only to the parent for food, and depends upon no other for counsel.
It is generally weak, but knowing itself so, it is safe.
O happy state to be rightly brought into! may we never be ashamed of it,
but for our encouragement remember, that of such is the kingdom of heaven.

[.small-break]
'''

1788.--Self-gratification in our own way and time,
has not been allotted us for the path to solid peace;
and if increasing humiliation should prove the food most convenient for us,
we wish to accept it from that Hand,
which has an indisputable right to do with us as
seems good in the sight of infinite Wisdom,
and which has power to convert the greatest trials into true spiritual refreshment.

The ways of infinite Wisdom with those He chooses to bring through and
redeem from the fallacy of human understanding and corrupt nature,
are so incomprehensible and humiliating, as indeed put us out of the capacity of saying,
"`what are you doing?`"
for who has been his counsellor?
seeing he gives not account to any of his matters,
till the simplicity of a babe in Christ is attained unto, when he reveals,
according to his purposes, those mysteries unto them,
which are hid from the wise and prudent.

That junction between the monthly meetings is comforting`',
if only from the strength which the few living members may be
permitted to feel in the unity of one another`'s spirits,
and the blessings which may be upon their endeavours to wash one another`'s feet,
and to bear up one another`'s hands.
That love which has heretofore flowed in my heart as a river,
to the poor in spirit on that side the county, sweetly revives as I am writing,
under a renewed hope, that the eternal Fountain of life will not be closed among them,
however low and unworthy they may sometimes feel themselves to be,
of its pure refreshment.
And if it be in abundant mercy kept open,
and they that are acquainted with it gather to it, having their qualifications from it,
and use them under its influence, they will be a blessing one to another,
and more may be gathered to an inward experience of the same purifying anointing, than,
in some seasons of discouragement, they have an idea of.

[.small-break]
'''

+++[+++In the twelfth month 1788 she engaged, with other Friends,
in a visit to the meetings and families of Friends in the city of Cork;
and during her employment in that service,
the following letters appear to have been written.
Though they do not express much account of the visit, yet they may be acceptable,
from the instructive remarks they contain,
and the weighty and concerned spirit which they manifest under this engagement.]

[.small-break]
'''

We have been steadily engaged with sitting in four families a day;
and though we often seem ready to give up, and feel like imprisoned spirits, yet,
upon the whole, we have no just cause to be discouraged;
best help being near to strengthen us with might in our inner man,
or such a proportion of it as is necessary for the performance of, and perseverance in,
the work of the present day.
As doing the will of our heavenly Father, is the only thing really worth living for,
I wish to consider it as an unmerited favour, to know what that will is,
and to be furnished with any degree of capacity to do it.

The season of the year, the closeness of the city,
and the complicated occasions of heaviness and depression,
in the view of the state of things here,
all contribute to suffering both of body and mind;
so that were we clear of unprofitably adding thereto,
we do not lack a pretty full cup thereof Indeed we have no
business to seek for a portion or baptism differing in nature
from that which the great Pattern himself submitted to,
and which the true seed here and elsewhere, have still, for wise purposes, to experience.

Whether any good may come of our labour and travail here, must be left:
it is the blessing only which can render this,
and every other endeavour of the poor servants,
effectual to the building up of any drooping member in the most holy faith.
My soul has in the course of our visit to the families of Friends in this city,
passed by the gates of death.
But the deceitfulness of my own heart is such,
that it cannot be removed by pleasant things;
nor does fitness for the little services we are engaged in,
spring out of the most sensible and gratifying operations of the spirit;
but out of these unsearchable baptisms, which, nevertheless,
demonstrate they are of the Holy Ghost and fire, because they leave an empty temple,
a temple ready to be filled with that presence wherein there is life.

According to my small knowledge of good, I may assert that, after all,
the joy of the Lord is our strength; and were it not that,
in the beginning of this visit, my spirit had been sweetly comforted therewith,
I very much doubt whether, from many of my feelings and deep provings since,
I should have held out till now: peradventure it possessed some of that sacred efficacy,
which Elijah`'s forty days sustenance is distinguished for, and thereby,
to the praise of that grace, by which I am what I am,
my confidence has not wholly failed me in the deeps.
All that is within me prays, that as we have been mercifully strengthened to drink,
in this place, a bitter cup, we may not, in our own wills,
refuse any dregs which in infinite Wisdom are intended, in part,
to constitute the cup of salvation.
But the flesh is weak!
A few have refused us, and whether their hearts will relent, is yet to try.

We cannot but sympathize with a tried, afflicted remnant in this meeting,
whose hands I do believe will grow stronger and stronger,
be more and more instructed to war, and their fingers to fight.
However the boasters over the pure lowly seed may exalt themselves,
yet they cannot stand in the day of judgment, nor prevent the fulfilling of the promise,
that the law shall be magnified and made honourable.
I concluded to stay third-day meeting; and though, as is often my lot,
speaking to men did not relieve my inward oppression,
yet in prostration before the almighty Helper,
who in abundant mercy is touched with a feeling of our infirmities,
there was a secret sustaining evidence of living again in His presence,
whereby those bones that were broken did rejoice.
Thus are the poor of the flock helped in their extremity,
and encouraged to maintain their confidence in the
Omnipotent gathering arm of Israel`'s Shepherd.

[.small-break]
'''

Twelfth month 1788.--We have been sitting in a Friend`'s family,
where +++_______+++ demonstrated that her mind, through all these storms and tempests,
has found where to anchor and unload her vessel,
with an increase of simplicity and obedience.
I wish she may now leave the things that are behind;
and that we may all become more and more, not only as children, but as weaned children.
To be reduced to this humble state, has not only its mortifications, but its joys.
The Christian`'s life consists not in the abundance of the
apparent consolations and gratifications he possesses;
but in the renewal from time to time, of the hidden manna which the golden pot contains,
within the veil of perishing things.
You know enough of such situations as ours,
to make you believe we are not without a portion of trials,
no doubt wisely proportioned to us; yet I dare not complain,
having thus far as we have passed along, found Him whom my soul loves,
in whose presence no murmuring has a right to appear.
Childlike simplicity is an experience which every chosen servant, however feeble,
ought to endeavour for.
We get nothing by the contrary; for by ever so much taking thought,
we cannot add one cubit to our stature, or make one hair of our head white or black.

May you proceed on this family visit, in the faith, nothing doubting.
It was not the abundance of bread, nor yet the fineness of it,
which fed the multitude formerly.
For lack of faith, we lose many miracles which the blessing would still effect.
Remember poor David`'s sling and stone, and out of whose mouths,
strength and praise are ordained.

[.small-break]
'''

Twelfth month 1788.--I received your affectionate sisterly salutation, which,
like a little help to the weak and feeble, was salutary and acceptable.
Be assured I am one of the weak and feeble; may I therefore be wise enough,
like those little creatures spoken of in Scripture, which being feeble folk,
built their nest in a rock!
Truly, dear friend, were it not for the shadow at least, of this Rock,
amidst the conflicts between nature and grace, the mind would often be overwhelmed,
and make the sorrowful conclusion, "`there is no hope.`"
Ah this Rock! how safe a residence is it! and
methinks its obscurity from the worldly wise,
and the selfish mind, adds greatly to its safety.
I seldom get to it but by combat, which shows that my enemies are lively;
and though it is sometimes my lot, in the cross,
to set before others their inherent infirmities and transformed adversary,
yet I humbly trust I shall not, and pray that I never may, forget mine own.

May we not be afraid of suffering; for in this land however,
they that dwell with the seed, must dwell in a low spot,
and give up their names to reproach.
"`If you were of the world, the world would love his own:
but because you are not of the world, but I have chosen you out of the world,
therefore the world hates you:`" "`it hated me before it hated you.`"
To be of this happy, though afflicted number,
is more to be desired than to join ourselves in affinity with a spirit which,
instead of suffering with the seed, wars against it,
in the wrath and cruelty of the king of the locusts which came out of the pit:
a spirit that cannot stand in the day of judgment, but which being airy and unsettled,
leads from the quiet habitation, and leaves the mind without a stay.

How excellent, yes how much to be desired, is that state wherein,
through holy chastisement and suffering for the seed`'s sake,
that precious seal of adoption, the language of Abba Father,
is feelingly obtained and breathed!
This is indeed a something in ourselves wherein we can rejoice,
an unmerited gift which excludes all boasting,
a preservative from moving in the line of others`' experience,
further than it is made our own, or from having our rejoicing in them.
Were the active members of our Society,
more generally and individually gathered to this
deep inward feeling of the life of Truth,
and the evidence of its operations in themselves,
how much more effectual would their labours be,
in building up one another in the most holy faith!
I am afraid for myself, I long to be more truly weighty in my own spirit;
not to assume a consequence among men, or to plume myself with borrowed feathers;
but really to be preserved in company with the seed, and through its operations to live,
move, and have my being, in the church especially.

A series of deep exercises has fallen to my lot,
on account of the law and testimony of Truth in this province,
and near sympathy with some who dare not let it fall to the ground,
without discovering themselves, and on whose side they are.
These find it to be a day of trial, of perplexity, and of treading down;
and there are so few, even among the well-minded, who are skillful either in lamentation,
or in war, that the work lies heavy on a few;
and sometimes I am afraid that the ointment made after the art of the apothecary,
gets unpleasantly tinctured by the dead flies, the unquickened efforts for the cause,
being cast into it.

Though I often find it my duty to wash and anoint, rather than appear to men to fast,
yet the secret travail of my soul is sorrowful,
and beset with many discouragements unknown but to itself and its almighty Helper.
I find that the more deep and hidden my exercises are,
and the more I seek for strength to unite myself, in a covenant never to be broken,
with the Beloved of my soul,
the more I am capable to distinguish the consolations of the Spirit,
the pure unerring Spirit,
from every inferior or corrupt source of gratification to the natural senses.
I know my experience of this is but very small, and yet, as far as I have attained,
I have abundant cause to admire the wisdom there is in
the paths of true abasedness and self-denial;
yes, the fortress they lead to, and the safety there is in them.

Never are we favoured with a clearer perception of our religious duty,
in little as well as greater things, than when our spiritual eye has been purged,
by the ministration of some baptism that has
afflictingly removed every film of self-love;
which discovers itself by an over-attention to our own reputation,
to the ease of the flesh,
and a desire for pleasant things in spirituals as well as temporals.
Ah! may we think nothing too near or too dear to part with,
for the secret acceptance of the Beloved!
The very putting forth of his hand, as through the hole of the door,
little as the intimation may seem,
is a powerful call to admit him in the way of his coming,
however it may oppose our own way.

[.small-break]
'''

Twelfth month,
1788.--My heart was favoured to enter a little into
your affecting account of dear M. G.`'s decease,
and your united visit previous thereto.
That valuable woman`'s last days being so memorably employed in her Master`'s service,
after a life of diffidence and obscurity,
compared with her religious qualifications and attachment to the cause of Truth,
was a distinguishing mark of everlasting love and favour to her.
Her close seems so lively, and her sun set in such brightness and serenity,
that it conveys something animating to those who are far behind in fitness, like myself,
to count not their lives dear unto themselves,
if they also may so finish their course with joy.
And that humble tribulated disciple L. H. appears also
ready to rise triumphant above death,
hell, and the grave:
all that is covetous within me exerts itself in the prospect
of the joyous settlement of such travailing souls,
in undefiled mansions where there is no more change.

Oh that I were but as willing to commit my spirit into the divine hand,
during my residence in this poor frail tabernacle, where there is most need of help,
as to inherit the rewards of those who, through more tribulations,
more effectual washing, and better occupation of their gifts,
enter into the joy of their Lord!
Well! dear friend,
fear not though you have made an exchange so unsuited
to your natural disposition in your present station.
He who knows the sacrifice, because Himself prepared it,
how little soever you may think due to yourself,
will proportionally enrich you and present you with the blessings of His goodness,
and crown you the more with that humility and
self-abasedness which are so precious in His sight.
Were it not that He loved us before we loved Him,
peradventure we might sometimes think our lot a hard one,
and find some cause to despair of His mercy,
or conclude that His holy eye penetrates not into our lonesome and obscure dwellings,
however raised up as spectacles to angels and to men, neither marks the way that we take.
The sacred prerogative of the everlasting Father, of attracting and quickening the soul,
opening and shutting the heavenly treasury, is, I do believe,
the very thing which distracts that mind wherein patience has not had its perfect work,
though it is the very thing wherein it ought to glory.

[.small-break]
'''

1788.--My husband and I received your letter of affection for us,
and lamentation over yourself.
Our minds are drawn into near sympathy with you,
and we believe that this afflictive dispensation is designed
for your increasing acceptance with the Father of spirits,
who knows best how to purify the vessels of His own house.
These, you know, are not only to be of gold, but of beaten gold,
in order to fashion them according to His good pleasure,
and render them fit for the inscription of holiness.

Now, my dear friend,
as your heart`'s desire is to repose yourself in the joys of God`'s salvation,
endeavour to attain that holy quietude,
wherein the delusions of the grand enemy are baffled,
and the tribulated spirit is strengthened to receive the bitterest cup with thanksgiving.
We are of ourselves very weak, and it is sometimes consistent with infinite Wisdom,
that we should be left to a deep sense thereof, that no flesh may glory in his presence;
but that the hunger, the thirst, and the humiliation of the soul, may be fully proved.
Therefore marvel not, as though some new thing had happened unto you.
It is the path which the holy apostle was led in,
when he declared on his own and his brethren`'s behalf,
that they had the sentence of death in themselves,
that they should not trust in themselves, but in God who raises the dead:
and we have many instances in our Society in these parts,
of upright-hearted advocates of the Christian
religion being tried with deep poverty of spirit,
and discouragement in the prospect of the Lord`'s work,
and of their own incapacity to perform it.
We have also instances of these humiliations tending to root
them deeper in the experience of that fundamental truth,
that the true believers in Christ have received an anointing which abides in them,
and need not that another should teach them, but as this same anointing teaches them,
which is truth and is no lie.
And being thus led on to a higher degree of union and fellowship with the Father,
and with the Son, their qualifications have increased to endure,
for the precious seed`'s sake, the watchings, the fastings, and the deaths many,
unto which, according to our measure, we are all, in this mixed state of things, called.
And when their mouths have been opened again in the congregation of the people,
they have depended the more singly and simply upon divine impulse,
and the puttings forth and strengthening virtue of the Shepherd of Israel.
Thus the exercised have been benefitted, and the Lord`'s heritage comforted.
I humbly trust, that these blessings will result from your late tribulations;
and that you will have to say, hitherto the Lord, and not man, has helped me.
It is to be lamented when, for lack of these baptisms of spirit,
a superficial ministry and activity in the church prevail;
for these are like blasts from the wilderness, which, instead of cherishing,
chill the hidden life, and build up in the notion,
rather than in the humbling experience of true religion.
It is much better to appear nothing when we are nothing;
that we may be emptied and cleansed from all self-love,
and learn patience and contentedness therewith.
I salute you in Christian love and sympathy,
and as a tribulated fellow traveller encompassed with manifold infirmities,
remain your friend and sister in the Truth.

[.small-break]
'''

First month, 1789.---My mind has often secretly visited and sympathized with you,
under the various and deep exercises which I do believe have fallen to your lot,
in the course of unerring Wisdom; but it has often seemed more my business,
thus silently to feel you under the precious influence of that love
which the children of the one Almighty Father feel towards each other,
than to be forward in expressing it.

He who has graciously called you out of darkness into his marvellous fight,
turned his hand upon you for good, and thus far,
sustained you through many refining dispensations, will not now leave you,
when Jordan may rise high, and seem to overflow its banks; but in his own time,
which must be waited for, he will divide the waters, and discover to you,
with indisputable clearness, a way where you have seen none; yes,
according to his promise to his own seed, he will make darkness light before you,
and crooked things straight; these things will he do unto you, and will not forsake you.

I think I know, if I am dipped into a right sense of your state,
that the enemy of all good, is exceedingly envious against the precious life,
or seed of the kingdom, which is divinely intended, through suffering,
to be so brought into dominion,
as to establish you in the liberty of the children of God,
whereby your usefulness in the church, in this dark and cloudy day, will increase.
Like the woman seen by John in the vision of light and life,
you may have to flee into the wilderness for preservation,
because of the persecutions of the dragon,
and the floods he may be permitted to pour out of his mouth.
His enmity remains to be with the pure seed;
and they who desire to cherish this excellent treasure, in their earthen vessels,
and to live godly in Christ Jesus, must expect many of his cruel assaults,
in temptations, provocations, and insinuations;
but the Rock of ages remains to be their refuge,
and as their tribulated spirits endeavour to retire here,
and place no confidence in the flesh,
notwithstanding it may be with sore conflict they gain this sure dwelling place,
they will be amply rewarded, and have, in humility of soul,
to rejoice in the impregnableness of the defence,
and to magnify the power through which all things are possible.
Whatever has a tendency to subject and reduce the creaturely part in us,
however bitter its operations may be, is gratefully to be received by the upright soul,
as one of the means whereby the adoption,
and inheritance of the glorious promises of the gospel are attained,
and one of those bitter things which to the truly hungry soul is sweet.

Therefore, let me say to you, fear not, your God is with you, and will work for you,
as you are willing to have all the resistance of
your nature to every of his holy requisitions,
wrought upon and subdued, in the day of his power.
The just are to live by faith, that faith which gives the victory,
and triumphs over death, hell, and the grave.
May you fight the good fight thereof;
and may I be your companion in this necessary warfare;
that so the attacks of our grand adversary upon such Christian
virtues as have been mercifully conceived in our souls,
may all be rendered frustrate;
and we abiding under the sacred influence of the powerful word of patience,
may often have our spiritual eye opened to look beyond the things which are seen,
to the things which are not seen; and for this joy set before us,
count not our lives dear unto ourselves, neither love them unto death!
Though my heart, as I said in the beginning, has secretly visited and saluted you,
yet I had no thought of expressing so much on these solemn subjects,
when I took up my pen;
but only just to convince you that you have in me--though I acknowledge I was
restrained in your company lately from showing it--a sympathizing friend and sister,
according to my measure.
Though, dear friend, we may be led in silent travail,
and as by the gates of hell and death, yet, let us remember,
that this is the way in which inscrutable Wisdom
has ever led his redeemed children in all ages.

[.small-break]
'''

First month, 1789.--There are seasons wherein the Bridegroom of souls withdraws himself,
or, as to the sensible enjoyment of his sacred soul-enriching presence, is taken away,
and then the children of the bride-chamber cannot but fast and mourn.
As I do believe you are one of these, you must learn more and more to endure hardness,
and to bear such dispensations with Christian fortitude,
in that hope which anchors the soul on the invisible Rock of ages.
That which is seen is not hope, and therefore,
remember that this is the season wherein your confidence in almighty help, your faith,
patience, and fervent charity, are to be tried,
rather than when the Bridegroom is obviously with you, when you can not fail to rejoice.

[.small-break]
'''

Second month, 1789.--Your letter addressed to my husband, Mary Dudley and myself,
was very satisfactory to us;
as we found thereby that the precious unity of the
spirit was mercifully preserved in your mind and ours,
notwithstanding our remote situation,
and our own peculiar impediments to the growth of this immortal plant.
We all feel, at times, our faith to be closely tried,
and this has been the experience of those in all ages
who were pressing after a city which has foundations.
The spirit of this world, and the corruptions of our own nature, with great subtlety,
oppose the government of the Son of peace in the heart,
wherein the unity of the one spirit consists.

These enemies of our own houses, are the great objects of the spiritual war;
and as we maintain that by the aid of spiritual weapons,
our faith will grow stronger by its manifold provings,
and a victorious fight will at last abundantly compensate for
every afflictive dispensation and conflict of soul.
Let patience then have its perfect work, that you may "`be perfect and entire,
(as says the apostle) lacking nothing.`"
Many friends here, who love you in the Truth,
have sympathized with you on account of your late prospect of suffering,
concerning what some of you apprehend to be the law of your God;
and your relief therefrom is equally rejoicing.
Is it not cause of humble thankfulness,
that some weak minds are spared from giving public
demonstration of their fidelity to the Christian religion,
at a time when, peradventure,
their faith therein was not strong enough to be accompanied by such works?
A query of this sort to themselves ought deeply to convince them of
the renewed obligation they are under to their heavenly Father,
"`whose eyes run to and fro in the earth,
beholding the evil and the good;`" and that nothing
short of increasing faithfulness to known duty,
and watchfulness thereunto in spirit,
can render them approved in the sight of so gracious a Being.
We are glad to believe there are sincere-hearted men and women among you;
may these be of one heart and one mind, walking "`by the same rule,
and minding the same thing,`" gathering together in the sacred name,
and diligently waiting therein the time which infinite Wisdom prescribes,
(though in ever so much humiliation to the creature) before
the people`'s minds are drawn to outward testimonies.

Oh strengthen one another in this holy exercise!
It is essential for gospel ministers to experience;
that therein the spirits may be tried, every transformation of the enemy judged down,
and the suffering seed of the kingdom only exalted.
If this reduction of self, and all selfish working,
were the object of your strong and feeble members, your assemblies would be solemn,
your feeding would be upon the bread of life,
and your souls would worship and adore the divine Presence,
which delights to dwell in you, and among you.
Your account of the young people`'s faithfulness was acceptable; and, with you,
"`I wish it may be a sincere step towards virtue.`"
Hearing of the two marriages likely to be so agreeably accomplished, is also pleasant;
and I hope that the reflection will be lastingly comfortable to the parties
when their minds are growing under the influence of heavenly dew,
and in obedience to the cross of Christ.

[.small-break]
'''

Second month, 1789.--If you fully knew the state of our minds,
and how closely they have been occupied since our parting from you,
I am ready to conclude,
that sometimes you could hardly have refrained from dropping us a word in season.
Perhaps it is self-love which directs to this vein of consolation;
a hunger after sensible enjoyments, which generally manifests itself to be insatiable,
and the feeding of which seldom strengthens the
root and ground of true Christian fellowship.
It has been our lot, and I doubt not but it has been yours, since we saw each other,
to pass through trials inward and outward;
wherein nothing short of the arm of Omnipotence could possibly sustain and bring through.
O! that our faith may be strengthened in it; that as our race will soon be run, we may,
during its humiliating course, invariably pursue the one thing needful.
Then will our steps, amidst the briers and thorns of this world,
and all the chilling blasts of its spirit,
be rewarded in the riches of the mercy of Him who trod the path before us.
I remember the unity we were favoured to feel in our little services,
and the uninterrupted harmony of our connection as companions;
and these things have left upon my mind impressions too
sacred to be lost in forgetfulness.
Instead of their dying,
I think of late they have been replenished with a degree of the best life:
and as we endeavour simply to move in the lots assigned us by our all-wise Creator,
however distant our outward dwellings may be,
the immortal part will not fail to be assimilated in
the precious covenant of love and life.
It is a wonderful union which Christian travellers enjoy,
when they meet one another in spirit.
Though their communications be mournful, yet understanding each other`'s language,
and being companions, they are encouraged and strengthened thereby,
to proceed on their journey towards a city which has foundations,
whose peace is everlasting.

[.small-break]
'''

Third month, 1789.--The precious evidence of peace,
is one of those rare and valuable flowers,
that seem in danger of withering with too much display in the open air.
The shade, we are sometimes favoured to retire to,
when the world may judge us in its own fluctuating spirit: "`when you pray,
enter into the closet and shut the door,`" etc.

[.small-break]
'''

Third month, 1789.--It is a very low time with me.
There are few I believe that need such baptisms as myself, and therefore it is, no doubt,
best for me to bear them as quietly and profitably as I can.
He with whom we have to do, afflicts not willingly the children of men, and therefore,
if our afflictions are not of our own bringing on,
they are a part of the work of that righteousness which
produces quietness and assurance forever.
We must not expect to pass through the present vale of tears,
without bearing our proportion of suffering, for the body`'s sake,
and those abasements which are so necessary for our own preservation in the Truth.
Wherefore let us be patient, and establish our hearts,
that so we may not be moved or turned away from the hope of the gospel, but through all,
stand in the faith that the day of the Lord draws nigh.
We often find to the mortification of the creature,
that times and seasons are not at our command, nor even for us always to know:
it is the divine prerogative to dispose of them;
and the human mind is taught thereby its own dependency,
and driven in quest of that faith by which the just live.
Faith removes our doubts,
anchors the soul when upon the fluctuating waters of uncertainty,
"`is the very substance of things hoped for, and the evidence of things not seen.`"
Fight, my beloved friend, the good fight thereof, and give no place to the accuser;
so will your possession of this heavenly gift increase,
your offerings will continue to be acceptable,
and victory become sealed to you when the combat is over.

[.small-break]
'''

Third month,
1789.--If you and I are really favoured with the precious evidence of gospel union,
let us be tenacious of its purity.
On your part,
do not fail to "`exhort and reprove with all authority,`" even when
the deceitfulness of my heart judges itself better than it is.
What signifies that part in us which cannot inherit the kingdom?
I cannot say that I am lighthearted,
though it is comfortable to believe your burdens decrease;
nor do I wish to cast a gloom upon, and cloud that sky, which,
after much tempestuous weather, and a frequently oppressive atmosphere,
may attract the strengthened sight to greater heights of clearness and purity, than,
in some past seasons, the nature of things would allow.
I congratulate you as one, not Only beholding the vision,
but gradually and effectually ascending the ladder which reaches from earth to heaven;
on which, methinks, the descending angels are sent to strengthen poor weary pilgrims.
May I be your companion; not so much for the sake of your company,
though that is truly pleasant, as for the glorious rest within the pearl gates,
when the tribulated steps to it shall forever cease,
I believe I do not so frequently write to anyone on this subject as to yourself;
and I would not have you think that my citizenship is proportionally in heaven.
These prospects animate the soul;
but the discouragements and persecutions from that which is born of the flesh,
seem as if they would drag every holy aspiration
into the mire and the clay of the horrible pit.

[.small-break]
'''

Fifth month, 1789.--It just occurred to me as I took up the pen,
that probably there is a greater similarity in
our exercises than we are generally aware of,
and perhaps we are oftener dipped into sympathy one
with another than we are capable of perceiving.
Religious sympathy is I am persuaded a great mystery.
The apostle sought to fill up that which remained, of his portion,
of the sufferings of Christ, for the church`'s sake;
and may we be like-minded respecting those baptisms,
which introduce into a fellowship with the effectual sufferings of the Lamb,
and work in us a conformity to his death; thereby qualifying,
through the power of his resurrection, to demonstrate,
that they are not only for our own, but also for the church`'s sake.
Under these dispensations, can we fail, at times of feeling ourselves alone?
We should not be exercised according to our measures in this tribulated path,
if in the moment when the crucifixion of our wills is approaching,
our associates and friends stood around us with the cup of consolation;
no! it were his enemies then who, hastening their own destruction, pierced him,
and ministered the vinegar and the gall.
Let us then seize the comparison for our humiliation.
Christ in us can unseal the mystery, and amidst his holy leadings in the regeneration,
can renew the drooping mind with the consoling language of, "`fear not,
greater is He that is in you, than he that is in the world.`"
I wish that your mind may be encouraged, without unprofitable reasoning,
to labour onward in the hidden path and pilgrimage of the Jew inward.
You have put your hand to a good work, for which I do believe you are chosen.
The enemy of all good, will, as formerly, seek to destroy the immortal birth,
and not fail to cast forth floods out of his mouth,
and represent them to be the ministration of just condemnation.
To be preserved from this attack upon your best life,
peradventure you may be induced to flee into the wilderness,
where methinks I now visit you, and where you will not be permitted to fall;
but you will be sustained with the bread which the world knows not of,
and come forth in the appointed time, more and more weaned from all human dependencies.

[.small-break]
'''

Fifth month,
1789.--Few sources of comfort presented at the opening of these mixed assemblies,
and unless the one great Source of light and purity
produces to the believers the newness of the spirit,
they cannot but fast; and well is it for them, when, to their fasting,
they can acceptably add mourning.
For my part,
I have in general through the course of the sittings of this meeting (which
are mostly gone through) felt myself something like Mary,
who sat at the blessed Master`'s sepulchre, with a language similar to this;
"`they have taken away my Lord, and I know not where they have laid Him.`"
To your sympathetic mind,
this may be a sufficient description how things have gone with your Sarah Grubb.
Perhaps in the last moment of extremity (for sometimes we are wisely
tried to the last) the joyful tidings may salute the spiritual ear,
"`your Lord is risen, and behold he goes before you.`"
This is the crown of all true rejoicing;
this is the blessing of which the creature must ever acknowledge itself unworthy.
It is a knowledge which indeed puffs not up; and were it not that lucifer,
that fallen son of the morning, is seeking to intrude,
and sometimes does intrude himself,
and attracts the unwary mind to some mountain of self exaltation,
peradventure the manifestations and consolations of the Spirit, would more often,
and more eminently abound among the Lord`'s visited and adopted children.
"`Feed me then with food convenient for me,
lest I be full and deny you:`" O desirable resignation!

[.small-break]
'''

Fifth month, 1789.--I was sorry to hear that your mind was still in so dejected a state.
Causes for situations of this sort cannot always be comprehended by us,
and therefore we ought to be careful how we conclude that they either are, or are not,
in the ordering of best Wisdom.
One thing however affords consolation to the truly contrite mind;
that all things shall work together for good to those who love and fear God.
As I do believe, you are one of these,
and that you sincerely desire also to walk acceptably before him, learn more and more,
patiently and thankfully to receive from his holy hand,
whatsoever he appoints or permits, as dispensations which He only can sanctify.
It is a sort of school the mind has to enter into, when sensible of its own infirmities,
it pursues the things of the kingdom,
and the knowledge how to discern them from the mysterious workings
and cogitations of corrupt self It has many lessons to learn,
hard to flesh and blood; and perhaps one of the most difficult is,
to think nothing too hard, nothing too near or dear to part with,
for the sake of the prize in view.
And were we thoroughly to learn it,
I believe it would clothe us with many amiable and profitable dispositions,
which murmuring Israelites have seldom time to discover.

[.small-break]
'''

Sixth month, 1789.--You are often very near and dear to me;
and I have felt it renewedly during the course
of the exercising meetings we have had here:
for true love sometimes springs up, and attracts our attention to some suffering object,
when we are ready to think ourselves destitute of its sacred virtue,
and too much scattered in mind from its hidden track livingly to converse with it.
So, my dear friend, it has often been with me since we saw each other;
believing that you have trials peculiar to yourself, and peradventure,
are too much depressed therewith.
Let not any discouragement sink you below a holy confidence,
that the everlasting Arm is underneath; and that, if you "`deal your bread to the hungry,
and your water to the thirsty soul, your light shall break forth out of obscurity,
and your darkness become as the noon day.`"
Believe not the most subtle insinuation,
that your passage through life will continue thorny as it is;
for it is in the deceivableness of unrighteousness that these things are suggested to us,
in order to remove us from that steadfastness and hope of the gospel,
in which visited minds are designed to be established.

[.small-break]
'''

Seventh month,
1789.--My heart and eyes have been afresh affected by a
lively revival of days that are past:
days of sore tribulation, when the old heavens and the old earth were passing away,
and a capacity not yet begotten to rejoice in the discovery of the new.
Yes, they were days when the battle was hot between flesh and spirit;
and for lack of being accustomed to the weapons of warfare, mind and body were wearied,
and the vitals of both nearly overcome.
When I reflect upon the kindness of infinite
Goodness many ways manifested to my weak state,
and the ingratitude of my heart, I wonder at the long forbearance,
and continued effusions of the quickening and purifying virtue of the immortal Word.
I wonder at my present backwardness in the Christian life;
and my lack of zeal in the pursuit of the one thing needful.
May your bosom friend and yourself, be so helpful and blessed to each other,
as in the sacred covenant wherein you are bound, unitedly to stretch forth your hands,
unfettered by anything of your own, and let another bind, or gird you,
even though you may be carried thereby where you would not.
The inexpressibly near unity and affection which I felt with, and for your spirits,
in our late and short junction, has left a sweet and consoling savour behind; which now,
and sometimes when a different influence would prevail,
springs up as under the threshold of the door, and rises till it becomes a river,
which my often tried mind measurably rejoices and swims in.
Count not your lives dear unto yourselves, when called for at your hands and when not,
labour after tranquillity of soul; remembering that, however little and poor you may be,
you cannot, by taking ever so much thought, add one cubit to your stature.
But resignation itself is a gift.
Oh that you may covet the best gifts! for it is as we have them in view,
and pray for them, according to the mind of the spirit, that we receive.

[.small-break]
'''

Eighth month, 1789.--You are, dear friend, an epistle written in my heart,
where I sometimes read you and your mournful, humble stoppings, with joy;
consistent with the divine command to rejoice in his new creation, of which,
in infinite mercy, you are happily a part; having known old things to pass away,
and new ones to be brought in,
where the righteousness of the creature is beheld to be as filthy rags;
and where the righteousness of God, the obedience of faith, dwells.
Let it dwell, and more and more abound in your experience;
for thereby your strength will increase, and nothing, in divine appointment,
will be found too hard for you to perform.
In true simplicity to lean upon and follow the beloved of souls,
is a wonderful preservation from that reasoning,
and vain consultation with flesh and blood, which distracts the mind,
and often causes it to err from the faith.
It is true our spiritual guide, for wise purposes, conceals himself from us;
the Bridegroom is taken away, and then the disciples cannot but mourn;
and better is it for them that they should mourn,
than enter into the remotest confederacy with his enemy against Him,
call in question His manifestations, and doubt whether He is to us that friend,
of whom He has given us, in broad day light, living proofs.
An unbelieving heart is a temptation most subtle, and often very plausibly presented.
Beware of it, dear friend!
Be not afraid to have your foolishness for Christ`'s sake perfected; for His gospel,
which is the power of God unto salvation to all them that believe,
is a fund of requisites for the Christian traveller;
from the babe`'s to the strong man`'s food,
the clothing of the lilies in the heavenly garden,
to the accoutrements and victorious armour of the Lamb`'s soldiers.
Fear not therefore, though you be a child, and it seems to yourself that you can not go;
for the Lord has anointed you, and will therefore strengthen you for his work,
and feed you with food convenient for you.

[.small-break]
'''

Eighth month,
1789.--You are very often remembered by me in sisterly sympathy and affection,
though seldom told of it;
and I trust that nothing relating to my silence
will be able to make different impressions.
I find it very difficult in our large family,
and amidst other duties than those which relate to it (though but few of them
comparatively fall to my lot) to sit down and quietly converse with my friends;
and yet they come upon, or rather arrest, my mental attention,
when in the very thick of cares and anxieties;
so that I hope the invisible intercourse of kindred spirits,
is less dependent upon outward and visible signs, than we sometimes imagine;
and peradventure, the more we look beyond the things that are seen,
to the things that are not seen,
the more we then possess the very thing which our natures prompt us to toil for.
Nevertheless, as a secondary consolation, it is lawful thus to commune.

Your last joint epistle was to me a pleasant repast,
though some of its ingredients were bitter herbs.
You know so well how, in every new dispensation,
to look to "`the great first cause,`" and to Wait for that sanctification of the Spirit,
which causes all things to work together for good to them that love Him,
that it seems unnecessary for me to remark upon it;
an entire freedom clothes my mind respecting you; yes, and I may add,
a belief that your bitterest cups will be sweetened in the due and appointed time.
To wait for that, has often been a hard duty to the hastiness of my desires.
But were we not to be so exercised,
where or how could we obtain profitable experience in the Christian`'s path?
how could we live by faith, when all things were accounted for to us?
or when arrive at the quiet and safe harbour of pure resignation,
if the storms of carnal reasoning were never to rise?
There is a great and an attainable purity in that state of mind,
which forbears to judge even in its own cause; which, in singleness,
casts its burden upon the Lord, and accepts every permitted tribulation and chastisement,
as a renewed seal of adoption,
and evidence of our being intended to be joint heirs with Christ;
and therefore bound and induced, by the unfailing mercies of God, to follow through all,
our holy Head; and by the increase of his spirit,
not to fear humbly to breathe the language of Abba, Father.
I look up with an emulous eye, to an experience which I generally live far short of:
but let us press forward,
for we shall reap if we faint not You are a collection of chosen vessels at that place.
Oh permit not the enemy to put in his cloven foot among you,
for he mars the purest designs; and to frustrate the gracious intention,
of the Lord`'s children being helpmeets to each other, is one of his most subtle attempts.
When there are storms at sea, vessels are often scattered, and hid one from another;
perhaps all equally tossed: but there is a voice which both winds and waves obey,
and which unites them again.
Have faith in it, and wait for it, and you shall do well.

[.small-break]
'''

Eighth month, 1789.--As children of the same family,
I believe it allowable for us to commune together at times,
as we walk in the way and are sad; for, methinks,
the Master has herein joined himself to us,
and I trust will graciously continue to do so, as we hold fast our integrity,
and become more and more skillful in lamentation.
Elijah, in a time of deep revolt, thought himself alone,
and saw Israel with an eye clouded by discouragement, till He who knows all things,
revealed to him his own preserved seed.
In the word of eternal life only, is certainty.
Well! they that feared the Lord spake often one to another.
I look at you, dear friend,
as having very few to speak to who understand the Hebrew tongue.
One of the characteristics of many in this day who are called Christians is,
that they are half Jew and half Ashdod; but even at this be not too sorrowful:
"`when father and mother forsake you,
the Lord will take you up,`" and become himself the supplier of all your needs.
Who knows but He may make you an instrument for the turning of many to a pure language,
and inducing them to call upon the sacred name,
the refuge and sanctuary of the righteous;
that so they may be preserved in the secret places of the Almighty,
until his indignation be overpast.
Be a faithful watchman; yes,
be willing and thankful to become the most menial in the spiritual family.
This humility will, with the blessing, insure your preservation,
and at times furnish you with that bread of eternal life, which the world knows not of.

[.small-break]
'''

Ninth month, 1789.--I wish we could more frequently converse upon our various concerns,
believing that each of us finds them at times awfully important,
and attended with their peculiar perplexities.
A little company in such paths has a cheering effect, as it seldom happens,
in the right ordering of things, that all are sinking under discouragements together;
and therefore they can the better speak comfortably together;
when some one or other sensibly possesses the precious gift of faith,
which peradventure all are nevertheless living by.

My head often seems dropping below water; yes,
there are seasons when the billows actually pass over; and, through unutterable mercy,
they do pass over, and beyond the present trials.
Sowing as in tears, in the variety of ground which we find among the children,
my strength gets renewed; and my soul begotten again to a lively hope,
that infinite kindness will, in his own time and way,
bless our feeble endeavours to prepare subjects for the kingdom of the Prince of peace.
It is little we can do;
but that little let us labour to perform acceptably to the almighty Father,
and leave the world to gaze upon us, and judge of us, as it may.
When we take its sentiments into consideration,
or put them in competition with our soul`'s peace,
it is like the false balance which is an abomination to the Lord;
whereas the just weight, an implicit attention and obedience to divine requisition,
is His delight.
I wish, dear friends, that your hands may be strengthened,
in the faithful discharge of your duty towards the numerous family you preside in:
for the more you erect the standard of Truth there,
the more your services in society will increase; and what is still better,
the deeper your spirits will get in the undefiled
consolations of the humble followers of Jesus.
These are worth suffering for,
and they abound in proportion to our tribulations for His sake.

[.small-break]
'''

Ninth month,
1789.--I am truly glad you stands so dedicated to pour
water on the hands of this sweet spirited friend;
believing such a disposition, conceived in the integrity of the heart,
is often acceptable to, and blessed by,
the good Spirit which renews the hope of the humble,
and revives the minds of the contrite ones.
Let not the usual discouragements to these little surrenders,
so prevent you from following on to the full performance,
as to rob you of the reward of enriching peace,
and the increase of your experience in the work whereinto you are,
beyond all doubt to my mind, rightly introduced.
Having put your hand to the plough, it is not now a day for you to look back.
"`Remember Lot`'s wife,`" has often been an instructive caution,
and lesson of peculiar instruction to my mind,
when in danger of giving up my spiritual travail,
and rather than distinguish myself from those to whom my steppings appeared foolishness,
tempted in the bitterness of my spirit, to say, "`I will speak no more in your name.`"
The old heavens and the old earth will, I trust,
yield you no more of their forbidden delights; and therefore, how unwise would it be,
through an imperfect obedience,
to deprive your tribulated spirit of that undefiled rejoicing,
which is peculiar to the new creation of God.
I mean not, by this solicitude respecting you,
to be the means of promoting an activity from under the renewed influence of pure wisdom,
or even the premature disclosing of openings into the undoubted mysteries of the kingdom;
for it is a great but necessary attainment, to know how to keep the Lord`'s secrets,
and when to reveal them.
But a truly resigned and humble state of mind is a continual sacrifice,
and will produce the fruit of the Spirit.
I wish for you and myself, that this root of the matter may be found in us; then,
as steady and uniform travellers we shall gain ground in the new and living way;
and leaving the things that are behind, shall reach forth to those that are before,
having our eye single unto Jesus, who also took up the cross and despised the shame.

[.small-break]
'''

Tenth month, 1789.--I feel myself nearly interested in your and your wife`'s welfare,
and am pleased with every renewed capacity to sympathize with you in spirit, knowing,
that if you dwell in that faith which overcomes the world,
you must often experience trials of it, and, for its refinement,
be baptized into a sense of your own weakness; perhaps so much so, as to acknowledge,
with the holy Apostle, that we have the sentence of death in ourselves,
that we should not trust in ourselves, "`but in God who raises the dead.`"
If this is your exercise, be encouraged to faithfulness herein.
There are many who willingly cry, Hosanna to him who comes in the name of the Lord,
but who are not bound enough in heart to the pure seed of divine light,
to watch and to suffer with it, at a time when there is no form or comeliness in it;
and when it seems no otherwise to operate in the
soul than by making the creature abhor itself.
These take not that root in religion,
and have not that holy communion or fellowship with the Father and with the Son,
which qualifies the watchful Christian soul undoubtedly to know when good comes;
to rejoice in themselves, and not in another; yes, and to bear testimony,
in the quickening virtue of Truth, that the Lord is risen.

I greatly desire your preservation, dear friend,
believing that you are designed for an instrument in the Lord`'s hands,
to carry on his work, his great and marvellous work,
among a benighted and rebellious people, and to be the means,
in the little society you are joined to, of drawing them,
by your example as well as precept, from the "`lo here is Christ,
and lo he is there,`" to the kingdom of heaven in themselves;
and of instructing them in patient waiting for its coming.
This being a part of your office, I know you must endure much hardness,
and meet with persecution in yourself, and in others;
because the enemy of all good will transform himself as into an angel of light,
and try to beguile both the simple,
and those who are measurably instructed in the kingdom.
Take for your example a faithful servant^
footnote:[See William Leddra`'s epistle, Friends`' Library, vol.
vii. p 479.]
of Jesus Christ, who fled as the dove to the window of the ark,
and stood still in that watch.
Then will you be rewarded with the fulness of joy, at the coming of your Lord,
without whom you can do nothing;
strength will be given you faithfully to bear those Christian testimonies,
in which you have most surely believed, and also to suffer for them,
if it be the Master`'s will.
Then will the light in you be more and more useful in the house,
and the weightiness and reverence of your spirit,
excite the beloved youth also to purchase the field where the pearl lies.
May I be your companion in these exercises!
My attainment in religious knowledge is small; and without frequent baptisms of spirit,
and watchings unto prayer, I find even that little might soon be taken away.
Let me have your prayers and the sympathy of your spirit,
whenever the pure light teaches you so to do.
It is a comfort to us to feel you, and some others of your little flock,
in the precious covenant of love and life,
wherein we desire to be remembered by you and by them.

[.small-break]
'''

Tenth month 1789.--Your peaceful return is matter of joy to me.
I wonder not at it, because you were strengthened to humble yourself as a child;
and therefore, on the wings of laith and love,
are you exalted to behold and aspire after the hope of your calling,
and even to rejoice in the renewed prospect of the land which is very far off.
Ah! how often our spiritual eye lacks purging and re-anointing,
in order to see these things, and in our measure,
to "`behold the King in his beauty;`" and even when it is so prepared.
Wisdom, infinite Wisdom,
presents it at times with objects more conducive to the
establishment of the mind upon the Rock alone,
by leaving it so destitute of sensible enjoyment, that it loathes itself,
feelingly cries out, "`without you I can do nothing,`" and pants,
like the deer after the water brooks, for Shiloh, the river of life.
Here (in another metaphor) is Christ the Rock found, whereon,
a truly religious weariness, not impatience, of this world, and the things thereof,
tends to build, establish and strengthen us.
We are but sojourners here; let us then, with becoming earnestness of spirit,
invariably seek a city which has foundations;
the very knowledge of whose Builder and Maker is life eternal.

You are right, my dear friend, in believing me to be in a tried low state of mind,
though you are the first that seems to know anything of it.
I mourn over myself, not knowing why it is so with me.
As to opening my mouth in our meetings,
it seems as far from me as if I had never known such a concern.
A painful gloomy exercise, or a wandering imagination,
is what I have principally to travail through; and yet,
having been acquainted with a situation of mind much more destitute than this,
I dare not but consider the invisible support my soul is blessed with,
as an object of reverent gratitude.
Well might David (who knew the various dispensations of the
Lord) pray that His holy Spirit might not be taken from him,
at the same time that he craved the restoration of the joys of His salvation.
But let our allotment be what it may,
there is some attention to be paid to that precept of the gospel,
"`to wash and to anoint, rather than to appear to men to fast.`"
My situation in this large family, where many have their own exercises to pass through,
calls upon me for the practice of every Christian virtue which I have,
through unmerited mercy, been taught in the school of Christ; and much complaint,
or conversation about our inward state, except Truth opens the way for it,
which I trust is now the case, rather decreases than increases our strength.
We have a friend, blessed be the great and ever worthy name,
that sticks closer than any brother;
may we then cleave to Him with full purpose of heart!
He can renew our resignation, and abundantly prepare us to say, "`not my will,
but Yours be done.`"

[.small-break]
'''

Eleventh month 1789.--I am, through infinite kindness,
convinced that the immortality of the soul is manifest in the spiritual communion which,
according to our measures, we experience in these mortal bodies,
independent of every medium originating in the invention of man,
and though a very defective purity occasions with me a defective enjoyment of it,
yet I feel at times a holy resolution to hold fast that
which I have of the unspeakable gift of faith,
and to accept it as an earnest of the inheritance, until, by greater degrees of light,
love, and life, the redemption of the purchased possession is obtained.
That you are my companion herein, and in hidden conflict for this glorious prize,
I seem assured beyond a doubt;
and greatly desire that the present dispensation of unerring Wisdom may,
in proportion to the depths of sorrow which you have experienced, lead you up,
on consecrated ground, to this dignified attainment.
Ah, my friend, these are humble ascendings,
because they are the consequence of descendings: but they are safe; therefore fear not,
O daughter of Zion; lo "`I am with you, says the Lord; be not dismayed, I am your God;
I will strengthen you, I will help you, yes,
I will uphold you with the right hand of my righteousness.`"

[.small-break]
'''

Eleventh month 1789.--These are low trying times with us, and particularly to my mind,
feeling myself often as one that has abundant
need to go down again to the potter`'s house and,
through divine favour strength is at times afforded to descend
in spirit to where a right and true sense of myself,
and the purity of the cause I am sometimes engaged to advocate, is obtained.
We often have need of the prayers and sympathy of each other`'s spirits,
and oh! that we may be kept in that faith which gives the victory,
so as to wrestle effectually for the renewed supplies of the Spirit,
that none of the discouragements of our day may prevail against us.
I know you have your secret provings; but fear not, "`greater is He that is in you,
than he that is in the world.`"
We have champions in this land, who seem to defy little David`'s simplicity;
but if those who go forth against such in your parts, as well as here,
do it in the name of the Lord God of the armies of Israel,
and with those weapons which He approves, victory will finally be on their side.

[.small-break]
'''

Eleventh month 1789.--I have long seen it necessary to watch my own heart,
lest while I nourished an approved Christian sympathy with my fellow pilgrims,
and manifested it in the line of apprehended duty,
I should also draw their attention and affections to myself,
and thereby wound the pure life by strengthening the root of self-love in both;
and instead of building up in the most holy faith,
and in a single dependence upon the one true and everlasting Lawgiver,
make such a composition of nature and grace, as would keep the mind in fermentation,
rather than in perfect peaces rob of His honour the Captain of our salvation;
and prevent those mighty works being done in His name
which call for the singleness of the believing heart.
I have beheld an evil like this in our camp,
and its impediment to the growth of visited minds to that stature in Christ,
to which their peace assuredly called them.
Do not mistake me; I reverence the bond of Christian fellowship,
and in a sense of the fellowship itself, with its sacred consoling anointing,
my spirit has often been dissolved;
and fervently craved its increase in myself and others: yes,
I have rejoiced in the flowings of that language,
which I can now feelingly adopt to yourself,
not from partiality so much as from a renewed concern for your preservation,
"`My longed for and joy, stand fast in the Lord, my dearly beloved.`"
In seasons like this, we perceive where the mixture lies; the natural part,
which cannot inherit the kingdom,
blending with a rightly begotten exercise and sympathy with each other.
If our most amiable qualifications, and affectionate endearments, are not subservient to,
and sanctified by, the refiner of hearts, they are encumbrances to the gospel,
and the services of it.

[.small-break]
'''

Twelfth month 1789.--Accept the expression of my
renewed love and sympathy for and with you;
the remembrance of you is precious to my heart,
because I comfortably feel you to be a fellow
traveller towards a city which has foundations.
We must not expect the weather, the roads,
and the disposition of our minds for prosecuting the journey,
to be always pleasant but we must ever be careful to keep in the way;
to travel when light is upon the path; and to rest in the night.
We are not to conclude everything lost which is out of sight;
the most valuable grain the earth yields, passes through a temporary death.
We are most of us senseless enough, at times,
to be objects of the Apostle`'s arousing address, "`you fool,
that which you sow is not quickened except it die.`"
Human nature is so subject to deception, that it can frustrate,
by some pollution or other, almost every dispensation, but death: therefore,
be faithful unto that, remembering the consequent promise;
"`you shall receive a crown of life.`"

[.small-break]
'''

Twelfth month 1789.--I assure you my heart feels for you a cordiality,
which at times does myself good: for in loving those who love the Truth,
as I believe you do, we unite ourselves to a chain, the end of which,
however remote from the perfection of the divine life,
happily connects us with all the living,
in seeking after those things which excel in purity and duration.
One comfort that attends those who are simply and
singly pressing after the hope of their calling is,
that they are not bound to tell all they feel, neither with respect to themselves,
nor others; it is not essential that they should seek eminence,
even in the religious world.
They are happily spared the trouble of such vain objects, and find that,
in solitude of spirit, the Beloved of souls speaks most comfortably to them,
and enriches them with most spiritual blessings,
which he causes them to enjoy in heavenly places.
Oh, how often I covet for myself, and my friends, that we may keep sacred,
to these "`heavenly places,`" the gifts of the spirit!
Nature is apt to feed upon them, to bask itself in their influence,
and congratulate itself in the possession of such treasure; when alas! the gold,
the precious gold, this way becomes dim,
and is often unwisely tinselled over by the unsanctified affection of the creature.
I wish, that you and I may possess that love or charity which boasts not itself,
nor is soon extinguished by the changeableness
ever to be found in the face of perishing things;
but may cherish in ourselves the root from which every Christian virtue springs.
Then we may have rejoicing in ourselves, rather than in another,
and our mental salutations herein be more frequent than our expressions of them.
Your account of dear +++_______+++ is comfortable, she is a truly valuable woman,
and will I hope, more and more, show herself to be what she is.
Obscurity is not always granted to those who most seek it:
it is sometimes a favourable climate for the fruits of humiliation`'s valley;
but these are in wisdom, and for the good of mankind,
often exposed for those that thirst, and have nothing wherewith to buy.

[.small-break]
'''

Twelfth month 1789.--A week or two after our return from Dublin, A. S. departed this life.
We hear she had sore conflict of mind for some days, greatly fearing her future welfare:
so pure did that kingdom appear, when her admired liveliness,
and faculty of pleasing ceased;
when pleasant pictures of spiritual things were torn to pieces,
and the day that burns as an oven came upon them.
But this heaviness of spirit was a merciful dispensation;
the chastisement yielded peaceable fruit;
for before she finally took her leave of visible things,
she had to acknowledge unfailing mercies.

[.small-break]
'''

Twelfth month 1789.--I have seen, in my short life,
so much fallacy in human wisdom respecting matrimonial connections,
and so much blessing showered upon an attention to simple uncorrupted openings,
which have not at first appeared most plausible,
that I seem to have no faith left in any direction but
that which the devoted heart finds to make for peace.
In concerns of this sort, it is often very difficult for such to judge,
because prepossession and inclination are apt to influence our best feelings.
Natural affection bears some resemblance to sacred impulse; and therefore,
methinks that this seed, though ever so right,
must die in the ground before it be quickened and sanctified.
In short there are few openings, for our own and the general good,
which have not to pass through this temporary death,
few gifts but what are designed to be buried in baptism; and I wish you,
if ever you possess a female companion, to obtain her as a fruit of the new creation;
that so you may reap those spiritual advantages which those enjoy, who,
through the effectual working of the grace of God, drink together into one spirit,
whether in suffering or in rejoicing; for without this experience,
Zion`'s travellers must find such connections to be secretly burdensome and insipid.

[.small-break]
'''

+++[+++She attended the half-year`'s national meeting at Dublin in the fifth month, 1789;
and from there went to York, where she made her relations and friends a short visit,
and proceeded pretty directly for the yearly meeting at London: which she attended,
and returned home with an evidence, that, in this journey,
she had been occupied in her proper place.
This is agreeably testified by the following letter,
which is the only one that has appeared on this occasion.]

[.small-break]
'''

Our little flock looks pleasant and healthy.
Our joy was mutual at meeting yesterday, and home is felt by us to be a peaceful retreat.
In a little sitting which we had at home in the evening,
there seemed some ability to lie down as beside the still waters; a consoling experience:
and on looking back upon our late journey,
though there was no great professed draft to it, a hope arises, that,
consistent with our religious duty, we were going on with the work of the day.

[.small-break]
'''

+++[+++In the latter part of the year 1789,
she felt her mind drawn to have some public meetings in several places,
where none of our Society dwell, particularly at the town and garrison of Kinsale; where,
as well as at other places,
these services tended to open and spread the knowledge of the Truth.
Concerning her visit to the above-mentioned place, she writes thus:]

[.small-break]
'''

In much fear, and I trust humiliation of spirit, I have been to the town of Kinsale,
and permitted to have appointed, through an apprehension of duty, a public meeting there.
It was large, nearly as much so as the house belonging to the Society would admit.

There appeared to be about two hundred people,
who generally behaved with decency and solidity,
and the meeting was owned with the gathering influence of Israel`'s Shepherd; which,
in time of silence, was I thought comfortably experienced.
We also paid a visit to the fort, and particularly to a large company of deserters,
who are collected there for transportation, many of them good looking young men;
and I also ventured to remind some of the officers, of their religious and civil duties.
It was altogether a service much in the cross, and deserving of no reward,
for lack of timely resignation to it; but, in unmerited mercy,
I was favoured with a peaceful calm, which my beloved companions also enjoyed,
and earned with honest labour.

[.small-break]
'''

First month, 1790.--I rejoice that the Keeper of Israel, who sleeps not by day,
nor slumbers by night, has you under His providential care.
This is a sustaining persuasion, a hope in times of trial,
which settles the otherwise tossed mind on the consecrated ground of pure dependence:
may you never doubt it.
Satan will not fail to assault you, sometimes in roaring about your dwelling,
and sometimes, with the subtlety of the prince of the air,
seeking to take possession of ail within you,
which can possibly incline to disobey the commands of inscrutable and infinite Wisdom.
Remember he was a liar from the beginning;
and invariably opposes the exaltation of the mountain of the Lord`'s house.
He prefers any hill to this;
and had rather we were gathered to the heights of our own imaginations,
and the seat of judgment, there to condemn ourselves,
and reason out of doors the convictions of Truth,
than that we should die daily to the will of the creature,
and sit in reverent dependence at the feet of Him who bruises the serpent`'s head.

[.small-break]
'''

First month, 1790.--I want you to be encouraged,
and to put all your confidence in the everlasting Arm.
Leave, as much as possible, things that are behind;
be content with the present emptiness, when it is your portion,
and neither toil nor spin for future supplies.
He that clothes the lilies and the grass of the field, is abundantly able and ready,
in his own time, to reveal his gracious providence,
and minister from the treasures of wisdom and knowledge, to his flock and family,
even through the weak and foolish things of this world;
so that things which are not,--minds reduced to a sense of
their nothingness--may bring to nought things which are.

The Christian`'s strength consists in the favour and countenance of his Captain;
and the obtaining of this leads the mind into that
abasedness where Satan finds himself discomfited,
and his head bruised.
"`He shall bruise your heel.`"
Little indeed is in his power, if we maintain the humility, the simplicity,
and holy dignity of a converted soul.
Many words are unnecessary at present.
The Master, who knows what you can hear,
will I doubt not give you your meat in due season, waken you morning by morning,
and cause your ear to hear as the learned.
In all things may he instruct you to discretion,
and preserve you in the way whereinto he has led you,
even that way which truly no fowl knows!
I know, from a degree of experience,
that the farther we get from a dependence upon instrumental consolation,
the more likely we are, with holy certainty, to discover, amidst inward conflicts,
the indubitable evidence of being upon the true foundation, the seal of adoption,
the white stone with the new name, etc.
The very chastisements which introduce the mind to this humbling knowledge, are,
when passed by, sweet to the new taste, as the honey and the honeycomb.

[.small-break]
'''

First month, 1790.--I did not forget you;
but truly self was at that time so much the object and subject of my cares and exertions,
that if I could but any way keep my head above water thereby,
it was more than my doubting mind could at times hope for.
Ah, my dear friend, I have a heart prone to rebel against,
and live above the pure spirit of Truth; and because thereof,
my spirit is at times covered with mourning as with a garment; and more especially,
when I consider the greatness, and holiness of that Name,
of which I venture to make mention in the congregation of the Lord`'s people.
It is mercy, nothing short of mercy,
so marvellously displayed in the choice of vessels for sacred services in the church.
"`He will have mercy on whom he will have mercy:`" this truth baffles human reasoning:
and therefore, let you and I covet an increase in the increase of God,
and ask in faith for the best gifts.
Being afflicted with the impurity of struggling nature,
let us come boldly to the throne of grace, to help us in the needful time,
and to settle our spirits in calm acquiescence with, and resignation to,
the dispensations of infinite Wisdom; that so, from every temptation and tribulation,
our souls may be restored, with this immortal and unadulterated song,
"`your will be done.`"
If we are but as the ram`'s horns,
through which the Shepherd of Israel speaks at times to his people,
in concert with his inward and more despised teaching, let us be content,
and simply seek a holy conformity to, and adorning of, his doctrine.

[.small-break]
'''

Second month, 1790.--It is not by might or by power, but by the spirit of the Lord,
that his work prospers, or his praise is effected;
and therefore a little one may be made "`a thousand, and a small one a strong nation.`"
Under this persuasion,
the faith is strengthened in the Omnipotence of the smallest
revelation of the Lord`'s arm in our little services,
and our trust removed from the appearance of strength, to strength itself.
The rich man cannot glory in his riches, nor the strong man in his strength,
but the cause of glorying is found to be in the
righteous government and dispensations of our holy Head.

Your letter brought you all so much to my mind, that it seemed as if I was with you,
sharing in your concerns,
and feeling in part that weight of exercise with which
dependent servants are introduced into their field of labour.
Now perhaps I may congratulate you on the completion hereof,
and participate in that humble rejoicing wherewith Ebenezers are set up.
I fervently desire to possess an increasing capacity to
feel with the members of the mystical body,
wherever scattered,
or however concealed in the depths of the wilderness from the human eye;
for I am persuaded that, as our spirits are regulated by the President of this church,
they will, at times, be carried beyond the bounds of observation,
to visit the seed in prison.

[.small-break]
'''

+++[+++She was, indeed, much concerned, and laboured in her measure,
for the propagation of the cause of Christ, who is the light and life of men;
and she counted nothing too dear to give up, or part with,
for the promotion of his pure word in their hearts.
A renewed evidence of this appears,
in a fresh instance of dedication to a very trying and arduous service.
During her late travels on the continent, her mind had often sympathized in secret,
and been united in gospel love,
with a precious seed scattered up and down in those parts; but which,
it seemed not then the appointed season, to visit in person.

This time now approached, and as she apprehended, in the openings of divine wisdom;
so that she believed it her indispensable duty, to give herself up, in pure resignation,
to this service; which appeared in her view, to comprehend a visit to Dunkirk, Holland,
Pyrmont, and some other parts of Germany.
Under the weight of this important concern,
she experienced the near sympathy of Friends of the
monthly and quarterly meetings to which she belonged,
with those of the national meeting in Dublin, and yearly select meeting in London;
who concurred in testimonials of their unity and approbation.
Thus strengthened by the feelings and concurrence of the church,
and by a similar concern of her friend George Dillwyn,
she set forward to engage in the work before them, in the sixth month, 1790;
accompanied also by her husband and Sarah Dillwyn,
who felt their minds engaged to enter with them on this journey.

Her letters written under the prospect of this visit, during the progress of it,
and upon its conclusion, appear to form, in general,
so regular and connected an account of it, that nothing further appears necessary,
than to lay the extracts from them before the reader.]

[.small-break]
'''

Second month, 1790.--I seem very like one who has no resting place on earth,
or any consolations here in which I dare to trust; but if I am found worthy,
in the smallest degree, to resemble the great and holy High Priest of our profession,
it is enough.
As to the performance of great works, I look not for it;
my mind is taught to believe that I have no right thereto;
no reason to expect that an instrument so feeble, and so little a time in use,
is likely to be owned, in any extraordinary degree,
in the discharge of my small part of the great work.
But my spirit has often been dipped into sympathy inexpressible,
with a seed in those parts, of which I have not yet attained the outward discovery,
and peradventure, this second visit may prove like fishing and catching nothing.
This I desire to leave,
and to attain to a daily and simple reliance upon unerring direction,
which the creature knows must be attended with a dying daily.

[.small-break]
'''

Second month, 1790.--We stand in need of care, both of our own, and that of our friends;
our endeavours for peace being, in many respects, in a line rather new and important,
and in which we desire to be preserved from moving
further than the good Shepherd leads and goes before.
It has not been without a portion of deep exercise, and frequent baptisms,
known only to the Searcher of hearts,
that I have obtained so much strength as to cast my burden for a time upon the church;
and since they have taken it, and I believe some of them felt it, my relief has,
beyond my expectation, been effected.--But this is temporary.
I know, in a spiritual sense at least, that bonds and afflictions await me;
yet with thankfulness may acknowledge that, feeling the everlasting Arm to be underneath,
none of these things at present move me.
My capacity to promote the work of righteousness on the earth, is very small;
but according to that capacity, I long to be found faithful,
not counting my life dear unto myself.
I have not heard of any companion in the little services before me,
nor do I feel any anxiety on that head; believing that, if the concern is right,
suitable fellow-labourers will be provided, without any toiling interference of mine.

[.small-break]
'''

Third month, 1790.--May my mind be preserved in stability to the end:
for that I both watch and pray, well knowing that when I lose that,
it must be distinguished mercy indeed,
that preserves my poor little vessel from total wreck.
As a very hard gale of even fair wind may occasion great danger,
so I perceive that the urgency I feel, at times, in my spirit,
to do the Master`'s apprehended will, may frustrate the gracious design,
if ballast be not on board.
I never felt my mind so sensibly sustained in the prospect of any journey before.
I esteem it an unmerited mark of the great Shepherd`'s condescending care, who has,
blessed be his Name, richly replenished my soul with faith,
and so abandantly ministered its sister virtue, patience,
that my frail tabernacle being at times overcome,
the language of my heart is similar to that of the spouse, "`Stay me with flagons,
comfort me with apples; for I am sick of love.`"

This is a dispensation which I do not expect to continue;
for when a testimony of this love is called for, when difficulties are to be encountered,
both within and without,
when we are to be offered up a sacrifice in the service of the Christian faith,
oh how inconstant is the human heart! how many substitutes for obedience,
how many subterfuges does it find!
Remembering these things, the wormwood and the gall,
yes the anguishing exercises attendant on our late journey,
my heart is humbled within me,
and preserved from expecting the journey in prospect to be unmixed with similar trials;
or even to see in it, gratifying demonstrations of that glorious work, which,
in gospel vision, is beheld to be begun in the German empire,
and many other parts of the globe less known to us.
On any presumption of this sort, I have not dared to take one step;
but have much desired that my spirit may be deep enough, according to my measure,
to suffer and rejoice only with the pure seed, whether obviously the fig-tree blossom,
and fruit be on the vine, or not.

On second-day morning,
at the yearly meeting of ministers and elders held in London the 17th of the fifth month,
our certificates were read; which, far beyond what I dared have looked for,
created expressions of gospel unity and church encouragement,
that were not entirely unseasonable to my mind;
feeling myself as poor as seemed possible for spiritual existence.
But what also greatly contributed to lift up my head above the overflowing billows,
and say to the winds and waves, "`Be still,`" was the indisputable evidence,
that the Master had separated for a similar work, my beloved friend, George Dillwyn;
under which his oppressed mind was constrained publicly to acknowledge,
to his own and others relief, that he believed it to be his duty to go with us.
How precious is that help,
which is dispensed in better wisdom than our own! and being the fruit of mercy,
it is often reserved for the moment of extremity.
It was a very solemn uniting season; the spirit and the bride, the church,
appeared cordially to unite in the same language of encouragement.

I greatly desire a heart capable of humbly and reverently
returning acceptable obedience for these favours,
in the few feeble steppings through my future pilgrimage.
Trials I have learned to expect,
having a disposition that will not permit me to be exempt,
till it become lost in the ocean of gospel love.
In ourselves, as in the world, there is trouble;
oh that our acquaintance may become more and more intimate with Him,
in whom is the fulness of undefiled peace!
Then may we rejoice in every tribulation,
which has urged us to lay hold on eternal substance.

No female companion appearing, our former valuable fellow traveller, Sarah Dillwyn,
was naturally looked to, and no obstructions occurring, Ratcliffe monthly meeting,
of which she is a member, cordially testified its approbation therewith,
and granted her a certificate.
Thus we four being banded, left London, Joshua Beale accompanying us,
on the seventh-day after the yearly meeting.
There we met with many Friends like bone of our bone, and flesh of our flesh; yes,
so cemented have some of us at times felt,
as fully to convince us that it was the work of both grace and nature;
the latter of which, in our many separations,
is learning I trust to be more and more subject,
and to surrender its will to the divine will, which indeed sweetens many bitter cups,
and strengthens us to say amen to every requiring of Truth.
Without this experience, how are we like bullocks unaccustomed to the yoke!
The yearly meeting was large, and satisfactory in a good degree; but such assemblies,
composed of minds so various,
have generally a considerable portion of exercise and weight for the feeling members;
and it is an unspeakable favour that there are such preserved in the church,
whose spiritual faculties are so alive, that, like watchers on the walls of Zion,
they can give an alarm at the new and various attacks,
which our common and unwearied enemy is making upon Truth`'s ramparts:
and it is also a distinguishable mercy in our poor Society, that there are,
among the younger part of it, such as,
by the liveliness and faithfulness of their spirits,
promise a succession of standard-bearers.

We were at Rochester on first-day, at the monthly meeting at Canterbury on third-day,
and got to Dover that evening; from which we sailed next day for Dunkirk, and had a fine,
but slow passage, being on the water sixteen hours.
Here we found J. D. M. waiting for us; and Joshua Beale, also uniting himself to us,
we became six in number.
The day we arrived, was their week-day meeting;
and it may with thankfulness be acknowledged,
that it was mercifully owned with divine refreshment,
and the communication of counsel from the living Spring thereof.

What tended to heighten our joy, on sitting down with the Friends here,
was the scene which we had beheld just before.
What they call the host was carried about, with such a procession of the army,
corporation, clergy and little children, as I never saw before, or could have supposed;
there being many thousands of people, and images of silver, pewter, and wood;
hundreds of candles near six feet long; abundance of rich silk and other vestments;
barefooted and shaven headed friars; music, drums, etc. cannon firing, and bells ringing.
So that, after all this stir, to sit down with our friends,
under our own vines and fig-trees, and measurably to partake of substantial food,
was truly joyous; and more especially so, under the belief that the one shall decrease,
and the other increase.

We spent a full week at Dunkirk, to a good degree of satisfaction,
perceiving the blessing that these new settlers may be in that land,
and at this important juncture, if they wisely keep to, and are graciously kept by,
the preserving, unchangeable Spirit of Truth.
They are at present worth visiting,
and their number is likely soon to be increased from Nantucket.

After having four public meetings in Dunkirk;
at all which many not of our Society attended, and several private ones,
we proceeded to Ostend, B. R. going with us; here we spent a day to satisfaction,
finding a man and his wife from London belonging to the Society,
who had not seen any reputable Friends for seven or eight years.
Though they had the marks of being, in some degree, robbed and spoiled,
yet there was also something in them to visit, and which accepted the testimony of Truth,
as far as related to themselves.
Many books were also scattered,
and not without a hope that the blessing accompanied some of them;
for even in this little service, there is a great difference in our feelings.
It is often like casting bread upon the waters,
and sometimes without hope of return in any day or age.

From Ostend we continued our course along the coast, by way of Bruges, Flushing,
and Middleburgh; at the two latter of which, we solemnly paused,
and also exposed ourselves to the observation and acquaintance of the people;
intimating to some our errand, and making enquiry for such as were seeking the Truth.
With some small exception, they appeared to be in their strong holds, and fenced cities,
intent upon this world`'s gain, which is, with too much propriety, called their god.
However, a few books were left among them;
and finding the son of a Friend at Middleburgh,
we had an opportunity of religious retirement with him,
and of dropping such counsel as opened therein.

He appeared, by his acknowledgment and attention to us, to accept the visit kindly;
but his situation is exceedingly unsafe.
From Middleburgh we went to a little port, called Campveer,
and there hired a vessel to take us to Rotterdam.
We had a very pleasant passage, our minds being favoured with much tranquillity;
and after a thirty hours sail, arrived at our port, the 18th of the sixth month; where,
as we expected, we entered into a fresh trial of fidelity to the precious cause.
Here we stayed, three days, visited some former acquaintances, who were very kind;
and commenced new ones with such as seemed to understand how to receive disciples,
in the name of disciples.
To one or two of this class, our minds were particularly united.
Being there on a first-day, we had two public meetings, both considerably attended,
but especially the latter, which was also a truly solemn and profitable opportunity.

Between Dunkirk and Rotterdam,
we had several opportunities of disseminating the knowledge of the principles of Truth,
by the distribution of books, and some conferences in a private way;
but had no public meeting, though our minds were, in several places,
brought under a considerable weight of exercise; which seemed to answer no more end,
than the people`'s walking round the walls of Jericho;
and were it not that we are convinced, even from outward observation,
that the Lord is at work in the kingdoms of men, and making a way for his own seed,
we might conclude, that the fortifications which this world`'s spirit has erected,
particularly in Holland, will hardly ever be taken down.

We went pretty directly from Rotterdam to Amsterdam,
where we had our share of secret dippings and discouragements;
but not expecting great things in our setting out,
or desiring to be borne up above a feeling of what we are,
and the oppression and obscurity of the true seed,
we are the less exposed to a spirit of dismay; and engaged at times, in simplicity,
to sit down together, professedly to wait for the guidance of Truth,
or a discovery that the cloud rests upon the tabernacle.
In these seasons, we have been strengthened and cemented in best unity,
and also encouraged to hold on in a path to be trodden more by faith than sight.

In the public meetings, of which we have attended three, we experienced painful exercise;
and yet I thought on first-day, that both the sittings were upon the whole,
solid and lively.
We received accounts of our brother Joseph Grubb
being in a very declining state of health,
which had made its appearance before we left home;
and being in partnership with my Robert Grubb,
and the care of business forbidden to my brother,
my husband thought it his duty to offer him all the relief he could;
a tranquil mind respecting outward things,
being of unspeakable consequence to the latter part of a man`'s life; this,
without any anxiety about our own properly, and a presentiment before we left home,
that he would hardly go through the journey, induced us, though much in the cross,
to separate.

We were detained at Amsterdam longer than we expected;
one occasion of which was the printing of some extracts from Hugh Turford`'s writings,
with an addition from Mary Brook on silent waiting,
which some of our company translated into French.
It. contains very suitable matter for the present age,
and is an acceptable publication to J. M. and B. R. to distribute in France,
and also convenient to us in this journey, as many understand French.
We have a large stock of other books, very eligible for our purpose,
which the meeting for sufferings has given us for distribution.
The 6th of the seventh month, we came to Utrecht, where J. M. being tender took cold,
and was confined next day to the house;
and it suited our plan of spending one day quietly together, before we parted,
he and B. R. having concluded to go from hence to Dunkirk,
and J. M. from that place to his home.
This has been a trial to us, but knowing J. M`'s. attention to best direction,
and also his desire, if right, of keeping with us,
we dared not to persuade him to suit our inclinations and convenience; and therefore,
after enjoying each others company, in sweet fellowship and tenderness of spirit,
we parted; our little band then consisting of George and Sarah Dillwyn,
Joshua Beale and myself, with the most arduous part of the journey in prospect.
Perhaps this stripping of outward help is wisely dispensed to us;
in that light we view it, and dare not dispute divine sufficiency.

Soon after our friends were gone, we concluded to pay a visit to a family of Amsterdam,
with which we were acquainted when there before, who now resided at their country house,
about half way from that city to Utrecht; and accordingly set off,
and arrived about five,
and were received more like near relations united on the best ground,
than as people of another nation and profession.
We also met here two women of considerable account on a visit;
to one of them particularly, our minds were nearly drawn,
and the little instruction which was in our power to communicate,
from the exercise of our minds, broken French, and the use of the scriptures,
to particular passages of which we directed them as they occurred,
was received with a religious sensibility, which greatly united us together,
and which words cannot fully set forth.
Though we often lament our ignorance of the language of this people,
and its attendant inconveniences,
yet I was never more convinced of the influence of Truth
qualifying to speak to one another in our own tongues,
though utterly incapable in any other language, than that of the spirit;
for in the present case, we were not sensible of either us, or the cause,
suffering under our apparent disadvantages.
We cannot always judge why we are so led,
and why so destitute of some outward accommodations to the service,
which human prudence would naturally point out: but I may acknowledge that,
on this account, I never was more contented and supported in a humble trust,
that the good and almighty Hand is with us in "`these mortifying labours.`"

[.small-break]
'''

+++[+++Some time afterwards, she wrote the following letter to one of the women of that family.

[.embedded-content-document.letter]
--

Remembering your request to hear from our little company when we returned from Germany,
and being now so near you, I felt an inclination to tell you,
and your valuable brother and sister, that,
through the merciful direction and care of Providence,
we have got along to a good degree of satisfaction, and been favoured, upon the whole,
with a moderate share of health.
We pursued our journey from Utrecht, by way of Arnheim and Munster, to Pyrmont;
there we stayed two weeks, and then went to Rinteln, Minden, Osnabruck, and Bilefeld,
and so, by way of Munster, to Crevelt, Dusseldorff, Mulheim on the Rhine, Elberfelt,
and from there to Cleves.
We found a few in many of these places, who,
being weary of the ceremonial part of religion,
are desiring its living substance and to be true worshippers in spirit.
These have many difficulties from within and without; hut if they depend, singly,
upon divine help, and cease to recommend themselves by their own dead works,
we have a hope, that they will gradually retire from the confusion of the carnal mind,
to the true sheepfold.
Were the professors of Christianity more generally acquainted with the undefiled rest,
which the redeemed mind is strengthened to gather to,
they would detect the fallacy of unsanctified forms and ministry,
and rejoicingly receive the eternal Witness for God in themselves, for their Lawgiver,
Friend, and Comforter.

We reflect with satisfaction upon our visit to Middlewaart;
not only in remembrance of your affectionate hospitality,
but also of the uniting virtue of Truth upon our minds,
which left a pleasant savour after we separated; and now reviving,
with renewed desire for all our preservation,
and increasing intimacy with the good Shepherd of his sheep, I salute you,
my dear friend, in sisterly affection.

[.signed-section-signature]
Sarah Grubb

--

We left Utrecht on seventh-day morning, and came to Wageninge,
which is an agreeable little town.
The inhabitants were greatly surprised at seeing us,
but became uncommonly civil and courteous;
in part owing to a man who drove us from Utrecht, who by some means, unknown to us,
conceived so favourable an opinion of us,
and seemed furnished with such materials for description, that wherever we stopped,
he was sure to influence the people in our favour,
and they united in testimonies of affection and kindness.
We spent all first-day in Wageninge; had a little,
but solemn and refreshing meeting of our own company,
and had also the company of a young priest of good character.
He and George Dillwyn conversed, I believe intelligibly,
upon some important subjects in French,
though perhaps neither of them were fully acquainted with the language;
but the best sense being present, that defect was made up thereby.

We left a few suitable books with them, which were very kindly accepted;
and our parting was with apparent sentiments of affectionate esteem.
We also gave books to several others,
and had a satisfaction in spending this little time among a kind, simple-hearted people.
The people of the inn are particularly of this description,
their conduct manifesting a pleasure which they had in entertaining us.
These comfortable spots and feelings, somewhat resemble Elijah`'s food,
on the strength of which he had to travel many days.
As neither the great work, nor the capacity to do it, is ours,
so we may be emboldened to hope,
that our acceptance will stand in proportion to our obedience to that we have,
rather than to that we have not.

From Wageninge we came to Arnheim, where we spent one day agreeably,
were at the house of very civil people; and though we did not commence much acquaintance,
yet were satisfied with our little detention there,
and to one or other left several books.
Here we met with a kind man who speaks English well,
says he was seasonably and effectually served by a Friend in England,
when he was a stranger there; and this is, no doubt,
an additional inducement to lay himself out to oblige us,
which he does with the appearance of much sincerity.
These journeys, I sometimes hope,
will in future open my heart with more cordiality to strangers;
for "`knowing the heart of a stranger,`" a deficiency herein would be doubly culpable.

The next place we went to was Doesburg,
where our feelings were rather unusually pleasant;
but we did not find any stop thereby in our progress.
The landlady at the inn where we stopped,
appeared and approved herself to be far from the common sort,
for dignity of manners and solidity, if not religious weightiness, of mind.
Her conduct to us was truly friendly,
manifesting an affection and liberality becoming other parts of her character.
We gave her a Barclay`'s Apology in Dutch, and several books in French,
which she appeared fully qualified to read, and in a good degree to understand:
she wanted much to pay for them, but on any terms was glad to receive them;
and after looking over the summary, promised to lend them among some of her neighbours.

Germany is a country very unlike the Netherlands, both in the face of it,
and in the manners of its inhabitants;
the people being kept in a state of greater servility under princes of small territories.
Our difficulties in the way of travelling commenced when we left Holland;
for after gliding along in Treckschutes, upon their quiet waters, we got into wagons,
the best public conveyances the country afforded, and the roads being extremely bad,
we were jolted to a degree not easy to suppose; and for lack of knowing the language,
were imposed upon, and induced to take our passage in the post wagon,
understanding that we should have it to ourselves,
arrive seasonably at our lodgings the two nights in prospect,
and have time enough for rest.
But instead of these fine things, after they got our money, a Capuchin friar,
and a very ill looking man, were put in with us, and we kept in this situation,
with two meals lacking, through a dark rainy night, the wet coming in upon us,
till three o`'clock the next morning; when, after two hours rest, we were summoned again,
and without stopping to take any meals, save our dinners, travelled on till we arrived,
about one o`'clock next morning, at the gates of Munster, a fortified city;
where we had to wait for an entrance more than half an hour;
and then had to find our lodgings among a people of a strange language,
whose principal object was to get from us all they could.
This is a hint of the manner in which we got along,
and I mention it to show the inconvenience strangers are subject to,
and how different the fare of these countries is from that of England;
at the same time an acknowledgment of Providential care is abundantly due from us.
Our minds, during this extraordinary trial of body and spirits,
were remarkably sustained with cheerful tranquillity,
and abounding desire to comfort one another in this painful imprisonment.
We were also preserved at the time from suffering in our health,
and found that part of two days rest in Munster, recruited us finely.

Our stay in that city was very satisfactory,
finding it to be a place of considerable openness.
One man in particular, a professor of languages in the university, who was sick,
received our men with brotherly affection and joy,
had very satisfactory conversation with them,
and was glad to receive several of our books,
some of which he intended to put into their public library.
He told them of a relation of his, in a part of Germany where we have not been,
who is fully convinced of our principles, but who has not dared openly to avow them;
and said, that in some other parts, there are many such,
which we have since found to be the case.
A serious young nobleman, a pupil of his, intending to take a tour to England,
was desirous of being recommended to some Friend in London,
in which George Dillwyn gratified him.
Many other opportunities occurred of casting books into the hands of serious people,
and in an imperfect, way intimating to them such truths,
as at that time we were furnished with.

From Munster we came, by way of Warrendorf, Padderborn, etc. through Westphalia,
to Pyrmont, which we reached the 23rd of the seventh month.
Here our minds were soon comforted in the belief, that there is a seed in these parts,
which, however hidden from the world and the many churches professing the Christian name,
are pressing after an establishment on the right foundation.
We were greatly favoured with peaceful serenity,
and a steady reliance on Providential care; so that instead of difficulties depressing,
they rather animated our spirits to press forward,
toward the fulfilling of our allotted portion of travail and exercise,
and to bear up one another, according to our ability, through all.
Nevertheless,
there have been seasons when Satan did not fail to suggest to the weakness of my mind,
that we were running in vain.
But to our humbling encouragement, after we arrived at Pyrmont,
and particularly in the second meeting there, among a simple-hearted, seeking people,
we were convinced that it was not so,
and that infinite kindness would also preserve us from labouring in vain.
It was an opportunity wherein, to the praise of the grace which we depend upon,
we may say, that, for a time, "`the seed reigned over all.`"
Visitors and visited experienced it to be a season of uncommon contrition,
and during the extension of the holy Wing,
our spirits seemed gathered into perfect unity; so efficacious is divine life and love!

It appears that two years ago, there were about twenty in Pyrmont,
who being uneasy with the dead formality of many professors,
met together in their own houses, sometimes reading, singing, or praying,
as they apprehended most right.
They underwent considerable persecution on this account from the avaricious priests,
who persuaded people not to do business with them; and being generally low in the world,
they suffered in this respect;
but it appears that they were not hindered thereby from meeting together:
yet their rest not being a pure one was broken up.
Some of them finding their reformation from what they saw to be wrong, was very small,
concluded there was something more substantial than what they had yet experienced;
and this being suggested to the rest, occasioned a division among them.
A few returned to the profession they had left, and the others ceased to meet together;
yet it is wonderful to see the brotherly kindness which distinguishes them from others.
They call themselves Friends, and with much propriety, to each other.

We spent about two weeks in Pyrmont with satisfaction of mind.
For three rooms, three beds, fire, candles, and the use of the kitchen,
we paid fifteen shillings per week, found our own provisions, cooked them ourselves,
with the assistance of a girl and an elderly man,
one of the Friends who spoke English pretty well.
He marketed for us, interpreted on more important occasions,
and served us with great solidity and cheerfulness.
In many respects we felt as if we were at home, though among a people,
few of whom knew what we said; but they told us by signs,
that they felt that which was better than words, and which required none to set it forth:
O! that we may be preserved in, and feel more and more bound to,
our own line and measure of duty; that as the work is the Lord`'s,
the management of it may also be in his wisdom, and tend to his glory;
and then no matter how low and abased the creature becomes.

During our stay at Pyrmont, we had many meetings,
some of which were uncommonly contriting opportunities,
wherein their doubts seemed to subside,
and the virtue of Truth to sweeten and refresh their weary spirits.
At one meeting we had the company of four men,
who walked the day before nearly twenty miles, to sit with us; and that of another man,
who came about forty, also on foot.
In many respects they are weak,
and yet so sincerely desirous to obtain "`the
one thing needful,`" that we entertain a hope,
some of them will increase in steadfastness to what they know to be right.
Our minds are often involved in discouragement and conflict: the weakness of our frames,
and perhaps the prospect of the unfinished part of the work,
may be the occasion of these.
But let us remember, that till they are overcome by the power of victorious faith,
it is our seed time rather than harvest, and therefore we are called upon,
by merciful and heart-solacing intimations, to sow in hope.
Whether any apparent fruits ever appear from this journey,
we seem comfortably satisfied at times,
that it will not be lost in the unlimited family of the one universal Parent;
and if we are but favoured to keep the word of his patience,
so as to hold out to the end, and return without condemnation, it will not be lost to us.

We set off from Pyrmont for Rinteln,
upon a different plan from that on which we had travelled before;
for having a man to do little services for us when there, who is one of their Friends,
and speaks English well,
we saw an extraordinary convenience would attend our taking him with us;
and therefore have taken a light wagon and a pair of horses,
which save us imposition and trouble in procuring carriages, etc.

Our man conducts himself with great propriety and simplicity, as our friend, guide,
interpreter, and servant; being charioteer, and doing a great deal for us besides.
We spent a week at Rinteln, and had several meetings among them,
besides private religious opportunities, in several of their families,
and left some of our books for a university in that town.
In our way here, we came through a skirt of Hanover, where we beheld,
in the improvements of the country, and the appearance of the people,
a cheering resemblance of England.
About Rinteln, there are near twenty of those who call themselves Friends,
and some of them we believe to be lively spirited people,
and considerably experienced in the inward work of religion;
of whom we have a comfortable hope, whether they are ever known to our gathered,
visible church, or not.

We are now in this country under a frequent sense of inward poverty,
and with many confirmations, that of ourselves we can do nothing;
yet trusting that best wisdom has turned us into this little field of labour,
we dare not, with our present feelings, desert it; but we go on from spot to spot,
as we apprehend is most in the line of our duty.
From Rinteln we proceeded to Minden, where we found a little company of sincere-hearted,
and exercised Christian travellers, who appeared glad of our visit,
and expressed a belief that it was in divine appointment for their good.
They seemed more desirous for a right opening to sit down together in silent waiting,
than to enter into conversation about what they had already experienced.

We had several solid, and I hope edifying, meetings among them,
to which several came from the country many miles on foot,
which demonstrated their earnestness to be helped on in the right way;
among these was a blind woman who gets her living by spinning,
and who walked seventeen miles to meet us.
She is an example of Christian fortitude, and true nobility; for on our asking her,
if she was not under difficulties in procuring herself a living, she gratefully answered,
that her friends sometimes helped her, that she knew she was poor,
but when she reflected upon her supplies, and the query revived in her mind,
"`if she lacked anything,`" the acknowledgment always succeeded, "`nothing, Lord.`"
She told us with great humility and tenderness,
that her knowledge of the Truth was not obtained by books or outward means,
but by the operation of the divine Spirit in her own heart.

I hope we have been preserved, thus far,
from drawing the inward attention of those whom we have visited, to ourselves,
or attaching them in the affectionate part to any representation of good.
The secret, sympathetic exercise which we have felt on their account,
and in company with them, has, I do believe, brought us all at times,
to the renewed discovery of the everlasting foundation;
and we have a hope that some of these will acceptably build thereon.
We here met with great civility, and tenderness of spirit,
from a counsellor and director of this place; but the cross is a mighty stumbling block.
He often makes me think of Nicodemus: when we left the town,
he kindly went before us to an inn on the road, where he had provided coffee,
and convened several of the Friends to take their last leave;
a parting which I hope was attended with true solemnity, as well as brokenness of spirit.
With tears, he expressed his desire,
that He who said he would be with his disciples to the end of the world,
would go with us, and bless his own work.

Next day we travelled towards Buer, and dined sweetly in a field,
on provision which we took with us, while our horses were eating corn.
We then turned a little out of the road, to visit a man and his wife,
whom the priest is persecuting for absenting themselves from his place of worship.
He has got the magistrate to fine them nearly twenty shillings,
which is a great deal for them, and they refusing to pay it,
from an apprehension of duty, have suffered distress of their goods,
with Christian simplicity and firmness.
After spending nearly two hours with them, I hope to our and their edification,
we came on to Buer.
In the neighbourhood of this town live a little company of Zion`'s travellers,
with whom we had a meeting; and our gracious Helper being near, by his good spirit,
rendered it a humbling and refreshing opportunity.
We have many encampments, and when we shall get through this wilderness,
is very uncertain; for my part, I see no way yet!
This blindness is, probably, to try my patience, of which I seem, at times,
to have a reducing stock; but am secretly supported, in knowing Him in whom I have,
through holy help, believed.

We have great cause to be humbly thankful for that portion of sure direction and ability,
which, for our instruction as well as comfort,
has been revealed in the midst of our weakness, and become as a table in the wilderness,
furnished with food wisely adapted to the necessities of weary and hungry travellers.
It seems very singular, when I recollect myself, that we are keeping house in Prussia,
and considerably united to some of its inhabitants, who were lately entire strangers;
and, in degree, feel as if we were at home, though so far from that which is called home.
It is a little like being in a new world, yet so near the old one,
as to be distinguished for similar evils, and that fashion which passes away, when Truth,
which is strongest of all, takes its possession.
It is very pleasant in these journeys to feel this sentiment lively upon our spirits,
"`the earth is the Lord`'s.`"

We went from Buer to Osnabruck, the 26th of the eighth month,
where we spent several days, under considerable exercise of mind,
and not finding that our visit was likely to be attended with any use,
and being also fatigued various ways, we were so discouraged,
that we were about concluding to leave the town next day,
though we thought the way to it had opened as clearly as to most places we had been at;
but on feeling further about it, we thought it safest to try a little longer,
and not move in the dark.
Our situation was unfavourable,
being at a Roman Catholic inn where the Protestants are afraid to come,
and our friend and interpreter having no acquaintance in the place.
Thus we continued till seventh-day evening, without anything satisfactory occurring,
except giving a few summaries^
footnote:[These were books containing a summary account of our principles.]
to some shopkeepers on whom we had called,
and having the company of a young woman who had enquired concerning us,
and discovered a serious desire to be with us, and to have some of our books:
she appeared to us to be possessed of much sweetness, and valuable sensibility.

On seventh-day evening, our men called upon the merchant,
on whom they had a letter of credit, who speaks English well,
behaved with great kindness, and soon apprehending their errand,
having some knowledge of the Society in England,
went with them to an overseer of part of his business, who was a religious man,
and discontented with the ceremonious part of the world`'s worship.
They found this person a little shy at first, but he soon opened to them with simplicity,
and discovered himself to be a man who was
awakened to a profitable sense of his own state,
and to a sincere desire to be led in divine counsel,
to greater acceptance than the shadows of things could yield him.
He came with them to the inn, and we spent the evening agreeably together.
He told us of a few more in the town who were of his sentiments,
and met together every first-day evening, to read, etc., and on being asked,
if they would be willing to sit with us after our manner,
he expressed his own inclination so to do: and after enquiring of others,
told us next morning, that it was agreeable to them all.

In the morning we were surprised and comforted with the sight of a very solid,
feeling young woman from Buer, in the capacity of a servant,
who had walked fifteen miles to meet us,
in consequence of a secret draught in her own mind, without having any reason to expect,
from what had passed, that we should be at Osnabruck so long.
After getting her some refreshment, we six sat down together,
and had a strengthening opportunity, wherein dear George Dillwyn ministered to us.
At four in the afternoon, we had a meeting with about eight more,
among whom was an officer, who behaved solidly.
It was a time of favour, and I believe of deep instruction to some there,
who had not before seen the necessity of ceasing from their own works,
and depending only upon the renewal of divine life in the soul,
for qualification rightly to worship.
After meeting, we paid a visit to one of their friends who was sick,
with whom we were led into sympathy in silence,
and to whom we imparted such counsel as Truth unfolded at that time.
These were relieving circumstances to us, and set us at liberty,
comfortably to depart on second-day morning for Hertford or Herwerden.
We therefore set off with the prospect of a pretty easy day`'s journey,
but found the road very rough, and in many places dangerous,
and more of it than we expected; so that we were grievously jolted,
and out till near ten at night, very contrary to our inclination;
for we tried much to get lodgings in a town a few miles off,
but the people would not take us in.
We appeared very strange to many here,
but so different to a few who are acquainted with the Truth,
that the distinction of countries seems almost lost,
and proves the cementing virtue of religion.

At Hertford we were visited by two religious men,
who come under the description of those called Friends in these parts;
and they were encouraged to faithfulness.
Our men also visited a lawyer,
who being discontented with the usual ceremonies of religion,
keeps much to himself Next morning as we were at breakfast, proposing to depart,
there came two men from different parts,
who had walked many miles through the rain to meet us.
One of these men, some time ago, refused to be married by the priest, in which,
and in other things, he bore a steady testimony, under persecution,
against a hireling ministry.
The openness, kindness, and solidity of his manners and countenance, were pleasant to us;
and being evidently acquainted with silent waiting,
we had a solemn instructive opportunity together.

From Hertford, we proceeded to Bilefeld, a town where, and in its neighbourhood,
there are many religious people, and particularly agreeable as to the outward;
but it was a visit attended with as deep baptism and continual travail of spirit,
as we have experienced in any place that we have been in; which,
with the Providential openings and strength to
visit the precious seed in the needful time,
tended to convince us that we were in the way of our duty; a most cheering evidence,
in this dreary wilderness, and a full reward for all our little toils.

At this place there are some who live separate from all public profession,
who under an apprehension of being turned out of the way, and were afraid, for a while,
to give us their company: but being also afraid to let the opportunity slip,
we were invited to one of their houses,
to confer with several of them on such subjects as might occur,
in order to know a little of each other.
Both sides were somewhat surprised to find so much similarity of sentiment,
respecting the ground and testimonies of Truth.
They told us, that if there were a people there,
who ceased from all forms or activity of their own,
and sat down in simple dependence upon the operation of the heavenly gift,
they would embrace them with brotherly affection, and rejoice to unite with them herein;
but they were unwilling to believe,
that they two or three might be required to bear such a public testimony;
nor were they willing to unite with us in so doing,
for fear of the people whose eyes are much upon them.

They are people of considerable account,
and are very fearful of drawing the lower class of their neighbours to themselves;
and being of Nicodemus`'s class, like better to obtain and enjoy,
their religious knowledge in private.
We had, nevertheless, several opportunities of solid conference together;
which were attended with great unanimity and cordiality;
the last of which was particularly owned with the circulation of divine virtue,
and with strength fully to relieve our minds towards them.

We were very kindly invited to the house of a merchant,
who appears to be a very sincere man.
We paid him and his daughter a morning visit; but they were not content with that,
and therefore pressed us to spend first-day evening with them.
In the morning of that day, we sat together in the inn,
where we had the company of an honest man,
who came on foot sixteen miles to be at meeting with us,
and also of four others of the town.
In the afternoon, as Joshua Beale was taking a solitary walk,
he was met by a serious man,
who desired his company to a house a little way out of the town;
he complied with his invitation, and when they got there,
they found fourteen people met together, for the sake of religious improvement,
who soon made their request that we would all go and sit with them.
I was laid down, in a tried situation of mind,
when Joshua Beale brought the invitation which had in it so much of the right savour,
that we embraced it, and immediately set off, having above an English mile to walk.
By the time we got there, they were about twenty in number.

We soon settled down into a silence truly solemn,
which lasted a considerable time without interruption of any kind;
and when the channel of instrumental ministry opened,
the precious life mercifully continued,
and our parting was under its tendering impressions.
This circumstance, of dropping in with a people of whom we had no intelligence,
and with whom we contracted no further acquaintance,
with the sensible feeling of divine care over those who are as sheep halving no shepherd,
affords altogether a sweet and pleasant reflection;
accompanied by this encouraging truth, that "`the Lord can make a way,
where there seems to be no way:`" O that He may graciously continue thus to favour us!
After this opportunity,
we went to the aforementioned merchant`'s and were treated with genuine hospitality.

After supper, there came in eight or ten persons with the expectation of a meeting,
in which they were not disappointed; and I hope it was edifying to them,
George Dillwyn having suitable and lively matter to communicate.
We had also a religious sitting with a family from Elberfelt, a lively spirited couple,
and another person with them.
After spending five days here, and bearing the cross as faithfully, perhaps,
as in some places where a more open door was ministered, we departed in much peace,
and under the belief,
that the power of Truth is making its own way in that neighbourhood.
In our way from Bilefeld, we stopped at a large village called Gutterslots,
where there are many well disposed people.
We stayed one day there, and sat with a few people who met us at one of their houses;
after which, and distributing a few books to others in the town,
we went forward to Munster.

We are often very weary, and the accommodations we meet with but indifferent,
compared with those of England: the roads are also bad where we have already been, which,
with the construction of the carriages, occasions us sometimes to be grievously jostled;
and yet we have no cause to complain, having our consolations as well as toils;
as it seldom happens that Zion`'s travellers are qualified to salute each other,
even in a thorny difficult way, but the immortal birth, in some degree, leaps for joy.
This experience, with the belief that the Lord is at work in the kingdoms of men,
and even graciously rewarding such feeble endeavours as ours,
with a morsel of the bread that the world knows not of,
render any little sufferings of ours as objects unworthy the notice of ourselves,
or our friends.

From Munster we went to Crevelt.
We found our discouragements on entering it,
being refused admission at one inn we went to,
and at the next we had such a crowd gathered about us, with such shoutings and rudeness,
as greatly frightened our horses,
after we were out of the carriage and our driver had alighted, so that they ran away,
and he following, and taking hold of a chain behind, was thrown down, and his head,
to appearance, much hurt against the wheel.
Some of our feelings were low enough on this occasion.
But through the continued kindness of Providence, our man soon recovered,
being able to move about next day;
and the people of the house conceived such an affectionate respect for us,
and treated us with such true civility, as made our situation so far comfortable.
We also gradually made so much acquaintance,
as afforded a degree of hope that our going to Crevelt was right,
and that our secret and known exercises there, will not be in vain.
About the time of our concluding to come away, our company began to be more sought;
which opened the way for the disposal of some of our books,
and I feel a secret hope that they will be blessed to some there.
We came to Dusseldorff,
where we stayed one day and had the enjoyment of M. Wetterboar`'s company.
He seems aged, but is alive in the Truth.

We proceeded to Mulheim, where we arrived the 23rd of the ninth month.
It is a town about two miles from Cologne, like a Goshen on the confines of Egypt,
where many awakened, and some truly religious people reside.
We commenced an acquaintance with a few, who have got a clear insight,
from the work of Truth in themselves, into the gospel dispensation,
and the spirituality of the; Christian religion;
concerning these we have encouraging prospects; yet not without a mixture,
knowing something of Satan`'s devices.
They received us in the name of disciples.
We had several religious opportunities with them,
and parted under the precious sense of divine love and life.

We paid a visit to a merchant`'s wife, a woman of amiable character,
who through religious concern has got into a despairing condition.
It was attended with great satisfaction to ourselves,
from the sweetness which covered our own minds in her company and in that of her husband,
who seems bending under the affliction, and likely to profit by it.
She often expressed an earnest wish,
that she had seen us at a time when such a visit might have been blessed to her;
but said, that now it was too late for anything that was good to be offered to her.
This was, however, very far from our sense.
Through the renewal of unutterable mercy, and never failing help,
my soul acknowledges a relief and answer of peace, as far as relates to this service,
of which I am sure my little endeavours, and compelled dedication are unworthy.
We have had many discouragements since we came to the continent,
and many baptisms into death: we have also partaken largely of Providential care,
and been favoured, from time to time, when resignation was attained to,
with that direction whose effects have often proved its rectitude,
and strengthened our faith; and my soul, at times,
has been put into the capacity of lying down as beside the still waters.
Some of the last openings, or sense of duty, have been the most trying and in the cross;
but being yielded to, and the work performed,
a comfortable retreat has been clearly and sweetly
sounded from this large field of arduous labour:
and at a time, when an openness among the people was manifestly increasing.
This I esteem an inexpressible favour, and such a one as they only can be sensible of,
who have gone under the weight of similar mountains,
and been involved in the fear of being misled.

[.small-break]
'''

+++[+++At Mulheim, she drew up and signed a letter to Leopold the second, king of Hungary, etc.,
since emperor of Germany, in which her companions united.
For some time before her arrival at this place,
her mind had been very weightily exercised with
the important subjects expressed in this letter;
insomuch that, at one period,
she was under an apprehension that it would be required of her to go in person,
and relieve her mind to the king.
But from this very trying service, she felt herself comfortably released,
and the mode of addressing him by letter was satisfactorily substituted.
The address was entrusted to the care of a reputable merchant of Cologne,
who engaged to forward it without delay.
The following is a copy of it.]

[.embedded-content-document.letter]
--

[.letter-heading]
To Leopold the second, king of Hungary, Bohemia, etc.

Among the numerous congratulations awaiting your accession to the imperial crown, accept,
O king! our Christian good wishes and solicitude for your present and eternal well-being.
We are conscious that we have no claim to the liberty of addressing you,
but from a belief that the Lord Almighty, who rules in the kingdoms of men,
and gives them to whomsoever he will,
has inclined us to leave our habitations to visit some parts of this country,
and now engages us, in gospel love, to express our secret and united prayer,
that you may be an instrument in His holy hand, for the advancement of that glorious day,
spoken of by the prophet, "`when swords shall be beaten into plowshares,
and spears into pruning hooks, when nation shall not lift up sword against nation;
neither shall they learn war any more.

The great design of our universal Parent,
in sending his beloved Son a light into the world,
is for his own glory in the salvation of mankind; and for this gracious end,
he has given to all men a measure of his own eternal Spirit.
To cooperate with Him herein, dignifies human nature,
and is particularly deserving the most scrupulous attention of princes.
The smallest revelation of this heavenly gift in the believing soul,
having a degree of Omnipotence in it,
brings into subjection the natural will and wisdom of man,
and discovers to us the noble purposes of our creation;
it diffuses that true benevolence which characterises genuine Christianity,
and renders dear to a prince, the happiness of all, even the meanest of his subjects;
imprinting upon his mind the superior value of an immortal soul,
to all worldly acquisitions.

Through the neglect of a principle so pure and important,
how has the rational part of God`'s creation been
sacrificed to the irregular passions of sovereigns;
and many unprepared souls precipitated into an awful futurity!
That the gospel dispensation is intended to remedy these evils,
and promote the government of the Prince of peace;
that the Gentiles are to come to its light, and kings to the brightness of its arising,
are truths to which the sacred records abundantly testify.
May this be your happy experience,
O king! that so the power you are providentially
entrusted with being subservient to divine wisdom,
your example may influence the minds of other princes, who also beholding its excellency,
may unite in encouraging their subjects to decline, in mutual charity and forbearance,
whatever is contrary to the purity and simplicity of the religion of Jesus.
And may you be enriched with all spiritual blessings;
that these added to your temporal ones, may not only perfect your happiness,
but perpetuate it beyond the narrow limits of time, and qualify you, acceptably,
to cast down your crown at the feet of Him who is King of kings and Lord of lords,
who lives and reigns forever and ever.

[.signed-section-signature]
--George and Sarah Dillwyn, Burlington, New Jersey, North America.

[.signed-section-signature]
--Sarah Grubb, Clonmel, Ireland.

[.signed-section-signature]
--Joshua Beale, Cork, Ireland.

[.postscript]
Members of the religious Society of Friends in those countries and Great Britain,
commonly called Quakers.
Mulheim on the Rhine, 29th of the Ninth month called September, 1790.

--

+++[+++A short time before her return home, on a review of some parts of this journey,
she wrote as follows.]

[.small-break]
'''

In many places,
we found a people who were discontented and
weary with the mere profession of Christianity,
and the deadness of those forms and ceremonies with which it is encumbered;
and who were convinced of the sufficiency of the heavenly principle.
These,
having been mercifully visited with a lively sense of the spirituality of true religion,
received us in the name of disciples,
and rejoiced in being directed to the Christian`'s rest.
This true sabbath, was, however, imperfectly understood by many of them,
for lack of ceasing, when they met together in little companies,
from all activity of their own, and depending singly on the quickening virtue of Truth,
to qualify them for, and lead them into,
such services as are most acceptable and most consistent with the duty of true,
spiritual believers.
Some of this people appeared to be so near this great point,
as soon to discover and acknowledge it; but their increasing testimony thereto, will,
if rightly borne, prove the closest trial which they have yet met with.
We are indeed convinced, beyond all shadow of doubt,
that there is a choice heritage in Germany, and in other parts of the continent,
who are gradually retiring to the true sheepfold; but, at present, they are,
like the disciples, secreted in an inner chamber for fear of the Jews.
Our visit to this people, though attended with a degree of suffering,
has been productive of solid peace.

[.small-break]
'''

+++[+++Her mind being thus comfortably released from this field of labour,
she proceeded from Mulhelm to Cleves, and from there, through Flanders, to Dunkirk,
and arrived at London the 27th of the tenth month 1790;
and feeling a desire to visit her relations at York, etc. before her return home,
she went pretty directly for that city; where she stayed a few days,
very much to the comfort and satisfaction of her relatives and friends there.
At this time she laboured under evident indisposition of body;
but the sweetness of her spirit,
and the cheering effects of meeting again her beloved connections,
with the prospect of soon returning to those at Clonmel,
supported her in a great measure above it,
and encouraged her to set forward and proceed towards home;
which she did by way of Ackworth, Sheffield, Manchester, etc.
At these places, she was again refreshed by the company of several near and dear friends:
it appeared, indeed, by thus encompassing, in this short visit,
so many of her beloved connections, that,
as the time of her sojourning here was soon to close,
she was enabled and permitted to wind up the labours of her day,
with the mutual consolation of seeing again many
of those with whom she was closely united,
and bidding them a final farewell in mutability.
At Ackworth, she spent the night with a near and beloved relative, to whom,
in much brokenness of spirit, she thus expressed herself: "`Oh! my dear,
I think sometimes that I shall soon be gone; it seems,
as if my day`'s work was nearly done, and on looking towards home,
as if I might not long be there.`"

The following extracts from letters written during this year,
may be properly introduced here:]

[.small-break]
'''

Third month,
1790.--Though my heart sympathizes so nearly and tenderly with you and your dear wife,
as that I could mingle my tears with yours,
yet I dare not utter the language of commiseration,
for your late loss of a lovely plant out of your garden;
but rather of congratulation for the blessed experience,
that "`the eternal God is your refuge, and that underneath are the everlasting arms.`"
Herein I rejoice,
and will rejoice that such unadulterated consolation is ministered to the poor in spirit.
You have a fresh opportunity, my beloved friends, by pure resignation,
to commit your spirits, your children, and your substance, into divine keeping.
May nothing impede the progress and perfection of this work, this glorious work,
whereby the song of the redeemed is learned,
and qualification wrought to unite with the heavenly host, in proclaiming,
"`worthy is the Lord God and the Lamb, to receive riches, honour, and power,
both now and forever.`"
A mind centred to the source of instruction, wisdom, and strength,
can receive little more by such communications as these,
than an outward and visible sign of that inward and spiritual grace,
wherewith the soul is replenished,
and wherein it finds the substance of all that is truly good.
It is nevertheless an allowable accommodation to the weakness of sense, thus to commune;
and having, in moments of drooping,
been refreshed by your tender sympathy and salutations,
my heart is bound in Christian affection to share your griefs,
and hail you on every renewed accession to the Master`'s cross,
and participation of his crown.
Oh my friend, what nailing we take,
before we are bound to it! how nature opposes that holy
experience of being led as a lamb to the slaughter,
and as a sheep that is dumb before its shearers.
Hard as the work is, with God all things are possible;
and therefore let us watch and be sober, adding to our faith virtue;
that when the power is revealed by which we can do all things, we being in readiness,
may advance from strength to strength, and finally appear before the Lord in Zion,
among those who are fully sanctified.

We are now returned from our quarterly meeting,
where I trust the gospel cause did not go backward.
We ought not to look for great things; we do not deserve them.
And I perceive that when we are most dipped into this sense, life and immortality,
being graciously in waiting, are the most sure to be brought to light.
Therefore let us be humbled under the mighty Hand,
that we may be thus truly exalted in due time; yes, in all our provings,
let us sink down into our own nothingness,
and value every dispensation which clothes us with it; for then, methinks,
we shall learn in everything to give thanks.

[.small-break]
'''

Third month, 1790.--You have, my dear friend,
of late appeared to me to be preparing to set out,
according to the sacred counsel of the great Master to his disciples,
without scrip or purse, or two coats;
reduced to a simple dependence upon renewed supplies from the holy treasury,
and learning in a new.
line of service, to live by faith.
May you increase in the certain knowledge,
that the Lord is gracious unto such humble faithful walkers before him.
I feel a confidence that it will be so,
and that your feet will grow more and more conspicuously beautiful upon the mountains;
because they are, beyond all shadow of doubt,
shod with the preparation of the gospel of peace, and through adorable kindness,
washed for the service on which you are now set out:
therefore gird up the loins of your mind, and hope to the end.
Do not be afraid of the exercises into which your mind may often be baptised.
Remember that even the great Master,
who knew without fear or doubting that he should glorify the Father,
groaned in himself before he raised Lazarus from the dead.
I intreat you, offer yourself up freely,
and do not seek to cut your matter shorter than is consistent with your peace.
Look forward and not backward; for if I am not mistaken,
your progress in the work whereunto you are called,
is not designed to be as slow as some you may esteem your cotemporaries;
and it is as great an evil to take from the words of the prophecy of the book,
as to add to them.

[.small-break]
'''

Third month, 1790.--Your many testimonies of affection for us,
your repeated accounts respecting yourselves, and, above all,
your steady increase in saving knowledge, of which we are persuaded,
are frequent occasions of humble thankfulness to the Father of mercies, whose blessings,
variously showered upon you and us, are worthy of reverent commemoration,
and grateful enquiry, what we shall render unto him therefor.
It is little, very little, that we can do for so bountiful a Shepherd; nor does He,
blessed be His name,
require at our hands what he has not furnished us with ability to perform:
but that little, let us cast into the sacred treasury,
not doubting His compassionate acceptance.
A humble resigned spirit is a gift which, I believe, was never refused at the altar.
It is, while preserved, a continual offering, a sweet smelling sacrifice,
the savour of life unto life in those that believe; it is a. bulwark or fortress, where,
in times of desertion, temptation and tribulation, the weary soul finds shelter,
and all the armour of light against Satan`'s attacks and fiery darts.

Now, my beloved friends, my heart feels you as companions in the Christian path;
and in your exercises, your discouragements and poverty of spirit, I participate;
though distant in the outward, yet as the apostle said, "`present in spirit.`"
Be assured that the same afflictions are measurably
accomplished in every true member of the mystical body.
You have companions therein, and need not be told,
that all these things are intended for our refinement and increasing
usefulness and service in the church militant here on earth:
that when this mortal shall put on immorality,
the tribulated spirit may obtain an eternal residence, in the glorious church triumphant,
where all tears are wiped away.
These are animating considerations,
and prompt us to endure hardness like good soldiers of Jesus Christ,
and to receive with thanksgiving every humiliation and spiritual baptism.

I know, dear friend,
that if you are mercifully kept quick in understanding in the fear of the Lord, the weak,
unconverted state of many of your members will occasion you to go mourning on your way,
at the same time that you finds a necessity to
attend to that command of the great Master,
to wash and anoint, rather than appear unto men to fast.
This hidden exercise of spirit will espouse you more closely to the heavenly Bridegroom,
who has the spirit of wisdom and understanding,
and who judges not after the sight of the eye, or the hearing of the ear.
I do hope, my beloved friends, that your labours will be blessed,
though yourselves think them very weak and small.
If our treasure is but laid up in heaven,
no matter how little our corrupt hearts are entrusted with the knowledge of it.
Be not afraid of leaving the sheep and lambs, when the good Shepherd calls to any duty;
His care is better than ours, and He can supply all your needs,
by the riches of His grace in Christ Jesus our Lord.

[.small-break]
'''

Fourth month,
1790.--I am comforted in finding that your hearts are
knit together like David and Jonathan`'s,
in opposition to every stratagem which Satan may use.
As I do believe the cement is composed of materials acceptable
to the penetrating eye of the great Preserver of men,
so I trust you will feel your union to be a balm through the
future steppings of Christian and social travel,
however it may please infinite Wisdom to dispose of you, as to your outward settlements,
or journeyings in the present world.
Settle it in your heart, to expect a mixture of bitterness in that cup of comfort,
which the great Master may minister to you.
No deadly sorrow is in the blessing; but evil things, and mutable things,
till our purification is complete,
have a power over us which keeps our spirits in a state of profitable groaning;
and if we do but experience the fulfilling of that gracious promise,
that for the crying of the poor, and for the sighing of the needy, he will arise,
let us thank him and take courage.

My beloved +++________+++'`s letter came at a time more acceptable
than would be prudent for me this way to describe.
It renewed that precious participation of each other`'s exercises and consolations,
which I do believe originates in the Fountain of everlasting love.
I look with humble admiration at that holy hand which is leading you about,
and instructing you;
and my faith is strong that the Lord will keep you as the apple of his eye,
and in his own time, make all clouds of discouragement as the dust of his feet.
You know, and you will more and more know, that,
for the right performance of any religious service,
we need an emptying from vessel to vessel;
and when we consider how many have suffered by
an imperfect experience of this great work,
we ought not to lament at any dispensation, or change of seasons, which brings us,
in the least degree, nearer to that state and stature,
for which infinite Kindness designs us.

[.small-break]
'''

Fifth month, 1790.--That measure of conversion which is essentially necessary,
rightly to introduce us into every new line of service,
bears a strong resemblance to the first step of
the great Apostle into the Christian religion.
A light shone around him; such conviction seized his soul, that while he asked,
"`who are you,`" he called him Lord; he consulted not with flesh and blood;
happy resignation; which however, did not keep him out of the street called Strait,
neither for a time were his eyes suffered to be opened.
We have each our peculiar exercises, as we have each our peculiar infirmities; all which,
through sanctification and purification of heart,
may help us forward to a final settlement in that glorious city,
whose inhabitants no more say they are sick.
I hope you will not draw back from any opening to duty, which you may be favoured with.
The right time, and our time, do not always agree;
but we ought invariably to bear testimony to the first,
by the subordination of the latter.
"`Wisdom is justified of her children;`" and therefore
do not reason unprofitably upon your duty.

[.small-break]
'''

Seventh month, 1790.--It was pleasant to be informed of your safe landing in Ireland.
I hope your drooping mind has been refreshed,
not only by the strengthening sympathy of fellow travellers, but also by the composing,
and yet animating virtue of Shiloh`'s streams,
and that you have been enabled to lie down beside these waters which run softly.
You know that when we can get here, it is like getting home,
to a joy with which no stranger can intermeddle.
The increase of such a capacity is what my soul longs for;
that in this exercising journey before us,
wherein creaturely efforts can do little for the promotion of the great cause,
the pure seed may, from place to place, be at least secretly visited;
and that whether effects may be seen or not, the work, in divine condescension,
may be hid with the Lord.

[.small-break]
'''

Eleventh month, 1790.--The comfortable evidence you mentions,
of there being a power strong in proportion to your weakness,
strengthens my declining faith, and encourages me to lay hold on the same blessed hope,
because it met the witness in my heart, that says it is the truth.
A confidence so precious is not to be cast away;
it is designed for an anchor to the poor vessel, secretly attaching it to eternal help,
when, in divine wisdom,
its course is restrained on the waters of affliction and uncertainty.
Then let me say, cast not away your confidence, for therein is great recompense of reward.
We are often tempted to do this; sometimes, in the multitude of objects,
forgetting the great source of good, and means of preservation; and at others,
looking so timidly and doubtfully at them, as to lose our interest in both.
May you and I, watch against these and other evils; and pray,
according to our measure of faith, that that spirit may preside in us,
which can rejoice in God alone, though none else regard it, or can own its life.

[.small-break]
'''

1790.--I cannot know that your sufferings and temptations are so deep,
without feeling an affectionate, sisterly solicitude about you,
at the same time that I perceive with joy your
stoppings are in the footsteps of the flock.
But with the greatest cordiality do I find,
that you can not draw your consolations from even the springs of fellow-disciples.
The well`'s mouth being closed in yourself, you sit mourning at it,
and every drop of water brought you from your neighbour`'s overflowings,
serves but to augment your lamentation; for your thirst cannot be satisfied with that,
which is not the "`well in you springing up into everlasting life.`"
I am glad you are resolved to be patient; if you hold your integrity herein,
and let patience have its perfect work,
you will find more perfection in this dispensation than is manifest at present,
and moreover you will lack nothing.
Then be of good cheer, my beloved friend:
believe in the fatherly care and compassion of Him who is the Lord almighty;
and doubt not that all His chastisements are the more
indelibly to fix the seal of adoption upon your spirit;
whereby your qualifications may be strengthened to cry Abba,
Father! in proportion to the increase of your services in and for His name.
Were not the experiences of the Lord`'s dealings to us as individuals somewhat deep,
there might be more danger of stumbling in the paths of judgment, when,
for the welfare of others, we may be turned into them; and marvel not if,
after this baptism with which you are baptized, the Master, who is rich in mercy,
and inscrutable in wisdom, calls upon you for some new act of dedication.
Till then, fight the good fight of faith;
now is your time to prove the sufficiency of your ever victorious Captain.
Resolve if you perish, it shall be at His footstool.
Let not out your ear to the accuser of the brethren; believe him not,
even respecting yourself,
when he tells you that you are not what your friends take you to be.
But if the Father chastens, and draws you from man`'s judgment,
by showing you the fallibility thereof, cleave to him as to your best friend.

Experience will convince you,
that whoever stand through the storms attendant on
their pilgrimage for the honour of the great Name,
must learn to pass through good report,
as well as evil report,--with an equal neglect of it as such;
for the weapons of their warfare being spiritual,
they must not fail to apply them to the spiritual wickedness in the high, but secret,
places of their own hearts.
Self is apt to feed upon the manifest unity of our friends,
and to draw our attention from the pure and strengthening
virtue which supplies every joint of the mystical body;
rendering us less capable, than we otherwise should be,
of eating that bread which the world knows not of.

I have a comfortable hope respecting your prosperity and preservation,
and already rejoice in the symptoms thereof That one especially,
of the passing away of the old heavens and the old earth, is so favourable,
that I trust you will fully resign yourself thereto,
that so they may be remembered no more, nor come in,
to way-lay your mind in any of its preparations for gospel service.
Yes, my heart can feel with you,
in your frequent incapacity to rejoice in even the purest friendship,
or to support it by the effusions of natural affection.
Oh that all whose hearts and tongues have been animated
with the live coal from the sacred altar,
had fully passed through dispensations of this sort; methinks the priesthood,
and other living members in the church, would be more burning and shining lights,
have more true Christian sympathy for each other,
and oftener meet one another in the field of spiritual exercise, or, in other words,
enjoy the true communion of saints.
We miss many of the excellent promises of the gospel for lack of coming to,
and dwelling in, that humble situation of mind to which they belong.
How many sit in judgment, who never sufficiently,
by virtue of the meekness of their spirits, were guided in the midst of its paths!
How often do we hear attempts to sing the praise of Zion`'s King,
by those whose general conduct bears no testimony to a fervent travail of
their spirits after deliverance from the enemies of their own houses,
and who consequently cannot stand upon its banks.

Though I often fear it is the case, I dread to settle down,
because it sometimes appears to be my duty to show unto others their transgressions,
as if the work was done at home, and my soul`'s adversary overcome; when, peradventure,
his force is redoubled, and his artifice herein more than ever effectual.
"`Watch and pray,`" sweetly occurs to my mind, and for this good end,
"`that you enter not into temptation;`" that the vessel
may be preserved in sanctification and honour,
and that the immortal birth may have its habitation in a purified temple.
Then may the new heavens, the new earth, and the holy mountain, in times of refreshing,
break forth into singing, because the Lord comforts his people,
and has mercy upon his afflicted.

[.small-break]
'''

+++[+++She reached Dublin in time for the half year`'s meeting,
and in the select meeting there gave an account of her late journey,
with great meekness and humility of spirit; ascribing nothing to the creature,
but rendering to the Lord the praise of His own works.
From hence,
she proceeded directly for Clonmel--having account of the small pox being in
the family--where she was favoured to arrive the 12th of the eleventh month,
much relieved from a severe cough which had lately attended her,
though greatly exhausted in her strength and spirits.
On her way from Dublin, she writes thus to a friend.]

[.small-break]
'''

To be strengthened rightly to fill up our appointed
measure of sufferings for the body`'s sake,
whether at home or abroad, is a mark of divine favour,
and will be succeeded by undefiled rest.
I am now returning home, under a grateful sense of Providential care,
and in peaceful poverty of spirit.

[.small-break]
'''

+++[+++The following is extracted from a letter which she wrote at Clonmel,
a few days after her return.]

[.small-break]
'''

I can now once more salute you from home, in renewed and endeared affection,
and gratefully acknowledge the multiplied preservations of our never-failing Helper,
in thus far bringing through a variety of exercises,
from which the natural mind cannot relieve itself.
I reflect with solid satisfaction upon my visit at York, etc. and am glad I paid it,
though I feel myself a poor worn-out creature.

[.small-break]
'''

+++[+++The 24th of the eleventh month she set off from Clonmel
to attend their quarterly meeting at Cork:
previous to which she wrote the following letter to a friend.]

[.small-break]
'''

My present affliction has gained great ascendency over my mind,
so that I seem fast losing my hold and sense of Him that is invisible;
and remembering some past exercise, when I was in danger of losing the best life,
I am ready to say, with mournful Jeremiah, "`cause me not to return to Jonathan`'s house,
lest I die there.`"
I know that nothing has yet occurred,
which needs to scatter a well regulated mind from the Source of good;
but I am left to such a sense of my own wretchedness,
that even the grass-hopper or things comparable to it, are become a burden.
To attend a quarterly meeting under such impressions,
is a prospect which I need not describe;
but I fear to make a prey of your sympathetic mind.
May I be preserved from a murmuring disposition, by which the holy Spirit is grieved!

[.small-break]
'''

+++[+++At the quarterly meeting, she delivered a humble account of her late mission,
appeared in several acceptable testimonies,
and at the close of the meeting was taken ill.
This last conflict of nature, which was at times very severe, continued about ten days,
when it pleased infinite Wisdom to remove her from the toils and troubles of mortality,
to a mansion of everlasting rest, on the 8th of the twelfth month, 1790,
and on the 12th her remains were attended to the burying ground, by many friends.
It was a solemn, memorable time;
and living testimonies were there borne to the sufficiency of that power,
which had so eminently qualified her for His service,
to raise up and abilitate others to follow her footsteps.

During her illness, which was at the house of her beloved friends Samuel and Sarah Neale,
she dropped a few expressions, worthy of preservation, which have been collected,
and are as follows:]

[.small-break]
'''

In a message to a young woman who presided in the school at Clonmel, she said:
Salute her very affectionately.
I desire the sympathy of her spirit,
and that she may be endued with additional qualifications to bear her own,
and our joint trials, under these complicated circumstances.
Tell her, I have been much favoured with quietness of mind from the first,
though a stranger to how the present afflictions or trials may terminate;
but the grain of faith and hope which is mercifully vouchsafed,
I esteem preferable to all knowledge.

She further said; "`give my dear love to all our young women;
I hope that each will be preserved in their respective lines of duty.
I know their tenderness for me,
but would be sorry they should let down their spirits too low;
for I believe that Truth would rather increase, than lessen our strength,
at such times as these.
The children are all affectionately remembered by me:
I hope they will each endeavour to lighten the general burden, by their sobriety,
and doing that which they know to be right.
I am trying to get my mind to a settlement, that all things work together for good;
but it is hard to get at it.`"
She several times said; "`I must go.
You must let me go.`"
And nearly the last words she spoke were, repeating that passage of scripture,
"`my peace I give unto you.`"

[.small-break]
'''

+++[+++Four days before her decease, she dictated the following weighty, instructive letter,
to a particular friend.]

[.small-break]
'''

Your salutation met me, though apparently out of course, in the right time;
being under impressions which make time and circumstances of little account,
compared with the unlimited consolations of the Spirit,
or a preparation to receive them at the divine Hand, My soul,
though encompassed with the manifold infirmities of a very afflicted tabernacle,
can feelingly worship, and rejoice in nothing more than this,
that the Lamb immaculate is still redeeming, by his precious blood, out of every nation,
kindred, tongue and people; and making a glorious addition to the church triumphant,
whose names will stand eternally recorded in the book of life.
I express not these things from a redundancy of heavenly virtue,
but from the soul-sustaining evidence, that,
amidst all our weakness and conflicts of flesh or spirit,
an interest is mercifully granted in Him, who gives victory over death,
hell and the grave.

[.small-break]
'''

+++[+++Thus has the setting sun of this humble follower of the Lamb, gone down in brightness;
and though she has been called away as in younger life,
being only in the thirty-fifth year of her age,
yet her day`'s work appears to have been complete, and, with respect to herself,
every measure worth living for, filled up.
Honourable age is not that which stands in length of time,
or that which is measured by number of years; but wisdom is the grey hair to man,
and an unspotted life is old age.
May we who remain behind,
while we deplore the church`'s loss in the removal of so useful and dignified a servant,
be encouraged to imitate her example,
and to surrender ourselves in faithfulness and dedication to all the Lord`'s requirings;
that so, when the residue of our days is accomplished,
we also may be favoured to receive that blessed declaration; "`well done,
good and faithful servant, enter you into the joy of your Lord,
and into your master`'s rest.`"]
