[#remarks, short="Some Remarks on Christian Discipline"]
== Some Remarks on Christian Discipline, as it Respects the Education of Youth.

[.centered]
by Sarah R. Grubb

[.small-break]
'''

The author of the Christian religion came to redeem and save
from that spirit which opposed the coming of his kingdom.
He has wonderfully displayed the efficacy of that good, by which evil is overcome,
proving through the whole of his dispensations a coincidence of mercy with justice.
And the operation of this benign principle appears to
be in no case more necessary and profitable,
than in the true support and discharge of the duties which we
owe to those who are placed under our superintendence and care.
As there are dispositions manifest in children,
after the knowledge of good and evil is contracted,
which degrade the mind from that innocency wherein they were first created,
and which like an evil tree, if permitted to grow, will produce unwholesome fruit;
so there is also in the power of those who have rightly the care of them,
a means which may, by the concurring operations of Truth,
be rendered effectual to the reduction thereof:
and as both the disorder and the remedy lie deep in the heart,
they must be sought for there, without the love of superiority,
a carnal judgment of good and evil, or the influence of self-will.

To bring children to a true and profitable sense of their own states,
and direct them to the spiritual warfare in themselves,
is the main end of all religious labour on their account;
and herein a single eye ought to be kept to the witness of Truth in their minds,
for that must be visited and raised, before they can so see,
as to repent and convert from evil.
When this is the principal object in the view of those,
who consider themselves as delegated shepherds,
accountable for the preservation of their flock,
they are religiously engaged to promote it by such means as are put into their power,
under the influence of a Christian spirit;
which preserves from a desire of occasioning suffering, or more of it,
than is absolutely necessary for the obtaining of that end,
gives patience to persevere in labour without fainting,
strength to bear and forbear in their waiting for the springing up of the good seed,
and opens an eye of faith to look for, and depend only upon,
the blessing on their endeavours.
Hereby the conduct of such is deeply instructive to children; and may.
seal upon their minds the pious concern of their preceptors,
and affectionately endear them in a friendship lastingly profitable, when they prove,
through the influence of divine love upon their own understandings, the justice, mercy,
and nobility of that Christian discipline which has been exercised towards them,
and whereby they have obtained sweet communion with, and an opening to,
the fountain of good in themselves.

If in our passage through life, we are often brought to acknowledge that of ourselves,
without divine assistance, we can do nothing,
is it not abundantly obvious in the work of bestowing a religious education on youth?
and should any wisdom preside over that "`which comes down from above, and is first pure,
then peaceable, gentle, and easy to be intreated, full of mercy, and full of good fruits,
without partiality, and without hypocrisy?`"
It is lamentable to see how people in general,
and even some who seek the sense of Truth on other occasions,
seem to consider themselves, at any time, or in any disposition,
qualified to instruct and correct children,
without perceiving that their own wills require to be first subdued,
before they can acceptably be instrumental in subduing the will of others.
Though acts of indiscretion, or severities,
may have a tendency to humble those who receive them,
through whose sincerity all things work together for good,
even as persecution has been blessed to thousands,
yet the instruments are by no means acquitted thereby, their conduct not being the,
produce of that faith, which works by love, to the purifying of the heart.
It is not to be expected, but that there is reserved for such,
a proportionate degree of suffering, to that which, in their own wills,
they have occasioned to others: though, by their natural understanding only,
their perception of divine recompense may not be clear enough to distinguish it,
yet a righteous retribution,
or receiving that measure themselves which they have meted to others, may await them.

"`Provoke not your children to wrath,`" said the apostle.
A conduct may be exercised towards youth,
which being under the influence of the passions,
has a natural tendency to raise a similar return.
To punish a child because it has offended us, without the discovery of an evil design,
is to act under an unchristian spirit, which revenges injuries.
This is a disposition which is apt to receive its gratifications from a flattering,
cringing spirit,
and from such marks of respect as originate in an impure spring of action; and hence,
teachers of children may, from a superficial judgment,
approve and strengthen the little pharisees under their care;
while the pure life that is struggling in the hearts of some who resemble the publican,
is crushed and disregarded.
Many and deep are the sorrows of the childhood of some,
which proceed from different causes:
and doubtless that incapacity wherein they are placed
for obtaining redress from real grievances,
and the abuse of power being strengthened in those from whom they receive them,
may be numbered among those affecting occasions.
Many children, even in our Society, have a loose unguarded education,
and grow up as degenerate plants of a strange vine,
having very little care exercised towards them, except to indulge their unruly appetites,
and passionate desires;
these require the yoke to be laid upon them with caution and true judgment,
lest more should be commanded than they possess abilities to perform,
and so their deficiency be unjustly laid to their charge:
yet the cultivation of their minds should be steadily pursued,
under that holy assistance without which we can do nothing acceptably.
Past experience does not appear to be a sufficient qualification for this,
any more than for other religious services, even where it has been right,
and much less so, when it has not been strictly under the influence of that wisdom,
which is pure and without partiality.

Wisdom and strength must be waited for, day by day,
for the right performance of our duties,
before him who weighs our actions in the balance of pure justice,
and only approves those which are wrought in the spirit.
To educate children religiously,
requires a quietude of mind and sympathy in their guardians,
with the state of the good seed in them,
which will lead rightly to discriminate between good and evil;
to discover the corrupt source of many seeming good actions;
and to perceive that a real innocency is the root of others, which custom,
and a superficial investigation, have rendered reprehensible.
Here we see the necessity of true wisdom being renewed,
and the insufficiency of that which is carnal,
and boasts its own experience and strength.
It is the humbled mind to which is unfolded such mysteries of true godliness,
for its own edification, and that of those under its care,
as could not have been received in the support of a false consequence,
and the love of superiority.
If children are to be instructed in the ground work of true religion,
ought they not to discover in those placed over them, a lively example thereof?
or ought they to see anything in the conduct of others,
which would be condemnable in them, were they in similar circumstances?
Of what importance then is it for guardians of children, to rule their own spirits;
for when their tempers are irritable, their language impetuous,
their voices exerted above, what is necessary, their threatenings unguarded,
or the execution of them rash, however children may for a time suffer under these things,
they are not instructed thereby in the ground work of true religion;
nor will the witness of Truth as their judgments mature, approve a conduct like this;
though through the bias of self-will, it may be adopted in similar cases,
in a succeeding generation, by those who, instead of having gathered good seed, have,
from the mixture of their education, preferred the bad,
which meeting with a soil suitable to its nature, grows and becomes fruitful,
to the corrupting of many more.

The love of power is so deeply implanted in the natural mind,
that without we discover it, and its evil tendency, in the true light,
we are not likely to consider it as an enemy of our own house,
against which we are called to war with as much righteous zeal,
as against the evil in others; yes with more,
because it is declared such are our greatest foes.
Where this corrupt part is cherished, it stains our actions;
and having gained the ascendency over the pure, lowly seed,
bribes and influences the judgment respecting good and evil,
and establishes the mind in self complacence, which, however productive of reproof,
has seldom an ear open to that instruction by which itself stands condemned.
The prodigal display and use of power is the very destruction of Christian discipline.
Power is necessary; not to be assumed in the will of the creature,
but to stand subservient to the judgment of Truth, under which it ought to be exerted;
lying in ambush as a waiting assisting force, ready to be called in cases of difficulty;
when, if it step forth in true dignity, the appearance, rather than the use of it,
may generally prove sufficient,
and its wise retreat render it still more useful and reverenced.
True love, clearness of judgment, and the meekness of wisdom,
are the supporters of true dignity;
and where these prevail in a mind under divine government and control,
they give authority, firmness and benevolence, in thought, word, and deed;
which have a profitable and comfortable effect
upon those who are placed under their influence,
and open a door for undisguised familiarity, and affectionate intercourse,
wherein children receive instruction more suitably and cordially,
than under the arbitrary sway of a continually assumed power.
Should we lay hold of Christian discipline in all its branches,
and return with it to its root, either among children or in the church,
we shall always find it originate in a Christian spirit,
and that every plausible appearance which is defective in this ground,
is so far no better than sounding brass, or a tinkling cymbal.

The right education of children, especially in boarding-schools,
is no doubt a close and arduous work; those, however, who are rightly engaged therein,
and endeavour after their own refinement,
and an increasing acquaintance with the Fountain of purity in themselves,
need not have their eye outward for the establishment of power and authority;
for He who feeds the ravens and clothes the lilies, knows what they stand in need of,
and is able, out of his own treasury, to supply all their needs; to be mouth and wisdom,
tongue and utterance; and will not fail to help under their greatest difficulties,
if they support a patient dependence upon Him alone,
and profitably live under the persuasion, that when He shuts,
no one should attempt to open, and when he opens, none can shut.
